### ISSUE TITLE
App does not list any available apps when device is offline

### ISSUE THREAD

**Issue by AaronFriel** [microsoft/devhome#1000]
### Dev Home version

Latest Store (2023-05-31>

### Windows build number

22621.1702

### Other software

None, fresh install

### Steps to reproduce the bug

During setup, the WiFi driver reinitialized and dev home confusingly displayed no apps available, and a "requires app installer" (or similar) message appeared.

### Expected result

The app should provide visual feedback that the device is offline as the cause for listing no available apps.

### Actual result

No indication for the cause.

**Comment by AmelBawa-msft** [comment]
We should consider adding a state for no internet connection available which can affect the app search functionality and installation process (when downloading the installer). If the `winget` catalog was never downloaded in an earlier attempt (with internet connection), the list of popular apps will also not be available/displayed.

@AaronFriel the message for updating `App Installer` is displayed when there's an update available for `App Installer` from the Store app. Getting the latest `App Installer` allows Dev Home to benefit from the latest WinGet COM APIs which provide additional information for packages (e.g. publisher name). But we should also have an enhanced method to perform the update without having to restart Dev Home which is currently required, and maybe also communicate the update progress in the app if possible.
