### ISSUE TITLE
App hangs on fresh install when clicking add on VS Code

### ISSUE THREAD

**Issue by AaronFriel** [microsoft/devhome#1001]
### Dev Home version

Latest Store (2023-05-31)

### Windows build number

22621.1702

### Other software

N/@

### Steps to reproduce the bug

On a very fresh Windows install - this was the first installed app - after resolving #1000 (device offline), the app froze upon clicking the plus on VS Code.

### Expected result

VS Code should have been queued and the Dev Home App should remain responsive when adding apps.

### Actual result

The app hangs with the busy cursor showing upon trying to click the close window button. The app had to be closed via task manager.

**Comment by AaronFriel** [comment]
We are troubleshooting by running Windows Update.

**Comment by AmelBawa-msft** [comment]
App hanging when interacting with the FlipView in the App Install page is possibly a sign of a crash, which I suspect is related/has the same root issue as #768, addressed in this PR #1070

/dup #768
