### ISSUE TITLE
App does not show required app installer update on first run

### ISSUE THREAD

**Issue by AaronFriel** [microsoft/devhome#1002]
### Dev Home version

Latest Store (2023-05-31)

### Windows build number

22622.1702

### Other software

On first run, #1000 and #1001 were experienced. After subsequently restarting the device, a third start of the Dev Home app (second while online) the hero graphic was replaced with a warning to update the app installer.

### Steps to reproduce the bug

On a very fresh install of Windows, install Dev Home. There is no indication that there is any out of date functionality, and you may encounter #1001. On a subsequent restart, the app reports that it requires this app installer update.

### Expected result

I would expect required functionality to be installed with the store app, or for this to be detected on first run.

### Actual result

On a third execution of the app, the "app installer" update warning appeared.

**Comment by cinnamon-msft** [comment]
I'm curious if your app installer updated in the background from the Store between your second and third launch. I'm interested to see if we can get this to repro :)
