### ISSUE TITLE
Not powerful enough at installing programs

### ISSUE THREAD

**Issue by PloniAlmoni** [microsoft/devhome#1008]
### Suggested new feature or improvement

Make it more flexible with more selection of programs and automation. I was expecting something like what Linux can do with Ansible or Nixos, not a GUI front end to winget with a half a dozen selections.

### Scenario

scripted installs with more apps to install, for a complete environment. I can install visual studio without this, thank you very much, so it's useless.

**Comment by PloniAlmoni** [comment]
sorry, didn't notice the YAML feature which may be able to do more, I still think the GUI installation is a bit bare-bones.

**Comment by denelon** [comment]
You might want to take a look at:
* #1067
