### ISSUE TITLE
Minor button styling issues

### ISSUE THREAD

**Issue by itsWindows11** [microsoft/devhome#1009]
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1702

### Steps to reproduce the bug

1. Go to Settings > Accounts then add an account. In the dialog you will see a button from old Windows 10 styles that has the tilt effect when holding it.

   ![image](https://github.com/microsoft/devhome/assets/81253203/50b20e8f-6b6f-40f2-b9ce-7e457730abec)

2. In the Introducing Dev Home page, when hovering over the accent button "Get started", it does not use the correct style and then goes back to normal (i.e. not accented).

   ![image](https://github.com/microsoft/devhome/assets/81253203/9326a723-1b5a-4d7e-99fc-2a092cf6e7ff)

   On hover:
   ![image](https://github.com/microsoft/devhome/assets/81253203/56100fc2-0e95-4bcd-abc8-c682c3915ac5)

### Expected result

Use correct Windows 11 button styles and with correct hover effect.

### Actual result

Inconsistent button styles across the app.

**Comment by itsWindows11** [comment]
In case this issue is approved, I could try helping with it by the way.

**Comment by itsWindows11** [comment]
Where does this dialog content come from anyways? I can't find the source for it. `LoginUIDialog` only has the close button and title.
![image](https://github.com/microsoft/devhome/assets/81253203/105a9340-51e1-468c-9d4d-a20bee06882c)

**Comment by krschau** [comment]
@itsWindows11 The "Sign in to github.com" button comes from the Dev Home GitHub Extension, in the [microsoft/devhomegithubextension](https://github.com/microsoft/devhomegithubextension/) repo. That UI is an Adaptive Card rendered inside a ContentDialog. The other buttons you mention are simply WinUI 3 XAML and do live in this repo. We'd love to have your help!

**Comment by itsWindows11** [comment]
It looks like that button issue is in the adaptive cards library, so unfortunately out of scope for the app.
