### ISSUE TITLE
Minimum OS Requierements

### ISSUE THREAD

**Issue by LiorBanai** [microsoft/devhome#1015]
Hi
I'm getting the following error:

App installation failed with error message: Windows cannot install package Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe because this package is not compatible with the device. The package requires OS version 10.0.22000.0 or higher on the Windows.Desktop device family. The device is currently running OS version 10.0.19044.2965. (0x80073cfd)

Any reason to limit it to newer versions?

**Comment by Aaron-Junker** [comment]
It is limited, because dev home uses widgets, which are only available in Windows 11

**Comment by LiorBanai** [comment]
@Aaron-Junker Thanks
