### ISSUE TITLE
Resizable side panel

### ISSUE THREAD

**Issue by qinjoshua** [microsoft/devhome#1016]
### Suggested new feature or improvement

The side panel is currently much wider than it needs to be. It is collapsible, but not resizable. I'd like for it to be resizable.

### Scenario

I have a small screen. I want to resize the side panel. I hover my mouse over the border between the side panel and the main content area, and it turns into a resize cursor. I click and drag to make the side panel smaller.

**Comment by cinnamon-msft** [comment]
I'm unable to transfer this issue, but this would be a request on the @microsoft/microsoft-ui-xaml folks since we're using their NavigationView :)
