### ISSUE TITLE
Reorder widgets

### ISSUE THREAD

**Issue by LanceMcCarthy** [microsoft/devhome#1017]
### Suggested new feature or improvement

Currently, there doesn't appear to be a way to reorder the widgets in the Dashboard view.

### Scenario

You want to move a widget to a different position in the layout, for example a more important one to the top.

### Additional details

This is pretty self-explanatory, but I'm still happy to answer any follow-up questions.

**Comment by krschau** [comment]
Duplicate of #673

**Comment by LanceMcCarthy** [comment]
Thanks Kristen! I had a feeling this was going to be a dupe. Maybe a suggestion would be to first search the open Issue before submitting the FR (inside the app). Should I open a new FR with that?

**Comment by krschau** [comment]
@cinnamon-msft I know you put a "search existing issues" in the readme, but maybe it's not the most relevant place :) Do you think it makes sense to put a note in the bug/feature forms?
