### ISSUE TITLE
Can't search for applications

### ISSUE THREAD

**Issue by gbarrs-at-em** [microsoft/devhome#1018]
### Dev Home version

0.137.150.0

### Windows build number

10.0.22000.1936

### Other software

OS Build Version: 10.0.22000.1936.amd64fre.co_release.210604-1628
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Following the walkthrough for machine configuration. Selected a repository. That worked fine. Next step was to add an extension.  

### Expected result

I was expecting to see (or be able to search for ) extensions.

### Actual result

The placeholder text said something like Try GitHub, but I couldn't type anything.  There was no text box visible and clicking on where I thought the textbox should be had no effect.  No 

### Included System Information

CPU: AMD Ryzen 7 2700X Eight-Core Processor         
Physical Memory: 31.93GB (11.81GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by AmelBawa-msft** [comment]
If the search box is disabled it likely means that the catalog connection to enable search has not been established yet, or an error occurred when attempting to connect. To troubleshoot this issue, Is it possible to check in the log file (path details below) for this string: `Connecting to all catalogs completed`. If the string was not found, then either the connection has not yet been established or an error occurred (latter should be logged in the same file).

Log file directory: `%LOCALAPPDATA%\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\TempState\SetupFlow`

**Comment by gbarrs-at-em** [comment]
I just installed version 0.200.165.0 and the application now works as expected.  Thanks.
