### ISSUE TITLE
Dev Home crashing when installing apps

### ISSUE THREAD

**Issue by Mustafa-Hamad** [microsoft/devhome#1028]
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Sometimes trying to add application to install the whole Dev Home app crahses

### Expected result

To add the apps to the list without any crashing

### Actual result

Dev Home crashing

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i5-12400F
Physical Memory: 31.84GB (21.72GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by AmelBawa-msft** [comment]
Marking as duplication since that potentially has the same root issue as a related open issue.

/dup #768
