### ISSUE TITLE
Applications quick access

### ISSUE THREAD

**Issue by xk-rl** [microsoft/devhome#1030]
### Suggested new feature or improvement

To have any Applications on a quick access dashboard so we can have a overview.

### Scenario

Have an icon of for example Visual Studio Code where we can quick access it. It would maintain a good overview over everything and make developing real easier.

### Additional details

It would be good if it would do that automatically but I wouldn't mind adding the Applications myself on the quick access dashboard

**Comment by Aaron-Junker** [comment]
How would such a quick access differ from pinning something to the taskbar or the start menu?

/needinfo

**Comment by Tinibar** [comment]
> How would such a quick access differ from pinning something to the taskbar or the start menu?
> 
> /needinfo

There are many reasons like keeping the Simplicity of the taskbar as i dont really like a full taskbar but would also make it possible to add like relatable file for example you have the lets say Arduino IDE on the Dashboard, it would be good if it also would show like the files which are relatable to that and maybe even make a preview of it. So it not only shows you the Applications you save there but also relatable files or linked repositories. By that i mean linking a Repository in which you coded most of you applications with that IDE. But i get your point with the Taskbar

**Comment by Aaron-Junker** [comment]
> > How would such a quick access differ from pinning something to the taskbar or the start menu?
> > /needinfo
> 
> There are many reasons like keeping the Simplicity of the taskbar as i dont really like a full taskbar but would also make it possible to add like relatable file for example you have the lets say Arduino IDE on the Dashboard, it would be good if it also would show like the files which are relatable to that and maybe even make a preview of it. So it not only shows you the Applications you save there but also relatable files or linked repositories. By that i mean linking a Repository in which you coded most of you applications with that IDE. But i get your point with the Taskbar

Your issue sounds like a good feature request for Dev Home: https://github.com/microsoft/devhome
