### ISSUE TITLE
Repositorios de diferentes cuentas

### ISSUE THREAD

**Issue by negagl** [microsoft/devhome#1034]
### Dev Home version

0.137.150.0

### Windows build number

10.0.23471.1000

### Other software

OS Build Version: 10.0.23471.1000.amd64fre.ni_prerelease.230526-1341
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Agregar repositorios > seleccionar la cuenta (No URL) > escoger entre cualquiera de las cuentas que se haya agregado anteriormente.

### Expected result

Cuando cambie de cuenta quiero ver los repositorios disponibles para la cuenta actual y no para la primera a la que inicié sesión.

### Actual result

Solo filtra los repositorios de una sola cuenta, al seleccionar otra cuenta sigue mostrando los repositorios disponibles para la anterior

### Included System Information

CPU: AMD Ryzen 7 5700G with Radeon Graphics         
Physical Memory: 15.37GB (9.01GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
Bing Translated title: Repositories from different accounts

Bing translated summary: Add repositories > select the account (No URL) > choose from any of the accounts that were previously added.

**Comment by dhoehna** [comment]
Duplicate of #918
