### ISSUE TITLE
Ability to send commits from Dev Home

### ISSUE THREAD

**Issue by lyzzandro** [microsoft/devhome#1037]
### Suggested new feature or improvement

Gostaria que fosse possível enviar commit diretamente na interface desse aplicativo

### Scenario

Quando eu finalizar de desenvolver algo no VisualStudio, posso enviar commit diretamente por aqui, sem abrir o terminal

**Comment by luislhg** [comment]
**Translation**

I'd like to be possible to push commits directly from the application UI.

When I finish developing something in VisualStudio I'd be able to directly commit here, without opening the terminal.

**Comment by cinnamon-msft** [comment]
I think this is summarized pretty well in #1195, so I'll make this one a /dup of #1195
