### ISSUE TITLE
Create winget installation script

### ISSUE THREAD

**Issue by lyzzandro** [microsoft/devhome#1039]
Edited: Translated used Bing Translator by @denelon 

Original Title:
Criar script de instalação do winget

### Suggested new feature or improvement

I'd like to manage my apps and their list for installation

Original:
Gostaria de gerenciar meus aplicativos e sua lista para instalação

### Scenario

I would like to manage my applications and their list for installation, just by clicking and adding them in a script, and then when I format my computer, use the script to quickly and easily install all of them

Original:
Gostaria de gerenciar meus aplicativos e sua lista para instalação, apenas clicando e adicionando eles em um script, para depois quando eu formatar o meu computador, usar o script para instalar de forma rápida e fácil todos eles

**Comment by AmelBawa-msft** [comment]
Possibly related to this #721 ?

**Comment by denelon** [comment]
I think this is more like supporting `winget import` and possibly `winget export`. Related to:
* #1067

**Comment by denelon** [comment]
Duplicate of #795
