### ISSUE TITLE
Suggestion: Add List of Links to Projects

### ISSUE THREAD

**Issue by stamey** [microsoft/devhome#1041]
### Suggested new feature or improvement

On the dashboard, enable a configurable list of links to projects/development spaces.

### Scenario

Real-world development demands mounting code in various ways -- as a VS solution yes, but also as links to a VS Code workspace file perhaps, or a Windows Terminal window scoped to a work folder for command-line only tasks.  The links would allow the various coding experiences to be created and invoked.

### Additional details

As much as I admire the work on machine-wide configuration, that is a set it and forget operation. What would be more helpful would be to configure the project-wide coding experience where a link/widget would open a particular code editor, and an instance of a browser for hotlinking perhaps, or a session of a third-party tool like Fiddler or Postman.

**Comment by denelon** [comment]
This looks very similar to:
* https://github.com/microsoft/devhome/issues/678

**Comment by cinnamon-msft** [comment]
I think this would be encompassed in a solution for #1120, so I'll mark this as a /dup of #1120 :)
