### ISSUE TITLE
Git Repos Tab

### ISSUE THREAD

**Issue by Fish-Soup-Dev** [microsoft/devhome#1044]
### Suggested new feature or improvement

Show a menu where you can see all your downloaded repos and see info about them. You could also open then in like vs code or vim. 

### Scenario

For people to see the projects that they have and manage them in one spot on there pc, or to make new repos on your Git Hub account.

### Additional details

It could have a tag on the left bar under the configuration tab. Or even show you the revision history.

**Comment by KevinLaMS** [comment]
this may address this request.  Add Projects page #1049

**Comment by KevinLaMS** [comment]
@Fish-Soup-Dev, take a look at Add Projects page https://github.com/microsoft/devhome/pull/1049 and see if this addresses your issue!

**Comment by soroshsabz** [comment]
related to #679

**Comment by shakersMSFT** [comment]
Hi, please take a look at the proposed experience here to see if this solves your issue: https://github.com/microsoft/devhome/issues/2161
