### ISSUE TITLE
The widget cannot show anything 

### ISSUE THREAD

**Issue by clodderes** [microsoft/devhome#1047]
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.arm64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Add widgets in dashboard and windows 11 widget panel

### Expected result

Nothing is showing up in the widgets.

### Actual result

Blank widgets 

### Included System Information

Physical Memory: 15.47GB (6.52GB free)
Processor Architecture: ARMx64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_arm64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_arm64__8wekyb3d8bbwe

**Comment by krschau** [comment]
@clodderes Is the widget actually completely blank, or are you getting a "The widget could not be displayed" message, like in #722?
