### ISSUE TITLE
Create Dev Drive failed

### ISSUE THREAD

**Issue by g0t4** [microsoft/devhome#1051]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23471.1000

### Other software

OS Build Version: 10.0.23471.1000.amd64fre.ni_prerelease.230526-1341
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

I created and attached a `VHDX` externally with `diskmgmt`. I didn't format nor mount it.

Then, in Dev Home: 
- I opened the `Machine Configuration` tab.
- I chose a repo, then when it asked me where to store the repo, I chose `Create a Dev Drive` option which then suggested to use the VHDX I created externally. It suggested to mount it at `C:\Users\wes\DevDrives`. 
- Next page, I added 3 random applications too. 
- When I clicked the `setup` button I got a failure almost right away about the Dev Drive (see image below). Seemed to happen before any installers started which aligns with how the `winget configure` subsystem is supposed to keep going even if part of an install fails. 

Then, I clicked `retry` and it failed again, same messages.

Next, I went back to the `Add repository` view and this time when I added the repo and pointed it to a path on the Dev Drive, it successfully cloned the repo. So this issue is likely isolated to the `Create a Dev Drive` checkbox at the bottom of the `add repo` view.  

### Expected result

Format/mount the Dev Drive and clone the repo to it. 

### Actual result

See below for the error, though... upon inspection the Dev Drive was formatted and mounted. Not sure how to check it further for any problems. 

<img width="891" alt="image" src="https://github.com/microsoft/devhome/assets/180189/0377786d-961e-413f-aafe-62510256c9d3">

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
Physical Memory: 31.84GB (21.09GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by ItsQuadrus** [comment]
Same for me! Any fixes?

**Comment by bbonaby** [comment]
Also, @g0t4 can you take a screenshot of what your Settings disks and volumes page looks like, and add it to your issue as well?

you can access this by doing the following:

1. Windows key + R
2. type ms-settings:disksandvolumes into the textbox
3. Select the "OK" button

I just want to confirm that the top part of the page looks like this:

![top part of disks and volumes page when Dev Drive feature is enabled in the Windows OS](https://github.com/microsoft/devhome/assets/105318831/9e9d25fd-cb62-4c97-badd-c71c954a941f)


That will let me know if the feature is enabled on your machine.

Also @ItsQuadrus would you be able to add a screenshot of what yours looks like as well? That would be a big help. Thank you!

We're releasing a new version of DevHome soon, so if your disks and volumes page does indeed look like the screenshot above, then you should be able to create a Dev Drive on the latest version when its out.

**Comment by ItsQuadrus** [comment]
![image](https://github.com/microsoft/devhome/assets/89267584/e76d2f3b-44f9-4bc5-92d9-3e67e7ba0aa3)
I'm on Windows 11 Home Insider Preview Build `23475.ni_prerelease.230602-1331`

**Comment by bbonaby** [comment]
Thanks @ItsQuadrus. It looks like on your machine the Dev Drive feature in the OS isn't enabled. This won't be an issue once we put the Dev Drive feature into the main OS release. But for now, in the Dev Channel (**ni_prerelease**), what we've found is that after rebooting 1 to 2 times the feature will become enabled. After rebooting check that disks and volumes page again, it should look like my screenshot. Only when it looks like that will you be able to create a Dev Drive. Sorry for the inconvenience, Thanks!

**Comment by JohannesHelleve** [comment]
> Thanks @ItsQuadrus. It looks like on your machine the Dev Drive feature in the OS isn't enabled. This won't be an issue once we put the Dev Drive feature into the main OS release. But for now, in the Dev Channel (**ni_prerelease**), what we've found is that after rebooting 1 to 2 times the feature will become enabled. After rebooting check that disks and volumes page again, it should look like my screenshot. Only when it looks like that will you be able to create a Dev Drive. Sorry for the inconvenience, Thanks!

I have tried rebooting now 5 times, still nothing. And i am in the dev channel, 16 GB RAM and 100 GB storage
