### ISSUE TITLE
Add Devtoys to the recommended applications

### ISSUE THREAD

**Issue by crramirez** [microsoft/devhome#1052]
### Suggested new feature or improvement

Devtoys is a must have utility for developers, 

https://www.microsoft.com/store/productId/9PGCV4V3BK4W

### Scenario

ex. format a Json 

### Additional details

Many tools are available.
- Converters
|  - JSON <> YAML
|  - Timestamp
|  - Number Base
|  - CRON Parser
- Encoders / Decoders
|  - JWT
|  - HTML
|  - URL
|  - Base64 Text & Image
|  - GZip
- Formatters
|  - JSON
|  - SQL
|  - XML
- Generators
|  - Hash (MD5, SHA1, SHA256, SHA512)
|  - UUID 1 and 4
|  - Lorem Ipsum
|  - Checksum
- Text
|  - Inspector & Case Converter
|  - Regex Tester
|  - Text Comparer
|  - XML Validator
|  - Markdown Preview
- Graphic
|  - Color Blindness Simulator
|  - Color Picker & Contrast
|  - PNG / JPEG Compressor
|  - Image Converter
... and more are coming!

**Comment by denelon** [comment]
@crramierz take a look at:
* #375

**Comment by shakersMSFT** [comment]
As @denelon mentioned in the linked issue in the previous comment, "The current list is a hardcoded list of packages. We don't want to be in a constant state of flux where we continually modify the list via PRs. Different users will have different preferences depending on what type of development they do as well as the packages they prefer.

The goal is some kind of heuristic, AI (Artificial Intelligence), or ML (Machine Learning) to provide suggestions."
