### ISSUE TITLE
Complete window with focus mode

### ISSUE THREAD

**Issue by hammadsohail** [microsoft/devhome#1053]
### Suggested new feature or improvement

Hey team, 
what if we can have a window where we can work without any distraction and its like a focus mode for programming so we keep thinking about code only.

### Scenario

People cam focus more

### Additional details

Guys its time for your creativity I've done my contribution, Best of luck.

**Comment by cinnamon-msft** [comment]
I'm not quite sure what you're asking for here in terms of something Dev Home can provide. Is this a Windows feature you're requesting?
