### ISSUE TITLE
scrolling down

### ISSUE THREAD

**Issue by devnickborder** [microsoft/devhome#1057]
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

attempt to set up environment
try to scroll through attempted downloads
wont scroll past a certain point

### Expected result

be able to view all apps trying to download.

### Actual result

wont scroll down.

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i5-1335U
Physical Memory: 7.72GB (1.34GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
Closed by #1173
