### ISSUE TITLE
Intégrez Azure DEVOPS

### ISSUE THREAD

**Issue by Nishiio-enjinia** [microsoft/devhome#1058]
### Suggested new feature or improvement

Bien le bonjour, le top serait d'inclure Azure Devops comme les liens GitHub. Avec toutes les options, tout d'abord les repos. Mais pourquoi pas les pipelines, les wiki, Dashboard, etc... 

### Scenario

Un panel de connexion comme pour Github puis derrière l'accès aux fonctions des répos comme github. Puis le reste des fonctions dans un sous menu avec les widgets correspondant.

**Comment by krschau** [comment]
Bing Translate:

Good morning, the best would be to include Azure Devops as GitHub links. With all the options, first of all the rests. But why not pipelines, wikis, dashboards, etc...
A connection panel as for Github and then behind access to the functions of repos like github. Then the rest of the functions in a submenu with the corresponding widgets.

**Comment by krschau** [comment]
Duplicate of #521
