### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by aQUICKjoker68** [microsoft/devhome#1060]
### Dev Home version

0.137.150.0

### Windows build number

10.0.23471.1000

### Other software

OS Build Version: 10.0.23471.1000.amd64fre.ni_prerelease.230526-1341
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

After install and filling out the requirements  and close the app and restall laptop the dev home app crashing wich results with a popup about I don't have the rights or permissions, as im the administrator it not ok.

### Actual result

unusability

### Included System Information

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Physical Memory: 31.93GB (23.79GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by cinnamon-msft** [comment]
After installing v0.3, are you still seeing this crash?

**Comment by aQUICKjoker68** [comment]
Will install ASAP, update later, thnx

**Comment by aQUICKjoker68** [comment]
Hello there, i still got the crash after a one time opening the app, used the bundle from github, so still not working for me.

i am on a windows 11canary build now but set to unrollement.

**Comment by krschau** [comment]
Hi @aQUICKjoker68, can I ask about this again? Are you still seeing a crash with an error message about being an administrator?

/needinfo

**Comment by aQUICKjoker68** [comment]
Solution is uninstalled, not using it anymore untill windows is unenrolled from dev builds.
