### ISSUE TITLE
Scroll button for apps too small

### ISSUE THREAD

**Issue by pkbullock** [microsoft/devhome#1066]
### Dev Home version

0.137.150.0

### Windows build number

10.0.22000.2003

### Other software

OS Build Version: 10.0.22000.2003.amd64fre.co_release.210604-1628
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Create a configuration, when scrolling through the app list to setup, the button is too small, barely able to click with mouse.

### Expected result

Bigger button.

### Actual result

Button too small

### Included System Information

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Physical Memory: 31.73GB (19.2GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by AmelBawa-msft** [comment]
The App Install UI has been updated:
- FlipView was replaced by a ListView: #1690 
- Add/Remove button now has back plate: #1780

@pkbullock, is it possible to validate if the issue still repro with the latest changes from main brain (or on next release of Dev Home 0.7)?
