### ISSUE TITLE
Screen to edit Environment Variables

### ISSUE THREAD

**Issue by raprocks** [microsoft/devhome#1073]
### Suggested new feature or improvement

An Screen or option to edit environment variables would be great, different profiles for such sets of environment variables can be useful too. a selector would be needed in form of widget in order to quickly switch from A set of env vars to B set.

### Scenario

Multiple projects needing same env vars with different values. One project that can run in "test" mode or "prod" mode.

**Comment by dhoehna** [comment]
DevHome could even use the Environment Variables feature in Windows App SDK. :)

**Comment by cinnamon-msft** [comment]
This is related to #2072

**Comment by cinnamon-msft** [comment]
We deliver the Environment Variables Utility in Dev Home now :) closing as fixed!
