### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Joy-Majumder** [microsoft/devhome#1076]
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

when I turns on my pc then open this dev home app and  I'm trying to add a Widget as like cpu, gpu etc. 
note : I have to add Widget when I opens pc and this dev home  app.

### Expected result

I was expected as like this should not crash when I add Widget of cpu,gpu etc.
and also expected I don't have to add Widget everytime whenever  I turns on pc .

### Actual result

I turns on pc then opened dev home app and i saw there is no Widget of cpu, gpu and memory etc. and i tried to add them again i choose cpu it crashed 2nd time i choose cpu , gpu and it crashed again

### Included System Information

CPU: AMD Ryzen 5 3500X 6-Core Processor             
Physical Memory: 7.93GB (3.17GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
The issue with widgets disappearing after a reboot is tracked with issue #742. The crashing is tracked by #745.
