### ISSUE TITLE
I cannot return to the previous screen using the touch panel shortcuts on my laptop.

### ISSUE THREAD

**Issue by guliojodoy** [microsoft/devhome#1083]
### Dev Home version

0.137.150.0

### Windows build number

10.0.23466.1001

### Other software

OS Build Version: 10.0.23466.1001.amd64fre.ni_prerelease.230522-1422
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

When I access any option of the Application, I have the problem of going back to the previous option.

### Expected result

Improve the user experience when navigating through the Application UI.

### Actual result

To solve the error, I am selecting the options I want to access, which makes the user experience more tedious.

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Physical Memory: 15.69GB (6.32GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by Beizbol** [comment]
Likewise for Mouse Button Back
