### ISSUE TITLE
Widgets Disks

### ISSUE THREAD

**Issue by serard-bimandco** [microsoft/devhome#1085]
### Suggested new feature or improvement

Widget for disks, all or selected, may be many

### Scenario

I have many ssds, one for system, one for vm, one for code & compile

### Additional details

thanks guy !

**Comment by serard-bimandco** [comment]
Thank you @crutkas, so I close this one.

**Comment by crutkas** [comment]
Issue tracks the PR, we will close this when that work gets done. Another community member created the Pr with an issue so this was rather nice timing :)

let’s keep this open until the PR goes in
