### ISSUE TITLE
Cloning a repository in Dev Home over an existing folder crashes the app

### ISSUE THREAD

**Issue by cybtachyon** [microsoft/devhome#1090]
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. Select Machine configuration tab in Dev Home
2. Set-up and Clone a repository
3. Select a GitHub repository that has already been previously cloned to the system
4. Enter a path that contains the GitHub repository local copy, with a directory name matching the repository name.

### Expected result

Dev Home automatically discovers and adds the existing repository and attempts to install any missing prerequisites.

### Actual result

App crash to desktop, no error message

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.59GB (16.75GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
@cybtachyon please upgrade your DevHome version.  I am aware some older versions of DevHome did crash when cloning to a non-empty directory.

The most recent version in the store does not crash.
