### ISSUE TITLE
Setup development environment from configuration file fails 0x8A15C102

### ISSUE THREAD

**Issue by scottluskcis** [microsoft/devhome#1095]
### Dev Home version

0.137.150.0

### Windows build number

10.0.23475.1000

### Other software

OS Build Version: 10.0.23475.1000.amd64fre.ni_prerelease.230602-1331
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. Open Dev Home
2. Click Machine configuration
3. Click configuration file to setup development environment from configuration file 
4. Select file
5. Checkbox
6. Setup as Administrator 
7. Fails with error 0x8A15C102

Have checked error codes at: https://github.com/microsoft/winget-cli/blob/master/doc/windows/package-manager/winget/returnCodes.md

Unable to identify cause of problem

Example of resource beneath my resources section in YAML

    - resource: WinGetPackage
      id: vsCode
      directives:
        module: Microsoft.WinGet.DSC
        description: 'Install Microsoft Visual Studio Code'
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

### Expected result

Configuration to be successfully applied without error

### Actual result

Error occurs for every WinGet package in the YAML with error code 0x8A15C102

### Included System Information

CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Physical Memory: 4.17GB (1.27GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by AmelBawa-msft** [comment]
Adding @msftrubengu from [WinGet-CLI](https://github.com/microsoft/winget-cli) to help with this issue. 
Here are some info collected from the link in the issue description and winget-cli code.

> 0x8A15C102 The configuration unit could not be found.

Source: [Configuration Processor Errors](https://github.com/microsoft/winget-cli/blob/master/doc/windows/package-manager/winget/returnCodes.md#configuration-processor-errors)
Related code in winget-cli: [FindDscResourceNotFoundException](https://github.com/microsoft/winget-cli/blob/master/src/Microsoft.Management.Configuration.Processor/Exceptions/FindDscResourceNotFoundException.cs)

**Comment by scottluskcis** [comment]
I ran a `winget configure show` command and it shows everything I would expect to happen when applied, I don't think there are errors in the YAML 

Example

```
Apply :: WinGetPackage [vsCode]
  Install Microsoft Visual Studio Code
  Module: Microsoft.WinGet.DSC
  Settings:
    id: Microsoft.VisualStudioCode
    source: winget
``` 

Also, I am using Windows Terminal Preview and made sure everything is up to date for Dev Home, App Installer, Windows Terminal, etc. 

winget version I have is `v1.6.1573-preview` 

I'm not sure if this is an issue with Dev Home and the apply configuration from file feature or something else.

**Comment by scottluskcis** [comment]
@AmelBawa-msft, running the `winget configure -f myfile.dsc.yaml` I do receive an error when it tries to apply. 

Example, this is shown first, no error 

```
Apply :: WinGetPackage [vsCode]
  Install Microsoft Visual Studio Code
  Module: Microsoft.WinGet.DSC
  Settings:
    id: Microsoft.VisualStudioCode
    source: winget 
```

Then after confirming to proceed error occurs 

``` 
Apply :: WinGetPackage [vsCode]
  The configuration unit could not be found.
```

**Comment by JohnMcPMS** [comment]
`Microsoft.WinGet.DSC` is a pre-release module, so you would need to set `allowPrerelease: true`.

**Comment by scottluskcis** [comment]
@JohnMcPMS, that was it! Changing `allowPrerelease: true` it now is running without the error. Thank you, will close this one.

**Comment by scottluskcis** [comment]
I'm going to submit a feedback item in a separate ticket. Dev Home reported the code 0x8A15C102 where as running `winget configuration` directly at least gave me the text The configuration unit could not be found. In addition, perhaps some verbiage indicating check the allowPrerelease setting

**Comment by scottluskcis** [comment]
> I'm going to submit a feedback item in a separate ticket. Dev Home reported the code 0x8A15C102 where as running `winget configuration` directly at least gave me the text The configuration unit could not be found. In addition, perhaps some verbiage indicating check the allowPrerelease setting

Filed #1102
