### ISSUE TITLE
Clone a repository / connect advances to page before auth completes

### ISSUE THREAD

**Issue by asklar** [microsoft/devhome#1099]
### Steps to reproduce

Dev Setup tool -> Account -> Select GitHub -> within 5 seconds, the clone a repository dialog updates, before you've completed the github OAuth flow

![image](https://user-images.githubusercontent.com/22989529/226000437-979159d5-4c61-4b36-998e-bc6c6ad0b611.png)

**Comment by dhoehna** [comment]
completed in #1185
