### ISSUE TITLE
Put a spinning ring/Progress ring when getting repos.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#1104]
### Suggested new feature or improvement

When getting repos in the Repo Tool nothing shows on the UI for a few seconds.  Add something to tell the user operations are taking place.

### Scenario

When calling the network to get the repositories for an account.

**Comment by krschau** [comment]
@crutkas This todo came _from_ the PR linked above, it hasn't been committed.

**Comment by crutkas** [comment]
Ahhh
