### ISSUE TITLE
Files on Dev Drive are corrupted and contain all zeros

### ISSUE THREAD

**Issue by marknn3** [microsoft/devhome#1109]
### Dev Home version

0.137.150.0

### Windows build number

10.0.23475.1000

### Steps to reproduce the bug

Mounted and created a Dev Drive D: from a new SSD.

Copying files onto the drive does corrupt the destination files.
The content is all binary zero's, but the size is correct, so this is not noticed at the time of copying.

### Actual result

```
> copy e:\test.html d:\test
        1 file(s) copied.
```
 Now the destination file is corrupted.

![image](https://github.com/microsoft/devhome/assets/4366965/76819749-fd83-4f33-9900-25cd19598bc8)

This also happens e.g. when I do 'Save As' in Edge to save an html page.
This seems to be unrelated to the file type. Some specific files are copied correctly.

Files that are created in VSCode on the Dev Drive seem to be correct.
Same for cloning git repos.

**Comment by snickler** [comment]
@marknn3  - Please also file feedback in Feedback Hub with a repro for this issue since it involves an Insider build.
