### ISSUE TITLE
Files on Dev Drive are corrupted and contain all zeros

### ISSUE THREAD

**Issue by marknn3** [microsoft/devhome#1110]
### Dev Home version

0.200.170.0

### Windows build number

10.0.23481.1000

### Other software

OS Build Version: 10.0.23481.1000.amd64fre.ni_prerelease.230609-1655
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Mounted and created a Dev Drive D: from a new SSD.

Copying files onto the drive does corrupt the destination files.
The content is all binary zero's, but the size is correct, so this is not noticed at the time of copying.

E.g. this simple copy command corrupts the destination file:
copy e:\test.html d:\test
        1 file(s) copied.

### Actual result

The destination file is corrupted, and contains all binary zeroes.
![image](https://github.com/microsoft/devhome/assets/4366965/1c0b9fec-3c70-4e7a-8d54-e4fbc3812089)

This also happens e.g. when I do 'Save As' in Edge to save an html page.
This seems to be unrelated to the file type. Some specific files are copied correctly.

Files that are created in VSCode on the Dev Drive seem to be correct.
Same for cloning git repos.

### Included System Information

CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Physical Memory: 31.94GB (21.11GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe

(Edit: Updated issue with current DevHome and OS versions on 2023-06-23)

**Comment by marknn3** [comment]
Additional information.

When using copy/paste in Exporer I do get this error message:
![image](https://github.com/microsoft/devhome/assets/4366965/e7bb4120-a037-46d4-913f-597c9f61d829)

The file is created, but apparently cannot be written to.

**Comment by marknn3** [comment]
Found the cause of this serious issue!  Turning off virus scanning temporarily does solve the issue.
The protection software is 'KPN veilig' which is based on F-Secure.
Note that for this issue no alarm or message from the protection software is generated at all, also no Event Log. File copying just fails to copy the content.

The new Dev Drive is the only place in my PC which has this issue, which makes it likely that the protection software cannot handle this new configuration (yet).

I have now switched to Windows Defender and have experienced no issues since!

**Comment by bbonaby** [comment]
Thanks @marknn3 we appreciate the effort. Thats a lot of good information you provided and will help us in the future. I'm glad you were able to solve it for now!

**Comment by marknn3** [comment]
Still something bad going on.
I got this fatal error while compiling the dotnet runtime (for some experiments, yeah I know, but it should not crash!) 
![image](https://github.com/microsoft/devhome/assets/4366965/6ff954b0-6ea0-4ed6-9aa5-92799beb6497)

Again I see some 'zero' files in some locations. (Using Windows Defender)
![image](https://github.com/microsoft/devhome/assets/4366965/6afcd34d-a7aa-47d1-99c8-3a938c856a8c)
The json file in the same folder is correct:
![image](https://github.com/microsoft/devhome/assets/4366965/d50e8561-c7c2-4056-a890-a88ff8ce1ff2)

**Comment by marknn3** [comment]
@bbonaby Rerunning the runtime build (after renaming the artifacts folder) eventually resulted in the same crash, although this time it run much further. (Artifacts folder size 3.94 GB v.s. 235 MB after the first crash).

Then I turned off Real-Time protection:
![image](https://github.com/microsoft/devhome/assets/4366965/d1f54ca4-625b-44b8-b909-c424725d4ba3)
Renamed the Artifacts folder and started the build again.
This time the build ran to completion!
![image](https://github.com/microsoft/devhome/assets/4366965/9009e5e3-b8ce-4464-b2cf-5788c43a0919)

Then I turned on Real-Time protection again. Renamed the artifacts folder and started the build again.
And... again crash! This time the artifacts folder was filled with 3.50 GB.

So there seems to be a strong indication towards a generic issue involving Real-Time protection software.
Hope the above 'evidence' will help to pinpoint and fix the rootcause.

**Comment by marknn3** [comment]
To eliminate any hardware related drive issues on my side I did the following:
- Unmounted the M.2 Dev Drive
- Created a new dynamic vhdx Dev Drive of 200GB on an existing SATA drive.
- Cloned the dotnet runtime repo onto the new Dev Drive, and started the build.

Same fatal crash occurs after a few minutes (artifacts folder size 3.94 GB)

**Comment by marknn3** [comment]
I have reproduced the fatal crash in a VM! (Hyper-V)

At first it ran to completion in 1+Hr(...)  With 6 cores, 6GB and Dev Drive as E:.
Then I hard deleted the artifacts folder, changed cores to 8, Memory to 10GB and changed driveletter of Dev Drive to D:.
Started the build again, and within a few minutes the crash occured.

I have saved the MEMORY.DMP and Minidump.

**Comment by marknn3** [comment]
After installing latest Insider Preview: OS Build Version: 10.0.23486.1000.amd64fre.ni_prerelease.230616-1447
I am unable to reproduce the fatal crash.
But I do notice an extreme slowness at step 'Microsoft.NETCore.App.Runtime ->' in the build. This single step took almost 1 hour to complete! And eventually everything run to completion in  01:13:20.43.

**Comment by dhoehna** [comment]
Hi @marknn3,

Thank you for providing this information and taking the time to investigate this issue.  It does seem like an AV is getting in the way.

Can you please file a feedback hub item about this on `Developer Platform/Dev Drive` with all the information you have collected.

I'm going to close this issue because this is an OS and File System issue.
