### ISSUE TITLE
CPU Speed is showing Base Speed

### ISSUE THREAD

**Issue by QuadFlame** [microsoft/devhome#1113]
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Opening the add widgets panel

### Expected result

Show actual CPU Speed 

### Actual result

Showed CPU Base Speed
![image](https://github.com/microsoft/devhome/assets/103904638/30e6e7d2-3acc-433b-8f83-4a3a028b587e)
![image](https://github.com/microsoft/devhome/assets/103904638/13fb1afd-f8d0-482d-93fc-f0e96f698364)

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i9-13900K
Physical Memory: 63.78GB (28.59GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by daxter44** [comment]
I think I have a solution to this problem. 

At the moment the cpu widget shows a processor frequency counter. 
To solve this problem, cpu speed should show  = 'Processor Frequency' * ( '% Processor Performance' / 100);
You can assign this issue to me and i will prepare PR.
