### ISSUE TITLE
Extra feedback option

### ISSUE THREAD

**Issue by andrekolmeijer** [microsoft/devhome#1115]
### Suggested new feature or improvement

An extra feedback option like "General feedback" or "Other".

### Scenario

To give feedback that doesn't categorize in the current options for giving feedback.

### Additional details

I connected my GitHub account and wanted to specify a folder on WSL as the destination. The feedback I actually wanted to give is to specify in the documentation that this isn't possible. Because I read it and watched several video's before hand, because I am using WSL. I was pretty bummed out to discover it didn't work after all that effort. I know Dev Drives don't work with WSL, but I absolutely expected this to work.

**Comment by krschau** [comment]
@andrekolmeijer We do have a docs issue template on the [GitHub web interface](https://github.com/microsoft/devhome/issues/new/choose) but I see that it's not included on the in-app Feedback page. Including it there probably makes sense.
