### ISSUE TITLE
Crashes when doing intial setup

### ISSUE THREAD

**Issue by lightchipster** [microsoft/devhome#1121]
### Dev Home version

0.137.150.0

### Windows build number

10.0.23475.1000

### Other software

OS Build Version: 10.0.23475.1000.amd64fre.ni_prerelease.230602-1331
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Went to Dashboard, clicked on end to end setup. Selected add a repository, selected GitHub and tried to search for my repository.

### Expected result

Add the repository to Github

### Actual result

It crashed

### Included System Information

CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Physical Memory: 15.84GB (8.13GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
@lightchipster are you able to constantly repro this crash?
