### ISSUE TITLE
Create Dev Drive on Unallocated Space on disk 0 failes

### ISSUE THREAD

**Issue by creadicted** [microsoft/devhome#1127]
### Dev Home version

0.137.150.0

### Windows build number

10.0.23475.0

### Other software

Its the process of creating a Volume

### Steps to reproduce the bug

I am currently working with a single hard drive that has a 'C' partition as well as unallocated space. I've been trying to create a  'Dev Drive'.

Here's what I've done so far:

1.     I selected the "Unallocated Space on Disk 0" which has approximately 150 GB of free space.
2.     I assigned it the name "Dev" and the drive letter "D".
3.     I kept the rest of the options at their default settings and clicked "Format".

### Expected result

The Dev Drive is created with the right name

### Actual result

The volume appears to be created, but immediately after, I receive an error message stating that the formatting of the volume failed. As a result, I now have a "RAW" partition that does not have a name, and I cannot interact with it in any way.

**Comment by bbonaby** [comment]
hi @creadicted I believe you may have attempted to create a Dev Drive from the Windows Settings app. If that is the case, can you submit a bug via the Windows Feedback hub for this issue? You can quickly get there by typing the Windows Key + F

Thanks for submitting this!
