### ISSUE TITLE
Settings Preference page out of spec

### ISSUE THREAD

**Issue by TWhiteDesigns** [microsoft/devhome#1142]
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1848

### Other software

OS Build Version: 10.0.22621.1848.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Open Dev home > Click settings icon in lower left side nav > click Preferences. 

### Expected result

Currently, the preferences setting page has the theme selection via radio buttons when it should be shown as a drop down selector. Additionally, the 'Start Dev Home when I sign into Windows' and 'Hide get started content' features are missing. They are both controlled vis an on/off toggle 

### Actual result

Preference Settings page is missing two features controlled by on/off toggle switches. and the Theme selector is shown as radio buttons when it should be a dropdown list. 

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
Physical Memory: 31.85GB (11.45GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.GitHub_1.0.0.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
@TWhiteDesigns Could you please link to or screenshot the design spec? 

The "Start Dev Home when I sign into Windows" is covered by #1042 @ujjwalchadha

**Comment by TWhiteDesigns** [comment]
Actual results:
<img width="906" alt="image" src="https://github.com/microsoft/devhome/assets/127447480/5f85b65d-1edd-49d7-b829-17f34281b0c5">

Expected results:
<img width="589" alt="image" src="https://github.com/microsoft/devhome/assets/127447480/994eb277-d3fd-4068-9436-5d27b487523a">
