### ISSUE TITLE
Settings breadcrumb elements out of Spec

### ISSUE THREAD

**Issue by TWhiteDesigns** [microsoft/devhome#1143]
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1848

### Other software

OS Build Version: 10.0.22621.1848.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Open Dev Home > Click Settings icon in lower left nav > Select any settings L2 > Observe breadcrumb trail e.g, Settings > Accounts

### Expected result

When in an L2 page like 'Accounts' the bread crumb link 'Settings' remains filled in the primary text color, When it should be filled in the secondary text color. 

The chevron between the two bread crumb links appears to be too small and is vertically shifted up from center. recommended to increase chevron size ( to 16px if not already) and ensure vertical center alignment with the breadcrumb text links.

### Actual result

first text link remains in the primary text color when on L2's (should be secondary text color)

Chevron is vertically shifted up from center and appears too small.

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
Physical Memory: 31.85GB (11.81GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.GitHub_1.0.0.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by TWhiteDesigns** [comment]
actual results:
<img width="314" alt="image" src="https://github.com/microsoft/devhome/assets/127447480/4b62cbf5-cb71-4a71-9432-b820037f3ba3">

Expected results:
<img width="352" alt="image" src="https://github.com/microsoft/devhome/assets/127447480/1bbaaf39-0711-4266-a8d1-c1bf4e664f16">

**Comment by aqibbanday** [comment]
i am looking into this.

**Comment by aqibbanday** [comment]
It seems the issue is with the control not the DevHome app

**Comment by cinnamon-msft** [comment]
This might be something we'd have to resolve with the WinUI folks - I'm not sure we should start doing custom styling on their controls when we may want the control itself to be changed for everyone
