### ISSUE TITLE
[DSC] SampleConfigurations enhancements

### ISSUE THREAD

**Issue by AmelBawa-msft** [microsoft/devhome#1154]
### Provide a description of requested docs changes

- Add repo link in the header comment:
  - [dotnet/aspnetcore/configuration.dsc.yaml](https://github.com/microsoft/devhome/blob/main/sampleConfigurations/dotnet/aspnetcore/configuration.dsc.yaml)
    - Resource `Microsoft.VisualStudio.DSC/VSComponents` requires repo to be cloned
- Update winget package:
  - [PowerShell/PowerShell/configuration.dsc.yaml](https://github.com/microsoft/devhome/blob/main/sampleConfigurations/PowerShell/PowerShell/configuration.dsc.yaml)
    - Resource `Microsoft.WinGet.DSC/WinGetPackage` is referencing a [package id that was removed from winget-pkgs repo](https://github.com/microsoft/winget-pkgs/pull/95206).

**Comment by alexravenna** [comment]
@AmelBawa-msft regarding the ASP.NET Core configuration: do you mean this repo has to be cloned? If so, why? For the `${WinGetConfigRoot}\..\.vsconfig`?

**Comment by AmelBawa-msft** [comment]
I believe for this YAML we need to add a header comment referencing the [ASP.Net Core](https://github.com/dotnet/aspnetcore) repo. Correct, it's just a hint for the user to clone the ASP.Net Core repo before running the DSC configuration YAML (after placing it in `aspnetcore/.configurations/configuration.dsc.yaml`). The `${WinGetConfigRoot}` will be replaced at runtime by the config file absolute path.

CC: @ryfu-msft

**Comment by alexravenna** [comment]
Okay, thanks for the clarification! I've updated the PR 😃.
