### ISSUE TITLE
Missing telemetry when user clicks on Configure DevDrive from DevHome app

### ISSUE THREAD

**Issue by subhasan** [microsoft/devhome#1155]
### Steps to reproduce the bug

No event emitted when user click on configure DevDrive from DevHome, blocking us from measuring DevDrive conversion rate.

### Expected result

The telemetry should track DevDrive creation initiation through both the available options(Screenshot below) in DevHome. 
Option 1:
![image](https://github.com/microsoft/devhome/assets/105677616/95bb7186-6f05-4a41-870d-9933dc30c135)
Option 2:
![image](https://github.com/microsoft/devhome/assets/105677616/432ce673-236d-4aae-a129-5bcaff59086c)

_No response_

### Actual result

No event emitted when user click on configure DevDrive from DevHome, blocking us from measuring DevDrive conversion rate.

**Comment by bbonaby** [comment]
I believe we actually have telemetry for the first one here: https://github.com/microsoft/devhome/blob/aa68e6561cfc84fb660f757108739771d0be98a1/tools/SetupFlow/DevHome.SetupFlow/TelemetryEvents/DevDriveTriggeredEvent.cs#L14

the provider name is Microsoft.Windows.DevHome  and the eventName is CreateDevDriveTriggered. This gets triggered when a user creates a Dev Drive from Dev Home. 

@subhasan we get the duration, error code, size of the drive in bytes and the media type. 

Let me know if this is what you were looking for, thanks.

**Comment by subhasan** [comment]
***@***.***
________________________________

**Comment by chenyingMS** [comment]
As mentioned before, we would like to fire the event CreateDevDriveTriggered as well when user click "Create Dev Drive" from "Introducing Dev Home" tab. In this way we could know how many users try to create the DevDrive.
![image](https://github.com/microsoft/devhome/assets/128636403/67d55c10-54f6-4e29-904f-b2996301c33b)

**Comment by dhoehna** [comment]
@chenyingMS The CreateDevDrive button launches the settings page it does not add a task that will create a dev drive.  Adding a telemetry event to this button would not signify if a Dev Drive is going to be made, but the intent, or, curiosity, of making one.

I would guess that the settings app has their telemetry if a user creates a DevDrive inside the settings app.

I feel that adding telemetry to a button that only opens a settings app, will not answer the question "How many users try to create a dev drive"

**Comment by chenyingMS** [comment]
@dhoehna @subhasan 
There is an exiting event Microsoft.Windows.DevHome.LaunchDisksAndVolumesSettingsPageTriggered. It is fired when the setting page pop out. Here are 2 scenarios. The data field have "MainPageView" and "DevDriveView" for each of them.
1. 
![image](https://github.com/microsoft/devhome/assets/128636403/4f46efb3-a858-4e1e-851f-20e1c522cada)

2.
![image](https://github.com/microsoft/devhome/assets/128636403/d26dd055-d3b5-46de-b4ca-878ac86ddac8)

For this below scenario, there is no such event that we will miss the amount of user clicks from here. So please add the same event but with different view page. I think this will help us to know all the amount of the users that try to see and click the Create DevDrive.
![image](https://github.com/microsoft/devhome/assets/128636403/7eec453e-5e06-40ed-9564-78d600779bed)
