### ISSUE TITLE
Botão X para fechar janelas dentro do app não funciona

### ISSUE THREAD

**Issue by lucashahnndev** [microsoft/devhome#1161]
### Dev Home version

0.200.165.0

### Windows build number

10.0.22621.1848

### Other software

OS Build Version: 10.0.22621.1848.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Botão X para fechar janelas dentro do app não funciona

### Actual result

Botão X para fechar janelas dentro do app não funciona

### Included System Information

CPU: Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
Physical Memory: 3.87GB (0.53GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.165.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Bing Translate:

X button to close windows inside app not working
X button to close windows inside the app doesn't work

**Comment by krschau** [comment]
@lucashahnndev I'm guessing in this situation, the X of the window is on top of the main window's title bar. That issue is being tracked by #537. If you don't think that describes the situation you're seeing, please comment again and we'll reopen this issue.
