### ISSUE TITLE
Cloning a repository to a new Dev Drive fails

### ISSUE THREAD

**Issue by Georgios1999** [microsoft/devhome#1180]
### Dev Home version

0.200.165.0

### Windows build number

10.0.23481.1000

### Other software

OS Build Version: 10.0.23481.1000.amd64fre.ni_prerelease.230609-1655
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Go to Machine Configuration > End to End Setup
Clone any repository from GitHub, and set it to get cloned to a new Dev Drive
Procceed with the setup

### Expected result

The repository to be successfully cloned in a newly created Dev Drive

### Actual result

Immediate failure message. The setup also ends

### Included System Information

CPU: AMD Ryzen 9 5900X 12-Core Processor            
Physical Memory: 63.92GB (56.92GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by bbonaby** [comment]
Also, @Georgios1999 can you take a screenshot of what your Settings disks and volumes page looks like as well?

you can access this by doing the following:

1. Windows key + R 
2. type ms-settings:disksandvolumes into the textbox
3. Select the "OK" button

I just want to confirm that the top part of the page looks like this:

![top part of disks and volumes page when Dev Drive feature is enabled in the Windows OS](https://github.com/microsoft/devhome/assets/105318831/6a482a3d-f2db-4df3-99ea-cdb9617f7628)


That will let me know if the feature is enabled on your machine.

**Comment by Georgios1999** [comment]
Hi, @bbonaby! Thanks for reaching out. Here is the image you asked for containing the info about the drives in Settings > Storage > Disks & volumes:
![image](https://github.com/microsoft/devhome/assets/75626470/fade2471-3540-46e4-adc2-010295c90acd)

**Comment by Georgios1999** [comment]
Hello, @EricJohnson327! After installing the latest update and trying again, the Dev Drive was successfully created and the repository was cloned in it as well with no issues! Should I close the issue now?

**Comment by EricJohnson327** [comment]
Great! Glad to hear it's working for you now!
