### ISSUE TITLE
Have CPU widget show thermal throttling

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#1196]
### Suggested new feature or improvement

If a CPU thermal throttle has been happening, have me become aware via the CPU widget

### Scenario

I'm on my laptop and wondering why my build may be slow.  Knowing clearly my system is thermal throttling could be helpful to allow me to know about something that is possibly impacting my performance

**Comment by cinnamon-msft** [comment]
Duplicating this to #1238
