### ISSUE TITLE
Left part of a pane will have the contents of the pane above it rather instead of the contents of the pane

### ISSUE THREAD

**Issue by jtschuster** [microsoft/devhome#1208]
### Dev Home version

0.200.170.0

### Windows build number

10.0.23481.1000

### Other software

OS Build Version: 10.0.23481.1000.amd64fre.ni_prerelease.230609-1655
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Open any menu item with multiple panes / tiles. The first half of a character or icon is from the pane above it. It changes to look correct when the tile is being hovered over.

<img width="849" alt="Screenshot 2023-06-26 131811" src="https://github.com/microsoft/devhome/assets/36744439/f782ae4a-2858-4a30-bb79-66af77440127">

### Expected result

The tiles should look correct

### Actual result

The tiles have a half character from another tile on the left side 

### Included System Information

Physical Memory: 63.95GB (51.47GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe

**Comment by balaji-sivasakthi** [comment]
![image](https://github.com/microsoft/devhome/assets/65065614/7424c1ce-92e0-47c6-af4b-4c058529687e)

**Comment by balaji-sivasakthi** [comment]
Hi @jtschuster, I think you should double check your `Dev Home` with our recent version.

**Comment by krschau** [comment]
I think this is a rare, transient WinUI issue.
