### ISSUE TITLE
Banners misaligned in RTL

### ISSUE THREAD

**Issue by krschau** [microsoft/devhome#1209]
### Dev Home version

0.2

### Steps to reproduce the bug

Use a right-to-left language. Banner looks like screenshot in #744

### Actual result

Banner looks like screenshot in #744

**Comment by cinnamon-msft** [comment]
I'm just going to dupe this to #744 since this seems like all the same problem

/dup of #744

**Comment by krschau** [comment]
@cinnamon-msft I opened this because I specifically think it's a different issue. The Banner is a user control we just have no RTL support for. I opened #1320 to fix it.
