### ISSUE TITLE
Show loading screen errors in the summary screen.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#1228]
### Suggested new feature or improvement

Errors in the loading screen are not sent to the summary screen for easy viewing.  The summary screen should be smart and metnion errors.

### Scenario

In the summary screen.

**Comment by cinnamon-msft** [comment]
I think this is fixed, given the latest summary page I just produced. Error logs are displayed on the top left:
![image](https://github.com/microsoft/devhome/assets/48369326/b444f36f-97a0-4b88-9bea-fcf9346b32f9)

**Comment by krschau** [comment]
I believe this was fixed by #1583
