### ISSUE TITLE
Repo filter should filter on contains, and not startOf

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#1232]
### Suggested new feature or improvement

StartOf is a rudimentary way of filtering repositories.  Change to `Contains` to make it a bit better.

### Scenario

In the repo page.

**Comment by dhoehna** [comment]
Fixed in #2140

**Comment by krschau** [comment]
@dhoehna Please set the milestone on issues when you close them as fixed, thanks! It helps with release notes and future triage.
