### ISSUE TITLE
dark mode doesn't work

### ISSUE THREAD

**Issue by asdrubalp9** [microsoft/devhome#1234]
### Dev Home version

0.200.170.0

### Windows build number

10.0.22621.1848

### Other software

OS Build Version: 10.0.22621.1848.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

set the configuration to dark and it will look extraordinarily weird and not dark. 

### Expected result

to set the dark mode theme correctly

### Actual result

I set the configuration to dark mode and looks bad/weird but not dark. 

image: https://prnt.sc/tTn62BpvIF4h

### Included System Information

Physical Memory: 29.94GB (7.12GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
@asdrubalp9 Do you remember what the theme was set to before you changed it to "Dark" (ie. "Light" or "Default")? Also, can you tell me what theme your OS is set to? (Under Windows settings > Personalization > Themes?) I'm interested to know if that one is a light or dark theme.

**Comment by asdrubalp9** [comment]
I hople this helps:
https://prnt.sc/rumSOipj_ePB
its windows 11.
sorry for the delay

**Comment by krschau** [comment]
That was plenty fast! And helpful.

I think I know what's going on. This issue originally popped up in #511, where the issue originally called out that this only happened on the first launch. We fixed a bunch of other theming issues, and they all got bundled together into that one. But the first launch issue in particular was not fixed. Then it was opened again as #993, but we duped that to 511, thinking we had fixed it.

If you re-open Dev Home and try again to switch to dark mode, do you still see the same bad UI or does it look ok? I want to narrow down that this is indeed a first launch thing.

**Comment by krschau** [comment]
Duplicate of #993
