### ISSUE TITLE
Instalación VS

### ISSUE THREAD

**Issue by mnieto1973** [microsoft/devhome#1237]
### Dev Home version

0.200.170.0

### Windows build number

10.0.22621.1928

### Other software

OS Build Version: 10.0.22621.1928.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

no reconoce la instalación de Visual studio distinta de la commmunity

### Actual result

No reconoce mi instalacion de Vs 2022

### Included System Information

Physical Memory: 31.2GB (11.51GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe

**Comment by AmelBawa-msft** [comment]
@mnieto1973, to make sure I understand the issue, do you have multiple visual studio installed, and only the community edition is being detected in Dev Home as installed?

If you run the command below in cmd/powershell, do you see all the installed visual studio packages or some are missing? Dev Home uses this list to mark packages as installed on the UI, hence it will be helpful to compare the command output with what Dev Home shows on the UI.
```ps
winget list visualstudio
```

**Comment by AmelBawa-msft** [comment]
Thank you for the clarification on the target edition of Visual studio. If you search in Dev Home for "visual studio professional", does it show that the package is not installed? Here's a screenshot for reference where visual studio professional is not installed:
<img src="https://github.com/microsoft/devhome/assets/104940545/67983a8e-7bba-4011-bf10-f4fdeca42f9e" Width="500" />

From powershell/cmd, you can also verify if the target package is detected using winget:
```ps
winget list visualstudio
```
