### ISSUE TITLE
GitHub extension PRs and issues are not persisting after restart

### ISSUE THREAD

**Issue by AlexPshul** [microsoft/devhome#1250]
### Dev Home version

0.200.170.0

### Windows build number

10.0.23493.1000

### Other software

OS Build Version: 10.0.23493.1000.amd64fre.ni_prerelease.230624-1828
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. Add pinned widgets for PRs and issues from GitHub
2. Restart the PC
3. Open Dev Home

### Expected result

To see the pinned widgets on the dashboard

### Actual result

The dashboard has no widgets at all

### Included System Information

Physical Memory: 31.69GB (12.64GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Duplicate of #742
