### ISSUE TITLE
Please Publish a winget package

### ISSUE THREAD

**Issue by AndrewOttavianoAbb** [microsoft/devhome#1263]
### Suggested new feature or improvement

Please publish a winget package as this would help with automated installs.

### Scenario

Configuring a developer's new laptop could be completely automated if this app could be installed via winget. Additionally, developers could install it on their machines if they don't have access to the store.

**Comment by KevinLaMS** [comment]
@AndrewOttavianoAbb  Are you asking for being able to install DevHome via winget?
If so, it is already available.  See below:

C:\Users\>winget search devhome
Name               Id                Version     Match            Source
------------------------------------------------------------------------
Dev Home (Preview) Microsoft.DevHome 0.200.170.0 Moniker: devhome winget

**Comment by AndrewOttavianoAbb** [comment]
![image](https://github.com/microsoft/devhome/assets/78449844/bf68e183-0132-4cee-a2aa-685bdbf64309)
Is the winget version installable on windows 10? I remember seeing a PR or issue somewhere about adding win 10 support, I guess that hasn't been added yet? I'm probably just hallucinating (I promise I'm not an AI 😆).

**Comment by krschau** [comment]
@AndrewOttavianoAbb You're not hallucinating :-) But Dev Home is not currently available on Windows 10.
