### ISSUE TITLE
Extensions not loading

### ISSUE THREAD

**Issue by sean351** [microsoft/devhome#1266]
### Dev Home version

0.200.170.0

### Windows build number

10.0.23493.1000

### Other software

OS Build Version: 10.0.23493.1000.amd64fre.ni_prerelease.230624-1828
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Tried to add GitHub accounts. The popup said I needed to install extensions, when I go to the "Extensions" section of Settings tab, it is blank.

### Expected result

List of extensions to appear

### Actual result

blank page

### Included System Information

Physical Memory: 15.91GB (10.09GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe

**Comment by sean351** [comment]
I solved this issue. I guess I needed to go into the Microsoft Store and download the GitHub extension. 

Would be nice to also display the  extensions inside the Dev Home app.

**Comment by krschau** [comment]
The GitHub Extension should have been automatically installed by Dev Home. As for displaying the available extensions, we have #676.
