### ISSUE TITLE
[Perf] Improve launch perf

### ISSUE THREAD

**Issue by asklar** [microsoft/devhome#128]
### Steps to reproduce

This is to track / dependent on a XAML bug [8281](https://github.com/microsoft/microsoft-ui-xaml/issues/8281)

**Comment by AmelBawa-msft** [comment]
@manodasanW @asklar  can I close this issue? Looks like we're now using 1.3.2
```csproj
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.3.230331000" />
````

**Comment by AmelBawa-msft** [comment]
Closing. Please re-activate if necessary.
