### ISSUE TITLE
Error creating development unit

### ISSUE THREAD

**Issue by RAASORG** [microsoft/devhome#1280]
### Dev Home version

0.200.170.0

### Windows build number

10.0.23493.1000

### Other software

OS Build Version: 10.0.23493.1000.amd64fre.ni_prerelease.230624-1828
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Abrir Dev Home
Abrir Configuración del Equipo
Clonar Repositorio
Crear una unidad de desarrollo
ejecutar

### Expected result

Clonar el repositorio en el nuevo directorio, que es la nueva unidad de dsico

### Actual result

Error al crear unidad de desarollo

### Included System Information

Physical Memory: 7.35GB (3.09GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Bing Translate:

**Steps to reproduce the bug**
Open Dev Home
Open Machine Configuration
Clone Repository
Create a development unit
execute

**Expected result**
Clone the repository to the new directory, which is the new disk drive

**Actual result**
Error creating development unit

**Comment by kanismohammed** [comment]
@RAASORG  - Are you still hitting the issues in the latest windows insider flights?

**Comment by kanismohammed** [comment]
@RAASORG  - I was not able to repro the issue in the latest version. Please reach out if you are still hitting this issue.

**Comment by kanismohammed** [comment]
@RAASORG - I was not able to repro the issue in the latest version. Please reach out if you are still hitting this issue.
