### ISSUE TITLE
Small version of CPU / GPU / Network widgets are not useful, graphs do not resize

### ISSUE THREAD

**Issue by embender** [microsoft/devhome#1281]
### Dev Home version

0.200.170.0

### Windows build number

Version	10.0.23493 Build 23493

### Steps to reproduce the bug

Add all of the default widgets that come with Dev Home and set the size of the widgets to small, the graphs do not resize so that the information fits within the new panel size for the widgets. Having to scroll down to see relevant information makes this widget useless when in this small state and would be most useful if the small widget only displayed the graph with the medium size then having more information to be displayed within the widget.

Large widget sizes also do not seem relevant for the CPU, GPU, Network and Memory widget as the larger sizes do not display more information. 

### Expected result

The graph would fit neatly within the small widget so I could see all information at a glance

### Actual result

<img width="752" alt="image" src="https://github.com/microsoft/devhome/assets/44589070/a9b485e0-177a-47e1-a96c-4ba8f2bd4bab">

**Comment by guimafelipe** [comment]
A possibility here is in the case of a small sized widget, we use a different template only showing the graph, but without the buttons and scroll, for a more compact experience in the cost of a bit less functionality.

**Comment by chendrixson** [comment]
Working on this.
