### ISSUE TITLE
CPU widget End Process list updates too quickly

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#1284]
### Dev Home version

0.301.191.0

### Steps to reproduce the bug

Try clicking End Process on a process listed in the CPU widget

### Expected result

I'd expect that item to persist long enough for me to end its process.

### Actual result

The list seems to update every second when the graph updates, which caused me to accidentally close the wrong app because the button changed beneath my mouse.

**Comment by krschau** [comment]
@cinnamon-msft How often should it update? Should there be an "are you sure?" message?

**Comment by guimafelipe** [comment]
This is also an accessibility bug. When navigating with keyboard (for people that use narrator for example or just don't have a mouse at the moment), the keyboard focus is reset almost every 2 seconds, making it impossible to navigate in the widget and operate it.

**Comment by cinnamon-msft** [comment]
Could we maintain focus if the keyboard or mouse is hovering over an item and not have the list update?
