### ISSUE TITLE
Repositories and tools suggestion

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/devhome#1301]
### Suggested new feature or improvement

ITNOA

I think it is good to suggest missing repositories and tools in local machine based on Microsoft Account stored information of my previous dev machine.

### Scenario

1. Add new sub menu for repositories
2. Add new sub menu for dev tools
3. After scanning and identifying locally existing warehouses and tools #702 
4. Make diff from Cloud stored information of sync repositories and tools, and suggest installing those (such as roaming extension feature in Visual Studio)

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/devhome/issues/702
```

**Comment by soroshsabz** [comment]
related to #375

**Comment by cinnamon-msft** [comment]
I think this is something that would be handled through the GitHub repository cloning tool and the install applications tool. I don't think we want to have a separate page for these scenarios when Machine configuration can handle them with some feature augmentation :)

**Comment by soroshsabz** [comment]
@cinnamon-msft It is not relevant with GitHub (Repo maybe exists in anywhere), and this feature suggestion about helping developer to better bootstrapping new machine with fluent way and GUI base, without using solid and non-interactive approach like Machine configuration

 I think Repo is very important parts of developing env, So adding new menu for organizing repos on local machine can very useful for better productivity

So please reopen this issue
