### ISSUE TITLE
Repo cloning should have handling for Max Path

### ISSUE THREAD

**Issue by btueffers** [microsoft/devhome#1302]
### Steps to reproduce the bug

Attempt to clone a repo in a way that creates a path longer than Max_Path. For example, "C:\Users\<username>\Desktop\ThisIsAReallyLongPath\ThisIsEvenALongerLongerPath\AnEvenLongerPathThatIsAwesomeAndWontBreakTheLimitYet\LongLongerLongestThisIsALongFolderPathThatIsSoCool\ThisIsAClonePathPleaseCloneHereToBeAweomse". 

### Actual result

The clone fails with an exception without the error message. This exception happens with or without the regkey set.

**Comment by dhoehna** [comment]
Closing as not fixing because this is the same behavior in git.  However, PR [#386](https://github.com/microsoft/devhomegithubextension/pull/386) allows the extension to pass back the "Path too long" message.
