### ISSUE TITLE
cant login to github in dev home

### ISSUE THREAD

**Issue by Cvayay** [microsoft/devhome#1303]
### Dev Home version

0.200.170.0

### Windows build number

10.0.23493.1000

### Other software

OS Build Version: 10.0.23493.1000.amd64fre.ni_prerelease.230624-1828
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

login to github in dev home

### Expected result

login to github in dev home

### Actual result

cant login to github in dev home

### Included System Information

Physical Memory: 7.42GB (0.65GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
@Cvayay Can you please give more details about what happened when you tried to log into GitHub? Was there an error message? Did the browser not come up?
