### ISSUE TITLE
Update RepoTool_AddRepos_Event to critical event

### ISSUE THREAD

**Issue by chenyingMS** [microsoft/devhome#1308]
### Suggested new feature or improvement

We are trying to understand and analyze the drop off point of the DevDrive creation from DevHome App.
As the DevDerive creation related events are critical, we would like to make the previous step event critical as well. Then the  creation process events' data could match each other.

We will create the Funnel for DevDrive creation based on the events in the creation process
1. RepoTool_AddRepos_Event
2. CreateDevDrive_CreatingDevDrive_Event
3. CreateDevDriveTriggered

### Scenario

Update RepoTool_AddRepos_Event from measure to critical event

**Comment by bbonaby** [comment]
@dhoehna I saw you made this #1328 yesterday. Should this issue just be duplicated to that issue? Since you're going to make them all critical anyway?
