### ISSUE TITLE
Can't create Dev Drive

### ISSUE THREAD

**Issue by shaibarlev** [microsoft/devhome#1311]
### Dev Home version

0.301.198.0

### Windows build number

10.0.25905.1000

### Other software

OS Build Version: 10.0.25905.1000.amd64fre.rs_prerelease.230707-1739
.NET Version: .NET 6.0.18

### Steps to reproduce the bug

Press the create Dev Drive , The Windows Settings ->Storage ->Disk & Volumes get open. But there is no option to set anything

### Expected result

To have The Option to create a Dev Drive

### Actual result

No Option

### Included System Information

Physical Memory: 63.62GB (36.78GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe

**Comment by XenoPanther** [comment]
This is an issue with build 25905 itself. There's also an issue where you can't create a dev drive due to REFS not being supported. Should hopefully be fixed in the next flight

**Comment by cinnamon-msft** [comment]
I'm going to close this out, since this is a Windows bug and not a Dev Home bug :)
