### ISSUE TITLE
Does Dev Home work on Virtual Machine? having issue launching the app

### ISSUE THREAD

**Issue by gitunder** [microsoft/devhome#1316]
### Dev Home version

0.301.198.0

### Windows build number

Windows 11 version 22H2 build 22621.1992 on Azure and VMWARE v7

### Other software

I enabled developer mode and used winget to install dev home along with SDK on VMWARE/AZURE VM.  When i try to launch Dev Home, nothing happens.  Is Dev Home compatible on a virtual machine or it can only be installed on a physical 

### Steps to reproduce the bug

1. Enabled Developer Mode in Settings
2. Ran the following in PowerShell:
    - winget install --id "Microsoft.WindowsAppRuntime.1.3" -e
    - winget install --id "Microsoft.DevHome" -e
 3. Launch Dev Home and nothing happens

**Comment by AmelBawa-msft** [comment]
@gitunder, Dev Home should run fine on a VM (just tested it from my end). This issue is likely related to an instant crash that is happening for a subset of users since the first release version.
