### ISSUE TITLE
Clarify information and behavior of Dev Drive card on "Introducing Dev Home" page

### ISSUE THREAD

**Issue by btueffers** [microsoft/devhome#1334]
### Suggested new feature or improvement

When clicking the "Create Dev Drive" button is not clear to the user that they will be leaving Dev Home.

### Scenario

User is on the "Introducing Dev Home" page and sees the card for Dev Drive there is no indication that another app will be opened.

**Comment by cinnamon-msft** [comment]
I think this can be conveyed by adding this icon to the button/card:
![image](https://github.com/microsoft/devhome/assets/48369326/57b7164c-a483-4582-95e0-79831b9ab328)

We have it on the machine configuration page, but not on the Introducing Dev Home page
