### ISSUE TITLE
0x80131500 error

### ISSUE THREAD

**Issue by sarojm-MSFT** [microsoft/devhome#1336]
### Dev Home version

0.301.198.0

### Windows build number

10.0.25919.1000

### Other software

OS Build Version: 10.0.25919.1000.amd64fre.rs_dplat.230726-1400
.NET Version: .NET 6.0.18

### Steps to reproduce the bug

Create a new repo

### Expected result

success or failure with a message that I can understand.

### Actual result

I get 0x80131500.

Whats the meaning of 0x80131500

### Included System Information

Physical Memory: 63.59GB (52.02GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe

**Comment by JustLeska** [comment]
I got the same error:

![](https://filestore.community.support.microsoft.com/api/images/bbd9161d-36fc-4086-b787-8f187f74a2bc?upload=true&fud_access=wJJIheezUklbAN2ppeDns8cDNpYs3nCYjgitr%2bfFBh2dqlqMuW7np3F6Utp%2fKMltnRRYFtVjOMO5tpbpW9UyRAwvLeec5emAPixgq9ta07Dgnp2aq5eJbnfd%2fU3qhn54RjvtPcGDvZJT5H6fE3Ey3luzCtmta%2bNGlTjV60rl2UShbltIVjjopSv7UCoZfjTXlslOUdEucOlGt9r87Pku6Q5sqCA9OqVk4EbZ7XirkpS4PiuW0D%2f2gNhAU4ctcKWI1u3qpmlw4n99hw2tVvQpOLL61OFcAYJ1L%2b8W2B4z6HlKmRorOqI7Cz8dzG%2bU2HGcMeX7XTnO8S6DyuFMM8IiA8C1QYMefcdaNIHdKhJm%2b5uuwQh99gZ6hkoYhctxkOvZHp6vKol6egp7ArPpugEH7WaRTKIm4AC9Kax%2fLdvkq2I%3d)

**Comment by Gurrman375** [comment]
I experienced this just now. What helped me was clearing the app data and going through the process again.

**Comment by dhoehna** [comment]
This is an issue with older versions of DevHome.  Can you please update to the newest version of DevHome?  That should have more clear error messages.

**Comment by AdvitSphinX** [comment]
Is this issue resolved?

**Comment by Gurrman375** [comment]
Yes this issue was resolved. I reinstalled the app and it got updated and fixed the issue.

**Comment by coendewit** [comment]
Just installed dev home minutes ago and after setting up the dev drive and I got this exact error cloning the first repository from GitHub. Regression?

**Comment by Gurrman375** [comment]
> Just installed dev home minutes ago and after setting up the dev drive and I got this exact error cloning the first repository from GitHub. Regression?

Check what I posted above and see if that fixes your issue.

**Comment by coendewit** [comment]
Thanks, but reinstalling a freshly installed app? I lost interest in the product that solves a git clone with errors.

**Comment by Gurrman375** [comment]
You clearly haven't if your posting back here. The option is available to you when you want to reinstall.

**Comment by dhoehna** [comment]
Hi @coendewit thank you for posting this issue.  You said you did install DevHome minutes ago and got this issue.  I am sorry about the poor experience.  If after re-installing, the issue persists, please open a new issue so we can start investigating.
