### ISSUE TITLE
could not use FOXPRO 6.0

### ISSUE THREAD

**Issue by schoetz-tang** [microsoft/devhome#1343]
### Dev Home version

0.301.198.0

### Windows build number

10.0.23511.1000

### Other software

OS Build Version: 10.0.23511.1000.amd64fre.ni_prerelease.230722-2325
.NET Version: .NET 6.0.18

### Steps to reproduce the bug

after update to build 23511.ni_prerelease, we could not wake up FOXPRO 6.0

### Expected result

FOXPRO 6.0 was dead

### Actual result

NO any response for FOXPRO 6.0

### Included System Information

Physical Memory: 7.84GB (2.05GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Closing, since this doesn't sound related to Dev Home.
