### ISSUE TITLE
UAC timeout and application auto downloads  

### ISSUE THREAD

**Issue by ianyyu** [microsoft/devhome#1376]
### Dev Home version

0.301.198.0

### Windows build number

10.0.22621.1992

### Other software

OS Build Version: 10.0.22621.1992.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.18

### Steps to reproduce the bug

When user don't answer the UAC prompt, and it hits timeout, dev home auto start downloading app process, and show apps downloaded successfully even though app not actually downloaded

### Expected result

UAC timeout should terminate the app download experiences or end to end set up flow 

### Actual result

Dev Home auto starts the set up process, and UI show ap downloaded successfully 

### Included System Information

Physical Memory: 15.95GB (9.75GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe

**Comment by AmelBawa-msft** [comment]
In latest Dev Home, if the UAC was canceled or it timed out, the user has to click on "Set up" again to re-prompt the UAC for confirmation.
