### ISSUE TITLE
Title for installing application

### ISSUE THREAD

**Issue by MirolimMajidov** [microsoft/devhome#1388]
### Suggested new feature or improvement

Show the title of installing resources or configurating settings while installing application using configuration yaml file

### Scenario

I have  configuration yaml file to install lot of applications and setting up some configurations.
When I select config file and appley the changes, after some processing,  it will show the list of resources with the passed or failed status, but it does not have title. There is no way to know which one is failed or passed. 

### Additional details

That would be great if we could show the title. at less a description.

**Comment by MirolimMajidov** [comment]
I hope that would be implemented in this [PR](https://github.com/microsoft/devhome/pull/912)

**Comment by cinnamon-msft** [comment]
Hey Mirolim, we've just merged https://github.com/microsoft/devhome/pull/912, does it solve your request?

**Comment by MirolimMajidov** [comment]
> Hey Mirolim, we've just merged #912, does it solve your request?

Hi @cinnamon-msft,
It still is not showing intalling an application, but it more clear than before. When everything are done, it is showing all installed applications with the discription.  I will close the issue, I hope other part also will implemented as soon as posible.
Thank you for letting me know.
