### ISSUE TITLE
Dashboard breaks when running as admin

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#1391]
### Dev Home version

0.401.219.0

### Steps to reproduce the bug

Have widgets pinned to your dashboard when not running as admin.
Right click on Dev Home in the Start menu and launch as administrator.

### Expected result

The widgets I had pinned should still be visible.

### Actual result

Dashboard continues to spin and also display the "no widgets pinned" message
![image](https://github.com/microsoft/devhome/assets/48369326/c33dbe04-2b14-4bc7-b730-188b816243f9)

**Comment by krschau** [comment]
From my log:

[DashboardView] INFO: Register with WidgetHost
[DashboardView] ERROR: Exception in InitializeWidgetHost:
System.Runtime.InteropServices.COMException (0x800401F7): Some error in application program (0x800401F7 (CO_E_ERRORINAPP))
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.Windows.Widgets.Hosts.IWidgetHostStaticsMethods.Register(IObjectReference _obj, WidgetHostContext context)
   at DevHome.Dashboard.Views.DashboardView.InitializeWidgetHost()
[DashboardView] INFO: Get HostConfig file 'HostConfigLight.json'

**Comment by EricJohnson327** [comment]
Unfortunately, by design.  Creating the widgets uses out-of-proc COM which does not by default support creation at lower privilege levels (Dev Home admin trying to create a widget from user level extension).
