### ISSUE TITLE
Dev drive opt-out defaults to documents, not source 

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#1394]
### Dev Home version

0.401.219.0

### Windows build number

10.0.25926.1001

### Other software

OS Build Version: 10.0.25926.1001.amd64fre.rs_we_adept.230805-1700
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

1. do Clone repo w/ a dev drive selected
2. Click edit location
3. uncheck dev drive
4. click browse
5. location defaults to user docs, not source code 

![image](https://github.com/microsoft/devhome/assets/1462282/8889295b-c861-4644-bd1e-435c3cad8706)

### Expected result

source code dir like when you go through the normal flow

### Actual result

location defaults to user docs, not source code

### Included System Information

Physical Memory: 31.84GB (16.96GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome.Canary_0.401.219.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.400.219.0_x64__8wekyb3d8bbwe

**Comment by kanismohammed** [comment]
This is a known issue being tracked with https://github.com/microsoft/devhome/issues/1283

**Comment by krschau** [comment]
Duplicate of #1283
