### ISSUE TITLE
Clone repo has font consistency quirks

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#1395]
### Dev Home version

0.401.219.0

### Windows build number

10.0.25926.1001

### Other software

OS Build Version: 10.0.25926.1001.amd64fre.rs_we_adept.230805-1700
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

Path isn't aliased, Repo URL is not bold, Recent repos looks very aliased.

Here is the zoomed look
![image](https://github.com/microsoft/devhome/assets/1462282/2c7b36aa-fdc3-4d6e-aec8-35ff6b1f5abf)

![image](https://github.com/microsoft/devhome/assets/1462282/2e3fc773-4f1a-4bf4-875d-2009e1a7814a)

### Expected result

consistent headers :)

### Actual result

3 different styles being applied

### Included System Information

Physical Memory: 31.84GB (16.76GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome.Canary_0.401.219.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.400.219.0_x64__8wekyb3d8bbwe

**Comment by kanismohammed** [comment]
Fixed in the latest version of the app.
