### ISSUE TITLE
Crash observed when going through Clone Repositories flow

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhome#1396]
### Dev Home version

0.401.219.0

### Windows build number

10.0.22621.1992

### Other software

OS Build Version: 10.0.22621.1992.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

1. Navigate to the Machine configuration flow with a GitHub account already connected
2. Select a repository from the list of populated ones (I chose the Microsoft WSL repository)
3. Accept the default location and proceed to complete the clone operation

### Expected result

Repository is cloned successfully

### Actual result

Dev Home crashed (I'll file a Feedback Hub item to collect device information)

### Included System Information

Physical Memory: 63.95GB (54.91GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Dev_0.0.0.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension.Dev_0.0.0.0_x64__8wekyb3d8bbwe
DevHomeSamplePlugin_1.0.0.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.400.219.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome.Canary_0.401.219.0_x64__8wekyb3d8bbwe

**Comment by adrastogi** [comment]
Link to feedback: https://aka.ms/AAm1ypr

**Comment by bbonaby** [comment]
I believe we can close this one specifically right @adrastogi, looking at the internal bug it looks like it was due to the sdk changes back then? But do let me know if you're still having this issue. Thanks

**Comment by adrastogi** [comment]
Hey @bbonaby, yes, I'll close this out (this is no longer repro'ing for me). Thanks for following up!
