### ISSUE TITLE
Clone repo removes folder path during toggling from dev drive back to folder path

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#1397]
### Dev Home version

0.401.219.0

### Windows build number

10.0.25926.1001

### Other software

OS Build Version: 10.0.25926.1001.amd64fre.rs_we_adept.230805-1700
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

![image](https://github.com/microsoft/devhome/assets/1462282/a6d222ce-0045-4c20-8b76-429aac31ab47)
![image](https://github.com/microsoft/devhome/assets/1462282/33894515-8e50-4a35-82b5-158924e4a502)
![image](https://github.com/microsoft/devhome/assets/1462282/357c6485-a04d-4f63-a16a-62e209e8fcda)

### Actual result

blank folder

### Included System Information

Physical Memory: 31.84GB (16.76GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome.Canary_0.401.219.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.400.219.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
Issue does not show up in recent builds.  I believe the fix is in [This PR](https://github.com/microsoft/devhome/pull/1389)
