### ISSUE TITLE
Core Dev Home widgets consume a lot of resources

### ISSUE THREAD

**Issue by krschau** [microsoft/devhome#1398]
### Steps to reproduce the bug

Continuing from #760, we're now using SVG but the widgets still consume a lot of resources.

### Actual result

Too much.

**Comment by danielcranford** [comment]
I've seen cases where the CoreWidgetProvider reaches close to 1gb of memory used while not displaying anything (ie rendering the loading circle). To an outsider like me this sure feels like a memory leak.

**Comment by danielcranford** [comment]
CoreWidgetProvider is still running after the main window crashed or was closed and is consuming 2GB. Definitely feels like a leak.
<img width="569" alt="image" src="https://github.com/microsoft/devhome/assets/1479535/d99cfced-8d85-4024-91e7-13e24a1385cd">
See also #1335

**Comment by krschau** [comment]
CoreWidgetProvider process running was a design decision, but we've revisited that decision (#3411). For the record, it should have been running but not consuming so many resources. There's a bug we're trying to sort out with the Widget platform.
General resource use is being tracked right now with #1335, so I'm closing this to consolidate on that one.
