### ISSUE TITLE
Connex

### ISSUE THREAD

**Issue by ccupido37** [microsoft/devhome#1402]
### Dev Home version

0.301.198.0

### Windows build number

10.0.23521.1000

### Other software

OS Build Version: 10.0.23521.1000.amd64fre.ni_prerelease.230804-1452
.NET Version: .NET 6.0.18

### Steps to reproduce the bug

Streaming Live TV 

### Expected result

To run smooth and performing well while streaming live TV

### Actual result

Suddenly PC become extremely slow

### Included System Information

Physical Memory: 3.83GB (0.92GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
This does not sound like an issue with Dev Home and should be reported elsewhere. You may want to use Feedback Hub instead.
