### ISSUE TITLE
Summary page shows extra messages

### ISSUE THREAD

**Issue by AmelBawa-msft** [microsoft/devhome#1412]
### Steps to reproduce the bug

![image](https://github.com/microsoft/devhome/assets/104940545/59ef627c-c67f-49ad-8c15-bb09a4640bce)

### Expected result

Only one message showing "Failed to ..."

### Actual result

Multiple messages are displayed (including retry attempts)

**Comment by kanismohammed** [comment]
I am not able to repro this issue in the latest version of the app. Please re-activate if you are seeing it in the latest version.

**Comment by kanismohammed** [comment]
I am not able to repro this issue in the latest version of the app. Please re-activate if you are seeing it in the latest version.
