### ISSUE TITLE
Windows File Explorer cant display effects properly

### ISSUE THREAD

**Issue by amamiYukikaze** [microsoft/devhome#1413]
### Dev Home version

0.301.198.0

### Windows build number

10.0.23521.1000

### Other software

OS Build Version: 10.0.23521.1000.amd64fre.ni_prerelease.230804-1452
.NET Version: .NET 6.0.18

### Steps to reproduce the bug

By clicking the icon “>” in the Windows File Explorer directory bar

### Expected result

The text should appear with a dark background (or white, according to system theme settings)

### Actual result

The pop-up directory selecting menu floats simply on contents behind, without a background covering things behind.
![屏幕截图 2023-08-16 200523](https://github.com/microsoft/devhome/assets/132763879/0fa15a6f-1492-4216-8d99-55aea10f3cb2)

### Included System Information

Physical Memory: 31.85GB (17.54GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe

**Comment by AmelBawa-msft** [comment]
@crutkas @cinnamon-msft @KevinLaMS any suggestions on how/where to report issues related to file explorer?

**Comment by krschau** [comment]
Hi @amamiYukikaze, I'm going to close this since it's not related to Dev Home. If you'd like, you can report this issue in Feedback Hub ([Windows]+[f]).

**Comment by crutkas** [comment]
Please use windows feedback hub to report this. If you post the aka link back here happy to upvote
