### ISSUE TITLE
Cloning repository issue. 

### ISSUE THREAD

**Issue by edvanioFC** [microsoft/devhome#1424]
### Dev Home version

0.401.226.0

### Windows build number

10.0.22631.2199

### Other software

OS Build Version: 10.0.22631.2199.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

Just follow the instructions to clone an repository. 

### Expected result

To clone my repository. 
![Screenshot 2023-08-19 142953](https://github.com/microsoft/devhome/assets/122707296/505bb6cd-b38b-41ad-9a5e-f80b2722df84)

### Actual result

Couldn't clone the repository. 

### Included System Information

Physical Memory: 7.65GB (1.02GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.401.226.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.400.226.0_x64__8wekyb3d8bbwe

**Comment by edvanioFC** [comment]
> Hello @edvanioFC.  Super simple question.  I see that your system has 1.02GB free.  Are you sure the repo is smaller than a gigabyte?

This is my RAM memory.
My DEVHome is totally free.
I have 58Gb available/ of 60Gb.

**Comment by dhoehna** [comment]
Ah.  I am sorry.  I read that too fast.  My mistake.  A few more questions.  This time I want to figure out how you cloned the repo.

1.  Is this repo public or private?
2. What flow did you use to clone the repo?  Account or URL?

**Comment by edvanioFC** [comment]
> Ah.  I am sorry.  I read that too fast.  My mistake.  A few more questions.  This time I want to figure out how you cloned the repo.
> 
> 
> 
> 1.  Is this repo public or private?
> yes, it is a public repo.

> 2. What flow did you use to clone the repo?  Account or URL?
> account.
>

**Comment by dhoehna** [comment]
@edvanioFC sorry for the long pause.  This is a result of older versions of DevHome and the extension not communicating the error correctly.  Can you please upgrade both the extension and DevHome to the most recent version and reproduce the error.  The message should be more clear.
