### ISSUE TITLE
Clone Repository does not appear in dashboard

### ISSUE THREAD

**Issue by GiteshDohare** [microsoft/devhome#1446]
### Dev Home version

0.401.226.0

### Windows build number

10.0.23531.1001

### Other software

OS Build Version: 10.0.23531.1001.amd64fre.ni_prerelease.230821-1359
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

Whenever you clone a repository either via quick step or via End-to-end process, it just clone the repo at mentioned place and does not appear in the dashboard. 
This is making dashboard useless.

### Expected result

should appear in the dashboard

### Actual result

no effect at dashboard.

### Included System Information

Physical Memory: 15.65GB (5.87GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.401.226.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.400.226.0_x64__8wekyb3d8bbwe

**Comment by asklar** [comment]
See #1049
