### ISSUE TITLE
SSH keychain items are too separated

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#1472]
### Dev Home version

0.5

### Steps to reproduce the bug

Pin the SSH keychain widget and have at least 2 connections listed

### Actual result

Padding between each list item in SSH card is too tall compared to design spec, which has 4px for the padding
![MicrosoftTeams-image (8)](https://github.com/microsoft/devhome/assets/48369326/069f73dc-27d0-41d9-b354-52cc19e9fee6)

**Comment by krschau** [comment]
Plan is to update spec to have the larger, 8 px margins. This aligns with the space between the items in the GitHub widgets.
