### ISSUE TITLE
Text gets cut off in the Welcome to Dev Home Page 

### ISSUE THREAD

**Issue by joadoumie** [microsoft/devhome#1512]
### Dev Home version

0.401.226.0

### Windows build number

10.0.25948.1000

### Other software

OS Build Version: 10.0.25948.1000.amd64fre.rs_we_adept.230905-1700
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

When horizontally shrinking the Dev Home window, the header text and the corresponding description get cut-off. 

### Expected result

The text should be stacked (i.e. the size of the textbox changes, but the text itself is still visible)

### Actual result

Some of the text is cut off.

<img width="317" alt="image" src="https://github.com/microsoft/devhome/assets/98557455/00f122eb-a5d6-4514-a5e3-7566be3ebfe6">

### Included System Information

Physical Memory: 47.71GB (18.61GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.401.226.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.400.226.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome.Dev_0.0.0.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Closed by #1512
