### ISSUE TITLE
Ability to uninstall

### ISSUE THREAD

**Issue by fbantle** [microsoft/devhome#1542]
### Suggested new feature or improvement

Ich benötige diese App nicht und möchte sie deinstallieren.

### Scenario

Ich möchte diese App deinstallieren.

### Additional details

Eine Deinstallation der App wäre schön.

**Comment by asklar** [comment]
translation: 
I don't need this app and I want to uninstall it.

I want to uninstall this app.

Uninstalling the app would be nice.
