### ISSUE TITLE
"Create a dev drive" missing from End-to-End setup

### ISSUE THREAD

**Issue by pdsccode** [microsoft/devhome#1543]
### Dev Home version

0.401.226.0

### Windows build number

10.0.23545.0

### Steps to reproduce the bug

- Install Insider Dev build
- Install Dev Home (Preview)
- Log in to GitHub account in Dev Home
- Start End-to-end setup from Machine configuration
- select "Add repository" and choose one

### Expected result

Ability to check "Create Dev Drive to optimize performance"

### Actual result

mentioned option is not available

### Included System Information

Dev Drive option is available in system settings however.

**Comment by bbonaby** [comment]
Hi @pdsccode this will be resolved in v0.5 which is coming soon. Thanks
