### ISSUE TITLE
No action on button click

### ISSUE THREAD

**Issue by mdayeen** [microsoft/devhome#1544]
### Dev Home version

0.401.226.0

### Windows build number

10.0.22631.2338

### Other software

OS Build Version: 10.0.22631.2338.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

Dev home > settings > Account > Sign in to GitHub  

### Expected result

Should open a interface to sign-in Github
![Screenshot 2023-09-14 220415](https://github.com/microsoft/devhome/assets/55620202/9c86deeb-b594-4b30-95de-b5923f907415)

### Actual result

No action on button click

### Included System Information

Physical Memory: 13.85GB (7.1GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.401.226.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.400.226.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
I wonder if this is the same as the bug where sometimes the GitHub Extension settings toggle is unresponsive, it seems to be a transient Adaptive Cards issue. @mdayeen have you tried this since? Were you able to log in?

**Comment by vineeththomasalex** [comment]
Using this as the main bug for "Dev Home does nothing when clicking Signin button"

**Comment by mdayeen** [comment]
[Dev.zip](https://github.com/microsoft/devhome/files/12920772/Dev.zip)

**Comment by krschau** [comment]
See investigation in https://github.com/microsoft/devhomegithubextension/issues/108

**Comment by vineeththomasalex** [comment]
There is no evidence to suggest this is different from https://github.com/microsoft/devhomegithubextension/issues/108 . Duplicating this out.
