### ISSUE TITLE
Support updating app installer in-app without restarting Dev Home

### ISSUE THREAD

**Issue by joadoumie** [microsoft/devhome#1545]
### Dev Home version

0.401.255.0

### Windows build number

10.0.25947.1000

### Other software

OS Build Version: 10.0.25947.1000.amd64fre.rs_prerelease.230901-1416
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Right now, if you update the app installer and then do not restart Dev Home or forget to start Dev Home, the experience in machine configuration will not work (e.g. install apps flow)

### Expected result

We should have some way of properly handling this. 

Either via automatically restarting Dev Home OR somehow getting the process to load the proper things into memory without restarting Dev Home

### Actual result

The experience appears to be broken as certain components do not load (such as the app installing flow).

<img width="735" alt="image" src="https://github.com/microsoft/devhome/assets/98557455/377b3fd1-7296-4f85-b552-324ee188eb4b">

### Included System Information

Physical Memory: 63.95GB (53.62GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.401.255.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.400.255.0_x64__8wekyb3d8bbwe

**Comment by AmelBawa-msft** [comment]
Related work item: https://task.ms/47231997
