### ISSUE TITLE
Latest available Windows Web Experience Pack is not high enough for Dev Home widgets

### ISSUE THREAD

**Issue by timmee2222** [microsoft/devhome#1551]
### Dev Home version

0.401.226.0

### Windows build number

10.0.22631.2338

### Other software

OS Build Version: 10.0.22631.2338.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

dashboard/ add widget

### Expected result

get a list of wiudgets

### Actual result

pop up box asking if Windows Web Experience Pack is updated. checked and it is the latest version

### Included System Information

Physical Memory: 7.86GB (0.76GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.401.226.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.400.226.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
@timmee2222 Can you tell me what version you have? An easy way to see is run this in powershell: `get-appxpackage *webexp*`

**Comment by timmee2222** [comment]
Name              : MicrosoftWindows.Client.WebExperience
Publisher         : CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 521.20060.405.0
PackageFullName   : MicrosoftWindows.Client.WebExperience_521.20060.405.0_x64__cw5n1h2txyewy
InstallLocation   : C:\Program
                    Files\WindowsApps\MicrosoftWindows.Client.WebExperience_521.20060.405.0_x64__cw5n1h2txyewy
IsFramework       : False
PackageFamilyName : MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy
PublisherId       : cw5n1h2txyewy
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00_14.0.32530.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok

**Comment by krschau** [comment]
I thought that everyone on Windows Insiders builds would have 523 by the time you opened this issue, but clearly that was not the case. I hope that you have been able to update, or will be able to soon. There are some changes I'm hoping to make in the December/January timeframe that should fix this kind of problem.

**Comment by krschau** [comment]
Since this will be fixed by the same update that will fix #742, I'm duping it to that one.
