### ISSUE TITLE
Some Apps did not install due to an internal error

### ISSUE THREAD

**Issue by KarlSheldon** [microsoft/devhome#1562]
### Dev Home version

0.401.226.0

### Windows build number

10.0.22631.2338

### Other software

OS Build Version: 10.0.22631.2338.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

Installing all apps

### Expected result

All to install without issue

### Actual result

Docker, Intelj and Unity did not install

### Included System Information

Physical Memory: 63.92GB (51.01GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.401.226.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.400.226.0_x64__8wekyb3d8bbwe

**Comment by denelon** [comment]
Can you reproduce the errors and share log files?

**Comment by farukaf** [comment]
Dont know if its the same error 

Just followed this steps

- Machine Configuration
- Install Applications
- Notepad++ (tried several at once before same result)
- Next
- Agree -> Setup
- Error

![image](https://github.com/microsoft/devhome/assets/19143772/2db6c9dc-287f-417f-8d48-eb22d146499d)
[CoreWidgetProvider.zip](https://github.com/microsoft/devhome/files/12709402/CoreWidgetProvider.zip)

**Comment by KarlSheldon** [comment]
Hi Sorry for the late reply, hope these help, I could not get several to
install so I installed separately and all went OK,I have since ran
devhome and it allowed some installs over existing,

Thanks

*--*--*--*--*--*--*--*--*--*--*--*---*--*--*--*--*--*--*--

 email:  ***@***.***

*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--

**Comment by AmelBawa-msft** [comment]
@KarlSheldon, sorry for the delayed response. I've recently refactored WinGet's integration in the PRs below. Would it possible to validate if the issue still repros in latest Dev Home version?

- https://github.com/microsoft/devhome/pull/2089
  - Added recovery when RPC exceptions occur.
- https://github.com/microsoft/devhome/pull/3134
  - Elevated process now uses the same WinGet logic as Dev Home's main process (enhanced implementation overall + recovery)
- https://github.com/microsoft/devhome/pull/3307
  - Mitigated an issue that occurs when Dev Home's elevated process attempts to install multiple packages at the same time.

**Comment by KarlSheldon** [comment]
I am happy to report that I have now used devhome to install on 4 machines
without issues. Tried to trip it up with some apps already installed but it
now works as intended,

Thanks
