### ISSUE TITLE
version 23545.1000 ni_prerelease task manager

### ISSUE THREAD

**Issue by anierenris** [microsoft/devhome#1579]
### Dev Home version

0.401.226.0

### Windows build number

10.0.23545.1000

### Other software

OS Build Version: 10.0.23545.1000.amd64fre.ni_prerelease.230908-1421
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

right mouse button on the taskbar, open task manager

### Expected result

task manager open

### Actual result

the task manager does not open🙌
-
-I don't know, maybe it's just my problem🤔

### Included System Information

Physical Memory: 15.93GB (10.69GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.401.226.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.400.226.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Hi @anierenris. It sounds like you're having a problem with Windows, not with Dev Home in particular, which is what this repo is for. Please try opening a ticket in Feedback Hub (keyboard shortcut win+F) and your issue should get to the right people.
