### ISSUE TITLE
Add Repo button does nothing.

### ISSUE THREAD

**Issue by chrisdMSFT** [microsoft/devhome#1581]
### Dev Home version

0.401.226.0

### Windows build number

10.0.22621.2283

### Other software

OS Build Version: 10.0.22621.2283.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

Launch Dev Home
Machine Config
Add Repo
Click top or bottom button and nothing happens.

### Expected result

A dialog pops to let me add a repo.

### Actual result

Nothing.

### Included System Information

Physical Memory: 63.95GB (49.68GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.401.226.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by chrisdMSFT** [comment]
![46a263df-6f0f-4e34-b715-b619ffffaad3](https://github.com/microsoft/devhome/assets/73906532/2dfa365a-25dd-464c-9323-c45ddc69d308)

**Comment by dhoehna** [comment]
Hi @chrisdMSFT,

Recently the SDK that allows DevHome and the GitHubExtension to communicate had a breaking change.  It looks like the DevHome version and the GitHubExtension have different versions that crosses the SDK braking change.

Do you know how the version mismatch happened?  Did DevHome download the incorrect version of the extension, or did DevHome not upgrade itself, or something else?

**Comment by chrisdMSFT** [comment]
Oooh interesting!

So I have the same repro on two machines (my home pc and my devbox). In both cases, here are the steps I followed to install the software:

1. Navigate to https://learn.microsoft.com/en-us/windows/dev-home/.
2. Click 'Install Dev Home (Preview)' button.
3. Opens https://apps.microsoft.com/store/detail/dev-home-preview/9N8MHTPHNGVV in browser.
4. Click `Get in Store App`
5. Once app is installed, click open.

**Comment by chrisdMSFT** [comment]
I just followed the same steps, and the 'Get in Store App' offered me an update option which fixed the problem for my dev box. I'm unable to force the update for my home pc.

**Comment by krschau** [comment]
@chrisdMSFT I'm going to assume you got the update on your home PC, but if not, let us know.

**Comment by chrisdMSFT** [comment]
[like]  Chris Dern reacted to your message:
________________________________
