### ISSUE TITLE
Add ability to open logs file in action center

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/devhome#1582]
### Suggested new feature or improvement

ITNOA

Hi,

I try to install Microsoft SQL Server Mangement Studio with Dev Home, and I got below errors

![image](https://github.com/microsoft/devhome/assets/17947618/4aa6ed69-c9ce-43ef-9fec-b734098f5e9d)

As you can see error message has very few descriptive, so I suggest add button to see log files (setup logs) for better troubleshooting's setup failure

### Scenario

In last page before summary in install applications, add view logs in action center in failure setup situation.

**Comment by cinnamon-msft** [comment]
This looks to be fixed in https://github.com/microsoft/devhome/pull/1583

**Comment by soroshsabz** [comment]
related to #1229
