### ISSUE TITLE
[ci]: WinGet token permissions issue

### ISSUE THREAD

**Issue by mdanish-kh** [microsoft/devhome#1584]
### Steps to reproduce the bug

Take a look at https://github.com/microsoft/devhome/actions/runs/6264936186/job/17012688427#logs

The issue is that I believe the GitHub token was added by @vineeththomasalex as the repository secret when I last mentioned it in https://github.com/microsoft/devhome/issues/1307. But the GitHub releases are published by @cinnamon-msft and thus winget-create uses @cinnamon-msft's fork of https://github.com/microsoft/winget-pkgs to submit the PR.

As the token created by @vineeththomasalex is not accessible to @cinnamon-msft's fork, the CI fails to submit a PR.

### Expected result

PR creation is successful

```json
{"message":"Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.","documentation_url":"https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/"}
```

As highlighted in the error message, the token should be granted organization level access by @vineeththomasalex  or the token added as the repository secret should be the one created by @cinnamon-msft

### Actual result

PR creation fails

**Comment by cinnamon-msft** [comment]
Thanks for the heads up! Fixed the PAT and the action succeeded in making the PR :) https://github.com/microsoft/winget-pkgs/pull/120403
