### ISSUE TITLE
Dev Home does not appear in the All Apps list or the start menu, nor in the Windows Tools folder

### ISSUE THREAD

**Issue by adrianghc** [microsoft/devhome#1587]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Install Dev Home.

### Expected result

Dev Home should be present either in the All Apps list of the start menu or in the Windows Tools folder of the same.

### Actual result

Dev Home does not appear in the All Apps list or the start menu, nor in the Windows Tools folder. The only way to find it is through search.
This behavior appears to be inconsistent between machines, as it appears on one machine but not on two users of the other. Both are on 22621.2361.

### Included System Information

Physical Memory: 15.73GB (4.92GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by adrianghc** [comment]
When creating a new user on the faulty machine, the following behavior is exhibited:

1. The app first appears as "Dev Home" in the Windows Tools folder.
2. When the full app is installed and replaces the stub, the app disappears from Windows tools and does not appear in All Apps.

Number 1 seems to be correct behavior, but not number 2. It also appears to be a machine-wide issue and not per-user.

This issue is still present with 0.7.

**Comment by adrianghc** [comment]
I'd like to note that an in-place upgrade of Windows did not fix this or otherwise change the described behavior.

**Comment by etanmanjbbo11** [comment]
Same happens for me, running on Windows 11 26058. Really annoying.
![Screenshot 2024-03-09 102925](https://github.com/microsoft/devhome/assets/140823963/5ad734a5-bec1-4447-b728-ef2552bf858c)

**Comment by krschau** [comment]
Not repro'ed by @EricJohnson327 and @lauren-ciha with version 0.1701.

**Comment by adrianghc** [comment]
In the past months I have done two clean installs of Windows on two separate machines, and both have this issue. This has not been resolved!

**Comment by krschau** [comment]
@adrianghc What Windows version(s) are you seeing this on? During Windows setup, are you opting in as a "developer" or do you have "developer mode" turned on? Are you seeing it in neither Windows Tool or All Apps once the full app is installed?

**Comment by adrianghc** [comment]
@krschau I'm seeing this on both versions 23H2 and 24H2. If I recall right, on one machine, I opted in as a developer during OOBE while on the other I did it from Settings. I don't have developer mode turned on on either machine. The app doesn't appear in Windows Tools nor in All Apps.

**Comment by WinkelCode** [comment]
Same here on fresh 24H2 install. Shows up in `winget list` and was updated once, but doesn't appear through search or in All Apps.

**Comment by adrianghc** [comment]
This appears to have been fixed on 24H2 with a recent CU, most likely 26100.3624. Not that it matters anymore...
