### ISSUE TITLE
Unable to login to add GitHub account

### ISSUE THREAD

**Issue by victor-akande** [microsoft/devhome#1595]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Settings -> Accounts -> Add an account -> Sign in to GitHub.com

### Expected result

Clicked the sign in to GitHub button, was expecting to bring up a web browser to enable me login to GitHub

### Actual result

Nothing happened button doesn't seem to be working

### Included System Information

Physical Memory: 11.88GB (4.69GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Hi @victor-akande, can you double check that what's happening isn't what's described in https://github.com/microsoft/devhome/issues/472? (That the login page IS being launched, but just isn't coming to the foreground)

**Comment by dhoehna** [comment]
Could it be because the versions are different?

**Comment by victor-akande** [comment]
> Hi @victor-akande, can you double check that what's happening isn't what's described in #472? (That the login page IS being launched, but just isn't coming to the foreground)

On my PC it doesn't launch at all, just checked again now

**Comment by krschau** [comment]
Possible duplicate of #1544
