### ISSUE TITLE
Install Applications screen blank on clean win 11 install.

### ISSUE THREAD

**Issue by DerekSchmidt-Dev** [microsoft/devhome#1596]
### Dev Home version

Latest Store

### Windows build number

10.0.22621.0

### Steps to reproduce the bug

Clean install of windows 11,fresh installed devhome preview from windows store.

### Actual result

Install Application screen starts loading like normal:
![image](https://github.com/microsoft/devhome/assets/54153380/1876d541-fd41-45c9-bb42-05374a0f4a1f)

After a couple seconds it just goes blank and search box is unclickable:
![image](https://github.com/microsoft/devhome/assets/54153380/cc9b4da8-1ddc-4a5f-a80e-123ff3ae57dd)

### Included Extensions Information

None

**Comment by AmelBawa-msft** [comment]
@DerekSchmidt-Dev, looks like Dev Home was able to initialize the section (the shimmer controls are visible in the first pic) but there was an issue loading those packages from winget. Can you please post here the winget version you're using?

Steps:
1. Open cmd
2. Type `winget -v`
3. Copy/paste output here
