### ISSUE TITLE
GitHub URL Crashes application

### ISSUE THREAD

**Issue by matty** [microsoft/devhome#1597]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Add a new repository, enter the url of a GitHub repo which is in an organisation different to main account.

### Expected result

Repo should be cloned

### Actual result

Application crashes

### Included System Information

Physical Memory: 63.77GB (45.85GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by EricJohnson327** [comment]
Hello @matty, is it a private repo and does the signed in account have access to it?

**Comment by matty** [comment]
Hi @EricJohnson327. This is a private repo and the account has access. I am using the https URL of the repository by entering it in the "URL section" as the "Account" section doesn't show organisation repos.

**Comment by dileep-hegde** [comment]
> Hi @EricJohnson327. This is a private repo and the account has access. I am using the https URL of the repository by entering it in the "URL section" as the "Account" section doesn't show organisation repos.

Same in my system. App crashes while adding repos as mentioned above through End-to-end setup -> clone repositories or Clone repositories itself.

**Comment by dhoehna** [comment]
Crashing has been fixed.  Please update to the newest version and try again.  If Devhome can't access a repo it will not crash.

#1835 adds a message notifying that no logged in accounts can access the repo.

If this is still crashing after upgrading to the most recent version, please re-open this bug.
