### ISSUE TITLE
Ambiguous error when failing to clone repo

### ISSUE THREAD

**Issue by AlthalusDGr8** [microsoft/devhome#1598]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Trying to clone a repo from bitbucket I get this error code and message
<img width="1457" alt="image" src="https://github.com/microsoft/devhome/assets/13330897/7b5c1fca-980d-42e7-a0a4-e8903d1178fb">

### Expected result

Successfully cloning the repo

### Actual result

just displays error code 80131500

### Included System Information

Physical Memory: 31.69GB (15.32GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe

**Comment by EricJohnson327** [comment]
Hello @AlthalusDGr8 

What is the full repo URL you are trying to clone?  Is the repo public or private?

**Comment by AlthalusDGr8** [comment]
Its a private repo on bitbucket

**Comment by asklar** [comment]
@krschau 80131500 is the generic HRESULT for "a .net exception happened" - could we please special case that and provide a meaningful error message (from the exception itself) instead? @dhoehna

**Comment by EricJohnson327** [comment]
@AlthalusDGr8 Dev Home does not currently support private repositories outside of GitHub (and ADO is coming).  The extensions are responsible for authentication and cloning with that account.  So a BigBucket extension will need to be created to enable private repository cloning.

That said, I agree with @asklar that we need to better display that to the user.  Changing the title of this issue to reflect that.

**Comment by dhoehna** [comment]
@AlthalusDGr8 this is an issue with older versions of the extension and DevHome.  Can you please upgrade both the extension and DevHome to their most recent versions and reproduce the error?  The message should be more descriptive.

**Comment by KashaMalaga** [comment]
Hello we have interest into use private repos from bitbucket, does cloning have any change?

**Comment by krschau** [comment]
Issue #954 is tracking BitBucket support. I don't think it's on our current timeline, but anyone is free to create their own Dev Home extension that would support it!

**Comment by JKHSDTV** [comment]
This issue should be reopened. Leaving aside actual support for private repos, the error I get should not be just "80131500" but an explanation of what is going wrong.
