### ISSUE TITLE
cant clone

### ISSUE THREAD

**Issue by taltole** [microsoft/devhome#1599]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

tried to clone my repo 

### Actual result

https://github.com/taltole and got error 80131500

### Included System Information

Physical Memory: 15.91GB (8.24GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe

**Comment by EricJohnson327** [comment]
Hello @taltole 

What is the repo you are trying to clone?  What you linked in the issue is your profile account.
