### ISSUE TITLE
INSTALL APP

### ISSUE THREAD

**Issue by AYUSHUP2518** [microsoft/devhome#1601]
### Dev Home version

0.503.261.0

### 🌐 Language

ENGLISH

### ❌ Actual phrase(s)

NOT ABLE TO INSTALL APP WHEN CLICKING ON INSTALL APPS OPTION

### ✔️ Expected phrase(s)

MUST BE AINSTALLED APPS

### Why is the current translation wrong

NO APPS ARE BEING INSTALLED

**Comment by krschau** [comment]
Please don't open multiple issues for the same problem, we saw #1600.
