### ISSUE TITLE
Disable spell check

### ISSUE THREAD

**Issue by Solaestas** [microsoft/devhome#1611]
### Suggested new feature or improvement

I think there should be a option to disable spell check, It's so annoying that every time I type "github" in url, it becomes "GitHub" or has wavy lines

### Scenario

no more auto-capitalization and underlines

### Additional details

![image](https://github.com/microsoft/devhome/assets/49426220/0e21502a-0a5c-430f-aa58-28dcdcd257ee)

**Comment by asklar** [comment]
@Solaestas what UI are you seeing this spellcheck red line in? the screenshot you show seems to be of editing the text in this issue on the github website...
