### ISSUE TITLE
Weird symlink when cloning via Dev Home

### ISSUE THREAD

**Issue by sylveon** [microsoft/devhome#1612]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Steps to reproduce the bug

1. Clone a GH repo to a Dev Drive via Dev Home
2. Open the resulting clone in Explorer

### Expected result

I did not expect there to be a non-functioning symlink named "_git2_a06384" 

### Actual result

![image](https://github.com/microsoft/devhome/assets/6440374/a6d31e61-fc63-46c8-8103-be31d4102312)
![image](https://github.com/microsoft/devhome/assets/6440374/6ddc640e-05a3-4a85-a5d7-d23a8b575422)

### Included Extensions Information

Dev Home GH extension 0.503.261.0

**Comment by dhoehna** [comment]
This was an OS level fix and should be available.
