### ISSUE TITLE
Theme is not working correctly

### ISSUE THREAD

**Issue by mayur-ravindram** [microsoft/devhome#1617]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Got to Settings > Preference > Theme > Light

Get messed up theme

### Expected result

fonts and colors should be alright

### Actual result

not able to see anything in app

**Comment by EricJohnson327** [comment]
@mayur-ravindram can you please add screenshots of the issues your experiencing?  Thank you!

**Comment by mayur-ravindram** [comment]
@EricJohnson327 after restarting machine due to system update, I am now able to see no issue anymore. Hence closing the issue.
