### ISSUE TITLE
Cloning a repo does not clone submodules

### ISSUE THREAD

**Issue by asklar** [microsoft/devhome#1619]
### Steps to reproduce the bug

See https://twitter.com/James_M_South/status/1707623052207665308
![image](https://github.com/microsoft/devhome/assets/22989529/f9072b77-31de-4bc1-bb91-91e3d6558040)

Submodules seem supported by libgit2sharp; LFS seems implementable via libgit2/libgit2sharp#1236

### Actual result

submodules/LFS not cloned

**Comment by dhoehna** [comment]
https://github.com/microsoft/devhomegithubextension/pull/384 allows the GitHub extension to clone submodules.  LFS is still incomplete and needs more dev work.  The GitHub extension has a [feature-request](https://github.com/microsoft/devhomegithubextension/issues/385) to add LFS support.

**Comment by krschau** [comment]
Editing name to reflect that LFS is tracked separately.

**Comment by dhoehna** [comment]
PR is in the extension.
