### ISSUE TITLE
Not sure how to work with YML files?

### ISSUE THREAD

**Issue by ffMathy** [microsoft/devhome#1628]
### Provide a description of requested docs changes

Currently, in the UI, I see a way to import my configuration from a YML file.

But I can't figure out how to export an existing configuration as YML, or even see samples of how such an YML could look like. That makes it a bit difficult to use.

**Comment by shakersMSFT** [comment]
We don't currently have the support to export a configuration file in Dev Home (tracking several requests here https://github.com/microsoft/devhome/issues/970 https://github.com/microsoft/devhome/issues/721) but we just recently added links to our sample configuration files https://github.com/microsoft/devhome/issues/1916 so I hope that helps! We also have some documentation here on authoring and using configuration files: https://learn.microsoft.com/en-us/windows/package-manager/configuration/

**Comment by shakersMSFT** [comment]
Hi, we are currently exploring how we might accomplish this through Dev Home. Please take a look and let us know what you think! https://github.com/microsoft/devhome/issues/2160

**Comment by shakersMSFT** [comment]
https://github.com/microsoft/devhome/pull/2466
