### ISSUE TITLE
texture problem

### ISSUE THREAD

**Issue by Ruhaan838** [microsoft/devhome#1629]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

I thing you make a one mistake with the texture in  the panels ..🫡😊

![Screenshot 2023-10-01 105006](https://github.com/microsoft/devhome/assets/127672178/3ba60cd2-b08c-414f-beca-4542e1294103)

### Expected result

Make a corrections or do other..

### Actual result

The problem is actually the round shapes is not make perfectly 

### Included System Information

Physical Memory: 7.89GB (3.3GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Hi @Ruhaan838, can you be more specific about what you're seeing as wrong?
