### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by RanArkon** [microsoft/devhome#1633]
### Suggested new feature or improvement

Please add always on top option for main widgets window

### Scenario

Please add always on top option for main widgets window to stay useful information always on top of other windows.

**Comment by krschau** [comment]
Hi @RanArkon. I'd suggest using the [Always on Top feature in PowerToys ](https://learn.microsoft.com/en-us/windows/powertoys/always-on-top) to achieve this functionality.

**Comment by RanArkon** [comment]
Hi, Yes I forgot about this feature from PowerToys, thank you.
