### ISSUE TITLE
Dev Home sometimes doesn't render extension settings

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1638]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

When I go to Settings>Extensions>Manage Extension

### Expected result

It should load the "Manage Extension" menu

### Actual result

It went blank

### Included System Information

Physical Memory: 11.89GB (4.27GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
@skanda890 Could you include a screenshot that shows what's happening?

**Comment by skanda890** [comment]
The Screenshot:
https://1drv.ms/f/s!Aqq-Je19xlrfhFkodvljvcHc11_1?e=09HIv7

**Comment by skanda890** [comment]
Yes , It is

**Comment by krschau** [comment]
@skanda890 Sorry, maybe I checked this too late but the folder you linked to is empty. There isn't much on the settings page, since the extension only has one settings, a button that toggles the extension being enabled or disabled. Are you not seeing the button?

![image](https://github.com/microsoft/devhome/assets/47155823/e907b8e5-f616-466e-92d6-0ed7d56fa2de)

**Comment by skanda890** [comment]
No, I am not seeing any buttons.

**Comment by skanda890** [comment]
I got a picture.
![image](https://github.com/microsoft/devhome/assets/99239826/a309b0e7-591e-460f-acee-7a20855d2a6f)

**Comment by skanda890** [comment]
Another Picture.


![image](https://github.com/microsoft/devhome/assets/99239826/627a3424-6bcc-4d87-945c-d580a212d8d0)

**Comment by skanda890** [comment]
Now it is rendering the extensions.
