### ISSUE TITLE
The Dev Home app hangs and crashes

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1639]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

The Dev Home app hangs and crashes when I go to Introducing Dev Home>Connect accounts.
### Expected result

It should load that menu.

### Actual result

It hung and then crashed

### Included System Information

Physical Memory: 11.89GB (4.27GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by skanda890** [comment]
The files you asked for are in:
https://1drv.ms/f/s!Aqq-Je19xlrfhB5M-JEdfjojyp4X?e=bluwmy

**Comment by vineeththomasalex** [comment]
Duplicate of #1634
