### ISSUE TITLE
Connecting an account

### ISSUE THREAD

**Issue by nithin-byteC-in** [microsoft/devhome#1642]
### Suggested new feature or improvement

List repos that are accessible to u even its a collaboration repo or if its in organisation github

### Scenario

My git repo is in my organisation GitHub account, i have access to it, but is not shown in my account list

**Comment by vineeththomasalex** [comment]
This is already supported, but requires the organization to approve the DevHome Oauth app. You can create a request to your org:

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps
