### ISSUE TITLE
App Crash while adding repositories

### ISSUE THREAD

**Issue by nithin-byteC-in** [microsoft/devhome#1643]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

1. go to machine configuration
2. click on clone repositories
3. click on "+ Add Repositories"
4. click on URL
5. Paste the https URL in Repository URL fields"
6. left the source folder intact(created the folders as it was not created automatically)
7. clicked add

### Expected result

Going to the next step

### Actual result

App Crashing instantly

### Included System Information

Physical Memory: 15.36GB (9.21GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by nithin-byteC-in** [comment]
sorry for the delayed response.
here are the files u requested
[Microsoft.Windows.DevHomeGitHubExtension.zip](https://github.com/microsoft/devhome/files/12872801/Microsoft.Windows.DevHomeGitHubExtension.zip)
[Microsoft.Windows.DevHome.zip](https://github.com/microsoft/devhome/files/12872802/Microsoft.Windows.DevHome.zip)

**Comment by dileep-hegde** [comment]
Same in my system. App crashes while adding repos through End-to-end setup -> clone repositories or Clone repositories itself.

**Comment by worldofgeese** [comment]
> Same in my system. App crashes while adding repos through End-to-end setup -> clone repositories or Clone repositories itself.

I can neither add repositories or add an account as in https://github.com/microsoft/devhome/issues/1634. @cinnamon-msft can you please take a look at these? The problem appears widespread. This is a brand new install of Windows 11.

**Comment by dhoehna** [comment]
@nit

> sorry for the delayed response. here are the files u requested [Microsoft.Windows.DevHomeGitHubExtension.zip](https://github.com/microsoft/devhome/files/12872801/Microsoft.Windows.DevHomeGitHubExtension.zip) [Microsoft.Windows.DevHome.zip](https://github.com/microsoft/devhome/files/12872802/Microsoft.Windows.DevHome.zip)

Took a look at the logs.  The repo that you are trying to clone, is it a private repo that belongs to an organization?

**Comment by dhoehna** [comment]
Crashing has been fixed.  Please update to the newest version and try again.  If Devhome can't access a repo it will not crash.

#1835 adds a message notifying that no logged in accounts can access the repo.

If this is still crashing after upgrading to the most recent version, please re-open this bug.
