### ISSUE TITLE
Feedback Menu

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1646]
### Suggested new feature or improvement

Can you make a new menu called "Feedback" out of settings and replace it with the current feedback menu?

### Scenario

You can access the feedback menu but you don't have to go to settings anymore now you can directly you can access it.

**Comment by balaji-sivasakthi** [comment]
![image](https://github.com/microsoft/devhome/assets/65065614/f7879a95-aa72-41ed-8764-e7d8c450dd6d)

Shall I add the feedback menu above the setting icon?

**Comment by hamnarauf** [comment]
I believe Feedback was moved to Settings on purpose. See https://github.com/microsoft/devhome/issues/539

**Comment by balaji-sivasakthi** [comment]
> Feedback currently has its own entry point in the left nav. It should be grouped under the settings entry point, as a line item in settings.

So, shall we close this issue?
