### ISSUE TITLE
Cannot see any repo in dashboard after clone from the app

### ISSUE THREAD

**Issue by himself65** [microsoft/devhome#1653]
### Dev Home version

0.503.261.0

### Windows build number

1000.22674.1000.0

### Steps to reproduce the bug

After I clone one repo from the app, I cannot see that repo in the app.

![image](https://github.com/microsoft/devhome/assets/14026360/e2d7e313-43a4-4dee-a838-47fe69284194)

### Expected result

I think the repo I cloned should be shown in somewhere.

### Actual result

Cannot find it in the app. When I clone twice, it's says the directory is not empty.

**Comment by asklar** [comment]
See #1049, would this solve this problem?

**Comment by himself65** [comment]
I think so

**Comment by krschau** [comment]
Duplicate of #702

**Comment by skanda890** [comment]
It somewhat different.
