### ISSUE TITLE
'Backup' Button

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1654]
### Suggested new feature or improvement

Can you make a new button called 'Backup' in the Settings>Prefences?

### Scenario

This is used to import settings. Using- .yaml or .yml files.

**Comment by skanda890** [comment]
@krschau can you add the label 'Widget' to this issue?

**Comment by skanda890** [comment]
@krschau can you label this issue as 'Widget'

**Comment by skanda890** [comment]
Can somebody label this as 'New-Widget'

**Comment by krschau** [comment]
I'm sorry we weren't able to get to this last week, and usually we're not triaging GitHub issues during the weekend. If you're still interested in this widget, could you give us some more details about what kind of config files you think it would be useful to create from Dev Home, and maybe how you think the widget would work?

**Comment by skanda890** [comment]
This is not planned.

**Comment by skanda890** [comment]
Can anybody remove the 'Resolution-Closed-By-Author' and 'New-Widget' labels and add the 'Needs-Triage' label?

**Comment by skanda890** [comment]
I changed the idea a little bit.

**Comment by krschau** [comment]
Related to #804, maybe a dupe.

**Comment by skanda890** [comment]
This was already implemented.

**Comment by skanda890** [comment]
Can you remove the label: 'Resolution-Closed-By-Author' and add 'Resolution-Duplicate'
