### ISSUE TITLE
Can't sign to GitHub account

### ISSUE THREAD

**Issue by sanjarbek-ismatov** [microsoft/devhome#1657]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

When I click to sign GitHub account, browser doesn't open and dev home does nothing

### Expected result

I want to connect my GitHub account

### Actual result

Nothing

### Included System Information

Physical Memory: 7.33GB (2.96GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by skanda890** [comment]
I also have this issue.

**Comment by vineeththomasalex** [comment]
Duping to #1634
