### ISSUE TITLE
Dev Home created a second dev drive as opposed to using the one already created.

### ISSUE THREAD

**Issue by mwsteph** [microsoft/devhome#1659]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

I created a dev drive in settings and then when I went to configure my dev environment in dev home and added a repository, it created a second dev drive as opposed to using the one I created.  Ideally Dev Home should recognize that I already have a dev drive created and use that by default or ask if it wants to use the existing dev drive or create a new one.  

### Expected result

When adding a repository, dev home should have saved it to the existing dev drive.

### Actual result

Dev home created a second dev drive.  

### Included System Information

Physical Memory: 127.91GB (116.02GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
Hey @mwsteph,

DevHome does check if a DevDrive is on the system and should find a DevDrive.  I tried replicating this issue and was not able to run into this issue.   

Closing for non-repro.  However, if you do run into this issue, please re-open with detailed repro steps and /logs.
