### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1663]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Sometimes, when launching the application, a black screen may appear.

### Expected result

It should load the Dashboard.

### Actual result

A Black screen appears.

### Included System Information

Physical Memory: 11.89GB (5.54GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by skanda890** [comment]
A screenshot:
https://1drv.ms/f/s!Aqq-Je19xlrfhFqdW5eaCpr306aS?e=B6kQEa

Sorry, I couldn't make it in a normal picture

**Comment by krschau** [comment]
Does the black screen ever change? Does the app crash eventually?

**Comment by skanda890** [comment]
No, It was staying black only, I had to manually close the application.
