### ISSUE TITLE
Install selected applications onto Dev Drive rather than on the OS

### ISSUE THREAD

**Issue by snaildos** [microsoft/devhome#1665]
### Suggested new feature or improvement

I'd like to see an option to install the selected apps onto the Dev Drive rather than the OS.

### Scenario

Selecting the button will change the install Path onto the Dev Drive

**Comment by skanda890** [comment]
This is a good idea.

**Comment by cinnamon-msft** [comment]
We recommend putting source code repos, project files, package caches, and built output files into a Dev Drive, but not the apps themselves. If you want to learn more, feel free to check out our docs: https://learn.microsoft.com/en-us/windows/dev-drive/#what-should-i-put-on-my-dev-drive

**Comment by snaildos** [comment]
> We recommend putting source code repos, project files, package caches, and built output files into a Dev Drive, but not the apps themselves. If you want to learn more, feel free to check out our docs: https://learn.microsoft.com/windows/dev-drive/#what-should-i-put-on-my-dev-drive

Why not apps? Most apps allow custom install location?
