### ISSUE TITLE
Support for adding existing repositories

### ISSUE THREAD

**Issue by lim-kim930** [microsoft/devhome#1667]
### Suggested new feature or improvement

When adding a repository, I hope that I can add the existing git repository folder instead of having to clone it again.

### Scenario

In the tab bar above the pop-up window for adding a repository, add a new option, such as ‘Add existing’, just like Github Desktop:
![image](https://github.com/microsoft/devhome/assets/72185892/26107d6b-5ac2-4730-82eb-9968f434937c)

**Comment by leo-schick** [comment]
100% agree! most of the devs have already cloned repositories on their computer. For me, this is a vital function for the addoption of Dev Home

**Comment by lim-kim930** [comment]
Duplicate of https://github.com/microsoft/devhome/issues/702
