### ISSUE TITLE
Better User Interface and experience

### ISSUE THREAD

**Issue by muftifachrudin** [microsoft/devhome#1675]
### Suggested new feature or improvement

Custom located widget or responsive widget to this dev home app. I hope can improve many language programming to testing and performance and to be better developer tools before that project launched

### Scenario

we can adjust widget and resize it. if the project add repo to GitHub, and can be import to testing to this app and many scenario to another specs device to run that app

**Comment by krschau** [comment]
@muftifachrudin Can you explain more about what features you're asking for? It sounds like you're asking for a few things, but more detail would be helpful.
