### ISSUE TITLE
Cannot clone from organization's repositories

### ISSUE THREAD

**Issue by MilosKozak** [microsoft/devhome#1683]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2428

### Steps to reproduce the bug

When clicking to Clone repository with already authenticated GitHub, control for selecting private or organization's repo is disabled with prefilled personal repo
![image](https://github.com/microsoft/devhome/assets/11146458/8787f492-2d7d-4474-aae0-3f2d203e1bf8)

### Actual result

It's not possible to change to organization

**Comment by krschau** [comment]
@dhoehna FYI

**Comment by vineeththomasalex** [comment]
This is supported, but requires the organization to approve the DevHome Oauth app. You can create a request to your org:

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps

**Comment by vineeththomasalex** [comment]
Keeping this open for the UI support in Clone Repository window. @dhoehna

**Comment by vineeththomasalex** [comment]
Can confirm that Org repos will appear in the listview(not is the accounts drop-down) if the Org has authorized the Dev Home GitHub Extension OAuth app. Closing this.
