### ISSUE TITLE
Extension title is in different location

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#1686]
### Dev Home version

0.601.283.0

### Windows build number

10.0.23565.1000

### Other software

OS Build Version: 10.0.23565.1000.amd64fre.ni_prerelease.231006-1340
.NET Version: .NET 6.0.22

### Steps to reproduce the bug

![image](https://github.com/microsoft/devhome/assets/1462282/f5e11028-4c4b-4f15-8c52-35e9b5f3d287)
![image](https://github.com/microsoft/devhome/assets/1462282/37f361cc-c7af-4017-9bd9-5d8ac2ab213d)
![image](https://github.com/microsoft/devhome/assets/1462282/5a900009-d8bc-4909-b2c9-7f27289c9a46)

### Actual result

left aligned versus next to body

### Included System Information

Physical Memory: 31.84GB (18.1GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.601.283.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
This is happening because Extensions page uses the actual built-in header functionality, whereas all the other pages turn off the header and make their own. I think we fix this when we fix #566
