### ISSUE TITLE
Problem Adding GitHub Account

### ISSUE THREAD

**Issue by kevincifuentesdev** [microsoft/devhome#1693]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2428

### Other software

OS Build Version: 10.0.22621.2428.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Go to settings, click on accounts, then click on add accounts and login to GitHub.

### Expected result

Open a login window to log in with the GitHub account.

### Actual result

The login window does not open.

### Included System Information

Physical Memory: 7.36GB (2.36GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by vineeththomasalex** [comment]
Duplicate of #1544
