### ISSUE TITLE
Bug in adjusting brightness black screen

### ISSUE THREAD

**Issue by LC-70** [microsoft/devhome#1695]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22635.2419

### Other software

OS Build Version: 10.0.22635.2419.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

在调节屏幕亮度时，会有黑屏的情况，具体表现为：调节一次黑屏，再调节一次又恢复，如此反复。

### Expected result

解决该问题

### Actual result

屏幕无法正常调节亮度

### Included System Information

Physical Memory: 15.86GB (11.56GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Bing translate:

When adjusting the brightness of the screen, there will be a black screen, which is manifested as: adjust the black screen once, adjust it again and resume, and so on.

Resolve the issue

The screen does not adjust the brightness properly

**Comment by krschau** [comment]
It sounds like you're having a general problem with adjusting screen brightness, not a problem specific to Dev Home. This repo is only for Dev Home issues. Please open your issue in Feedback Hub, where it will be routed to the correct people.
