### ISSUE TITLE
Unable to sign in to Github

### ISSUE THREAD

**Issue by uniskela** [microsoft/devhome#1696]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22635.2419

### Other software

OS Build Version: 10.0.22635.2419.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Any possible way I can find the launch the Sign into GitHub modal

### Expected result

When clicking the Sign in, the GitHub sign in is meant to launch on my browser

### Actual result

Nothing happens

### Included System Information

Physical Memory: 15.93GB (1.28GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by vineeththomasalex** [comment]
Duping to #1544
