### ISSUE TITLE
Missing translation for computer configuration section

### ISSUE THREAD

**Issue by Mysterious-Dev** [microsoft/devhome#1697]
### Dev Home version

0.503.261.0

### 🌐 Language

French

### ❌ Actual phrase(s)

![image](https://github.com/microsoft/devhome/assets/40738104/e318d03e-ce6f-445b-b81f-22f9cf4bd59b)

### ✔️ Expected phrase(s)

"Suivant"

### Why is the current translation wrong

The current translation is in English, while other strings are in French.

**Comment by AmelBawa-msft** [comment]
Verified fix in preview
![image](https://github.com/microsoft/devhome/assets/104940545/44571f55-640c-4cb3-b3ed-2da474f707c9)
