### ISSUE TITLE
It is recommended to provide entry buttons for development environments for other platforms

### ISSUE THREAD

**Issue by BraveMomo** [microsoft/devhome#1701]
### Suggested new feature or improvement

It is recommended to provide other platform development environments, such as Android virtual machines, Linux virtual machines and other systems and software, I know that you can install and download, but I still hope to provide a button here, convenient for users to download and open the configuration from here, so that it is the developer home page, in order to improve efficiency, and the other is AI, which is also an important tool for developers, and it should also be added

### Scenario

It is recommended to provide other platform development environments, such as Android virtual machines, Linux virtual machines and other systems and software, I know that you can install and download, but I still hope to provide a button here, convenient for users to download and open the configuration from here, so that it is the developer home page, in order to improve efficiency, and the other is AI, which is also an important tool for developers, and it should also be added

**Comment by shakersMSFT** [comment]
Hi, we have added the ability to create, configure, and launch environments from within Dev Home. We currently support Hyper-V, Microsoft Dev Box, and WSL environments. Please let us know if there are any other environments or functionality you are interested in. https://github.com/microsoft/devhome/issues/2166
