### ISSUE TITLE
Dev Home does not support Windows Widget IsCustomizable package manifest value

### ISSUE THREAD

**Issue by MattHyman** [microsoft/devhome#1713]
### Steps to reproduce the bug

Dev Home does not support Windows Widget [IsCustomizable ](https://learn.microsoft.com/en-us/windows/apps/develop/widgets/widget-provider-manifest#definition)package manifest value. If you set the manifest value IsCustomizable  to false it does not disable/hide the widget customization button. 

### Expected result

Setting the manifest value IsCustomizable to false should disable/hide the widget customization button. 

### Actual result

Setting the manifest value IsCustomizable to false does not disable/hide the widget customization button, it still works as before.

**Comment by krschau** [comment]
Needs WinAppSDK 1.4
