### ISSUE TITLE
Missing Repositories directory in File Manager

### ISSUE THREAD

**Issue by Dru01** [microsoft/devhome#1716]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2428

### Other software

OS Build Version: 10.0.22621.2428.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

On the video of introducing dev home, in the part of dev drive when you show the file explorer there is a repositories "folder" in de panel just above quick access where it expands to the to cloned repositories. I think that is a cool feature but I cant find it, also the new view for the repositories such as git status.

### Expected result

Just to show up that option, and navigate trough repositories in file explroer

### Actual result

Nothing

### Included System Information

Physical Memory: 15.7GB (8.37GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by skanda890** [comment]
Same happens to me.

**Comment by cinnamon-msft** [comment]
This is a /dup of https://github.com/microsoft/devhome/issues/679

We're still working on this feature and it hasn't been implemented yet :)
