### ISSUE TITLE
Provide shortcut with recent project to all dev tools 

### ISSUE THREAD

**Issue by panchalrakesh** [microsoft/devhome#1717]
### Suggested new feature or improvement

On the home screen provide shortcuts to all my projects with different dev tools. VS Code, Android Studio, Visual Studio, and SQL Server Management Studio.

### Scenario

This will be one place to all developments tools for all my projects i am working in different IDE.

### Additional details

Also if possible add TODO app to show pending tasklist and Jenkins build start stop option then it will be complete dev suite.

**Comment by cinnamon-msft** [comment]
Looks like this will be fixed in https://github.com/microsoft/devhome/pull/1049
