### ISSUE TITLE
Use commands in Settings pages/headers

### ISSUE THREAD

**Issue by asklar** [microsoft/devhome#1719]
Hmm I wonder if we can use commands here? As in could we do the call in the view model instead of the view. Looks like the view model here is the settings view model. I think for maintainability purposes it might be good to use an event behavior from `Microsoft.Xaml.Interactivity` then use the `InvokeCommandAction ` to call the command function in the settings view model.

_Originally posted by @bbonaby in https://github.com/microsoft/devhome/pull/1707#discussion_r1362473806_

**Comment by krschau** [comment]
Another thing to do when we make page changes for/like #566.
