### ISSUE TITLE
Reconsider having two Extensions settings pages

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1728]
### Suggested new feature or improvement

Can you remove the Setting>Extensions tab because there is already an 'Extensions' tab it's almost the same.

### Scenario

Rather than going to Setting>Extensions, you can see it directly in Extensions.

### Additional details

No response

**Comment by krschau** [comment]
This is actually something we've discussed a lot 😄 On one hand, we'd like to have only one page to make things simple. On the other hand, there's reasons to keep around each of the pages. We put some telemetry in to see which version gets used more, and plan on making this decision once we have some good numbers around that.
@ethan-fang-MS

**Comment by skanda890** [comment]
Can you put a text in the Dashboard saying "Extensions have been removed from the settings" and remove extensions in the settings?

**Comment by ethan-fang-MS** [comment]
Like Kristen said, we'll have to continue testing which method users prefer and balance that with user expectations of where to access these settings, but point heard that one place for extensions settings under the extensions page and removing access to extensions settings from the settings page is your preference.

**Comment by skanda890** [comment]
Yes

**Comment by krschau** [comment]
Will be addressed by #2212.
