### ISSUE TITLE
feat: add projects to the dashboard

### ISSUE THREAD

**Issue by arthurboss** [microsoft/devhome#1739]
### Suggested new feature or improvement

Dev home can be the main app for devs to manage their projects, but for that, we need to be able to further manage them in it.

Please, add the possibility to manage local projects to the dashboard.

<img width="961" alt="Screenshot 2023-10-23 125317" src="https://github.com/microsoft/devhome/assets/37892811/449700af-12f9-4234-9643-100e1fe01bb3">

Personally, I think projects should be added from the dashboard instead of from the "Machine Configuration" tab. 
Machine configuration is ideal for settings such as the "install applications" (which is an amazing option, btw), "add DevDrive",  and, possibly, "open PowerToys settings" and a direct link to Windows' "Developer Settings".

### Scenario

1. open dashboard
2. see the button to add new / pin project
3. by clicking on the button, see the list of projects that were already cloned in "machine configuration", or, directly see the options to:

- clone project(s)
- add local project(s)
- create new

5. after adding it, the project will be directly visible from the dashboard
6. for each added project, have the options to manage it, such as:

- open with...
- remove from dashboard
- open project location

**Comment by krschau** [comment]
Thanks for being detailed about what you're imagining here! You might want to share it over in #702 as well.

**Comment by cinnamon-msft** [comment]
We're investigating adding a separate projects page for this functionality: https://github.com/microsoft/devhome/pull/1049

Would adding projects widgets to the dashboard solve what you're looking to do here? With the creation aspect staying within the projects page?

**Comment by arthurboss** [comment]
> We're investigating adding a separate projects page for this functionality: #1049
> 
> Would adding projects widgets to the dashboard solve what you're looking to do here? With the creation aspect staying within the projects page?

hey there! I'm sure that with the addition of a projects page my suggestion would be irrelevant, as long as the options to manage the projects are present as well, rather than only the option to launch them (as per the picture within the [PR](https://github.com/microsoft/devhome/pull/1049) description).

Thanks for the replies @krschau and @cinnamon-msft . I'll be closing the issue and look forward to the projects page!
