### ISSUE TITLE
Clone repositories crashes when adding GitHub repo from my organization

### ISSUE THREAD

**Issue by hart-wilson** [microsoft/devhome#1749]
### Dev Home version

0.601.285.0

### Windows build number

10.0.23575.1000

### Other software

OS Build Version: 10.0.23575.1000.amd64fre.ni_moment_directadept.231019-1359
.NET Version: .NET 6.0.22

### Steps to reproduce the bug

1. Added my GitHub account, which is linked to my organization (Microsoft), in Dev Home and signed in, authenticated, etc.
2. Clicked Clone repository, entered URL for a repo from my organization (tried https://github.com/microsoft/wil.git, https://github.com/microsoft/WindowsAppSDK).

### Expected result

Repo is added to the list and can be cloned (like other GitHub repos).

### Actual result

Dev Home app hung (observed once)/crashed.

### Included System Information

Physical Memory: 63.86GB (43.53GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.285.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
@vineeththomasalex and @ssparach This might be an SSO issue.  Like when Github asks to sign in before it shows the page.

**Comment by dhoehna** [comment]
Wait a moment still looking into this.

**Comment by krschau** [comment]
I'm labeling these with both areas, @dhoehna can you label appropriately after your investigation?

**Comment by vineeththomasalex** [comment]
@hart-wilson Would you be able to verify that the [Dev Home OAuth app ](https://github.com/settings/connections/applications/0b354bb03d7f1ee0128f)has been authorized to access Microsoft org?
![image](https://github.com/microsoft/devhome/assets/16733941/65131e1e-1c08-4a2d-b74c-c81e39b363b3)

**Comment by vineeththomasalex** [comment]
@hart-wilson Please reopen this issue if the above steps did not work.
