### ISSUE TITLE
Adding Contribution Section in readme.md

### ISSUE THREAD

**Issue by mohitd404** [microsoft/devhome#1775]
### Provide a description of requested docs changes

Why Contributors section:- A "Contributors" section in a repo gives credit to and acknowledges 
the people who have helped with the project, fosters a sense of community, and helps others
 know who to contact for questions or issues related to the project.

**Issue type**

- [✅] Docs

expected output:- 
![3](https://github.com/microsoft/devhome/assets/146939900/32d86138-ec97-4fb4-ae10-f7b382f22308)

kindly assign this issue to me ! I would love to work on it ! Thank you !

**Comment by cinnamon-msft** [comment]
This is great! If you want to take this on, you're more than welcome to! 🤗
