### ISSUE TITLE
Scrolling on settings is bad

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/devhome#1779]
### Dev Home version

0.601.285.0

### Windows build number

10.0.22621.2500

### Other software

OS Build Version: 10.0.22621.2500.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.22

### Steps to reproduce the bug

Open Settings.

### Actual result

Scroll bar on the setting cards, not on the page.
![image](https://github.com/microsoft/devhome/assets/65828559/2db0bea8-7b27-4935-8723-699439a2ba45)

### Included System Information

Physical Memory: 15.96GB (7.28GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.601.285.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Duplicate of #566
