### ISSUE TITLE
The installation application page in the computer configuration cannot be loaded in China,Loading is very slow

### ISSUE THREAD

**Issue by 19e2k67** [microsoft/devhome#1802]
### Dev Home version

0.601.297.0

### Windows build number

win11 Pro 22621.2506

### Steps to reproduce the bug

The installation application page in the computer configuration cannot be loaded.
It took a long, long time to open it

### Expected result

![Snipaste_2023-11-01_18-16-38](https://github.com/microsoft/devhome/assets/102461738/9a2883b4-b64e-4cb6-b1df-f9e93a50caeb)

![Snipaste_2023-11-01_18-12-42](https://github.com/microsoft/devhome/assets/102461738/bc7f8434-7b74-4b72-86b5-2b5470d2133f)

### Actual result

I hope Successfully loaded in China

**Comment by AmelBawa-msft** [comment]
Possibly related to:
- https://github.com/microsoft/winget-cli/issues/3803
- https://github.com/microsoft/winget-cli/issues/2489

CC: @denelon
