### ISSUE TITLE
App closes when an account is to be added

### ISSUE THREAD

**Issue by 4theEmpire** [microsoft/devhome#1814]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2506

### Other software

OS Build Version: 10.0.22621.2506.arm64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

When i want to add an account the app is closing without any error

### Expected result

The function for adding an account is coming up

### Actual result

The app closes without any error

### Included System Information

Physical Memory: 31.41GB (25.9GB free)
Processor Architecture: ARMx64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_arm64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_arm64__8wekyb3d8bbwe

**Comment by 4theEmpire** [comment]
I found this in the Windows Application Logs:

Name der fehlerhaften Anwendung: DevHome.exe, Version: 1.0.0.0, Zeitstempel: 0x65180f23
Name des fehlerhaften Moduls: Microsoft.UI.Xaml.dll, Version: 3.1.3.0, Zeitstempel: 0xd254d5a6
Ausnahmecode: 0xc000027b
Fehleroffset: 0x0000000000009be8
ID des fehlerhaften Prozesses: 0x0x1558
Startzeit der fehlerhaften Anwendung: 0x0x1DA0D84C2E82275
Pfad der fehlerhaften Anwendung: C:\Program Files\WindowsApps\Microsoft.Windows.DevHome_0.601.297.0_arm64__8wekyb3d8bbwe\DevHome.exe
Pfad des fehlerhaften Moduls: C:\Program Files\WindowsApps\microsoft.windowsappruntime.1.3_3000.934.1904.0_arm64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll
Berichtskennung: 2878fc47-a9cf-4ec2-b114-03e06aba7156
Vollständiger Name des fehlerhaften Pakets: Microsoft.Windows.DevHome_0.601.297.0_arm64__8wekyb3d8bbwe
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: App

**Comment by jmorgan276** [comment]
Exact same problem.
Fresh OS install running on a Virtual Machine.
Using local user account.

Dev Home 0.601.297.0

Device name Windows11
Processor 13th Gen Intel(R) Core(TM) i9-13900 2.00 GHz
Installed RAM 8.00 GB

Edition Windows 11 Pro
Version 23H2
Installed on ‎11/‎3/‎2023
OS build 22631.2715
Experience Windows Feature Experience Pack 1000.22677.1000.0


[github_TempState.zip](https://github.com/microsoft/devhome/files/13391573/github_TempState.zip)
[local_TempState.zip](https://github.com/microsoft/devhome/files/13391574/local_TempState.zip)

**Comment by 4theEmpire** [comment]
Hi,
sorry for the late answer. Here are the Files you wanted.
[DevHome.zip](https://github.com/microsoft/devhome/files/13408052/DevHome.zip)
[DevHome_Githu_Extension.zip](https://github.com/microsoft/devhome/files/13408054/DevHome_Githu_Extension.zip)

**Comment by 4theEmpire** [comment]
Hey guys,
after the last updates of Windows and DevHome it´s now possible to add an Account. I don't know which update was the reason for working now. 
But now i get an Error when i want to Clone my 2 GitHub Repos into my DevDrive (Drive D on my Computer). This Drive was created by the DevHome App. This Drive is normal accessable with the Windows Explorer. 

Here is the Log File for this transaction.
 
[SetupFlow_20231123-113058.zip](https://github.com/microsoft/devhome/files/13448806/SetupFlow_20231123-113058.zip)

**Comment by vineeththomasalex** [comment]
@4theEmpire Thanks for following up! Since the original issue is resolved, I'll close this. I've opened a separate issue for the cloning error "Some tasks failed; showing retry button"  #1958 

@jmorgan276 Looks like the update to Microsoft.Windows.DevHome_**0.701.323.0**_arm64__8wekyb3d8bbwe fixed the problem for @4theEmpire. Please try the update and reopen this issue if it persists. Thanks!
