### ISSUE TITLE
Add Local Repo

### ISSUE THREAD

**Issue by Sickjuicy** [microsoft/devhome#1832]
### Suggested new feature or improvement

Ein Repo das schon existiert hinzufügen.  

### Scenario

Man hat schon vorher repos auf dem PC die man auch gerne über devhome später managen will

**Comment by krschau** [comment]
Bing Translate:

Add Local Repo

**Suggested new feature or improvement**
Add a repo that already exists.

**Scenario**
You already have repos on your PC before, which you would like to manage later via devhome
