### ISSUE TITLE
Create Dev Drive needs to inform user that it is doing a VHDX

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#1853]
### Dev Home version

0.701.311.0

### Steps to reproduce the bug

No where does dev drive here is creating a virtual HD / there is alternative to doing a a bare metal drive with better perf

![image](https://github.com/microsoft/devhome/assets/1462282/aca10776-c71d-421e-a061-905ff9c5a4b4)

![image](https://github.com/microsoft/devhome/assets/1462282/34fd93fd-623d-4d7a-bdf1-bc4ccb439194)

### Expected result

better text

### Actual result

incomplete information to end user

**Comment by AdamBraden** [comment]
@btueffers - please clarify the wording

**Comment by crutkas** [comment]
proposed:
src\tools\SetupFlow\DevHome.SetupFlow\Strings\en-us\Resources.resw

DevDriveWindowOnlyOneDevDriveAllowedHeader.Text
"A Dev Drive optimizes performance for development. You can create only one in Dev Home and it will be a VHDX."

DevDriveWindowLaunchSettingsDisksAndVolumesHeader.Text
"For advanced settings such as creating a native volume, open the settings app"
