### ISSUE TITLE
Generate Dev Environment Configuration (YAML) File

### ISSUE THREAD

**Issue by jjguzzardo** [microsoft/devhome#1857]
### Suggested new feature or improvement

Right now I can import an existing YAML configuration file to clone repositories, install applications, and create dev drives, etc.  But what if this is a new set up and I don't have a configuration file ready to go?  It would be way faster to use a visual tool like Dev Home to set all of that up and then export the configuration file (YAML) so I have it for later use or for installing on other machines.

### Scenario

I'm starting a new project and I have multiple machines that I need to set up with a dev environment.  So starting from scratch, I open up Dev Home and say what dev drives I need.  I then add the repositories I need cloned and map them to the appropriate dev drives.  I can also start adding the applications I need installed, and any other intial setup dev home supports. 

Once I have everything configured in Dev Home, I want to review my configuration in Dev Home and once satisfied, press the go button to start the configuration process and/or export the configuration as a YAML file so that I can quickly set up other machines with the same development environment configuration.  Like a PC + Laptop, for example.

Taking this a step further, I can also check in the YAML file to version control where the rest of my team can pull it and configure their development machines in exactly the same way.

### Additional details

In an ideal world, Dev Home would be able to read a configuration and determine the delta between the config and the current machine so that only what's missing is setup.  Obviously removing anything is probably not a good idea but at least closing the gap for what's missing would be great.

**Comment by cinnamon-msft** [comment]
I think this is a /dup https://github.com/microsoft/devhome/issues/721

**Comment by shakersMSFT** [comment]
Hi, we are currently exploring how we might accomplish this through Dev Home. Please take a look and let us know what you think! https://github.com/microsoft/devhome/issues/2160
