### ISSUE TITLE
The File Converter Feature 

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1873]
### Suggested new feature or improvement

Can you make a feature called Configuration Files?

### Scenario

This is used to convert the Configuration Files  ( .yml or .yaml files ) or vice versa.

**Comment by cinnamon-msft** [comment]
Would you mind providing more info here? What are you looking to convert the files to?

**Comment by skanda890** [comment]
Like .yml to .yaml or .yaml to .yml.

**Comment by cinnamon-msft** [comment]
Checked with the team and the tool should accept both formats, if you have any issues here please let us know, but for now I'm going to close this out :)

**Comment by skanda890** [comment]
In some places .yaml files don't work and vice versa.
