### ISSUE TITLE
Probably remove this option

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1877]
### Suggested new feature or improvement

Note: You should have an extension installed for this to work.
Probably remove the Extensions>3 Dots option.

### Scenario

Remove this option because there is only one option in it, that is the uninstall extension option. Why can't you replace that option as the main option?  As this image shows.
![Screenshot 2023-11-11 142525](https://github.com/microsoft/devhome/assets/99239826/798accd7-3297-45a3-940e-8d33ce2f109c)

**Comment by cinnamon-msft** [comment]
We're planning to add additional items outside of just Uninstall, which is why we added the submenu. :)

**Comment by skanda890** [comment]
Oh, okay.
