### ISSUE TITLE
Can you rebrand something

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1878]
### Suggested new feature or improvement

Can you rebrand Settings>Accounts as Profile

### Scenario

The rebrand probably sounds good.

**Comment by skanda890** [comment]
Do you have plans to rebrand anything?

**Comment by cinnamon-msft** [comment]
We aren't planning to rebrand Accounts to Profile. The accounts just provide authentication to other pieces of Dev Home, but there isn't a notion of a profile (which traditionally adds additional info such as name, preferences, etc.).

**Comment by skanda890** [comment]
Okay.
