### ISSUE TITLE
Can you shift something

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1879]
### Suggested new feature or improvement

Can you shift the Settings>Accounts below settings.

### Scenario

This is used to quickly go to Accounts rather than going to Settings>Accounts.
![Screenshot 2023-11-11 153511](https://github.com/microsoft/devhome/assets/99239826/40f72a8a-62a8-4919-87d8-95d768151ab7)

**Comment by cinnamon-msft** [comment]
We aren't anticipating a lot of traffic to the accounts page, since you sign in once and should be good to go. Due to this, we aren't looking to move it out from the settings page :)
