### ISSUE TITLE
Where is the format button?

### ISSUE THREAD

**Issue by omidshojaee** [microsoft/devhome#1888]
### Dev Home version

0.601.297.0

### Windows build number

10.0.23585.1001

### Other software

OS Build Version: 10.0.23585.1001.amd64fre.ni_prerelease.231104-1132
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Follow the steps to create a Dev Drive.

It'll reach to this step where there's no option other than a Cancel button:

![Screenshot 2023-11-12 142057](https://github.com/microsoft/devhome/assets/31741561/653c7cd9-7bee-4fe5-9b5c-701034267c86)

### Actual result

There's no Format button so the Dev Drive cannot be created.

### Included System Information

Physical Memory: 31.78GB (20.63GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by cinnamon-msft** [comment]
This looks like a bug with the Windows creation flow, rather than the flow inside Dev Home

**Comment by bbonaby** [comment]
Hi @omidshojaee, this was a bug in the Windows insiders channel, the fix should be flowing into there now. Let me know if you're still running into this. Thanks!
