### ISSUE TITLE
System instability ,crashing , slow to respond and freezes Windows 11 OS (build:22621.2506 ,Windows Feature Experience Pack 1000.22677.1000.0)

### ISSUE THREAD

**Issue by FormigaElectra** [microsoft/devhome#1889]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2506

### Other software

OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Instabilidade no sistema ,travamento , demora para responder e congela o sistema operacional Windows 11 (build:22621.2506 ,Windows Feature Experience Pack 1000.22677.1000.0)

### Expected result

Instabilidade no sistema ,travamento , demora para responder e congela o sistema operacional Windows 11 (build:22621.2506 ,Windows Feature Experience Pack 1000.22677.1000.0)

### Actual result

Instabilidade no sistema ,travamento , demora para responder e congela o sistema operacional Windows 11 (build:22621.2506 ,Windows Feature Experience Pack 1000.22677.1000.0)

### Included System Information

Physical Memory: 31.91GB (26.3GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Bing Translate:

Steps to reproduce the bug
System instability ,crashing , slow to respond and freezes Windows 11 OS (build:22621.2506 ,Windows Feature Experience Pack 1000.22677.1000.0)

Expected result
System instability ,crashing , slow to respond and freezes Windows 11 OS (build:22621.2506 ,Windows Feature Experience Pack 1000.22677.1000.0)

Actual result
System instability, crashing, slow to respond and freezes the operating system

**Comment by krschau** [comment]
Hi @FormigaElectra. It sounds like you're having issues with the OS, rather than Dev Home. Please file feedback in Feedback Hub (keyboard shortcut: win+F). That will ensure that your problem gets to the right people to fix it.

If I'm misunderstanding and you do have a problem with Dev Home, please give us more information so we can understand what is wrong.

**Comment by FormigaElectra** [comment]
Não sei se o problema e o sistema operacional ou o próprio software .
