### ISSUE TITLE
Erros de Português

### ISSUE THREAD

**Issue by gabagpereira** [microsoft/devhome#1902]
### Dev Home version

0.601.297.0

### 🌐 Language

Português

### ❌ Actual phrase(s)

Entire application

### Why is the current translation wrong

Even though my PC is configured in my native language (Portuguese), the app is displayed in the brazilian dialect. I prefer to use the app in a language I'm familiar with, when my native language is not available, like English, for instance, instead of being forced to see things displayed in a dialect I don't speak. This is an act of cultural offence and must be fixed as soon as possible, or it will be reported.

**Comment by krschau** [comment]
Dev Home is not translated into every language or dialect, and the operating system will choose a fallback language when the preferred language is not available. If you have feedback on the fallback language order, please open a ticket in Feedback Hub (keyboard shortcut: win+F) and your ticket will be seen by the correct people. Thanks!
