### ISSUE TITLE
Logo/Icon confusingly similar to TP-Link's Tapo logo/icon

### ISSUE THREAD

**Issue by MathewBeldon** [microsoft/devhome#1905]
### Suggested new feature or improvement

A more unique logo/icon

### Scenario

It would help differentiate between Tapo and devhome

**Comment by cinnamon-msft** [comment]
I don't think we have plans to change our icon. I'll bring this up with our designers, but I'll close this issue for now. If we plan on changing it, I can reopen this! :)
