### ISSUE TITLE
"Install App" hangs

### ISSUE THREAD

**Issue by Spinachy** [microsoft/devhome#1912]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22635.2771

### Other software

OS Build Version: 10.0.22635.2771.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

On first open, I selected a repo (from GitHub), and then chose "Docker", "SQL Management Studio", and "Powertoys" to be installed. 

### Expected result

I expected to start using Dev Home

### Actual result

The install of SSMS failed with an error message.
Dev Home process then hanged on trying to install "PowerToys".
(I am running on a Hyper-V VM, which is running Win 11 (which was upgraded from the previous Win 10 install on the same VM). I think some needed installation component for "Dev Home" is missing from my VM?

### Included System Information

Physical Memory: 5.3GB (1.47GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by denelon** [comment]
Dev Home leverages WinGet to display installed packages.

What version of WinGet is installed?
You can run winget -v in Windows Terminal to see which version is installed.
If it is less than 1.6, try updating the "App Installer" in the Microsoft Store.
