### ISSUE TITLE
Missing Unity Software License

### ISSUE THREAD

**Issue by thefutureismatthew** [microsoft/devhome#1918]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

1: Install Unity 2022
2: Open Unity 2022

### Expected result

Unity Editor should load/open.

### Actual result

A text box appears.

"License error"
"No valid Unity Editor license found. Please activate your license."

The only button says "Exit"

### Included System Information

Physical Memory: 11.73GB (2.36GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
I believe this is an issue with Unity, not Dev Home. Closing.
