### ISSUE TITLE
Run Some Software or Commands to start coding

### ISSUE THREAD

**Issue by mbpcoder** [microsoft/devhome#1919]
### Suggested new feature or improvement

Project Templates with Customized Run Commands
Description:
The proposed feature aims to introduce a functionality within the Dev Home Windows app to create project templates that include pre-defined commands or scripts for execution. This feature will assist developers in setting up new projects efficiently by automating initial configuration and setup processes.

Features:
Project Template Creation:

Users can define project templates within the Dev Home app, specifying project name, directory structure, and associated run commands or scripts.
Templates may include various language or framework presets (e.g., JavaScript/Node.js, Python/Flask, etc.) with default configurations.
Customized Run Commands:

Users can add custom commands or scripts specific to each project template.
Ability to define multiple sequential or parallel commands for various tasks like environment setup, package installations, database setup, etc.
Template Management:

Users can manage, edit, and delete existing project templates.
Option to import/export templates for sharing across teams or for personal backup.

### Scenario

Setting up a New Project:
User navigates to Dev Home app and selects "Create New Project."
Chooses a template or creates a new custom template.
Specifies project name, location, and any additional settings.
Defines specific run commands or scripts to be executed during project setup.
Confirms settings and initiates the project creation process.
Running Predefined Commands:
Upon project creation, user navigates to the created project within Dev Home.
Selects the option to run predefined commands or scripts associated with the project template.
Observes the execution of commands and confirms successful setup.
Additional Notes:
This feature aims to simplify the initial setup process, ensuring a seamless and consistent development environment for users.
It caters to both novice users who need basic templates and advanced users who prefer customizable options.
Improved developer experience and reduced setup time are anticipated benefits.

**Comment by cinnamon-msft** [comment]
This looks like a /dup https://github.com/microsoft/devhome/issues/2043
