### ISSUE TITLE
ohne Funktion

### ISSUE THREAD

**Issue by richtertoralf** [microsoft/devhome#1920]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Widgets funktionieren nicht

### Expected result

.

### Actual result

.

### Included System Information

Physical Memory: 31.67GB (23.26GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Hi @richtertoralf. From what you wrote, there's not enough information for me to understand what went wrong and fix it. If you'd like to update this issue with more details, I'd be happy to reopen it.
