### ISSUE TITLE
Can't remove virtual disk

### ISSUE THREAD

**Issue by Maniform** [microsoft/devhome#1921]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22631.2715

### Other software

OS Build Version: 10.0.22631.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

I created a virtual disk that went into my user folder and I want to delete it from Settings > System > Storage > Disks and Volumes as indicated in the documentation.

### Expected result

Find and remove the disk.

### Actual result

The virtual disk drive is present but not the disk. And I can’t delete the disk from my files because access is denied.

### Included System Information

Physical Memory: 28.74GB (15.66GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by Maniform** [comment]
General picture of the issue.
![image](https://github.com/microsoft/devhome/assets/44653826/4d4742ee-9637-40a6-a204-d301d5f71a1f)

**Comment by Maniform** [comment]
Inside Msft Virtual Disk, I can disable and convert it to MBR but that's all.
![image](https://github.com/microsoft/devhome/assets/44653826/b2e6088d-47a8-4575-b712-a627a048e4ab)

**Comment by IntNinja** [comment]
devs should've tested this before letting us dev drive feature, now i lost 50gb of my ssd just because of this bug

**Comment by IntNinja** [comment]
> General picture of the issue. ![image](https://private-user-images.githubusercontent.com/44653826/284023644-4d4742ee-9637-40a6-a204-d301d5f71a1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODQ0OTcsIm5iZiI6MTcwMTA4NDE5NywicGF0aCI6Ii80NDY1MzgyNi8yODQwMjM2NDQtNGQ0NzQyZWUtOTYzNy00MGE2LWEyMDQtZDMwMWQ1ZjcxYTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDExMjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMTY4NDdkOWM0NTc5M2NiYzBiNjViNTcxZTA2M2Q5ZDJkYjI2NjQ3NTE3ZTU5ZjFiOGY1ZDVmNDEzMzFmYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qqN1zhhUwO-XETgfoYHO7PihQqpe-LCSXKk-uYuoOj0)

Possible Temporary Workaround:

Try Going into Advanced Startup (Usually restarting with holding `shift` key)
Click `Troubleshooting`
Then click `Advanced Options`
Then Open `Command Prompt`
type `X:` (in place of X type your drive name where the vhdx is)
`cd DevDrive`
and type `del DevDrive.vhdx`

and boom it's gone!

@krschau this is not the best workaround but it works!

**Comment by dhoehna** [comment]
Another work around is
1. Go to Disk Management
2. Expand the window to see the dev drive.
3. Right click near the icon
![image](https://github.com/microsoft/devhome/assets/2517139/579c8c22-6c80-4dfc-a5ef-c2cb08a65f11)
4. Select "Detach VHD"
5. A warning will ask "Are you sure" note down the location of the vhdx.
6. Press okay.
7. Navigate to the vhdx and remove it.

**Comment by neoncube2** [comment]
@dhoehna Can we reopen this? :)  I know there's a workaround, but I think this root issue needs to be fixed :)

**Comment by IntNinja** [comment]
> @dhoehna Can we reopen this? :) I know there's a workaround, but I think this root issue needs to be fixed :)

You can uninstall the driver of the VHD, simple
