### ISSUE TITLE
Visual Studio 2022 Preview not recognized

### ISSUE THREAD

**Issue by nepp95** [microsoft/devhome#1922]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22631.2715

### Steps to reproduce the bug

Visual Studio 2022 Community preview version is not recognized as having Visual Studio 2022 Community installed.

### Expected result

Show it as installed

### Actual result

Not showing it as installed

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by denelon** [comment]
Dev Home leverages WinGet to display installed packages.

What version of WinGet is installed?
You can run `winget -v` in Windows Terminal to see which version is installed.
If it is less than 1.6, try updating the "App Installer" in the Microsoft Store.

Can you run `winget list Visual` in Windows Terminal and confirm whether or not WinGet is aware of Visual Studio?

**Comment by nepp95** [comment]
```
winget -v

v1.6.3482
```

```
winget list visual

Name                                    Id                                       Version            Available    Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2010  x64 Redistr… Microsoft.VCRedist.2010.x64              10.0.40219                      winget
Microsoft Visual C++ 2013 Redistributa… Microsoft.VCRedist.2013.x64              12.0.40664.0                    winget
Microsoft Visual C++ 2015-2022 Redistr… Microsoft.VCRedist.2015+.x64             14.38.33130.0                   winget
Microsoft Visual C++ 2015-2022 Redistr… Microsoft.VCRedist.2015+.x86             14.38.33130.0                   winget
Microsoft Visual C++ 2012 Redistributa… Microsoft.VCRedist.2012.x86              11.0.61030.0                    winget
Microsoft Visual C++ 2013 Redistributa… Microsoft.VCRedist.2013.x86              12.0.40664.0                    winget
Microsoft Visual C++ 2012 Redistributa… Microsoft.VCRedist.2012.x64              11.0.61030.0                    winget
Microsoft Visual C++ 2010  x86 Redistr… Microsoft.VCRedist.2010.x86              10.0.40219                      winget
Visual Studio Build Tools 2019          Microsoft.VisualStudio.2019.BuildTools   16.11.32                        winget
Visual Studio Community 2022 Preview    Microsoft.VisualStudio.2022.Community.P… 17.9.0 Preview 1.0              winget
Microsoft Visual Studio Code (User)     Microsoft.VisualStudioCode               1.85.1                          winget
Microsoft Visual C++ 2008 Redistributa… Microsoft.VCRedist.2008.x64              9.0.30729.6161                  winget
Microsoft .NET SDK 8.0.100 (x64) from … {603FF09B-ADA6-4EBF-B5CA-D21069C73E8B}   8.1.23.55115
Microsoft Visual Studio Installer       {6F320B93-EE3C-4826-85E0-ADF79F8D4C61}   3.9.107.56113
Microsoft Visual C++ 2005 Redistributa… {ad8a2fa1-06e7-4b0d-927d-6e54b3d31028}   8.0.61000
Microsoft Visual C++ 2013 Redistributa… Microsoft.VCRedist.2013.x64              12.0.30501.0       12.0.40664.0 winget
Microsoft Visual C++ 2005 Redistributa… Microsoft.VCRedist.2005.x86              8.0.61001                       winget
Microsoft Visual C++ 2008 Redistributa… Microsoft.VCRedist.2008.x86              9.0.30729.6161                  winget
Microsoft Visual Studio Tools for Appl… {f3fbabb4-bcfb-45eb-8fff-9b784fd68c38}   16.0.31110
Microsoft Visual C++ 2013 Redistributa… Microsoft.VCRedist.2013.x86              12.0.30501.0       12.0.40664.0 winget
Microsoft Visual C++ 2015 UWP Runtime … Microsoft.VCLibs.140.00_8wekyb3d8bbwe    14.0.32530.0
Microsoft Visual C++ 2015 UWP Desktop … Microsoft.VCLibs.Desktop.14              14.0.32530.0                    winget
Microsoft Visual C++ 2012 UWP Desktop … Microsoft.VCLibs.110.00.UWPDesktop_8wek… 11.0.61135.0
Microsoft Visual C++ 2013 UWP Desktop … Microsoft.VCLibs.120.00.UWPDesktop_8wek… 12.0.40653.0
Microsoft .NET Core Runtime - 3.1.30 (… Microsoft.DotNet.Runtime.3_1             3.1.30             3.1.32       winget
```

It is in the list as you can see.
Currently on 0.801.344.0 dev home version, so a bunch of updates later.

**Comment by AmelBawa-msft** [comment]
Searching for `Visual Studio Community 2022` yields 3 results:

### Dev Home
![image](https://github.com/microsoft/devhome/assets/104940545/1a88bb9a-2927-4f88-ba38-1a0a1dec58a1)

### WinGet CLI
![image](https://github.com/microsoft/devhome/assets/104940545/da63e151-20ea-42af-94a0-2df8c63aab1c)

### About the result:
- Out of the box, `winget` will return the results from the default sources `winget` and `msstore`.
  - `winget source list` for more details.
- The first result is from the store (`msstore`), and the second and third results are from `winget`.
- Because [Visual Studio Community 2022](https://github.com/microsoft/winget-pkgs/tree/8cd77b6035e2689580fa2784c017dcab53b080b4/manifests/m/Microsoft/VisualStudio/2022/Community) and [Visual Studio Communit 2022 Preview](https://github.com/microsoft/winget-pkgs/tree/8cd77b6035e2689580fa2784c017dcab53b080b4/manifests/m/Microsoft/VisualStudio/2022/Community/Preview) are two different packages and are registered correspondingly in `winget-pkgs` repository (click on links for details), only the installed package is expected to reflect as installed in Dev Home.

### Follow up
- Would it be possible to post a screenshot for the search result of `Visual Studio Community 2022` (similar to my screenshots above)

**Comment by nepp95** [comment]
> Searching for `Visual Studio Community 2022` yields 3 results:
> 
> 
> 
> ### Dev Home
> 
> ![image](https://github.com/microsoft/devhome/assets/104940545/1a88bb9a-2927-4f88-ba38-1a0a1dec58a1)
> 
> 
> 
> ### WinGet CLI
> 
> ![image](https://github.com/microsoft/devhome/assets/104940545/da63e151-20ea-42af-94a0-2df8c63aab1c)
> 
> 
> 
> ### About the result:
> 
> - Out of the box, `winget` will return the results from the default sources `winget` and `msstore`.
> 
>   - `winget source list` for more details.
> 
> - The first result is from the store (`msstore`), and the second and third results are from `winget`.
> 
> - Because [Visual Studio Community 2022](https://github.com/microsoft/winget-pkgs/tree/8cd77b6035e2689580fa2784c017dcab53b080b4/manifests/m/Microsoft/VisualStudio/2022/Community) and [Visual Studio Communit 2022 Preview](https://github.com/microsoft/winget-pkgs/tree/8cd77b6035e2689580fa2784c017dcab53b080b4/manifests/m/Microsoft/VisualStudio/2022/Community/Preview) are two different packages and are registered correspondingly in `winget-pkgs` repository (click on links for details), only the installed package is expected to reflect as installed in Dev Home.
> 
> 
> 
> ### Follow up
> 
> - Would it be possible to post a screenshot for the search result of `Visual Studio Community 2022` (similar to my screenshots above)

Hello,

Following up on your response; sadly to say I no longer have Windows 11 or dev home for that matter installed so I can not show you this. At the time it did not show up but it is possible since I reported this 5-6 months ago, that it got fixed in the meantime. If no other users report on this, I think we can assume this has been resolved.

*happily continuing development on my Win10 system*

Kind regards,
Niels
