### ISSUE TITLE
Dev Home says it is Not Responding

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1924]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Launch the application and go to the Feedback option.

### Expected result

It should load that menu.

### Actual result

It says it is Not Responding.

### Included System Information

Physical Memory: 11.89GB (1.28GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Hi @skanda890. Is this an issue you're hitting consistently, or a one-time thing?

**Comment by skanda890** [comment]
> Hi @skanda890. Is this an issue you're hitting consistently, or a one-time thing?

A one time thing.

**Comment by krschau** [comment]
As it only happened one time, I'm going to close this. We have other issues open for crashes in other parts of the app, but if it happens again here please let us know and if you can, include the logs.

**Comment by skanda890** [comment]
@krschau I found that issue today, but I am on leave.
