### ISSUE TITLE
한국인

### ISSUE THREAD

**Issue by NidanurCabbar** [microsoft/devhome#1928]
### Dev Home version

0.601.297.0

### 🌐 Language

터기어

### ❌ Actual phrase(s)

The Microsoft Dev Home interface is in Korean on my computer.

### ✔️ Expected phrase(s)

 I request that this language be corrected to Turkish.

### Why is the current translation wrong

There are no translation errors. The interface is in a completely different language. I want it to be Turkish.

**Comment by krschau** [comment]
Hi @NidanurCabbar. Currently, Dev Home should be displaying in whatever language you have your Windows settings set to. I want to double check that you mean your computer is set to Turkish but Dev Home is showing up in Korean, and not that you mean you'd like to have your computer set to Korean and be able to set Dev Home specifically to display in Turkish.

**Comment by krschau** [comment]
Hi @NidanurCabbar. Dev Home is not translated into every language, and the operating system will choose a fallback language when the preferred language is not available. If the fallback language isn't correct, please open a ticket in Feedback Hub (keyboard shortcut: win+F) and your issue will be seen by the correct people. Thanks!
