### ISSUE TITLE
used an organization git clone URL and dev Home crashed.

### ISSUE THREAD

**Issue by sanzserif** [microsoft/devhome#1930]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

1. Navigate to machine configuration -> add a repository
2. give URL option and enter git repo url (mine was a organization URL, didn't authorized at that time)
3. gave a custom folder.
4. click ok.

### Expected result

needs to be return a success message saying repository cloned or failed reason. didn't know the actual response cause i didn't even saw the success screen at the first place.

### Actual result

whole project freezes for a second and then crashes. did happen when create dev drive tickbox on and off.

### Included System Information

Physical Memory: 31.64GB (19GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
Hello,

Thank you for bringing this to our attention.  Is it possible to share the URL you are using so we can test with it?

**Comment by dhoehna** [comment]
This is a known issue in version 0.6.  Can you please upgrade both DevHome and DevHomeGitHub extension to version 0.7?

**Comment by sanzserif** [comment]
> Hello,
> 
> Thank you for bringing this to our attention. Is it possible to share the URL you are using so we can test with it?

I'm afraid i can't because of a company private repository.



> This is a known issue in version 0.6. Can you please upgrade both DevHome and DevHomeGitHub extension to version 0.7?

I'll check and inform.
