### ISSUE TITLE
Why is the filter bar be visible

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1938]
### The Question

Why is the filter bar visible?

**Comment by skanda890** [comment]
Can anybody label this as 'Issue-Question' and remove the label 'Issue-Feature'?

**Comment by krschau** [comment]
What filter bar are you referring to?

**Comment by skanda890** [comment]
This bar



![Screenshot_2023-11-22-16-40-08-182_com.github.android-edit.jpg](https://github.com/microsoft/devhome/assets/99239826/ffeafd2a-be37-44a3-ac9e-d8729a3173a4)

**Comment by skanda890** [comment]
Oh, sorry, wrong repository.
