### ISSUE TITLE
Problem on screen

### ISSUE THREAD

**Issue by dany118d** [microsoft/devhome#1939]
### Dev Home version

0.701.323.0

### Windows build number

10.0.22631.2715

### Other software

OS Build Version: 10.0.22631.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

Just open the app and navigate the sections

### Expected result

Normal images and screen view

### Actual result

Blurry parts

### Included System Information

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Physical Memory: 15.85GB (5.19GB free)
Processor Architecture: x64
NVIDIA GEFORCE GTX 1060 GPU + Intel UHD 630

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Hi @dany118d, was this a one time thing or are you seeing it all the time? If you can reproduce it, can you include a screenshot?

**Comment by krschau** [comment]
This isn't an issue we can fix on Dev Home, but if you submit it through Feedback Hub it should get to the right people who can.
