### ISSUE TITLE
Why is Dev Home automatically installed after a Windows 11 update

### ISSUE THREAD

**Issue by AntMaster7** [microsoft/devhome#1942]
I just noticed that this tool has been installed on my computer without any prior consent. In my case the tool might be helpful. But why does it have to be installed on each and every Windows 11 installation? Most users are not developers and have no use for such a tool.

**Comment by BenS13** [comment]
You did consent

**Comment by AntMaster7** [comment]
@BenS13 Maybe indirectly through some agreement text when I installed Windows 11. But I never explicitely agreed to install dev home. I mean I wasn't even aware it existed until I noticed it in my start menu.

**Comment by domoaligato** [comment]
@cinnamon-msft Why are preview releases of this pushed to all windows 11 users? 
Why not only push to users that have enabled developer mode?
Shouldn't the project become GA before pushing to every windows 11 user?

**Comment by AntMaster7** [comment]
> /dup #1615

@cinnamon-msft This other issue has already been closed. But since there is no satisfying response as to why this is pushed to each and every client, the issue still remains.

**Comment by gpz1100** [comment]
It's almost end of February 2024 and this issue appears to be ongoing.  Just had to remove this app from a vm I was testing win11 23h2 in.
