### ISSUE TITLE
New button for the Extension menu

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1944]
### Suggested new feature or improvement

New button on the Extensions menu and on each extension, called 'Check for updates'.

### Scenario

This could be used to update the Dev Home Extensions.

**Comment by cinnamon-msft** [comment]
Can you provide more info here about what you mean by "add updates"? Do you mean in Dev Home itself? In the repo somewhere?

**Comment by skanda890** [comment]
I have changed the issue a little bit.

**Comment by cinnamon-msft** [comment]
We have a "Get updates" button on the extensions page, which has this functionality. :)
![image](https://github.com/microsoft/devhome/assets/48369326/d5771ff5-7de4-46e3-bf9f-c1a84619e308)

**Comment by skanda890** [comment]
I wasn't there before.

**Comment by krschau** [comment]
The button only shows up when you have extensions installed, otherwise there aren't any updates to check for.
