### ISSUE TITLE
Dev Home crashes after clicking on Settings>Account>Add Account

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1945]
### Dev Home version

0.701.323.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

Note: You should be signed out.
Go to Settings>Account>Add Account.

### Expected result

It should load that menu.

### Actual result

The Add Account option became greyed out, and after that, the Dev Home app crashed.

### Included System Information

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Physical Memory: 11.89GB (0.67GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.200.323.0_x64__8wekyb3d8bbwe

### A picture for reference

![image](https://github.com/microsoft/devhome/assets/99239826/c92e5980-6304-4164-8a71-e0a53064c036)

**Comment by mpekurin** [comment]
I'm not the author but I have approximately the same issue. The button is not greyed out but the app suggests to install an extension when I'm trying to log in, even though I have the GitHub extension installed and the app shows it on the Extensions page.

Here's the log:
```
[2023.12.14 06:05:05.7751][DevHome] ERROR: Failed to get IDeveloperIdProvider provider from 'Dev Home GitHub Extension (Preview)'
System.Runtime.InteropServices.COMException (0x80131500)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.Windows.DevHome.SDK.IExtensionMethods.GetProvider(IObjectReference _obj, ProviderType providerType)
   at ABI.Microsoft.Windows.DevHome.SDK.IExtension.global::Microsoft.Windows.DevHome.SDK.IExtension.GetProvider(ProviderType providerType)
   at DevHome.Models.ExtensionWrapper.GetProviderAsync[T]()
   at DevHome.Services.AccountsService.GetDevIdProviders()
```

**Comment by skanda890** [comment]
> I'm not the author but I have approximately the same issue. The button is not greyed out but the app suggests to install an extension when I'm trying to log in, even though I have the GitHub extension installed and the app shows it on the Extensions page.
> 
> Here's the log:
> 
> ```
> [2023.12.14 06:05:05.7751][DevHome] ERROR: Failed to get IDeveloperIdProvider provider from 'Dev Home GitHub Extension (Preview)'
> System.Runtime.InteropServices.COMException (0x80131500)
>    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at ABI.Microsoft.Windows.DevHome.SDK.IExtensionMethods.GetProvider(IObjectReference _obj, ProviderType providerType)
>    at ABI.Microsoft.Windows.DevHome.SDK.IExtension.global::Microsoft.Windows.DevHome.SDK.IExtension.GetProvider(ProviderType providerType)
>    at DevHome.Models.ExtensionWrapper.GetProviderAsync[T]()
>    at DevHome.Services.AccountsService.GetDevIdProviders()
> ```

For me, the same thing came.

**Comment by vineeththomasalex** [comment]
There seems to be some problem around reading/removing credentials from Credential Manager. Would you be able to try the following:
- Open "Credential Manager" from start menu
- Go to "Windows Credentials"
- Under "Generic Credentials", delete all credentials under "GitHubDevHomeExtension".
- Restart DevHome and see if this still occurs

Please let me know if this works. Also, thanks a lot for filing this issue and providing the logs!

**Comment by andrenascentes** [comment]
The solution works for me! Thanks!

**Comment by skanda890** [comment]
I didn't find that credential.

> There seems to be some problem around reading/removing credentials from Credential Manager. Would you be able to try the following:
> 
> * Open "Credential Manager" from start menu
> * Go to "Windows Credentials"
> * Under "Generic Credentials", delete all credentials under "GitHubDevHomeExtension".
> * Restart DevHome and see if this still occurs
> 
> Please let me know if this works. Also, thanks a lot for filing this issue and providing the logs!

**Comment by skanda890** [comment]
Fixed!
