### ISSUE TITLE
Why is there no Experimental Features

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1946]
### The Question

Have you implemented any Experimental Features or not? Because it is empty for me.

### A picture for reference

![image](https://github.com/microsoft/devhome/assets/99239826/2ed1422b-efb1-47d1-82c6-9ed7d9e0f9a3)

**Comment by skanda890** [comment]
Label this as 'Issue-Question', and remove the label 'Issue-Bug'.

**Comment by krschau** [comment]
Nope, not yet. But we wanted to get the framework for experimental features in, so people could work on experimental features.

**Comment by skanda890** [comment]
Oh, okay.
