### ISSUE TITLE
Why is there no '>' in the Azure Extension

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1949]
### The Question

Why is there no '>' in the Azure Extension?

### A picture

![image](https://github.com/microsoft/devhome/assets/99239826/f9beb831-b9c4-4893-a0de-c6a44be28596)

**Comment by skanda890** [comment]
Can somebody label this as 'Issue-Question' and remove 'Issue-Feature'?

**Comment by vineeththomasalex** [comment]
This depends on whether the extension provides a way to set extension-specific settings. Azure Extension does not currently have this (SettingsProvider)

**Comment by skanda890** [comment]
But still there should be that option.

**Comment by skanda890** [comment]
At least label this as 'Issue-Question'.
