### ISSUE TITLE
can't unisntall this app

### ISSUE THREAD

**Issue by JyothiPrakash1812** [microsoft/devhome#1951]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22631.2715

### Other software

OS Build Version: 10.0.22631.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

can't unisntall this app the button is in disabled state. OR unable to figure out how to unistall 

### Expected result

unistall

### Actual result

can't unistall

### Included System Information

Physical Memory: 23.84GB (10.95GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by Namefi** [comment]
open PowerShell as administrator and paste this in " Get-AppxPackage *Windows.DevHome* | Remove-AppxPackage"
