### ISSUE TITLE
Program installing yourself for no reason out of nowhere

### ISSUE THREAD

**Issue by Ssssoar** [microsoft/devhome#1953]
### Dev Home version

0.701.323.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

Being alive and owning a windows PC

### Expected result

For windows to not install shit without asking outta nowhere

### Actual result

Windows installed this shit without even telling or asking permission or anything at all.

**Comment by BenS13** [comment]
It doesn't need to ask permission bro
