### ISSUE TITLE
Widgets on windows desktop (explorer)

### ISSUE THREAD

**Issue by hikinine** [microsoft/devhome#1954]
### Suggested new feature or improvement

I would like to know if its possible to use Dev Home widgets on my desktop explorer. I understand that is something different be able to display the widget on explorer or  inside the DevHome. 

It's interesting the dashboard panel, but not useful when I have to open a screen to look at it... (Why not just open GitHub instead). 

### Scenario

Something like right button click on the preferred widget -> add to explorer. 

OR

Right button click on explorer -> add widget from DevHome.

### Additional details

![image](https://github.com/microsoft/devhome/assets/30875229/e7e837d8-1f02-44c6-ae47-cb7a5756ba69)

**Comment by cinnamon-msft** [comment]
This would be a feature added to Windows to support desktop widgets, which is out of scope for us unfortunately. :( I'd suggest filing this request on Feedback Hub!
