### ISSUE TITLE
Move the Feedback row in the Settings page to the bottom

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1956]
### Suggested new feature or improvement

Can you make the 'Feedback' column the last column? 

![image](https://github.com/microsoft/devhome/assets/99239826/7ab41654-5b3d-491a-bc95-82b0f1ec8cdb)

### Scenario

Before the previous update the 'Feedback' column was the last.

**Comment by cinnamon-msft** [comment]
Yeah I think this makes sense

**Comment by skanda890** [comment]
So, tell me when fix is completed.
