### ISSUE TITLE
Upgrade to .NET 8

### ISSUE THREAD

**Issue by snickler** [microsoft/devhome#1957]
### Suggested new feature or improvement

Upgrade to the latest .NET 8 LTS. 

### Scenario

.NET 8 brings much performance enhancements and stability.

### Additional details

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8

**Comment by snickler** [comment]
I'd be glad to take this one on since I just finished the .NET 8 upgrade of PowerToys.

**Comment by crutkas** [comment]
@snickler  here is the current branch @dhoehna is working on.  https://github.com/microsoft/devhome/tree/user/dhoehna/UpgradingToDotNetEight
