### ISSUE TITLE
Error while cloning: Some tasks failed; showing retry button

### ISSUE THREAD

**Issue by vineeththomasalex** [microsoft/devhome#1958]
### Dev Home version

Microsoft.Windows.DevHome_0.701.323.0_arm64__8wekyb3d8bbwe 

### Windows build number

10.0.22621.2506.arm64fre.ni_release.220506-1250

### Steps to reproduce the bug

Clone to DevDrive after logging in

>when i want to Clone my 2 GitHub Repos into my DevDrive (Drive D on my Computer). This Drive was created by the DevHome App. This Drive is normal accessable with the Windows Explorer.

Copied from #1814

### Actual result

"Some tasks failed;"

Here is the Log File for this transaction.
[SetupFlow_20231123-113058.zip](https://github.com/microsoft/devhome/files/13448806/SetupFlow_20231123-113058.zip)

Noticed the "Some tasks failed; showing retry button" line

**Comment by dhoehna** [comment]
Closing as this message does not indicate how to reproduce the error.  Looked at the logs. No errors are in the logs.

If you are still seeing issues, please re-open with repro steps.
