### ISSUE TITLE
Add new repository button not work

### ISSUE THREAD

**Issue by miladashrafi** [microsoft/devhome#1959]
### Dev Home version

0.701.323.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

Go to machine configuration
Try to add a new repository

### Expected result

It should open a window to add repo url

### Actual result

Add new repository button not work

### Included System Information

CPU: Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz
Physical Memory: 31.94GB (21.9GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe

**Comment by miladashrafi** [comment]
Hi, Thank you for your reply.
The problem is fixed now after auto-update of windows to build: 22631.2715

[Click Here to get logs](https://1drv.ms/u/s!AnBMpyOeZ2UXb-q8qeUOTKqZ8r4?e=cVgFxA)

%LOCALAPPDATA%\Packages\Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe not found to retrieve logs.
@dhoehna

**Comment by dhoehna** [comment]
I'm glad the issue was resolved.  Odd though that a new windows build fixed the issue. Still.  Good it is fixed.
