### ISSUE TITLE
Enable compatibility with MAC OS

### ISSUE THREAD

**Issue by shrijayan** [microsoft/devhome#1972]
### Suggested new feature or improvement

- Add support for MAC OS

### Scenario

Currently, Microsoft Dev Home does not support MAC OS. This means that MAC OS developers cannot use the IDE to develop their applications. This is a significant limitation, as MAC OS is a popular platform for developers.

**Benefits of adding support for MAC OS:**
_Increased developer reach:_ By adding support for MAC OS, Microsoft Dev Home would be able to reach a wider audience of developers. This would help to grow the community of users and make the IDE more popular.

_Improved developer productivity:_ MAC OS developers would be able to use Microsoft Dev Home to develop their applications, which would improve their productivity.

_Reduced fragmentation:_ Adding support for MAC OS would reduce the fragmentation of the developer landscape. This would make it easier for developers to develop applications for all platforms.

**Call to action:**
I suggest the Microsoft Dev Home team add support for MAC OS in the next major release of the IDE. This would be a significant improvement that would benefit a large number of developers.

**Comment by cinnamon-msft** [comment]
To add a bit more context here, Dev Home isn't an IDE, but rather a tool to help you get started coding and stay productive on Windows as a developer. It doesn't assist with the actual writing of code (not yet anyway 😉). We deliver Windows-specific features, so supporting MacOS isn't on our roadmap on the moment. I'm going to close this out, but if we decide to support MacOS, I'll happily reopen this!
