### ISSUE TITLE
Percentage memory in widget

### ISSUE THREAD

**Issue by KurroLopez** [microsoft/devhome#1986]
### Suggested new feature or improvement

It might be useful if the memory widget shows the percentage of memory used in addition to the total memory used

### Scenario

![image](https://github.com/microsoft/devhome/assets/40236469/17b93ec0-2923-4ddd-84e5-ee705548eeca)

**Comment by Gobinath-B** [comment]
Hai, I want to work in this feature.

**Comment by cinnamon-msft** [comment]
Go for it!

**Comment by Gobinath-B** [comment]
I raised a pr that has this feature @cinnamon-msft

**Comment by KurroLopez** [comment]
I am looking forward to use this new feature, good job @krschau
