### ISSUE TITLE
It cannot be restarted after closing the software

### ISSUE THREAD

**Issue by HelloPeter123456789** [microsoft/devhome#1995]
### Dev Home version

0.701.323.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

我关闭软件后无法启动软件

### Expected result

软件可以启动

### Actual result

软件关闭后无法重新打开，重启后恢复。

### Included System Information

CPU: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Physical Memory: 31.85GB (20.8GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Bing Translate:
It cannot be restarted after closing the software

Steps to reproduce the bug
I can't start the software after I close it

Expected result
The software can be launched

Actual result
The software cannot be reopened after it is closed, and it can be restored after restarting.
