### ISSUE TITLE
PLEASE

### ISSUE THREAD

**Issue by kazuser** [microsoft/devhome#1996]
### Suggested new feature or improvement

![image](https://github.com/microsoft/devhome/assets/3335273/ec61398b-ef9a-4692-8b00-2461667e8e29)

Remove this shit from my computer and don't install it again. Never.

I didn't ask for it.

I don't need it.

### Scenario

1. Take Dev.
2. Go Home.

**Comment by kazuser** [comment]
Yes, it sounds strange, but it actually disappeared from my computer after my request here.

I wonder if they could install it and remove it from macOS? 🤔

**Comment by CanePlayz** [comment]
🤨

**Comment by BenS13** [comment]
> ### Suggested new feature or improvement
> ![image](https://private-user-images.githubusercontent.com/3335273/287429128-ec61398b-ef9a-4692-8b00-2461667e8e29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTk2OTEsIm5iZiI6MTcwMTg1OTM5MSwicGF0aCI6Ii8zMzM1MjczLzI4NzQyOTEyOC1lYzYxMzk4Yi1lZjlhLTQ2OTItOGIwMC0yNDYxNjY3ZThlMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDZUMTA0MzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjZmNjVmODMwZGE5OGY4MzliNDFkMjdiNWRjOGFjODEyZjY0YmI0MmExYTNhMTE3MDM1ZWNkNjhhZWVlMzA3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pT-qg9AmkvSlMzV2fmDAIRMeHsN97wn5NcqM1AbDCGg)
> 
> Remove this shit from my computer and don't install it again. Never.
> 
> I didn't ask for it.
> 
> I don't need it.
> 
> ### Scenario
> 1. Take Dev.
> 2. Go Home.
> 
> ### Additional details
> _No response_

You kinda agreed when u wanted to use MS Services and Products

**Comment by kazuser** [comment]
I paid for their operating system only. Not for testing their other software 🥲

**Comment by BenS13** [comment]
Did you read the terms when you purchased the software. Probably not.

**Comment by kazuser** [comment]
When you learn to listen to your users, then you will win.
And as long as you play unfairly and force consumers to do things they don’t ask for, you will always lose.
These are the rules of this simple game.

**Comment by Jay-o-Way** [comment]
> I paid for their operating system

You what? 😧
