### ISSUE TITLE
already have a dev drive

### ISSUE THREAD

**Issue by matebenyovszky** [microsoft/devhome#2002]
### Suggested new feature or improvement

I already have a dev drive, it should be detected

### Scenario

I already have a dev drive, it should be detected

### Additional details

I already have a dev drive, it should be detected

**Comment by bbonaby** [comment]
Also @matebenyovszky would you be able to send us the output from running the following command in an elevated command prompt or PowerShell window?

"fsutil devdrv query "drive letter of dev drive"

Thank you!

**Comment by matebenyovszky** [comment]
[TempState.zip](https://github.com/microsoft/devhome/files/13572863/TempState.zip)
[TempState_Github.zip](https://github.com/microsoft/devhome/files/13572868/TempState_Github.zip)

![image](https://github.com/microsoft/devhome/assets/57362482/2db55dc1-57ab-42c1-ae72-16365777a84c)

**Comment by matebenyovszky** [comment]
![image](https://github.com/microsoft/devhome/assets/57362482/00e25898-5a37-47cc-bc44-95a466f0d53b)

Windows Settings app recognized it. I made this Dev Drive on this machine.
I don't know if it is in relation with the issue, but I have to manually mount the drive after every reboot.

**Comment by bbonaby** [comment]
Thanks for the info @matebenyovszky, quick question. Are you saying that Dev Home does not detect that you have a Dev Drive? 
E.g The only place where we detect a Dev Drive in Dev Home is on the clone repository page where we auto select your Dev Drive as a clone location:

![image](https://github.com/microsoft/devhome/assets/105318831/6e4da3a3-5468-4061-8585-c7b42e4a7fb2)

 

As for the automount issue, we're having the Storage team take a look at that issue. Unfortunately, it can't be solved on the Dev Home or Windows Settings side of things.
