### ISSUE TITLE
No access to my repositories

### ISSUE THREAD

**Issue by JumbaJookiba** [microsoft/devhome#2012]
### Dev Home version

0.701.323.0

### Windows build number

10.0.22631.2792

### Other software

OS Build Version: 10.0.22631.2792.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

I tried importing a repository from DevOps.
When I select my account, no repository is found.
If I try using the repository URL, I am asked twice to authenticate; but the import fails anyway

### Expected result

I wanted to clone a repository on my computer

### Actual result

I was not allowed

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
Physical Memory: 15.84GB (3.59GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.200.323.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
Hi @JumbaJookiba,

The reason why DevHome could not find your DevOps account is because DevHome did not have access to DevOps servers because it did not have an Azure extension.

Currently, DevHome does come with an Azure extension.  Can you please get the latest version of DevHome and try again?  If you are still running into issues, please supply your /logs so I can further diagnose your issue.

**Comment by JumbaJookiba** [comment]
> Hi @JumbaJookiba,
> 
> The reason why DevHome could not find your DevOps account is because DevHome did not have access to DevOps servers because it did not have an Azure extension.
> 
> Currently, DevHome does come with an Azure extension. Can you please get the latest version of DevHome and try again? If you are still running into issues, please supply your /logs so I can further diagnose your issue.

You did not notice I opened the issue on December, 7th last year, after the release of the DevOps extension.
I am still haveing the same problem: no repo is displayed, if I connect with my DevOps, and if I try to clone a repo, it still says I am not authorized:
![image](https://github.com/microsoft/devhome/assets/14105436/26dea06d-eddc-4d6c-8330-a21c9a1060d4)

**Comment by JumbaJookiba** [comment]
%LOCALAPPDATA%\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\TempState\DevHome is empty
Find %LOCALAPPDATA%\Packages\Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe\TempState contents in 
[TempState.zip](https://github.com/microsoft/devhome/files/14946190/TempState.zip)

**Comment by dhoehna** [comment]
Hello.  You are correct.  I apologize for mis-reading your issue.

Thank you for the logs and I'll need one more from you to diagnose this issue.  Sorry for asking for logs a second time.

Can you provide the logs at %LOCALAPPDATA%\Packages\Microsoft.Windows.DevHome`Azure`Extension_8wekyb3d8bbwe\TempStat?

Also, I noticed that the versions you have installed are out-of-date.  Can you please upgrade to the newest versions if you haven't already and try again?

**Comment by JumbaJookiba** [comment]
Hello.
I tried with several repo, all used by our development teams; therefore, I am quite sure they are enabled (I did not even know they can be disabled).
I work (or at least, try to) with DevHomePre, and it is automatically updated. The same for the extension, that is up to date at March, 20th.
It fails both on my work and private accounts, that is a very standard Visual Studio subscription.

**Comment by dhoehna** [comment]
Hello,

Thank you for keeping DevHome updated.

You tried with all the repos used by your development team.  Hmm.  I wonder if this is because the repos are protected and can't be accessed unless DevHome has permission to access the repos.  This is akin to organization repos on GitHub.

Can you do 2 things for me?
1. Can you make a free Azure ADO account with your personal account and make a private repo.  Try cloning that repo with DevHome.  If you can clone it, that tells me something is blocking the app (DevHome) from accessing the other repos.
2. Can you attach the /logs for DevHome and the Azure extension?  The logs should give me more insight into what is happening.

**Comment by JumbaJookiba** [comment]
Indeed, a private repo of my personal account, ***@***.***, was correctly synchronized on my PC.
Now, it seems that is my organization environment, that is problematic.
You see, when I authenticate by my organization, I am often presented a list of directories, and I have to switch to the right one, because the default is not correct.
Is it possible that DevHome Azure extension takes arbitrarily that directory for good? Is there a way to switch to the right one? Or otherwise to change the default for my profile?

Best regards,

D A Galliano
Ingegnere
________________________________

**Comment by dhoehna** [comment]
Hey @JumbaJookiba,

I had no idea a directory was a thing in Azure DevOps.  Thank you for mentioning it.

I do believe this is what is causing the issue.  I was able to repro this by
1. Logging out of DevHome.
2. Changing to a directory (that had no repos)
3. Adding a new repo.
4. Logging into DevHome.

The add repo via account tab did not show the new repo.  

I'll look into this.

**Comment by dhoehna** [comment]
Looked into this.  The root cause is in the Azure Extension and I see you made an [issue](https://github.com/microsoft/DevHomeAzureExtension/issues/125) there already.  I'm going to continue the discussion there.

/dupe https://github.com/microsoft/DevHomeAzureExtension/issues/125
