### ISSUE TITLE
Cannot add more than one GitHub account

### ISSUE THREAD

**Issue by brandonh-msft** [microsoft/devhome#2024]
### Dev Home version

0.601.297.0

### Windows build number

Tented

### Other software

.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Install & Enable the GitHub extension
Add one GH account (e.g. work/corp)
Attempt to add another GH acct (e.g. personal)

### Expected result

Both GH accts should be added to the extension

### Actual result

"Something happened"

### Included System Information

Tented

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_arm64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_arm64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Duplicate of https://github.com/microsoft/devhomegithubextension/issues/276
