### ISSUE TITLE
Dev Home does not recognize GitHub extension

### ISSUE THREAD

**Issue by andrenascentes** [microsoft/devhome#2030]
### Dev Home version

0.701.323.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

1- Install GitHub extension
2- Log In to GitHub
3- Log out from GitHub
4- Try to log in again

### Expected result

I would like to login in to GitHub again

### Actual result

DevHome tells me that there are no extensions installed

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i7-1365U
Physical Memory: 31.6GB (18.43GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_x64__8wekyb3d8bbwe

**Comment by andrenascentes** [comment]
Hi! The logs are in the zip file. Inside it there are other 2 zip files, each one with the logs of each log folder. Thanks! 
[all-logs.zip](https://github.com/microsoft/devhome/files/13649703/all-logs.zip)

**Comment by vineeththomasalex** [comment]
@andrenascentes  Logs show that DevHome knows about the existence of the GitHubExtension, but has trouble trying to call any of the interfaces. GitHubExtension logs don't really show anything (maybe it crashed before being able to write anything). 
Would you be able to try resetting these apps and see if that fixes it? Just go to Settings > Apps > Installed Apps
![image](https://github.com/microsoft/devhome/assets/16733941/6197ff73-af03-4241-a3cf-a8ed78752c12)

Click the 3 dots next to Dev Home or the Extension, and select Advanced Options. Try Repair of Both Dev Home and the GitHub extension. If this doesn't fix it, please try Reset as well. This might make you lose your Dashboard widgets and require you to login again unfortunately.
![image](https://github.com/microsoft/devhome/assets/16733941/fd17353c-1eca-41e1-a4bb-4d00c5c42a62)

Keep us posted on how it goes!

**Comment by andrenascentes** [comment]
I did the steps above for no success =/  I even try uninstalling and installing the GitHub extension but it does not work. Is there anything else I can do? 
[logs.zip](https://github.com/microsoft/devhome/files/13701337/logs.zip)

**Comment by vineeththomasalex** [comment]
Ah I see. There seems to be some problem around reading/removing credentials from Credential Manager. Would you be able to try the following:
- Open "Credential Manager" from start menu
- Go to "Windows Credentials"
- Under "Generic Credentials", delete all credentials under "GitHubDevHomeExtension". 
- Restart DevHome and see if this still occurs

Please let me know if this works. Also, thanks a lot for filing this issue and providing the logs!

**Comment by vineeththomasalex** [comment]
Duplicating this to #1945
