### ISSUE TITLE
Widgets disappear after Windows update

### ISSUE THREAD

**Issue by rigiddesign** [microsoft/devhome#2052]
### Dev Home version

0.801.344.0

### Windows build number

10.0.26016.1000

### Other software

OS Build Version: 10.0.26016.1000.amd64fre.rs_prerelease.231208-1532
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

- Add widgets
- Install a Windows feature update (Insider builds I my case, I case this is relevant)

### Expected result

Widgets retain until manually removed

### Actual result

Widgets not retained

### Included System Information

CPU: AMD Ryzen 9 3900X 12-Core Processor            
Physical Memory: 127.92GB (96.53GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.800.344.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.801.344.0_x64__8wekyb3d8bbwe

**Comment by iqnite** [comment]
Experiencing the same issue and I can say that it's extremely annoying. It also occurs on the widgets board.
Widgets are the main feature of Dev Home, if they don't work as expected it's already 50% of the app not working.

**Comment by krschau** [comment]
Could you please let us know what version of the Windows Web Experience Pack you have? You can see this info by opening a Powershell prompt and running "get-appxpackage *webexp*". There was a bug where sometimes it would lose widgets, and I'm not sure if that fix has rolled out everywhere.

**Comment by rigiddesign** [comment]
Thank you for the comment. The command "get-appxpackage webexp" returns nothing, so, I found "MicrosoftWindows.Client.WebExperience" by writing out all packages.

Is this the correct one? If so:

 Version : 523.34300.0.0

**Comment by krschau** [comment]
Ah, sorry. I typed asterisks around "webexp" but forgot GitHub markdown would render that as italics.

There was an older bug in the Widgets Service that would cause this which we tracked with #742, but that particular fix should be in 523.34300.0.0. It's interesting that @iqnite is seeing this behavior on the Window's widget board, I wonder if they have an older version without this fix.

@rigiddesign If you see the widgets disappear in Dev Home again, could you provide us with some logs as per the instructions below?

/logs

**Comment by rigiddesign** [comment]
Please see: https://aka.ms/AAoj8iq
