### ISSUE TITLE
Make the Settings option Spin when clicked

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2067]
### Suggested new feature or improvement

Make the Settings option Spin when clicked, because it only spanned the first time.

### Scenario

This is used to satisfy the users, or it is like a stress toy.

**Comment by skanda890** [comment]
When using the WinUI Navigation View the settings icon spins when clicked.

image
Here it is in the Windows Calculator app

 Recording.2023-12-20.095153.mp4

**Comment by krschau** [comment]
The icon spins every time I click it. I think it only spinning once was a fluke.
