### ISSUE TITLE
It installed as Japanese?!

### ISSUE THREAD

**Issue by nukem** [microsoft/devhome#2069]
### Dev Home version

0.801.344.0

### 🌐 Language

English

### ❌ Actual phrase(s)

xx

### ✔️ Expected phrase(s)

xxx

### Why is the current translation wrong

I cant use it. When the first time I clicked it, it decided to update and make itself Japanese.

**Comment by krschau** [comment]
@nukem Can you tell us your Windows Display Language and Preferred Languages on your computer? In Windows Settings, this is on the "Time & language > Language & region" page.
