### ISSUE TITLE
Dev Home lags for a bit of time

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2070]
### Dev Home version

0.801.344.0

### Windows build number

10.0.22621.2861

### Other software

OS Build Version: 10.0.22621.2861.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

Go to Dashboard>Add New Widget>Issues>Type a valid URL.

### Expected result

Have to show the widget.

### Actual result

The cursor was moving, but nothing it didn't show the widget.

### Included System Information

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Physical Memory: 11.89GB (3.2GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.800.344.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.801.344.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.300.344.0_x64__8wekyb3d8bbwe

**Comment by OsamaAlMomani** [comment]
I cloned the project and i will work on the bugs

**Comment by skanda890** [comment]
Logs: 

https://1drv.ms/f/s!Aqq-Je19xlrfhFh8beR0rTcSiR_z?e=jMdQx2

**Comment by krschau** [comment]
If you create a GitHub widget with a query that hasn't been used before, it makes sense that it would take some time to bring down the data. Would a message indicating that the widget is loading information help?

**Comment by skanda890** [comment]
How?

**Comment by skanda890** [comment]
What... How?

**Comment by krschau** [comment]
Asking the question again, would a "loading" message be helpful here?

**Comment by skanda890** [comment]
Dev Home lags for some time.

**Comment by krschau** [comment]
Closing, since there's not enough information here to do anything.
