### ISSUE TITLE
Add some PowerToys utilities

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#2072]
### Suggested new feature or improvement

We should add Registry Preview, Environment Variables, and Hosts File Editor from PowerToys as utilities in Dev Home. Dev Home can house the "stable" versions of these tools, while PowerToys maintains their "preview" versions.

### Scenario

These utilities were built with the intent of migrating into Dev Home. They're useful for a majority of developers and their integration can also help provide awareness to PowerToys.

### Additional details

We can add a "Utilities" page in Dev Home and have these tools be launchable from there.

**Comment by crutkas** [comment]
PowerToys team is onboard with the proposal of 'stable' features moving to dev home so we can continue to iterate on new concepts / features inside PowerToys
