### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by MiampoKT** [microsoft/devhome#2083]
### Suggested new feature or improvement

Hello,
It will be great to add more options for widgets such displaying the cores use for cpu or displaying gpu motors uses. Also give the possibility of pinning the widgets on the top without using powertoys.
thank you and have a nice day.

### Scenario

these new features will gives more accurate informations. for my case i'm using my gpu for finite element simulation and IA  so i usualy monitoring the use of my gpu.

**Comment by crutkas** [comment]
"pinning the widgets on top" is the ask here to allow the dashboard for Dev Home to toggle to be always on top like task manager can? /needinfo
