### ISSUE TITLE
Make an option that allows the user to make the widgets disappear

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2087]
### Suggested new feature or improvement

Make an option that allows the user to make the widgets disappear.

### Scenario

This would allow the user to make the widgets disappear.

**Comment by cinnamon-msft** [comment]
Can you add more info here? You can remove the widget if you want, so I'm not sure what you mean by "disappear" /needinfo

**Comment by skanda890** [comment]
An option that allows the user to remove the widgets

**Comment by cinnamon-msft** [comment]
This feature already exists in the triple dot menu of the widgets
