### ISSUE TITLE
Install GitHub extension by default

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#2102]
### Suggested new feature or improvement

We should install the GitHub extension by default to help provide immediate value once someone opens Dev Home

### Scenario

This would help developers be more successful within Dev Home as well as on Windows

**Comment by dongle-the-gadget** [comment]
I think that now Dev Home has GitHub and Azure DevOps now, let the user choose what to install on app launch?

**Comment by nepp95** [comment]
It would make more sense to ask what git service people are using, you know that they are going to change it anyway if it's incorrect. There is a lot of people that don't have a single repository on Github, so forcing git on them would be... well.... like we used to force internet explorer on people....

**Comment by riverar** [comment]
I suppose by the presence of https://github.com/microsoft/devhome/pull/2116 @krschau has rejected your questions/comments.

**Comment by nepp95** [comment]
> I suppose by the presence of #2116 @krschau has rejected your questions/comments.

Yep. It seems tens of millions of people will be left out for no reason, again.

**Comment by krschau** [comment]
If you don't find the GitHub extension useful, you can uninstall it from the Apps list in Windows Settings (there's a shortcut there from inside Dev Home's Extensions page, as well).
