### ISSUE TITLE
windows is not taking inputs from keyboard

### ISSUE THREAD

**Issue by kanugurajesh** [microsoft/devhome#2120]
### Windows build number

10.0.22621.2861

### Steps to reproduce the bug

1. Open the windows and then open windows start
2. Try to enter any  keys it is not working

### Expected result

1. The keys should work

### Actual result

1. The windows is not responding to inputs from keyboard

https://github.com/microsoft/devhome/assets/77529419/de7d6a1e-9ecd-475b-867a-2cff4ada655c

**Comment by krschau** [comment]
Hi @kanugurajesh. It looks like you're having an issue with Windows, but this repo is specifically for Dev Home. Please file the issue you're seeing in Feedback Hub (keyboard shortcut: windows+F) and your issue will get in front of the right people. Thanks!
