### ISSUE TITLE
Scalable Dashboard Widget Size

### ISSUE THREAD

**Issue by ShaunaGordon** [microsoft/devhome#2128]
### Suggested new feature or improvement

It'd be great if the widgets could be scaled down as the window size is reduced, without truncating the content for widgets that don't have scrolling content (so for things like the hardware and network status widgets). The current size options on the widgets shrink the widget's height, but hide content in the process.

### Scenario

I work on 3D rendering and other resource-intensive projects, so I like to have the hardware and networking widgets on my Dev Home to keep an eye on my resource usage, so that I can get a feel for my normal usage and thus help catch things like memory leaks or uploading/downloading too much data early on. However, these widgets are quite large and take up a lot of screen real estate if I want them all visible. Making the window smaller simply reflows them, which works great until it starts putting all the widgets one per row and hiding them.

### Additional details

Alternatively, I'd love for these to be widgets that I can just stick on my desktop and see when I don't have other windows open.

**Comment by ShaunaGordon** [comment]
While they appear to want bigger widgets (where I want smaller), #2124 appears to be related.

**Comment by krschau** [comment]
Our current thinking around this is to give the widgets a specific design for each size, so that the most useful information is displayed instead of just getting cut off at the top. To keep the discussion contained, I'm going to dupe this to #1281
