### ISSUE TITLE
Painel não abre

### ISSUE THREAD

**Issue by soouzza** [microsoft/devhome#2135]
### Dev Home version

0.901.374.0

### Windows build number

10.0.22631.3007

### Other software

OS Build Version: 10.0.22631.3007.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

Após configurar todos os parâmetros no Dev Home, a tela "Painel" não exibe nada, apenas uma mensagem de erro

### Expected result

abrir os widgets

### Actual result

aparece uma mensagem de erro:
Você não tem a versão necessária do Pacote de Experiência da Web do Windows para exibir widgets. Certifique-se de que você tenha a versão mais recente instalada e reinicie a Página inicial para desenvolvedores.

ao abrir a Microsoft Store, constata-se que o Windows Web Experience Pack já está na versão mais atualizada.

### Included System Information

CPU: AMD Ryzen 5 3600 6-Core Processor              
Memória Física: 31.94GB (21.85GB free)
Arquitetura do processador: x64

### Included Extensions Information

Extensões: 
Microsoft.Windows.DevHomeGitHubExtension_0.900.374.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.901.374.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.400.374.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g

Serviço de widget: 
MicrosoftWindows.Client.WebExperience_521.20060.135.0_x64__cw5n1h2txyewy

**Comment by vineeththomasalex** [comment]
Translations from Microsoft Translator:

Steps to reproduce the bug
After configuring all the parameters in Dev Home, the "Dashboard" screen doesn't display anything, just an error message.

Expected result
Open the widgets

Actual result
An error message appears:
You don't have the required version of the Windows Web Experience Pack to view widgets. Make sure you have the latest version installed and restart the Developer Homepage.

When you open the Microsoft Store, you see that the Windows Web Experience Pack is already in the most up-to-date version.

**Comment by soouzza** [comment]
Hi @vineeththomasalex 
There is no logs in both of paths, I'm attach prints of folders
<img width="555" alt="log002" src="https://github.com/microsoft/devhome/assets/18272970/aa44d531-d6d0-417d-a5fa-bdf9cece98c5">
<img width="497" alt="log001" src="https://github.com/microsoft/devhome/assets/18272970/14e67280-4f91-48e5-9258-aae0187248b8">

**Comment by krschau** [comment]
The original bug shows that MicrosoftWindows.Client.WebExperience_521.20060.135.0_x64__cw5n1h2txyewy is installed. Widgets need at least version 523 (or 423 on non-Insider Windows versions) to work. You may need a Windows update to get version 523, do you have a Windows Update available?

**Comment by soouzza** [comment]
Hi @krschau thanks for your commente

My WebExperience is in 521 version (print 1), but in my Windows update do not hav update available (print 
<img width="617" alt="tela01" src="https://github.com/microsoft/devhome/assets/18272970/17af3669-ba09-45d8-8145-68b58805f987">
<img width="806" alt="tela02" src="https://github.com/microsoft/devhome/assets/18272970/4e0926b0-48b5-40c7-a0d5-e2ca3b43c9c6">
2)

Any way to update the package in powershell?

**Comment by krschau** [comment]
Hi @soouzza. I believe this has to do with your Windows Insider settings. You may have disabled Insider updates or are stuck on an old version. Updating to a newer version should bring along a newer version of the WebExperience package.
