### ISSUE TITLE
Cannot add more than one GitHub account

### ISSUE THREAD

**Issue by lamaspacemud** [microsoft/devhome#2137]
### Dev Home version

0.901.374.0

### Windows build number

10.0.22631.3007

### Other software

OS Build Version: 10.0.22631.3007.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

Add one GitHub account.
Try to add another (I get a message saying: "Something failed, consider using Feedback to report" or similar wording)

### Expected result

I would be able to add more GitHub accounts and not just one.

### Actual result

Error message received.

### Included System Information

CPU: AMD Ryzen 7 7800X3D 8-Core Processor           
Physical Memory: 31.21GB (20.95GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.901.374.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g
Microsoft.Windows.DevHomeGitHubExtension_0.900.374.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.400.20.0_x64__cw5n1h2txyewy

**Comment by vineeththomasalex** [comment]
Hi @lamaspacemud, unfortunately this is not supported for the GitHub extension at this time, but work is actively going on to enable Multi-user support.

Tracked by https://github.com/microsoft/devhomegithubextension/issues/276
