### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by evilmonkeyslayer** [microsoft/devhome#2158]
### Dev Home version

0.901.374.0

### Windows build number

10.0.22631.3007

### Other software

OS Build Version: 10.0.22631.3007.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

Attempting to uninstall is blocked

### Expected result

Ability to uninstall dev home

### Actual result

Did not uninstall

**Comment by BenS13** [comment]
dont worry you cant uninstall it anyways

**Comment by vanilla-thunder** [comment]
i managed to get rid of this bloatware trash by using the following command in powershell:
`Get-AppxPackage *devhome* | Remove-AppxPackage`
