### ISSUE TITLE
Dev Home Feature Exploration: Dev Home machine configuration generates a configuration file

### ISSUE THREAD

**Issue by shakersMSFT** [microsoft/devhome#2160]
## Please Provide Feedback & Ideas!
Please let us know what you think about this feature by commenting on this issue! We'd love to hear your ideas and feedback! 
Let us know:

- What do you like about the feature?
- What do you think is missing / what could improve the experience?

## Overview
This issue outlines the proposed experience to generate a Winget configuration file at the end of the end to end machine configuration flow based on the details specified in the flow. This would allow a user to easily re-create their set up on another machine, or share it with others. 

### The Problem
Today a user can specify details for setting up their machine in the end to end configuration flow, but they don't have a way to easily repeat that set up. Winget configuration files make it easy and fast to configure a machine like the end to end flow, but there isn't a way to generate a configuration file easily today. 

### Scenario

| # | Scenarios|
| -------- | -------- |
| 1 | As a user, I go through the end to end set up flow, and I specify repos to clone, dev drive creation, and applications to install. At the end of the flow, in addition to setting up my machine, I am able to generate and 'save as' a winget configuration file so that I can repeat this set up process on another machine or share my set up with others. 
| 2 | As a user, I am able to view the configuration file and edit it before I create and save it.

**Comment by dennybiasiolli** [comment]
This could be a great feature!

As a developer, I'd like to create a configuration and share it with other members of the team, either via the GitHub repo requiring that specific configuration, or just sending the yaml file manually to users saying "it works on my machine" 😄 

This could be interpreted like a "share a working setup" feature, in order to allow maintainers and users to recreate the same environment.

**Comment by ffMathy** [comment]
This seems like a good way to do it! Thanks! 😍

**Comment by localden** [comment]
The `winget` part is easy, to be frank, to even replicate somewhat manually. That is - I can chain some `winget` commands and install all the required packages and versions. The interesting part, and specifically what I refered to in #721, is the ability to _export the proper machine configuration_ - `winget` is part of that, but also get me all the dev settings (e.g., dashboard configuration, Git connections, repository links, registry settings enabled for development, etc.)

Without that functionality, the `winget` export alone is not really a huge value prop for my own scenarios.

**Comment by berlintay** [comment]
Maybe add some sort of .ps1 module that sources authorized configuration files
where you can browse through a list of them and the features ( as a widget ? )
