### ISSUE TITLE
Impossible to find the copilot

### ISSUE THREAD

**Issue by vcartel** [microsoft/devhome#2163]
### Dev Home version

0.901.374.0

### Windows build number

10.0.23615.1000

### Other software

OS Build Version: 10.0.23615.1000.amd64fre.ni_prerelease.240105-1510
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

In _Settings > Customization_ you cannot enable **copilot**, nor in _Dev Home_. I gather it's not present, but it should be included in this Build.

### Expected result

Enable and use **copilot**, since the news released by Microsoft **news release** introducing copilot by trial.

### Actual result

I can't actually find the **copilot** and its settings.

### Included System Information

CPU: Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
Memoria fisica: 7.84GB (1.33GB free)
Architettura processore: x64

### Included Extensions Information

Estensioni: 
Microsoft.Windows.DevHomeGitHubExtension_0.900.374.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.901.374.0_x64__8wekyb3d8bbwe

Servizio widget:

**Comment by krschau** [comment]
Hi @vcartel, Dev Home does not currently house Copilot settings. If you're having trouble finding them, please file an issue with Feedback Hub and it will get to the right people.
