### ISSUE TITLE
Always allow user to directly alter folder path for cloning

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#2169]
### Suggested new feature or improvement

I should be able to always directly alter the file path.  By default, this is a locked text box.
![image](https://github.com/microsoft/devhome/assets/1462282/a3862f71-0027-4810-8daf-138d239ca557)

Only after i click browse and cancel does it shift back
![image](https://github.com/microsoft/devhome/assets/1462282/3ae6e669-a04b-4fb8-83a1-8119f3f636de)

### Scenario

I want to quickly type the path where i want to go.

VS lets me do this directly
![image](https://github.com/microsoft/devhome/assets/1462282/8dd01610-00b0-419c-be99-922b22b4b2b8)

**Comment by Gobinath-B** [comment]
can i start work on this issue?

**Comment by cinnamon-msft** [comment]
> can i start work on this issue?

@Gobinath-B Go ahead! I'll assign #1201 to you :)
