### ISSUE TITLE
dev drive default clone path should be [Drive]:\source.  

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#2170]
### Dev Home version

Dev Home: 0.1001.383

### Steps to reproduce the bug

Go through flow

![image](https://github.com/microsoft/devhome/assets/1462282/c7f0740f-f985-45bc-9c3f-e127fef4ee66)

### Expected result

Mimic VS's default

![image](https://github.com/microsoft/devhome/assets/1462282/5fa6522b-8168-4950-8a21-b3a7d781c1af)

### Actual result

![image](https://github.com/microsoft/devhome/assets/1462282/c7f0740f-f985-45bc-9c3f-e127fef4ee66)

**Comment by shakersMSFT** [comment]
duplicate of https://github.com/microsoft/devhome/issues/806
