### ISSUE TITLE
ssh is missing :-)

### ISSUE THREAD

**Issue by vibescirca81** [microsoft/devhome#2203]
### Dev Home version

0.1001.389.0

### Windows build number

10.0.22631.3007

### Other software

OS Build Version: 10.0.22631.3007.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

I have a ssh config file for vscode remote code extension. Since it shows up on the keyring, I can try and connect to it. When it does it fails, because there is no ssh.exe / ssh.com in the path.

Steps: Upgrade to Win 11 from Win 10. Have putty installed, vscode installed, vscode Remote-SSH extension. Define some hosts for the vscode Remote-SSH extension to use. Run Dev Home. Have it detect your keyring, and the hosts in it should show up. Now, click on a host.

### Expected result

ssh.com/openssh/putty connection to the server on the keyring. In fact, I thought it might try and use putty, since putty already showed up on the installed applications list.

### Actual result

'ssh' is not recognized as an internal or external command, operable program or batch file.
![image](https://github.com/microsoft/devhome/assets/46790729/e5608564-3384-42c0-a584-a2868f718ca6)
![image](https://github.com/microsoft/devhome/assets/46790729/090948b7-3384-4aaa-af6d-60d7bd3ae315)

### Included System Information

CPU: AMD Ryzen 5 2600X Six-Core Processor           
Physical Memory: 31.92GB (10.6GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1001.389.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1000.393.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.400.20.0_x64__cw5n1h2txyewy

**Comment by crutkas** [comment]
Do have an SSH client installed?  OpenSSH does ship on by default but admins / enterprises / yourself can turn it off via "add optional features"  /needinfo
