### ISSUE TITLE
Remove "Extensions" from Settings Page 

### ISSUE THREAD

**Issue by ethan-fang-MS** [microsoft/devhome#2212]
### Suggested new feature or improvement

Given user flow patterns and our push to simplify the design of the extensions experience, we should remove any navigation to extensions-related settings.

Simply put, this work should be to remove the "Extensions" expander found within the Settings page (while still keeping access to those same settings from the dedicated "Extensions" page in the left-hand navigation).

### Scenario

If a user needs to access settings for a given installed extension, they should do so by navigating to the "Extensions" page, then clicking on the expander for the desired extension they wish to modify.

### Additional details

_This closes out the design discussion on where users should expect to navigate to for interacting with their installed (and to-be installed) extensions_

**Comment by tusharwebd** [comment]
Hi! New contributor here. Can you share any screenshots/images of what the current UX is vs what the new expected UX would look like?

**Comment by krschau** [comment]
@ethan-fang-MS Gentle reminder to use/check for existing issues rather than opening new ones. We don't like to dupe old issues to new ones since there could be discussions and people following the old one already, but I'll do that here since this one has the decision of which page to use.
