### ISSUE TITLE
Executing Machine Configuration fails with 0x80131501 on each step

### ISSUE THREAD

**Issue by Makciek** [microsoft/devhome#2217]
### Dev Home version

v0.1001.389.0

### Windows build number

10.0.22631.0

### Steps to reproduce the bug

I've got a fresh Windows 11 installation, winget ver v1.6.3482

1. Start Dev Home
2. Go to Machine Configuration
3. Click "Configuration File"
4. Select file downloaded from: https://github.com/microsoft/devhome/blob/main/sampleConfigurations/DscResources/Microsoft.Windows.Developer/EnableWindowsSettings.yaml
5. Select "I agree and want to continue"
6. Click "Set up as admin"
7. Authorise admin execution
8. Error occurs(it happens regardless of the configuration file used on each step)

When I'm running from console:
`winget configure .\EnableWindowsSettings.yaml`
It works as expected

### Expected result

The configuration should be applied

### Actual result

![image](https://github.com/microsoft/devhome/assets/15693079/770ea4cc-cc49-478b-b34f-6d6809bdcdf1)
![image](https://github.com/microsoft/devhome/assets/15693079/e6d225da-c8b5-4780-a3a6-86881d5f2bd9)

**Comment by ryfu-msft** [comment]
@Makciek , can you share the logs associated with this failed configuration: %LOCALAPPDATA%\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\TempState\SetupFlow

**Comment by Makciek** [comment]
Sure
[SetupFlow-Elevated_20240206-091940.log](https://github.com/microsoft/devhome/files/14176685/SetupFlow-Elevated_20240206-091940.log)

**Comment by AmelBawa-msft** [comment]
@Makciek, thanks for reporting this issue. 

Can you please help validate this issue with the changes in #2125? I was getting an error with the previous in-proc implementation, but the same file ran successfully with the change (out-of-proc).

**Comment by Makciek** [comment]
@AmelBawa-msft 
That worked :)
(I've cloned the repo, installed components from CLI, switched to your branch, and built the app)
![image](https://github.com/microsoft/devhome/assets/15693079/d4efe233-a019-40bf-8617-4ad90c08fc3b)

**Comment by AmelBawa-msft** [comment]
@Makciek awesome! Thank you for validating! I will work on completing the PR to close this issue.
