### ISSUE TITLE
Dash doesn't load on startup due to failed catalog subscriptions

### ISSUE THREAD

**Issue by danielcranford** [microsoft/devhome#2219]
### Dev Home version

0.1001.389.0

### Windows build number

10.0.22631.3007

### Other software

OS Build Version: 10.0.22631.3007.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Every time I start the app it just hangs and spins loading the dashboard which simply has a single widget (the CPU widget). Unsure what the app is doing,

### Expected result

Uncomplicated dash should load quickly

### Actual result

Dash never loaded

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i7-1265U
Physical Memory: 15.83GB (1.72GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1001.389.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1000.393.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.500.389.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.40.0_x64__cw5n1h2txyewy

**Comment by danielcranford** [comment]
Logs are attached.
[DevHome_20240205-094021.zip](https://github.com/microsoft/devhome/files/14249742/DevHome_20240205-094021.zip)

I was a little worried I wouldn't be able to reproduce it, but I just hit the same state. This time my dashboard has all four basic widgets (cpu, memory, network, disk) and the issue didn't occur on startup. Instead it occurred when I returned to the dashboard screen after visiting others. Here's a screenshot of my dashboard and the Dev Home process in Task Manager.

![image](https://github.com/microsoft/devhome/assets/1479535/54905db9-b9da-498e-b693-2608ae41200c)

**Comment by danielcranford** [comment]
Whoops, misunderstood where the logs were. The entire TempState is logs and I uploaded only a fraction. Here's the whole TempState directories
[dev-home-azure-TempState.zip](https://github.com/microsoft/devhome/files/14250003/dev-home-TempState.zip)
[devhome-github-TempState.zip](https://github.com/microsoft/devhome/files/14250006/devhome-github-TempState.zip)
[dev-home-TempState.zip](https://github.com/microsoft/devhome/files/14250022/dev-home-TempState.zip)

**Comment by krschau** [comment]
Thanks for the logs! I was just coming here to say that I saw similar behavior but apparently mine was due to a different scenario. From your logs, it looks like Dashboard isn't recovering from this error (pasted here so I can find again easily):

```
ERROR: Exception in SubscribeToWidgetCatalogEvents:
System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable.

The RPC server is unavailable.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.EventSource`1.Subscribe(TDelegate del)
   at DevHome.Dashboard.Views.DashboardView.SubscribeToWidgetCatalogEventsAsync()
```

**Comment by krschau** [comment]
Changing the name of this one, so I can differentiate from #2252
