### ISSUE TITLE
feature that allows users to install development applications within the dev drive.

### ISSUE THREAD

**Issue by ItzSwapnil** [microsoft/devhome#2238]
### Suggested new feature or improvement

Include an option to install applications in the dev drive directly.(via dev home)

### Scenario

Many of us prefer to utilize the dev drive for all our projects. Having this option would greatly assist in organizing our modules and applications.

**Comment by cinnamon-msft** [comment]
We recommend putting source code repos, project files, package caches, and built output files into a Dev Drive, but not the apps themselves. If you want to learn more, feel free to check out our docs: [learn.microsoft.com/windows/dev-drive/#what-should-i-put-on-my-dev-drive](https://learn.microsoft.com/windows/dev-drive/#what-should-i-put-on-my-dev-drive)
