### ISSUE TITLE
Unable to pin Dev home widgets to Windows 11 widget

### ISSUE THREAD

**Issue by argoyal** [microsoft/devhome#2247]
### Dev Home version

0.1001.389.0

### Windows build number

Edition	Windows 11 Pro
Version	22H2
Installed on	‎10-‎02-‎2024
OS build	22621.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

### Other software

Windows 11 22H2 widgets option

### Steps to reproduce the bug

1. I installed Dev home preview from the official Microsoft website.
2. I went to the windows 11 widget option by pressing Windows + W button
3. I tried adding the widgets by clicking on the + button.
4. I went to the Dev Home (preview) option to pin CPU, GPU and Memory widgets.
5. The pin option was disabled and I could not pin those widgets.

### Expected result

The pin option should be enabled.
![Screenshot 2024-02-10 220645](https://github.com/microsoft/devhome/assets/10412881/1aea619c-7473-4084-9c35-4d7bd3eb81d6)

### Actual result

The pin option is disabled for CPU, GPU and Memory but is enabled for SSH and Network.

**Comment by Gobinath-B** [comment]
hai @argoyal , I can't really reproduce this issue. It works properly here. Any other specific scenerio to reproduce this?

**Comment by argoyal** [comment]
@Gobinath-B thanks for reaching out and apologies for the delayed response. I think it got auto-resolved after a recent update. But I don't know why these widgets keep disappearing after I turn off my machine. I add them there and arrange them but after a while, they just seem to disappear and I have to add them back again. Are they not persistent?

**Comment by krschau** [comment]
Dev Home widgets are not officially supported on the Windows Widget Board. The inability to click "Pin" is odd, I'm glad it resolved itself. If the widgets on the Windows Widget Board are disappearing, please open an issue in Feedback Hub.
