### ISSUE TITLE
Error during installation (0x80073CF3) from MSIX on Windows 10

### ISSUE THREAD

**Issue by MichaelAgarkov** [microsoft/devhome#2250]
### Dev Home version

0.1001.389.0

### Windows build number

10.0.19045.2193

### Steps to reproduce the bug

Installing Dev Home.

### Actual result

This error:
![Screenshot_1](https://github.com/microsoft/devhome/assets/81249219/632ec205-95b3-4877-9577-5a01851a96ee)

### Included System Information

Windows 10 Pro

**Comment by MichaelAgarkov** [comment]
I got Dev Home to install from the Microsoft Store, but this error is still a thing.

**Comment by MichaelAgarkov** [comment]
I got Dev Home to install from the Microsoft Store, but this error is still a thing.

**Comment by MichaelAgarkov** [comment]
I got Dev Home to install from the Microsoft Store, but this error is still a thing.
![image](https://github.com/microsoft/devhome/assets/81249219/2724f9fe-e749-491d-a443-e483e134476a)

**Comment by krschau** [comment]
As a data point, someone was able to update their existing store install to the latest package, and then also separately install it (after uninstalling first) and didn't hit any dependency errors. Store seems to be installing something the MSIX does not.

**Comment by krschau** [comment]
Lowering severity since the Dev Home stub is now included on Windows 10, installation (even when started by the MSIX) seems to be working. Please let me know if anyone sees differently.
