### ISSUE TITLE
Min OS verification failing incorrectly while running 'machine configuration -> from a file' for Dev Home

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/devhome#2251]
### Dev Home version

0.1001.389.0

### Windows build number

10.0.22621.3085

### Steps to reproduce the bug

- Open Dev Home
- Go to machine config
- 'From a file'
- Select the dev home file from this repo (.configurations/configuration)
- Try to run it
- Fails at 'Check OS version'

### Expected result

Should have seen my OS version as correct, and continued to install.

### Actual result

OS version was detected as not sufficient (despite being sufficient) and failed out early.
![image](https://github.com/microsoft/devhome/assets/42221804/81a3f41a-ef11-41e6-8a94-c8d2b213bf34)

**Comment by scottluskcis** [comment]
I'm having this same issue, the configuration file I've used on other machines in past without issue but setting up a fresh machine with latest versions I encounter the same issue. Nothing has been changed about the configuration file. If I remove the os check the resources fails too.

**Comment by scottluskcis** [comment]
I did find that if I run terminal as administrator and run winget configure and point to same file it does run successfully.

**Comment by AmelBawa-msft** [comment]
@scottluskcis thank you for reporting this issue. Can you please try again using the latest version of Dev Home (v0.1101.x.x)?

Possibly related issue:
- #2217
