### ISSUE TITLE
Allow to import existing cloned repos

### ISSUE THREAD

**Issue by jagomf** [microsoft/devhome#2271]
### Suggested new feature or improvement

Devs already have repos cloned on our disks. Allow to import existing repos and not only clone new ones.

### Scenario

Get an "import" button or similar, same way as there is a "clone" one.

**Comment by shakersMSFT** [comment]
Hey, check out this feature proposal to see if it would solve your ask: https://github.com/microsoft/devhome/issues/2161 
A follow up question: What do you want to do with the repo(s) once its in Dev Home?

**Comment by shakersMSFT** [comment]
dupe of https://github.com/microsoft/devhome/issues/799
