### ISSUE TITLE
microsoft.windows.devhome.sdk nuget DLLs do not have version information

### ISSUE THREAD

**Issue by MattHyman** [microsoft/devhome#2276]
### Steps to reproduce the bug

Microsoft.Windows.DevHome.SDK.Lib.dll and Microsoft.Windows.DevHome.SDK.dll do not have expected file version information.

![image](https://github.com/microsoft/devhome/assets/1520739/70187317-927c-4189-b0fa-f0abd0fef82b)

![image](https://github.com/microsoft/devhome/assets/1520739/b63baf4b-3a0d-45bb-bb79-1d0dd1d45d99)

### Expected result

Microsoft.Windows.DevHome.SDK.Lib.dll and Microsoft.Windows.DevHome.SDK.dll have relevant file version information.

### Actual result

Microsoft.Windows.DevHome.SDK.Lib.dll and Microsoft.Windows.DevHome.SDK.dll do not have expected file version information.

**Comment by krschau** [comment]
@EricJohnson327 Let's make sure this gets into the next SDK version.
