### ISSUE TITLE
No redirect when signing in with second GitHub account

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#2277]
### Dev Home version

0.1101.409.0

### Steps to reproduce the bug

Navigate to Machine Configuration
Clone repositories
Clone by account - GitHub
Click account dropdown and sign in with another account
Browser says it's redirecting to the app once it's been authorized

### Expected result

Dev Home should update while on the clone repo page with my second account

### Actual result

There's no redirect and the second account isn't recognized in Dev Home. If I go to settings, the account does show up there. 
![image](https://github.com/microsoft/devhome/assets/48369326/f44c7405-fc7f-44e9-a96d-b37c9f4bbd02)

**Comment by krschau** [comment]
Sometimes the event that Dev Home is waiting for never gets fired, so there is a 30 second wait - probably logging in is happening in that 30 seconds, so waiting 30 seconds you would see the second account. Maybe should switch to 10 seconds. Re-assigning teams.
