### ISSUE TITLE
Dashboard space

### ISSUE THREAD

**Issue by jorge-zazueta** [microsoft/devhome#2278]
### Suggested new feature or improvement

allow content area to have more space, currently is centered and with lots of space in left and right

### Scenario

if a user wants to have more widgets in a row, allow content area to take on empty spaces

![image](https://github.com/microsoft/devhome/assets/136114115/968ecfa8-26bd-4c8d-ab67-477a11333977)

**Comment by krschau** [comment]
Duplicate of #724
