### ISSUE TITLE
Xcopy doesn't work on Dev Drives

### ISSUE THREAD

**Issue by Rabadash8820** [microsoft/devhome#2280]
### Dev Home version

0.1001.389.0

### Windows build number

22631.3007

### Other software

xcopy

### Steps to reproduce the bug

Create a text file and an empty folder somewhere in the Dev Drive, then run:

```cmd
xcopy /Y "<filePath>" "<folderPath>" & echo %ERRORLEVEL%
```

I should also note that I created my Dev Drive manually through Windows Settings, _not_ through Dev Home. Apologies in advance if this is not the right repo to post Dev Drive issues. 😬

### Expected result

No errors, and the text file would be copied into the empty folder.

### Actual result

The file is not copied, and xcopy's status code is 2. According to the [xcopy docs](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy#remarks), this status code means `The user pressed CTRL+C to terminate xcopy.` 🤔 I assume this has something to do with the ReFS file system used by dev drives, but I didn't think xcopy was tied to NTFS or anything.

### Included System Information

Device specifications:
```txt
Device name	HP-5CG3380DPS
Processor	12th Gen Intel(R) Core(TM) i7-12850HX   2.10 GHz
Installed RAM	32.0 GB (31.6 GB usable)
Device ID	174F125C-3ADF-44B6-B87A-F9D41BF86D8E
Product ID	00330-80000-00000-AA344
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

Windows specifications:
```
Edition	Windows 11 Enterprise
Version	23H2
Installed on	‎2/‎6/‎2024
OS build	22631.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0
```

**Comment by krschau** [comment]
Hi @Rabadash8820, your hunch was correct and this issue would really be better to open in Feedback Hub, where the right people will see it. Win+F is the keyboard shortcut to bring it up.

@bbonaby FYI

**Comment by Rabadash8820** [comment]
Cool, just opened [this Problem](https://aka.ms/AAp725o) through Feedback Hub. 👍
