### ISSUE TITLE
Can't add additional accounts using Github

### ISSUE THREAD

**Issue by Stijnheemskerkk** [microsoft/devhome#2282]
### Dev Home version

0.1001.389.0

### Windows build number

10.0.22621.3155

### Other software

OS Build Version: 10.0.22621.3155.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Go into settings
Click Accounts
Press Add Account
Press Sign in to Github.com

### Expected result

Take you to the github sign in page allowing you to sign in and add an additional Github account.

### Actual result

Displays a pop-up with the title "Connect your account"
Then underneath that the text says: 
"Something went wrong :(
Please consider filing some feedback"
![afbeelding_2024-02-18_001909618](https://github.com/microsoft/devhome/assets/144661262/6449aa8f-d01b-4d11-9349-581c18556824)
![afbeelding_2024-02-18_001924468](https://github.com/microsoft/devhome/assets/144661262/ee308250-e775-465a-b3b0-d8994911f102)

### Included System Information

CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Physical Memory: 15.85GB (8.15GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1001.389.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1000.393.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.40.0_x64__cw5n1h2txyewy

**Comment by Stijnheemskerkk** [comment]
Here is additional evidence of what actually happens: 

Uploading Dev Home (Preview) 2024-02-18 00-26-42.mp4…

#2282

**Comment by vineeththomasalex** [comment]
This will be fixed in the upcoming release [v0.11](https://github.com/microsoft/devhome/milestone/14)
