### ISSUE TITLE
Extensions not working

### ISSUE THREAD

**Issue by BayKedi** [microsoft/devhome#2285]
### Dev Home version

0.1001.389.0

### Windows build number

10.0.22631.3155

### Other software

OS Build Version: 10.0.22631.3155.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

I downloaded the github extension and the widget extension. When I create a widget using one of these it shows a blank screen.

### Expected result

Work properly (show updates; github issues, pull reqs etc.)

### Actual result

Blank screens
![image](https://github.com/microsoft/devhome/assets/96437373/597db908-f5d0-4d52-bfa7-18605da4502c)

### Included System Information

CPU: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
Physical Memory: 15.87GB (5.33GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.1000.393.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1001.389.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.40.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment]
@BayKedi Did the widget content load after some time? Maybe 20-30 seconds or so? The extensions do take some time to start up and provide content. If not, can you share logs?
/logs

**Comment by BayKedi** [comment]
> @BayKedi Did the widget content load after some time? Maybe 20-30 seconds or so? The extensions do take some time to start up and provide content. If not, can you share logs?
> /logs

it 12.30 am here. can't send the logs now

**Comment by krschau** [comment]
Logs would be helpful whenever you get a chance. It would also be helpful to know if no widgets ever load, or if some do and some don't -- a bug may exist in one widget provider and not another.

**Comment by BayKedi** [comment]
> Logs would be helpful whenever you get a chance. It would also be helpful to know if no widgets ever load, or if some do and some don't -- a bug may exist in one widget provider and not another.

alright. i can send the logs after 13 hours when i come back from school

**Comment by BayKedi** [comment]
alright so how do i access the logs again?

**Comment by BayKedi** [comment]
https://1drv.ms/u/s!AhfWNp1ary_jhONcBEvYwyZZQe6xVw?e=vOrTQ5 OneDrive
or
https://drive.google.com/file/d/1ygvKFJkX65Nd7nEQNbrPrJrSPe4aaMni/view Google Drive
use which one works best

**Comment by BayKedi** [comment]
GitHub works fine now. but i suppose WingetUI needs and update. 
![image](https://github.com/microsoft/devhome/assets/96437373/28087c22-2d0e-4bc3-8678-56e002333ee7)
