### ISSUE TITLE
devops

### ISSUE THREAD

**Issue by Eves101** [microsoft/devhome#2294]
### Suggested new feature or improvement

it would be nice if there was a possibilty to connect with a microsoft dev account to my repositories in devops.... untill then this is useless

### Scenario

connect with repos in devops

**Comment by Aaron-Junker** [comment]
You can download the Dev home Azure extension to access devops repos.

https://github.com/microsoft/DevHomeAzureExtension

**Comment by krschau** [comment]
Duplicate of #521
