### ISSUE TITLE
Remove ProxyStubs from appxmanifests

### ISSUE THREAD

**Issue by krschau** [microsoft/devhome#2354]
### Suggested new feature or improvement

Should be done for both extensions, but core Dev Home stays the same.
Default proxy stubs are included in Microsoft.Windows.Widgets.dll and your appxmanifest should be prepopulated with the registration entries when you build with 1.5.

**Comment by beervoley** [comment]
Host proxy stubs should still stay in place :)

**Comment by krschau** [comment]
> Host proxy stubs should still stay in place :)

Task updated. Thanks!
