### ISSUE TITLE
[Canary] Extensions library doesn't show display name of each extension now that we support multiple extensions in a single package

### ISSUE THREAD

**Issue by bbonaby** [microsoft/devhome#2378]
### Steps to reproduce the bug

Install an app that currently supports multiple extensions. E.g Dev Home Canary, Go to extensions library in Dev Home and you'll see the manage extension option twice, but no indicator of which one the toggle relates to:
![image](https://github.com/microsoft/devhome/assets/105318831/f7a489c7-6cd5-4a13-952c-328fa829f331)

### Expected result

Based on the xml in the package manifest we should use the "displayName" to show the name of the extension:
<img width="803" alt="image" src="https://github.com/microsoft/devhome/assets/105318831/2eec825e-e72b-4087-9f60-f4fe8f884615">

At the same time we can probably rename the Hyper-V displayname to just be "Hyper-V Extension" so it's more readable for the UI

### Actual result

multiple items just say "Manage extension".

**Comment by krschau** [comment]
Looked at this a bit, got part way there. Anyone else is free to use my branch: user/krschau/extension-displayname

**Comment by krschau** [comment]
Depends on #2538
