### ISSUE TITLE
Dev Home widgets don't support Web Experience Pack v521

### ISSUE THREAD

**Issue by NewSkyLineTwitter** [microsoft/devhome#2382]
### Dev Home version

0.1101.416.0

### Windows build number

10.0.22635.0

### Steps to reproduce the bug

I encounter an error message when I access the "Dashboard" section of Dev Home. It reads: "You do not have the required dependency installed to display widgets. Please install or update the package from the Store and then restart Dev Home."
Below there is a link to "Windows Web Experience Pack", which I have already installed, since I am using a fresh installation of Windows 11.

### Expected result

A fresh Windows 11 installation should not display any error messages when showing widgets.

### Actual result

Error message reading: "You do not have the required dependency installed to display widgets. Please install or update the package from the Store and then restart Dev Home."
<img width="1431" alt="Screenshot 2024-03-09 211408" src="https://github.com/microsoft/devhome/assets/69757762/41183bd9-3bc3-4c5c-84f9-8dd9a06fc641">

**Comment by krschau** [comment]
@NewSkyLineTwitter Can you include the version of the Web Experience Pack you have installed? You can see it by running this in powershell: `get-appxpackage *webexp*`

/needinfo

**Comment by NewSkyLineTwitter** [comment]
@krschau Of course!
Here is the Version-Number: `521.20060.315.0`

If you need, here is the whole output:
```
RunspaceId             : 488bdfb3-0975-46a6-a4cf-67f4875aa8b3
Name                   : MicrosoftWindows.Client.WebExperience
Publisher              : CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
PublisherId            : cw5n1h2txyewy
Architecture           : X64
ResourceId             :
Version                : 521.20060.315.0
PackageFamilyName      : MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy
PackageFullName        : MicrosoftWindows.Client.WebExperience_521.20060.315.0_x64__cw5n1h2txyewy
InstallLocation        : C:\Program
                         Files\WindowsApps\microsoftwindows.client.webexperience_521.20060.315.0_x64__cw5n1h2txyewy
IsFramework            : False
PackageUserInformation : {}
IsResourcePackage      : False
IsBundle               : False
IsDevelopmentMode      : False
NonRemovable           : False
Dependencies           : {Microsoft.VCLibs.140.00_14.0.33519.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged      : False
SignatureKind          : Store
Status                 : Ok
```

**Comment by krschau** [comment]
So, you have 521, and Dev Home widgets require 523 (or 423, if you're on a non-Windows Insider build) or higher. I've been told that Insider branch settings are what determine if you're on the 523 track, but unfortunately, I don't know exactly which ones get you on that track.

What we need to do is figure out if the fixes that caused us to require 523 in the first place ever got backported (I don't believe they were last time I checked, but it's been a bit). If they did, we can change the versions we allow. If they didn't, we should try to get them backported.

Sorry I don't have a better short-term solution.

**Comment by NewSkyLineTwitter** [comment]
Alright, thanks for the clarification. 
_Still misleading, at least from my point of view. Installing the App as a core component of Windows 11, while still knowing one of its core features, won't work because of wrong dependencies, that will only be available if you are on an `Insider Branch`. But you have to look up which one, if you want it to work. But well..._

Still thanks :)

**Comment by krschau** [comment]
I looked into backporting, and unfortunately that's not an option. The way to get a newer version is to check Windows Insider settings to try to get on a more up-to-date build ring.

**Comment by NewSkyLineTwitter** [comment]
The thing is that I'm inside a Insider-Version of Windows 11 (Preview-Channel). But alright... Thanks for looking into it. 👍🏻
