### ISSUE TITLE
Rename Experimental features

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#2384]
### Suggested new feature or improvement

Now that we're adding in experimentation, we should rename Experimental features to avoid confusion. Here's the text we should use in the Settings page:

[Header]: Preview features
[Subtitle]: Try new Dev Home beta features

### Scenario

See above

**Comment by Gobinath-B** [comment]
@cinnamon-msft i wanna work in this can you please elaborate the exact expectation

**Comment by krschau** [comment]
@Gobinath-B I don't think this is the best one to pick up. I had started looking at this last week and the current wording isn't just confusing for users but for developers as well, and I think it's going to be a huge change to modify every instance in the code.

**Comment by Gobinath-B** [comment]
Okay ,So I think I should choose another issue to work

**Comment by Gobinath-B** [comment]
hai @krschau would you close this issue?

**Comment by Gobinath-B** [comment]
@krschau lemme try 😼

**Comment by krschau** [comment]
No longer planned.
