### ISSUE TITLE
Extra space in the uninstall menu

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2393]
### Dev Home version

0.1101.416.0

### Windows build number

10.0.22621.3235

### Other software

OS Build Version: 10.0.22621.3235.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Go to Extensions  --> Click on any extension's three dots.

### Expected result

~The uninstall button's size should be exactly as the size of the text.~
The uninstall item should have even margins around it.

### Actual result

~The button size is more than the text in the button's size.~
The margins when hovering over the item are uneven.

### Included System Information

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Physical Memory: 11.89GB (3.17GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeAzureExtension_0.600.416.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1101.416.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1100.422.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g

Widget Service: 
MicrosoftWindows.Client.WebExperience_523.11500.0.0_x64__cw5n1h2txyewy

**Comment by Gobinath-B** [comment]
Hi, @krschau @skanda I wanna work on this issue

**Comment by skanda890** [comment]
Okay, I guess.

**Comment by krschau** [comment]
The original bug is slightly incorrect -- if you look at other xaml Flyout Menus, there is always a margin around the button. Here is the WinUI 3 Gallery, when you click on one of the "Documentation" flyouts:
![image](https://github.com/microsoft/devhome/assets/47155823/25acce50-faf8-42ff-baac-cf15845a9f4b)

There is a very simple fix to make the margins even -- if you want to try to figure it out as an exercise in xaml, you are free to, but otherwise we can do it.

**Comment by Gobinath-B** [comment]
Got it !!!

**Comment by Gobinath-B** [comment]
> The original bug is slightly incorrect -- if you look at other xaml Flyout Menus, there is always a margin around the button. Here is the WinUI 3 Gallery, when you click on one of the "Documentation" flyouts: ![image](https://private-user-images.githubusercontent.com/47155823/314101728-25acce50-faf8-42ff-baac-cf15845a9f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NjcxMjQsIm5iZiI6MTcxMDg2NjgyNCwicGF0aCI6Ii80NzE1NTgyMy8zMTQxMDE3MjgtMjVhY2NlNTAtZmFmOC00MmZmLWJhYWMtY2YxNTg0NWE5ZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE2NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NDRiN2ZiZGYzZTNhNjgyZjc4ZDQ3YWM2YWM1MGY3MGI4ZDZlZTk4M2YwOTdmNDNmM2IzMjk5NDM2NzdlOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z4eQFyuzqwkppaOdROaoYe6FmS-Yl0M-gNoubdnqeo4)
> 
> There is a very simple fix to make the margins even -- if you want to try to figure it out as an exercise in xaml, you are free to, but otherwise we can do it.

But In this case the flyout is wrapped inside Button tag instead and it has its own style Height and width. Can i add margin property there? @krschau 

```
 <Button x:Uid="MoreOptionsButton"
         Content="&#xe712;"
         Height="36" Width="36"
         FontFamily="{StaticResource SymbolThemeFontFamily}" 
         Background="Transparent"
         BorderThickness="0">
     <Button.Flyout>
         <MenuFlyout>
             <MenuFlyoutItem
                 x:Uid="UninstallItem"
                 HorizontalAlignment="Center"
                 Command="{x:Bind UninstallButtonCommand}">
             </MenuFlyoutItem>
         </MenuFlyout>
     </Button.Flyout>
 </Button>
```

**Comment by Gobinath-B** [comment]
@krschau  I think , we have to use common width, height and margin from ThemeResourse for uniform style.

```

MaxWidth="{ThemeResource MaxPageContentWidth}"
Margin="{ThemeResource ContentPageMargin}"
```

**Comment by krschau** [comment]
The MoreOptionsButton is fine, but there's something on the MenuFlyoutItem itself that affects its placement inside the MenuFlyout.

**Comment by Gobinath-B** [comment]
I will try to add margin to the Menuflyout.if it's not working lemme try some otherways

**Comment by krschau** [comment]
There's an even simpler way to do it that doesn't need adding a margin.

**Comment by Gobinath-B** [comment]
wrap installed item code inside that <Grid> </Grid> right?

**Comment by krschau** [comment]
I could imagine that having that result in the same layout of the fix I'm thinking of, since Grids _stretch_ to fill their available space. But you don't need any new controls here.

**Comment by skanda890** [comment]
The margin is visible, but the margin doesn't go till the space.

**Comment by skanda890** [comment]
> The margin is visible, but the margin doesn't go till the space.

I say

**Comment by skanda890** [comment]
It is like this:

![image](https://github.com/microsoft/devhome/assets/99239826/642b0584-ff5f-45fb-b97e-c89973c6d4b0)

**Comment by skanda890** [comment]
Is this the margin you are talking about:

![image](https://github.com/microsoft/devhome/assets/99239826/ee4ab872-49e7-4aba-a775-2da7d710a2da)

**Comment by Gobinath-B** [comment]
Yes,I guess

**Comment by krschau** [comment]
I'm worried that this conversation is going down the wrong path and I don't want anyone to waste their time implementing an incorrect fix, so I'm going to open a PR for this one.

**Comment by skanda890** [comment]
https://github.com/microsoft/devhome/pull/2441#issuecomment-2014817195

**Comment by skanda890** [comment]
Re-open this issue.

**Comment by krschau** [comment]
The fix is checked in, but hasn't been published yet. Please wait until the next release of Dev Home.

**Comment by skanda890** [comment]
But the pull request? Did you change it?
