### ISSUE TITLE
Why is the Submit new issue button greyed out, even if the conditions were met

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2394]
### Steps to reproduce the bug

Create a new issue, meet the requirements, and observe the Submit new issue button.

### Expected result

It should not be greyed.

### Actual result

The Submit New Issue button was greyed out.

### A picture

![image](https://github.com/microsoft/devhome/assets/99239826/54b0b3b6-a620-4a51-b576-044fb1fa05d4)

**Comment by krschau** [comment]
What part of Dev Home are you talking about here? I'm not sure where has both "Submit new issue" and "uninstall"

**Comment by skanda890** [comment]
> What part of Dev Home are you talking about here? I'm not sure where has both "Submit new issue" and "uninstall"

Sorry, wrong picture. I have updated it now.

**Comment by skanda890** [comment]
> What part of Dev Home are you talking about here? I'm not sure where has both "Submit new issue" and "uninstall"

This is an issue related to the Dev Home repository in GitHub.

**Comment by krschau** [comment]
Our issue templates haven't been changed in a long time. I have found that I have to click outside the final required text box for the submit button to update. If you're still having trouble, it would be a GitHub.com problem and I would bring the issue up there.

**Comment by skanda890** [comment]
But this doesn't happen for other repositories.
