### ISSUE TITLE
Widgets don't load

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2400]
### Dev Home version

0.1101.416.0

### Windows build number

10.0.22621.3296

### Other software

OS Build Version: 10.0.22621.3296.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Dashboard  --> Add Widget.

### Expected result

It should come.

### Actual result

It didn't come.

### Included System Information

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Physical Memory: 11.89GB (3.65GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeAzureExtension_0.600.416.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1101.416.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1100.422.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g

Widget Service: 
MicrosoftWindows.Client.WebExperience_523.11500.0.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment]
Please give us details in your description so we can understand the problem. As it is, we can't diagnose this problem.

Did the "Add Widget" dialog not populate with the available widgets? Did you select a widget and click Pin, but it didn't show up on the Dashboard? Did nothing show up, or did it show up but never load?

**Comment by skanda890** [comment]
Logs:

[Dev Home TempState.zip](https://github.com/microsoft/devhome/files/14588602/Dev.Home.TempState.zip)

https://1drv.ms/f/s!Aqq-Je19xlrfh0dLjzK3oqZ7FZko?e=sK2M4T

**Comment by skanda890** [comment]
> Please give us details in your description so we can understand the problem. As it is, we can't diagnose this problem.
> 
> Did the "Add Widget" dialog not populate with the available widgets? Did you select a widget and click Pin, but it didn't show up on the Dashboard? Did nothing show up, or did it show up but never load?

@krschau, The Add Widget dialog came, I selected a widget and clicked Pin, but it did not be pinned.

**Comment by krschau** [comment]
Duplicate of #1736

**Comment by krschau** [comment]
Duplicate of #1730
