### ISSUE TITLE
Dashboard keeps loading

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2401]
### Dev Home version

0.1101.416.0

### Windows build number

10.0.22621.3296

### Other software

OS Build Version: 10.0.22621.3296.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Launch the app and wait until the app is fully loaded.

### Expected result

The Dashboard should also load.

### Actual result

The Dashboard was still loading, even after every other component in Dev Home was loaded

### Included System Information

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Physical Memory: 11.89GB (3.84GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeAzureExtension_0.600.416.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1101.416.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1100.422.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g

Widget Service: 
MicrosoftWindows.Client.WebExperience_523.11500.0.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment]
I've seen this issue on occasion. I believe something is going wrong in caching the widget icons.

**Comment by skanda890** [comment]
> I've seen this issue on occasion. Something is going wrong in caching the widget icons.

When I restarted Dev Home, even Machine Configuration and Extensions were lagging.
