### ISSUE TITLE
Couldn't clone git repository because LibGit2 library threw an exception.

### ISSUE THREAD

**Issue by dylan-k** [microsoft/devhome#2404]
### Dev Home version

0.1101.416.0

### Windows build number

10.0.19045.4170

### Other software

OS Build Version: 10.0.19045.4170.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Via Machine Configuration, attempted to clone a GitHub repository to a local directory, but it failed with an error "because LibGit2 library threw an exception."

### Expected result

I expected it to clone a copy of my repository to the directory I had indicated. I also expected that, if an error occurs, I should be able to read that error so that I could troubleshoot it myself. Additionally, and this may qualify as a feature request, but I expected to determine exactly which directory the repository would be cloned into. All I could do was to pick a directory, and then the repository would be created within another folder inside that one, with no option to determine its name. This isn't as specific as I can be, when I do this in any other way.

### Actual result

I got a message about an error, and not an error. I was unable to clone the repository. I was unable to specify exactly what should be the name of the repository's local directory

### Included System Information

CPU: Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz
Physical Memory: 39.85GB (27.87GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.1100.422.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.2.0.0_x64__g91dtg5srk15g
Microsoft.Windows.DevHome_0.1101.416.0_x64__8wekyb3d8bbwe

Widget Service: 
Microsoft.WidgetsPlatformRuntime_1.1.0.0_x64__8wekyb3d8bbwe

**Comment by mattycarlson** [comment]
I'm getting the same issue. All repos I'm trying to clone exist, and I am the owner of them.

From SetupFlow log:

`[2024/04/20 07:25:16.8157][SetupFlow] ERROR: Unable to query for Dev Drive enablement: Unable to find an entry point named 'GetDeveloperDriveEnablementState' in DLL 'api-ms-win-core-sysinfo-l1-2-6.dll'.`

I'm using Windows 10, and from my understanding, "DevDrives" in DevHome are only available on Windows 11. My drive _is_, however, a mounted VHDX. DevHome was installed from winget.

**Comment by dhoehna** [comment]
Closing because the ticket is stale.  If you are experiencing the same issue, please re-open the ticket with /logs.

**Comment by dhoehna** [comment]
Hey @mattycarlson.

Thank you for the issue.  However, this issue is un-related to the DevDrive issue.  Can you please either
1. File a feedback item on feedbackhub, or
2. Make a new issue with logs?

/feedbackhub

**Comment by dylan-k** [comment]
The link is https://aka.ms/AAq7vt9

**Comment by 32x0lf** [comment]
Hi,

I am experiencing the same error. Is there a fix?
