### ISSUE TITLE
As a user I want to be able to open an IDE or text editor easily.

### ISSUE THREAD

**Issue by jmfallecker** [microsoft/devhome#2435]
### Suggested new feature or improvement

From within the Dev Home app, I should be able to open an external Visual Studio or VS Code, IntelliJ, notepad++, notepad, vim, what have you. Give me a widget for running a batch command. (These are all examples, but just generally we should be able to set up something like a button that runs an executable.

### Scenario

I'm a developer, I'm using this new product "Dev Home" and I have a stream lined experience interacting with my a database or application instance, etc.

**Comment by shakersMSFT** [comment]
related items: https://github.com/microsoft/devhome/issues/1984 https://github.com/microsoft/devhome/issues/2043
