### ISSUE TITLE
How do I create an environment or use the Environment page

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2449]
### The Question

How do I create an environment or use the Environment?

**Comment by skanda890** [comment]
This is a question change it to Issue-Question, since this is a question.

**Comment by bbonaby** [comment]
Hi @skanda890  The environments feature is still under active development. It is currently not released yet. Once we release it it'll be in a Dev Home Preview build. The ability to create an environment and documentation surrounding environments will be included as part of this release as well.

Thank you
