### ISSUE TITLE
Define specific command to run on setup

### ISSUE THREAD

**Issue by FMorschel** [microsoft/devhome#2454]
### Suggested new feature or improvement

Define specific command to run on setup

### Scenario

I work with Flutter/Dart. It would be nice if I could create a script to install it and simply run in any machines I need. (we use puro if that makes any difference, its a environment manager for dart/flutter https://puro.dev/)

**Comment by cinnamon-msft** [comment]
Do WinGet configuration files solve your need? https://learn.microsoft.com/windows/package-manager/configuration/
