### ISSUE TITLE
Cut off message in DevBox UI

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2456]
### The Question

The sentence 
![image](https://github.com/microsoft/devhome/assets/99239826/1b00e5a3-f81f-4a15-9007-7a3c19f4a7c9)
 is incomplete, and we can't scroll sideways to see the whole sentence.

**Comment by skanda890** [comment]
This is a question or a task, please change the label to the respective label.

**Comment by skanda890** [comment]
Make a down slider bar, so you can see the whole sentence.

**Comment by huzaifa-d** [comment]
This was fixed, as a side effect, on the extension side - https://github.com/microsoft/DevHomeAzureExtension/pull/142
