### ISSUE TITLE
Why is this screen like this?

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2457]
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22621.3296

### Other software

OS Build Version: 10.0.22621.3296.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Go to Machine Configuration --> Set up target.

### Expected result

What should be in this screen ![image](https://github.com/microsoft/devhome/assets/99239826/6b4b6ec7-d127-455e-b5ac-c6d7dd521943)

### Actual result

It is blank, but it should be something else, right?

### Included System Information

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Physical Memory: 11.89GB (3.35GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.435.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.700.442.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_523.11500.0.0_x64__cw5n1h2txyewy

**Comment by skanda890** [comment]
Because Hyper-V Manager is enabled.

**Comment by krschau** [comment]
This experimental feature is still under development.

**Comment by skanda890** [comment]
> This experimental feature is still under development.

This is in Machine Configuration --> Set up target.

**Comment by skanda890** [comment]
But what are we supposed to do at this screen?

**Comment by skanda890** [comment]
> But what are we supposed to do on this screen?

How do you click the Next button?
