### ISSUE TITLE
Why did Dev Box and Hyper-V switch places

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2458]
### The Question

Dev Box and Hyper-V switched places from:

![image](https://github.com/microsoft/devhome/assets/99239826/58d51e62-e317-4352-9c3b-f9946c66a779)

to:

![image](https://github.com/microsoft/devhome/assets/99239826/4c377f84-633a-4f64-8fce-5ed978c40c7f)

**Comment by skanda890** [comment]
This is a question, label this as Issue-Question.

**Comment by krschau** [comment]
Environments are an experimental feature and things may move around and change, especially while it's still under active development.

**Comment by skanda890** [comment]
> Environments are an experimental feature and things may move around and change, especially while it's still under active development.

This is in Machine Configuration --> Set up target.
