### ISSUE TITLE
[Environments] Hyper-V environments don't show up when not in Hyper-V admin group

### ISSUE THREAD

**Issue by bbonaby** [microsoft/devhome#2476]
### Steps to reproduce the bug

- Enable hyper-v Windows feature and reboot if not already enabled.
- create Hyper-v VMs in Hyper-V manager if you don't have any already
- Install Dev Home (Dev) 
- Navigate to Environments page
- Note no Hyper-V VMs show up

**
Note: this is due to the user not being in the Hyper-V administrators group. Unfortunately there is no way around this, the user must be in the Hyper-V adminstrator group before we attempt to use any hyper-v apis OR the process we use them in has to be elevated.
**

 Work around for now would be adding yourself to the Hyper-V admin group by

entering the following in an elevated cmd or powershell window  

- net localgroup "Hyper-V Administrators" (whoami) /add
- Then logging off/on  or rebooting

We plan on adding a message telling the user about this and a button that will prompt a UAC and run the commands for the user in the future. They'll still need to log off/on again afterwards. This is only a one time thing.

### Expected result

Hyper-V VMs show up in the environments page

### Actual result

No Hyper-V VMs show up.

**Comment by kanismohammed** [comment]
This issue is being tracked by this P0 issue
https://github.com/microsoft/devhome/issues/2784

**Comment by krschau** [comment]
Duplicate of #2784
