### ISSUE TITLE
Application crash when attempting to add a repository at certain screen resolutions

### ISSUE THREAD

**Issue by sasuntolayan** [microsoft/devhome#2485]
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22631.3374

### Other software

OS Build Version: 10.0.22631.3374.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

On Machine configuration section, when I go to the clone repositories menu (directly or indirectly via Set up local machine menu) and select add repository, application crashes without presenting me the popup window. 

![Recording 2024-03-29 031921](https://github.com/microsoft/devhome/assets/123330195/689f8031-4d30-42ea-bd10-7a041c5a8590)

### Expected result

The popup menu to add repositories showing up.

### Actual result

Application crashes and gets closed.

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i7-1360P
Physical Memory: 31.71GB (20.7GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.700.442.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.450.0_x64__cw5n1h2txyewy

#### Source: .NET Runtime 
Application: DevHome.exe
CoreCLR Version: 8.0.123.58001
.NET Version: 8.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at ABI.AdaptiveCards.Rendering.WinUI3.IAdaptiveCardRendererMethods.RenderAdaptiveCard(WinRT.IObjectReference, AdaptiveCards.ObjectModel.WinUI3.AdaptiveCard)
   at DevHome.Dashboard.ViewModels.WidgetViewModel+<>c__DisplayClass12_0+<<RenderWidgetFrameworkElementAsync>b__1>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[DevHome.Dashboard.ViewModels.WidgetViewModel+<>c__DisplayClass12_0+<<RenderWidgetFrameworkElementAsync>b__1>d, DevHome.Dashboard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<<RenderWidgetFrameworkElementAsync>b__1>d ByRef)
   at DevHome.Dashboard.ViewModels.WidgetViewModel+<>c__DisplayClass12_0.<RenderWidgetFrameworkElementAsync>b__1()
   at ABI.Microsoft.UI.Dispatching.DispatcherQueueHandler.Do_Abi_Invoke(IntPtr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference, Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at DevHome.Program.Main(System.String[])

#### Source: Application Error (Faulting module name: coreclr.dll)
Faulting application name: DevHome.exe, version: 1.0.0.0, time stamp: 0x65680000
Faulting module name: coreclr.dll, version: 8.0.123.58001, time stamp: 0x65684720
Exception code: 0xc0000005
Fault offset: 0x00000000001bf0cc
Faulting process id: 0x0x58DC
Faulting application start time: 0x0x1DA818D02F1F8B4
Faulting application path: C:\Program Files\WindowsApps\Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe\DevHome.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe\coreclr.dll
Report Id: 34e2aa37-d3cd-40a6-8c96-d7bd02cce7f4
Faulting package full name: Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

#### Source: Application Error (Faulting module name: Microsoft.UI.Xaml.dll)
Faulting application name: DevHome.exe, version: 1.0.0.0, time stamp: 0x65680000
Faulting module name: Microsoft.UI.Xaml.dll, version: 3.1.5.0, time stamp: 0x7fd76c03
Exception code: 0xc000027b
Fault offset: 0x0000000000404495
Faulting process id: 0x0x13B0
Faulting application start time: 0x0x1DA818E41528089
Faulting application path: C:\Program Files\WindowsApps\Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe\DevHome.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.5_5001.70.1338.0_x64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll
Report Id: 875963d5-6a61-47f7-b6b8-561c89521500
Faulting package full name: Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by krschau** [comment]
Something's not adding up for me here. I see that IAdaptiveCardRendererMethods.RenderAdaptiveCard() is throwing a System.AccessViolationException, and that is clearly something we need to handle, so I appreciate this report. But when you navigated to the Machine configuration page, that method stopped being called (widgets are no longer rendered). Is it possible you grabbed the wrong error from the Event Viewer?

In case I'm missing something, do you think you still have the Dev Home logs from this time? (The bot will give you instructions to find Dev Home and GitHubExtension logs, I don't need the extension)
/logs

**Comment by dhoehna** [comment]
> Something's not adding up for me here. I see that IAdaptiveCardRendererMethods.RenderAdaptiveCard() is throwing a System.AccessViolationException, and that is clearly something we need to handle, so I appreciate this report. But when you navigated to the Machine configuration page, that method stopped being called (widgets are no longer rendered). Is it possible you grabbed the wrong error from the Event Viewer?
> 
> In case I'm missing something, do you think you still have the Dev Home logs from this time? (The bot will give you instructions to find Dev Home and GitHubExtension logs, I don't need the extension) /logs

I know adaptive card stuff was added in a recent PR.  @bbonaby and @huzaifa-d you two know anything about adaptive card stuff crashing?  It might be related to the ActionCenter.

**Comment by krschau** [comment]
> > Something's not adding up for me here. I see that IAdaptiveCardRendererMethods.RenderAdaptiveCard() is throwing a System.AccessViolationException, and that is clearly something we need to handle, so I appreciate this report. But when you navigated to the Machine configuration page, that method stopped being called (widgets are no longer rendered). Is it possible you grabbed the wrong error from the Event Viewer?
> > In case I'm missing something, do you think you still have the Dev Home logs from this time? (The bot will give you instructions to find Dev Home and GitHubExtension logs, I don't need the extension) /logs
> 
> I know adaptive card stuff was added in a recent PR. @bbonaby and @huzaifa-d you two know anything about adaptive card stuff crashing? It might be related to the ActionCenter.

@dhoehna The stack in the OP specifically points to WidgetViewModel, although I'm more than happy to get other eyes on this.

**Comment by bbonaby** [comment]
@dhoehna  The action center code isn't instantiated at this point and doesn't use any dashboard code, so I don't believe it has anything to do with that. Judging by the stack trace it seems like an issue with widgets. There might be a null exception somewhere in the native code that the widgets view model calls into and that might be getting translated to this access violation. I've seen this type of crash with adaptive cards before. @krschau  It might be possible that the view model hadn't been garbage collected yet when this error occurs so its possible that it could still occur, I think when navigating away. 

@sasuntolayan If you attempted to go to the Dev Home Settings page instead of Machine configuration, then go to Accounts > Add accounts > GitHub. Does this crash still happen?

**Comment by krschau** [comment]
Since you can repro it consistently, it's a good candidate for trying to get us a dump. I'll have the bot leave instructions:
/feedbackhub

**Comment by dhoehna** [comment]
I can get a repro on my personal device :)  I'll be looking more into this tomorrow.

**Comment by dhoehna** [comment]
Update.  AddRepoDialog is encountering a layout cycle.  I'm currently looking into where it is.

A question that will need to be answered after debugging is "Why is this error not seen on all machines?"

**Comment by dhoehna** [comment]
Rolled-back to Segmented control package from #2123 locally.  No crashes.

**Comment by dhoehna** [comment]
Apologize about the length of time between now and my message about a PR.  #2524 fixes this issue by using a new version of `Segmented` control.  The new version released 2 weeks ago.

Tested the change with different resolutions.  No more crashing.
