### ISSUE TITLE
I restarted Dev Home after #2497 then it just crashed.

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2498]
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22621.3374

### Other software

OS Build Version: 10.0.22621.3374.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Restart the app after #2497.

### Expected result

It should the app.

### Actual result

It crashed.

### Included System Information

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Physical Memory: 11.89GB (2.08GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.435.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.700.442.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.4.0.0_x64__g91dtg5srk15g

Widget Service: 
MicrosoftWindows.Client.WebExperience_523.11500.0.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment]
Hi! Thanks for opening this issue. Unfortunately, there's not enough information here which makes it very hard for us to diagnose and triage. If you can add more information, like detailed repro steps, logs, or a link to a crash recorded in Feedback Hub, we can consider reopening.

**Comment by skanda890** [comment]
https://aka.ms/AApvy9v
