### ISSUE TITLE
Must make more explicit when it runs

### ISSUE THREAD

**Issue by simeyla** [microsoft/devhome#2500]
### Suggested new feature or improvement

Setting option to 'Run when Windows starts'
and whatever else may be related

### Scenario

Developers like control of their machine and to understand why something is running.

I couldn't find any settings indicating this was a 'Startup app' or anything of the sort.  However it is running in the background even when closed. I cannot tell whether or not this is a bug or a feature, but it's taking up CPU and I'm going to kill it now and probably never give it another chance again.

**Comment by krschau** [comment]
Duplicate of #624
