### ISSUE TITLE
Add already cloned repos

### ISSUE THREAD

**Issue by Nudelsuppe42** [microsoft/devhome#2548]
### Suggested new feature or improvement

A option in the "Machine configuration" page where you can add already locally cloned repositories from Github/git in general.
Like the option Github Desktop has.

### Scenario

I have all my projects for VSCode stored in a "Dev" folder, i want to import those into Dev Home. Or all my Intellij Projects are in the "IdeaProjects" folder and so on.

**Comment by adrastogi** [comment]
See also #702

**Comment by krschau** [comment]
Duplicate of #702
