### ISSUE TITLE
List/Library of installed apps.

### ISSUE THREAD

**Issue by rkoro** [microsoft/devhome#2549]
### Suggested new feature or improvement

List of installed apps with possibility to run them.

### Scenario

Instead of having shortcuts on desktop, you could have all in Dev Home. Like on Steam.

**Comment by krschau** [comment]
Similar to #2462

**Comment by AmelBawa-msft** [comment]
Related: #1984

**Comment by cinnamon-msft** [comment]
I think this is a /dup of #1984 
We could add the launch ability to that feature
