### ISSUE TITLE
Local & Server PUSH Notifications

### ISSUE THREAD

**Issue by CamiloJi** [microsoft/devhome#2550]
### Suggested new feature or improvement

Me gustaría que Microsoft implementara una API para nosotros los desarrolladores para notificaciones push, ya que las opciones en internet son muy limitadas. Esa API que funcione tanto para aplicaciones móviles, escritorio y web

### Scenario

En un sistema de tickets de soporte, un usuario creará su ticket con su solicitud, el admin recibirá ese ticket y se encargará de asignar ese ticket a alguien de soporte el cual se tendrá que encargar de atender ese ticket; al de soporte que se asigno debe llegarle una notificación para que sepa que tiene un ticket nuevo y así mismo agilizar el trabajo

**Comment by cinnamon-msft** [comment]
You should be able to programmatically send Windows notifications. The [GitHub extension](https://github.com/microsoft/devhomegithubextension) sends them if you want a reference to use :)
