### ISSUE TITLE
DevHome should refresh environment state when state changes

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2556]
### Steps to reproduce the bug

Run DevHome
choose local VM
look at state

Run Hyper-v Manager
Change state.

Look at DevHome. State has not changed.
<img width="1134" alt="image" src="https://github.com/microsoft/devhome/assets/2146880/e773e59c-a7e3-4dca-b409-d0da47143344">

### Expected result

expect state of devhome to match vm state

### Actual result

devhome state is wrong and needs to be manually refreshed.

**Comment by huzaifa-d** [comment]
This is by design; we added the sync button for this.
