### ISSUE TITLE
Environment sorting is inconsistent.

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2557]
### Steps to reproduce the bug

I have multiple DevBox and VMs.
Normally the DevBox are listed on top and the local VMs below.
But something happened to mix it up. And I have  no idea what.

Sorting says none. 

<img width="891" alt="image" src="https://github.com/microsoft/devhome/assets/2146880/7d42ae1a-bc04-4c85-ab37-60dc788225a7">

### Actual result

As you can see the normal layout changed. Maybe we should have a cosistent pattern unless specified.

**Comment by kanismohammed** [comment]
@KevinLaMS  - First load displays the environments that are retrieved first and is not sorted. 
@shakersMSFT  - Should we have some indication in the UX that the user explicitly needs to click sort
