### ISSUE TITLE
Environments, You can sort by alternative name. What is that?

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2558]
### Steps to reproduce the bug

As you can see in the image there is a menu to sort on alternative name.
But I do not see that listed in the card. So what is it?

![image](https://github.com/microsoft/devhome/assets/2146880/057b3447-0777-4181-97f1-7989f67be301)

### Actual result

It should be clear to the user what they are sorting on so that they can arrange the environments in the way that they choose.

**Comment by kanismohammed** [comment]
Do we need to sort by Alternative Name? We should remove this since not all environments have the alternative name.
