### ISSUE TITLE
Launching local VM needs UI to show it is doing something.

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2560]
### Steps to reproduce the bug

Click Launch on DevHome VM environment.
There is NO indication it is doing anyhing. It takes 30 seconds for something to happen.

We need a UI to reflect that action is happening.

https://github.com/microsoft/devhome/assets/2146880/5eacd1bc-54c7-423f-b343-164c55716a6f

### Expected result

Click Launch. Expect to understand what is happening

### Actual result

Because the buttons are so subtle and there is no visual action, i end up clicking launch a bunch

**Comment by bbonaby** [comment]
Should be fixed in next Canary. Let me know if it isn't. But I've added code to allow for this.
