### ISSUE TITLE
Environments Launch splitbutton arrow shows empty flyout for compute systems with no alternative launch options

### ISSUE THREAD

**Issue by nieubank** [microsoft/devhome#2574]
### Steps to reproduce the bug

Install a compute system extension that only supports launch and no other operations.

see
            
            <DataTemplate x:Key="LaunchButton" x:DataType="vm:ComputeSystemViewModel">
                <SplitButton
                        VerticalAlignment="Top"
                        Command="{x:Bind LaunchActionCommand}"
                        x:Uid="ms-resource:///DevHome.Environments/Resources/LaunchButton"
                        Style="{StaticResource CardBodySplitButtonStyle}">
                    <SplitButton.Flyout>
                        <customControls:CardFlyout ItemsViewModels="{x:Bind LaunchOperations}"/>
                    </SplitButton.Flyout>
                </SplitButton>
            </DataTemplate>

### Expected result

The split button arrow should not appear (or at least be disabled?).

### Actual result

The split button arrow can be clicked resulting in an empty flyout.

![image](https://github.com/microsoft/devhome/assets/7259210/ed49d308-c467-4aa1-b8d0-7cc0b16a4202)

**Comment by huzaifa-d** [comment]
Fixed in #3365
