### ISSUE TITLE
Environments three dots button shows empty flyout for compute systems with no dot operations

### ISSUE THREAD

**Issue by nieubank** [microsoft/devhome#2575]
### Steps to reproduce the bug

Install a compute system extension that only supports launch and no other operations.

see

            
            <DataTemplate x:Key="ThreeDotsButton" x:DataType="vm:ComputeSystemViewModel">
                <Grid>
                    <Button
                        Style="{StaticResource HorizontalThreeDotsStyle}">
                        <Button.Flyout>
                            <customControls:CardFlyout ItemsViewModels="{x:Bind DotOperations}"/>
                        </Button.Flyout>
                    </Button>
                </Grid>
            </DataTemplate>

### Actual result

![image](https://github.com/microsoft/devhome/assets/7259210/bfa7a94e-fe0f-4d43-b230-b141cb91fa27)

**Comment by huzaifa-d** [comment]
This is a P3, since this involves using an extension that has no supported operations, i.e. - this is theoretical.

**Comment by huzaifa-d** [comment]
Fixed in #3365
