### ISSUE TITLE
Application hangs while adding a repository

### ISSUE THREAD

**Issue by Devesh192** [microsoft/devhome#2589]
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22631

### Steps to reproduce the bug

1. Open machine configuration tab
2. Click on set up local machine
3. Click on Add Repository

https://github.com/microsoft/devhome/assets/63630655/c16641b8-0ec3-4975-a281-29958ce2f3b0

### Actual result

It hangs down the whole application and after some time closes the whole application.

**Comment by krschau** [comment]
Duplicate of #2485
