### ISSUE TITLE
Navigating away from the environments page and returning causes them to reload

### ISSUE THREAD

**Issue by denelon** [microsoft/devhome#2594]
### Dev Home version

0.1201.466.0

### Windows build number

10.0.26100.1

### Other software

OS Build Version: 10.0.26100.1.amd64fre.ge_release.240331-1435
.NET Version: .NET 8.0.3

### Steps to reproduce the bug

Leave the environment page after they are loaded, and upon return they need to be loaded again.

### Expected result

I expected the environments to be present since they had been previously loaded.

### Actual result

The environments had to be reloaded.

>I had left the environments page, cloned the dev home repository and run the configuration, then when I returned to the environments page it had to reload. I'm hoping this information might help if the repro is elusive.

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
Physical Memory: 31.84GB (14.72GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeAzureExtension.Dev_0.1199.424.509_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Dev))
Microsoft.Windows.DevHome.Dev_0.1199.431.1_x64__8wekyb3d8bbwe (Dev Home (Dev))
Microsoft.Windows.DevHome.Dev_0.1199.431.1_x64__8wekyb3d8bbwe (Dev Home (Dev))
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.DevHomeMicrosoftGameDevExtension.Canary_0.400.456.0_x64__8wekyb3d8bbwe (Dev Home Microsoft Game Dev Extension (Canary))
Microsoft.Windows.DevHome.Canary_0.1201.466.0_x64__8wekyb3d8bbwe (Dev Home (Canary))
Microsoft.Windows.DevHome.Canary_0.1201.466.0_x64__8wekyb3d8bbwe (Dev Home (Canary))
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1200.466.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHomeAzureExtension.Canary_0.700.466.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.1302.60.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment]
Not observed in latest Canary.
