### ISSUE TITLE
DevHome Hyper-V Create: The layout of the summary page is not intuitive

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2598]
### Steps to reproduce the bug

When creating the new hyperv image, you start with 
1) Create a name for it
2) choose an image
3) info

But when you hit next, the order is completely different. The page feels like it was authored by some one else.

It should be Name of VM you are creating
Image
then details.
It would be nice to have the info button again, to see if chose the right image.

My proposal below actual, though design should evaluate

<img width="468" alt="image" src="https://github.com/microsoft/devhome/assets/2146880/733219d7-f30a-431c-94f1-09cd9bdb7848">

### Expected result

it should naturally flow from previous page

### Actual result

It does not.  :) see image.

**Comment by kanismohammed** [comment]
This is by design.
