### ISSUE TITLE
DevHome Hyper-V Create: Too many clicks to create vm

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2599]
### Steps to reproduce the bug

Feels like too many clicks.
1) Choose VM Image
2) Need to Name
3) Need to click Next
4)  Navigate to summary page
5) Click Create Environment

### Expected result

I want to double click on an image and start creating the image. I navigated to the creation flow page.

### Actual result

5 clicks (6 if you count switching to this page)

**Comment by kanismohammed** [comment]
This is by design.
