### ISSUE TITLE
DevHome Hyper-V Create: Very confusing

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2600]
### Steps to reproduce the bug

The Creation flow is confusing. After clicking create environment, you are presented with a static page, and there are 2 disconnected buttons. 
1) Done
2) Environments Page

i did not know what to do. I was scared about clicking done because I did not want it to cancel. 

### Expected result

I should see the creation of the image and status like we show on the enviroments page. 

### Actual result

I am lost and do not know anything is happening or what to do next.

**Comment by kanismohammed** [comment]
This is by design until we have notifications support in Dev Home.
