### ISSUE TITLE
DevHome Hyper-V Create: Seems to kill hyper-v services

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2602]
### Steps to reproduce the bug

OK, this bug report is less than ideal.

When playing with create, all of a sudden hyperv manager no longer was working correctly. The local images I had did not show up under the hyper-v manager.

This has happened a couple of times. Guessing .... the service crashed.

I came back later and it was working again. As if it restarted.

![image](https://github.com/microsoft/devhome/assets/2146880/bddee0fa-7238-46dd-bfa7-16290006afc1)

### Actual result

My services were supposed to be running, but the images were not showing.

**Comment by KevinLaMS** [comment]
This may be related to memory.
looking in event viewer
hyper-V-compute 
DM operation add for the virtual machine 'Windows 11' failed with error: Not enough memory resources are available to complete this operation.  (0x8007000E)  (Virtual machine ID E74B0D27-5E02-4527-B92F-E004D14BD774).

**Comment by sshilov7** [comment]
I see VMMS service gone time to time on my machine without using Dev Home (I've never seen it gone while configuring a VM from Dev Home), I checked for crashes from my machine, and nothing is reported.
Resolving as external. If we find what triggers those service terminations, we can work with VMMS team to improve it.
