### ISSUE TITLE
DevHome Hyper-V Create:  sometimes has Create Environment, and sometimes is does not

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2604]
### Steps to reproduce the bug

I am guessing at the steps:
if i go to enviroments page to start, there is no Create Environment
If it go after creating an environment then i see the button.

### Expected result

this one makes me happy.
![image](https://github.com/microsoft/devhome/assets/2146880/48c1f3f7-6770-4127-a19e-ec229bd6d43a)

### Actual result

But i SWEAR, I have seen it without the button.

**Comment by kanismohammed** [comment]
No repro. Please re-activate with the exact repro steps
