### ISSUE TITLE
If Adaptive Card fails, should there be a refresh?

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2608]
### Steps to reproduce the bug

When using DevHome i was creating an environment and the received an error about the adaptative card.
I am not sure what i was doing.

What i would have liked to do was hit F5 and refresh the page so the card could load.

![image](https://github.com/microsoft/devhome/assets/2146880/01fdd2ed-03cf-4ec2-9bb9-25945d46b053)

### Actual result

blocked from next step.

**Comment by kanismohammed** [comment]
https://github.com/microsoft/devhome/issues/2616
