### ISSUE TITLE
Dev Box creation gives error about compute system operations

### ISSUE THREAD

**Issue by hamza-usmani** [microsoft/devhome#2616]
### Steps to reproduce the bug

Click create new environment, select dev box. On that page I get the error message about the compute system not supporting creation.

### Actual result

![image](https://github.com/microsoft/devhome/assets/15319966/bfba1ebc-608c-4abe-9bf4-9e285a304692)

**Comment by bbonaby** [comment]
this is related to https://github.com/microsoft/devhome/issues/2608, but we can keep this up as a way to track DevBox creation not being checked in yet. This should not show up once thats checked in.
