### ISSUE TITLE
Unexpected Close when Add repository in set up local machine window

### ISSUE THREAD

**Issue by goldenhand76** [microsoft/devhome#2624]
### Dev Home version

0.1201.442.0

### Windows build number

10.0.26058.1400

### Steps to reproduce the bug

Machine Configuration --> Setup local machine --> `+ Add repository`

### Expected result

Open up a window that shows my repos.

### Actual result

Unexpectedly close.

**Comment by dhoehna** [comment]
/dupe #2485 

Hello.  This issue is fixed in #2524 and should be in the next DevHome release.
