### ISSUE TITLE
Hopefully you can add a star to GitHub

### ISSUE THREAD

**Issue by RBHakureiReimu** [microsoft/devhome#2631]
### Suggested new feature or improvement

Hopefully you can add a star to GitHub

### Scenario

Hopefully you can add a star to GitHub

**Comment by krschau** [comment]
Hi @RBHakureiReimu. There's not enough information here to understand what you're asking for, and therefore nothing we can do. If you want to add more details about your feature suggestion, I might be able to re-open this issue.
