### ISSUE TITLE
'Dev Home needs to update' fails

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/devhome#2633]
### Dev Home version

Don't know

### Windows build number

10.0.26097

### Steps to reproduce the bug

- Open Dev Home

### Expected result

Dev Home opens as expected.

### Actual result

- A Window pops up saying Dev Home needs to update:
- ![image](https://github.com/microsoft/devhome/assets/42221804/3065ec57-3f6b-498c-9afe-dac6bbac409d)
- This fails
- ![image](https://github.com/microsoft/devhome/assets/42221804/f56ea5de-d06a-4448-a322-e772a1de2b67)
- Retry and the Window looks slightly different
- ![image](https://github.com/microsoft/devhome/assets/42221804/e9780db2-a8dd-4303-a064-883fea359892)
- But it fails again.

**Comment by krschau** [comment]
This is probably Store being flaky, but if you can reproduce this for Feedback Hub it might be helpful.
/feedbackhub

**Comment by craigloewen-msft** [comment]
When trying to repro with feedback hub it seemed to finish the download and now I can't repro it.

**Comment by krschau** [comment]
That makes me suspect even more that it was a transient Store issue. Closing but happy to reopen if you or someone else sees an indication to the contrary.
