### ISSUE TITLE
SSH widget does not show hosts with multi-word alias names

### ISSUE THREAD

**Issue by Gohellp** [microsoft/devhome#2646]
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22631.3447

### Other software

OS Build Version: 10.0.22631.3447.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

1. Point the SSH widget to a config file where one of the hosts has a multi-word alias name
3. See that that host is not shown in the list

### Expected result

The presence of the new configuration in the list

### Actual result

The application ignores the configuration

### Included System Information

CPU: AMD Ryzen 5 3600 6-Core Processor              
Physical Memory: 63.92GB (49.35GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.456.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.450.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment]
@Gohellp This issue was a little vague, so I'm going to re-word it. If you actually meant something else, please let me know.

**Comment by Gohellp** [comment]
> @Gohellp This issue was a little vague, so I'm going to re-word it. If you actually meant something else, please let me know.

Widget ignore record with multiple host aliases. I wrote this config:
```
Host hshp-vps
    Hostname server_ip
    User gohellp
    IdentityFile ~/.ssh/id_rsa_hshp-vps

Host router openwrt
    Hostname 192.168.1.1
    User root
    IdentityFile ~/.ssh/id_rsa_home-router
```
And widget ignore router/openwrt record.
![image](https://github.com/microsoft/devhome/assets/47943965/eb2ba469-2252-47b5-bb01-9b44f8ff6830)
