### ISSUE TITLE
Environment creation content is misaligned

### ISSUE THREAD

**Issue by shakersMSFT** [microsoft/devhome#2657]
### Steps to reproduce the bug

When selecting an environment for creation, the content to select an environment is mis-aligned throughout the flow. Review page is fine. 

### Expected result

Content on the page should be left aligned with the headers.

### Actual result

![image](https://github.com/microsoft/devhome/assets/45182130/f226f966-a8b1-4f67-99ea-4f6f83cfc7af)
![image](https://github.com/microsoft/devhome/assets/45182130/867267ee-8c79-499b-b22f-bc3a6e2b0bc1)

**Comment by bbonaby** [comment]
should be fixed in latest canary tomorrow, but will keep up until after that

**Comment by kanismohammed** [comment]
Issue is fixed in April Release
