### ISSUE TITLE
Environments page - Bloom image should be used for Dev Box not Hyper-V

### ISSUE THREAD

**Issue by shakersMSFT** [microsoft/devhome#2660]
### Steps to reproduce the bug

Dev Boxes are already using the 'Bloom' image in the Dev Box portal. We should ensure alignment and use the same image for Dev boxes and something else for Hyper-V environments. 

### Actual result

![Screenshot 2024-04-17 120201](https://github.com/microsoft/devhome/assets/45182130/d5ab2d87-6681-4d6c-8cf0-458b58ffaf9e)

**Comment by SohamDas2021** [comment]
https://github.com/microsoft/devhome/pull/2823

https://github.com/microsoft/DevHomeAzureExtension/pull/170
