### ISSUE TITLE
Map strings for actions for Hyper-V to align with Hyper-V manager

### ISSUE THREAD

**Issue by shakersMSFT** [microsoft/devhome#2665]
### Steps to reproduce the bug

The actions for a Hyper-V environment are different than what the hyper-v manager calls them. It would be good to align those actions to ensure continuity and clarity. 

### Expected result

'Stop' should be 'Shut down'
'Terminate' should be 'Turn off'

### Actual result

![image](https://github.com/microsoft/devhome/assets/45182130/c6e0f3b1-3478-4b6f-952a-9ed0c4f009d4)

**Comment by bbonaby** [comment]
Fixed by #2892 

For some reason it wouldn't let me link to this issue in the PR

**Comment by bbonaby** [comment]
Fixed by #2892 

For some reason it wouldn't let me link to this issue in the PR
