### ISSUE TITLE
Environments that are in progress for creation should be pinned to the top of the list

### ISSUE THREAD

**Issue by shakersMSFT** [microsoft/devhome#2669]
### Suggested new feature or improvement

Environments that are in progress for creation should be pinned to the top of the list until the environment is created and synced with the page. 

### Scenario

As a user, if I am creating a new environment, I want to be able to keep track of it on the environments page. If I have a lot of environments, the new one could currently be lost amongst the existing ones and it would be great to have them pinned at the top for easy monitoring.

**Comment by SohamDas2021** [comment]
Spoke to @shakersMSFT offline, we have agreed to not to mess with the Sorting options. To summarize, we will keep the newly created VMs on top. But if the user uses Sorting options, that will override the ordering.
