### ISSUE TITLE
Quiet Mode icon is not properly loading

### ISSUE THREAD

**Issue by joadoumie** [microsoft/devhome#2676]
### Dev Home version

0.1301.472.0

### Windows build number

10.0.26100.1000

### Other software

OS Build Version: 10.0.26100.1000.amd64fre.ge_release_we_adept.240331-1700
.NET Version: .NET 8.0.3

### Steps to reproduce the bug

Navigate to Windows Customization

### Expected result

All the icons are properly loaded for the features inside of Windows Customization.

### Actual result

The icon for quiet mode is not properly loading: 

<img width="957" alt="image" src="https://github.com/microsoft/devhome/assets/98557455/e0f5a7c3-5c1a-43fe-8580-c6fa91c27af3">

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
Physical Memory: 47.71GB (24.47GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
9932MartCliment.WingetUIWidgets_0.4.0.0_x64__g91dtg5srk15g (WingetUI Widgets (Preview))
Microsoft.Windows.DevHome.Dev_0.1201.457.0_x64__8wekyb3d8bbwe (Dev Home (Dev))
Microsoft.Windows.DevHome.Dev_0.1201.457.0_x64__8wekyb3d8bbwe (Dev Home (Dev))
Microsoft.DevHomeMicrosoftGameDevExtension.Canary_0.400.456.0_x64__8wekyb3d8bbwe (Dev Home Microsoft Game Dev Extension (Canary))
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1200.466.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHome.Canary_0.1301.472.0_x64__8wekyb3d8bbwe (Dev Home (Canary))
Microsoft.Windows.DevHome.Canary_0.1301.472.0_x64__8wekyb3d8bbwe (Dev Home (Canary))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.10301.0.0_x64__cw5n1h2txyewy

**Comment by joadoumie** [comment]
@btueffers for visibility.

**Comment by kanismohammed** [comment]
Fixed in the latest build
