### ISSUE TITLE
Create an Extension - Learn More goes to nonexistent file in github

### ISSUE THREAD

**Issue by chendrixson** [microsoft/devhome#2679]
### Dev Home version

0.1301.472.0

### Windows build number

10.0.26201.5000

### Other software

OS Build Version: 10.0.26201.5000.amd64fre.ge_current_directadept.240416-1700
.NET Version: .NET 8.0.3

### Steps to reproduce the bug

Open Settings -> Feedback and click learn more on extension item.
![image](https://github.com/microsoft/devhome/assets/17891214/1f4398ba-d0f4-4021-9231-b03e39c1ff81)

### Expected result

See a nice markdown with info.

### Actual result

The file isn't there in the main branch at least.
![image](https://github.com/microsoft/devhome/assets/17891214/15f2d0f0-c80e-44d0-a938-63afd1383960)

**Comment by cinnamon-msft** [comment]
Fixed :)
