### ISSUE TITLE
[Dev Drive Insights] Prepopulate the file path for moving caches

### ISSUE THREAD

**Issue by joadoumie** [microsoft/devhome#2681]
### Suggested new feature or improvement

When suggesting that users move their caches, it'd be nice to prepopulate the most sensible file path for the user so they don't have to browse and create a new folder or type in a new path. The default should be what is shown in the example. 

### Scenario

Make it more seamless for users to move their package caches.

<img width="401" alt="image" src="https://github.com/microsoft/devhome/assets/98557455/647c0480-de53-49e6-8c71-0665f5a0cb02">

**Comment by zadjii-msft** [comment]
I also don't think that it'll let you "make changes" unless you actually "Browse" first. If you just type the path in, you need to _still_ Browse to that same path:
![image](https://github.com/microsoft/devhome/assets/18356694/c724494f-ef84-4258-ad9c-a42ba5e5dc76)
