### ISSUE TITLE
Dev Drive insights titles should have sentence case

### ISSUE THREAD

**Issue by btueffers** [microsoft/devhome#2698]
### Dev Home version

0.1301.472.0

### Windows build number

10.0.26100.1

### Steps to reproduce the bug

Go to Windows customization page and navigate to Dev Drive insights

### Expected result

Titles should be "Dev Drive insights" and "Dev Drive volumes" - lowercase insights and volumes

### Actual result

Main title is "Dev Drive Insights" and subtitle is "Dev Drive Volumes"

### Included System Information

![image](https://github.com/microsoft/devhome/assets/82911735/a8c92712-ad63-450d-81f7-4e946a74a94b)

![image](https://github.com/microsoft/devhome/assets/82911735/48669027-1bea-4dbb-a45c-4a924ee86244)

![image](https://github.com/microsoft/devhome/assets/82911735/45026679-afbe-4590-9f65-9cae22bd2c48)

**Comment by krschau** [comment]
#2682 Fixed the "i" in "Insights" but not the "v" in "Volumes"

**Comment by kanismohammed** [comment]
Issue is resolved

**Comment by krschau** [comment]
@kanismohammed Looking at current main, it is not.
![image](https://github.com/microsoft/devhome/assets/47155823/e3234686-8696-4f1b-a7f3-c17b81c974e4)

**Comment by SohamDas2021** [comment]
Yes, I looked at "Dev Drive insights"and that was fixed. Will address the rest as part of this bug.
