### ISSUE TITLE
Dev Drive insights section header missing

### ISSUE THREAD

**Issue by btueffers** [microsoft/devhome#2702]
### Dev Home version

0.1301.472.0

### Windows build number

10.0.26100.1

### Steps to reproduce the bug

Navigate to Windows customization -> Dev Drive insights

### Expected result

Each section of the page should have a subtitle. 

![image](https://github.com/microsoft/devhome/assets/82911735/ee89f8e7-e503-40db-9d23-63a2870ce2a9)

### Actual result

The package cache section does not have a section header.

![image](https://github.com/microsoft/devhome/assets/82911735/58587395-214e-48b1-a23d-b58fe7293f88)

**Comment by SohamDas2021** [comment]
Fixed in https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

**Comment by SohamDas2021** [comment]
Fixed in https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

**Comment by krschau** [comment]
@SohamDas2021 Can you fix the link above? Just use #xxxx, it's easier than inserting a link yourself.
