### ISSUE TITLE
Dev Drive insights broken links

### ISSUE THREAD

**Issue by btueffers** [microsoft/devhome#2703]
### Dev Home version

0.1301.472.0

### Windows build number

10.0.26100.1

### Steps to reproduce the bug

Navigate to Windows customization -> Dev Drive insights

### Expected result

Web links open a valid location.

### Actual result

When there is a suggestion for a package cache the associated web links to direct users to further information don't currently open documentation.

![image](https://github.com/microsoft/devhome/assets/82911735/fcbbb860-d4b8-4e5b-a7b1-b8eb8dd1a5c8)

**Comment by SohamDas2021** [comment]
Fixed in https://github.com/microsoft/devhome/pull/2803
