### ISSUE TITLE
[Dev Box] Sometimes the first class to the management plane results in a The 'Authorization' header is missing the access token." Https error

### ISSUE THREAD

**Issue by bbonaby** [microsoft/devhome#2707]
### Steps to reproduce the bug

Make use the Dev Box provider to get a list of the users Dev Boxes. This can happen in any one of these scenarios:

-Install Azure extension that has the Dev Box provider
- Launch Dev Home for the first time (try on a new VM for example)
- Go to one of the following:
    - Environments page (wait for the page to load and you should see an error)
    - Machine configuration > Setup an environment. (wait for the page to load and you should see an error)
    - Machine configuration > Create an environment > wait for providers to load > Select Dev Box provider > click next > wait and observe the error.
 
You can also click the sync button on the Environments page and the Setup an environment pages and you may see the error.

I attached the log file, from someone who used Environments for the first time. (removed their user name)
[Dev Box provider log.zip](https://github.com/microsoft/devhome/files/15044088/Dev.Box.provider.log.zip)

Based on the logs it looks like the first time they attempted, the DeveloperId sent to the extension was empty. Then the second time they attempted, we sent the correct DeveloperId and they were able to get data back from the Dev Box provider.

### Expected result

A better error message is sent from the azure extension if the DeveloperId properties are empty.

We shouldn't send an empty provider Id if the user already logged into the azure extension.

Interestingly, after this error occured I checked with the user by going to Dev Home's settings page to see if they were logged into the azure extension. When we checked we confirmed they were already logged in.

Upon going back to the Create environment page and trying again, the were able to get the creation adaptive cards with the Dev Box pools and project information. That is why in the logs you'll see the second time they tried we see the developerId information.

### Actual result

issue seems to be that we send an empty developerId, to the Dev Box provider. That shouldn't happen in this case as the user had already logged in to the azure extension.

I believe the issue here is that we sent an empty developerId to the DevBox provider. We associated the compute system providers with developerIds here: 
https://github.com/microsoft/devhome/blob/c8ac78cf28ef1130cd667cb88d36b0397d1d692e/common/Services/ComputeSystemService.cs#L64

its possible at the time of this call this call the `devIdList` in that code did not have developerIds available. We'll need to investigate and add logging in that method.

**Comment by huzaifa-d** [comment]
Fixed in https://github.com/microsoft/DevHomeAzureExtension/pull/162
