### ISSUE TITLE
Disabled experimental feature for Machine Configuration persists

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#2709]
### Dev Home version

0.1301.473.0

### Steps to reproduce the bug

Navigate to "set up an environment" in machine configuration
Navigate to settings and disable the environment experimental features
Navigate back to machine configuration

### Expected result

Machine configuration should go back to its home screen

### Actual result

You can still see the set up an environment page and continue through the steps
![image](https://github.com/microsoft/devhome/assets/48369326/6ebd4903-01f5-47fc-b9f8-a68cc6bfd82b)

**Comment by kanismohammed** [comment]
@bbonaby  Please add more details.

**Comment by AmelBawa-msft** [comment]
Discussed offline with @bbonaby, re-assigning.

**Comment by bbonaby** [comment]
closing since we're no longer an experimental feature

**Comment by adrastogi** [comment]
I need to file an issue for it, but I think Quickstart Playground suffers from this same problem... @AmelBawa-msft / @bbonaby, would be interested in chatting more with you about what you were theoretically planning to do for this issue. I can follow up offline.
