### ISSUE TITLE
Typos with Microsoft Dev Box

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#2726]
### Dev Home version

0.1301.473.0

### Steps to reproduce the bug

Go to create a Microsoft Dev Box in Environments and give it a name with spaces

### Expected result

Proper name is "Microsoft Dev Box" with a space
Hyphen is spelled correctly

### Actual result

Should be "Microsoft Dev Box"
![image](https://github.com/microsoft/devhome/assets/48369326/a4d201dc-6502-43a4-b7c2-a346e45cd582)

Should be "hyphen"
![image](https://github.com/microsoft/devhome/assets/48369326/b1151c8a-ca13-4694-bea9-92e308db3944)

**Comment by huzaifa-d** [comment]
Fixed in https://github.com/microsoft/DevHomeAzureExtension/pull/162
