### ISSUE TITLE
Environments sync information never updates

### ISSUE THREAD

**Issue by shakersMSFT** [microsoft/devhome#2740]
### Steps to reproduce the bug

The environments page 'last synced' message always says Moments ago... even if it has been minutes since I synced. Either we are syncing too frequently, or we aren't updating the message accurately. 

### Actual result

<img width="652" alt="image" src="https://github.com/microsoft/devhome/assets/45182130/25418183-03d0-49c8-97bf-3eae2e51784c">

**Comment by huzaifa-d** [comment]
Accidentally removed by @bbonaby.
