### ISSUE TITLE
environments status mismatch between pages

### ISSUE THREAD

**Issue by shakersMSFT** [microsoft/devhome#2742]
### Steps to reproduce the bug

My environments page and the environment configuration page have mismatched status for the same set of dev boxes. 

### Expected result

Environment status should always be in alignment. 

### Actual result

environments configuration:
<img width="937" alt="image" src="https://github.com/microsoft/devhome/assets/45182130/341afb37-ab40-406b-bb5c-11eff19ad7ea">
environments page: 
![image](https://github.com/microsoft/devhome/assets/45182130/20f1fb14-1f67-422b-ae4d-7d847764dcd5)

**Comment by kanismohammed** [comment]
Environment page should update the dev box environment status for operations initiated by the user in dev home

**Comment by huzaifa-d** [comment]
@shakersMSFT I can't repro this. What might have happened is the two pages might have been loaded at different times, during which the status of the Dev Box changed. 
Please let me know additional details if you can repro this.
