### ISSUE TITLE
Hyper-V is confusing

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2745]
### Steps to reproduce the bug

On a new machine, add support for environments.
You will get error about adding user to hyper-v admins
Click OK to add the user to hyper-v admins

You get a next error.

<img width="245" alt="image" src="https://github.com/microsoft/devhome/assets/2146880/11579e81-fef9-4f52-9dee-5beb072055ca">

It suggested that i should look at the logs and i have no idea where that is.

### Expected result

Error help me to either open the log, or hyper link to the log file.

### Actual result

<img width="245" alt="image" src="https://github.com/microsoft/devhome/assets/2146880/58f5ecd4-1569-4838-91c3-1d22e7491125">

**Comment by kanismohammed** [comment]
Tracked by this P0 issue https://github.com/microsoft/devhome/issues/2784

**Comment by krschau** [comment]
Duplicate of @2784
