### ISSUE TITLE
Deleting a dev box shows an indeterminant progress bar until you manually click refresh.

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#2746]
### Dev Home version

0.1301.477.0

### Windows build number

10.0.22635.3500

### Other software

OS Build Version: 10.0.22635.3500.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Create a Dev Box
Delete the Dev box
Wait

### Expected result

Dev Home should check regularly to see if the dev box delete operation is complete and remove the dev box from the environment page.

### Actual result

The dev box and the animated progress bar run continuously for as long as you have dev home running and the environment page open.
You have to click refresh to see the updated list of dev boxes.

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (11.63GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHomeGitHubExtension_0.1300.477.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.800.477.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.11001.0.0_x64__cw5n1h2txyewy

**Comment by bbonaby** [comment]
Should be fixed once both https://github.com/microsoft/devhome/pull/2732 and https://github.com/microsoft/DevHomeAzureExtension/pull/163 are checked in
