### ISSUE TITLE
Moving .cargo to DevDrive should also adjust PATH

### ISSUE THREAD

**Issue by hansSchall** [microsoft/devhome#2749]
### Dev Home version

0.1301.477.0

### Windows build number

10.0.22631.3296

### Other software

OS Build Version: 10.0.22631.3296.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

1. Use the option to move the .cargo dir
2. Try to use cargo/rustc/rustup

### Expected result

cargo/rustc/rustup should work

### Actual result

The term 'cargo' is not recognized as a name of a cmdlet, function, script file, or executable program.

PATH still points to old .cargo/bin

### Included System Information

CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Physischer Speicher: 15.86GB (4.19GB free)
Prozessorarchitektur: x64

### Included Extensions Information

Erweiterungen: 
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Vorschau))
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Vorschau))

Widgetdienst: 
MicrosoftWindows.Client.WebExperience_424.1301.450.0_x64__cw5n1h2txyewy

**Comment by SohamDas2021** [comment]
@manodasanW @btueffers shall we document this in https://learn.microsoft.com/en-us/windows/dev-drive/#storing-package-cache-on-dev-drive
