### ISSUE TITLE
Microsoft 365 problems.

### ISSUE THREAD

**Issue by KrazyP** [microsoft/devhome#2756]
### Provide a description of requested docs changes

I have been trying to get my Microsoft 365 on my computer, for three days.  It will not let me in. Instead I was on a different site that was intended for another location. My account is paid in full for two years. Still cannot get it registered. All the codes, passwords, are wrong. I want to install my documents, but cannot because Microsoft will not allow. I made a mistake on the serial number which has caused many days of extreme anxiety and grief. I still cannot get on to extract my documents.

**Comment by KrazyP** [comment]
No more comments, I just want to get my photos and documents printed. Then I will leave all the sadness behind. All the codes and passwords were incorrect all the time. Sent codes were NOT AVAILABLE.  Just allow me to get my documents printed. I will vacate Microsoft.

**Comment by krschau** [comment]
I'm sorry, this is not the correct place to report issues with Microsoft 365. In order for the right people to see your issue, please file your issue on Feedback Hub. Instructions will be in the next comment.

/feedbackhub

**Comment by KrazyP** [comment]
FORGET THE WHOLE THING!
