### ISSUE TITLE
Attempt of example EnableWindowsSettings.yaml fails for 5 of the 7 resources

### ISSUE THREAD

**Issue by mattmazzola** [microsoft/devhome#2760]
I was learning about [winget Machine Configuration](https://learn.microsoft.com/en-us/windows/package-manager/configuration/) and  trying to apply a copy of [EnableWindowsSettings.yaml](https://github.com/microsoft/devhome/blob/aca7c203676137cc8ee9fd0c580d20310d5e73e1/docs/sampleConfigurations/DscResources/Microsoft.Windows.Developer/EnableWindowsSettings.yaml) to my own machine and surprisingly found it mostly **_fails_** with partial success.

## Output

```
Apply :: TaskBarAlignment
  The configuration unit was not in the module as expected.
Apply :: ShowSecondsInClock
  Configuration successfully applied.
Apply :: HideFileExtensions
  The configuration unit was not in the module as expected.
Apply :: ShowTaskViewButton
  The configuration unit was not in the module as expected.
Apply :: ShowHiddenFiles
  The configuration unit was not in the module as expected.
Apply :: HideTaskBarLabels
  The configuration unit was not in the module as expected.
Apply :: EnableDarkMode
  Configuration successfully applied.
Some of the configuration was not applied successfully.
```

## Expected

Given this example comes directly from the devhome repo, AND `winget configuration validate` reported success, I expected ALL configurations to be applied successfully (7/7)

## Actual

Only 2/7 were applied successfully

Here is one of the failing resources: 
https://github.com/microsoft/devhome/blob/aca7c203676137cc8ee9fd0c580d20310d5e73e1/docs/sampleConfigurations/DscResources/Microsoft.Windows.Developer/EnableWindowsSettings.yaml#L10-L15

By looking at the logs I can see it will complain the resource, such as `Microsoft.Windows.Developer/TaskBarAlignment` does not exist. or perhaps a property is invalid.

## Questions

- How to discover appropriate resource names?
    - For example, what powershell command can I run to list all possible configuration resources available within Microsoft.Windows.Developer module?
- How to discover available settings for a given resource?
    - Specifically how to I know which settings can be listed such as `HideLabels: Never` vs `Ensure: Present` or which need `RestartExplorer: true`

**Comment by denelon** [comment]
@mattmazzola, we're doing some changes to that Module and the resources inside. I'll get the sample updated to match our current implementation.

**Comment by mattmazzola** [comment]
Ok! 

> I'll get the sample updated

Would the updated sample include answers to the questions above?

If yes, then it I'll wait for the sample update.
If not, could you or someone else answer them here?
It would help me understand how this works in my exploration.
(For example, maybe the reason the winget validate passed despite failure is because it only checks syntax but not actual existence. Maybe there is an option to do more complete validation?)

**Comment by denelon** [comment]
WinGet validate is looking at the "overall" syntax for the configuration file. It's not able to validate the "settings" are correct for a specific DSC Resource. We're still working on how we would be able to achieve that and improve the experience building configuration files given the specified DSC Resources.

You can use "Get-DscResource -Module <the module>" to discover individual resources inside a PowerShell module. Note, the module should be "ClassBased" as InvokeDscResource (called by WinGet Configuration) has a limitation such that "Binary" resources aren't supported.

**Comment by denelon** [comment]
@mattmazzola the PR to update the sample configuration was just merged. I'm going to go ahead and close this issue. Feel free to @ mention me if you have any challenges validating.

I threw an image in below to show the resources in the module.

Note: We're going to be covering all Windows Settings in future modules, so many of these will be duplicated and eventually they will most likely be removed from the Microsoft.Windows.Developer module.

![image](https://github.com/microsoft/devhome/assets/61799811/f74c5696-7a0c-4bf1-8db0-189880116e31)

**Comment by mattmazzola** [comment]
Hmm, I am unable to verify although I assume the commands work.

![image](https://github.com/microsoft/devhome/assets/2856501/b1c7dbac-12fe-4bad-b618-16cde72cd4c9)

When I try to replicate `Get-DscResource -Module Microsoft.Windows.Developer`
It responds: `WARNING: There are no modules present in the system with the given module specification.`
