### ISSUE TITLE
Dev Box configuration does not currently work

### ISSUE THREAD

**Issue by hamza-usmani** [microsoft/devhome#2762]
### Steps to reproduce the bug

Setup an environment (Dev Box) currently errors out with a BadRequest code

### Actual result

Error when "set up" is clicked in final configuration screen.

**Comment by jiayac** [comment]
[devhome20240424.zip](https://github.com/microsoft/devhome/files/15153612/devhome20240424.zip)
This is the logs I have seen with machine configuration

**Comment by huzaifa-d** [comment]
Closing as this was due to the incorrect version of the Azure Extension being used.
