### ISSUE TITLE
[Environments] [HyperV] Error code when you don't have VMP installed isn't specific

### ISSUE THREAD

**Issue by chendrixson** [microsoft/devhome#2766]
### Dev Home version

0.1301.473.0

### Steps to reproduce the bug

Launch environment page when you don't have HV installed.  First it will tell you that you're not a member of the HV group, but if you fix that and reboot, then it just gives a generic error.  "check HV logs".

This was on an ARM device, but I don't know if that's a requirement.

### Expected result

VMP not installed, please go to Turn on/off windows features to enable.  

### Actual result

Same "check hv log" error code when anything else is wrong.

**Comment by kanismohammed** [comment]
This is being tracked by this P0 issue

**Comment by krschau** [comment]
@kanismohammed Could you link the issue?
