### ISSUE TITLE
HyperVManager.cs crashes with a powershell error.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#2771]
### Steps to reproduce the bug

Navigate to "Set up an environment"

### Expected result

I can set up an environment

### Actual result

Crash with the message

`Unable to get disk size due to PowerShell error: 'D:\vhds\release-220506-Desktop_1DA0BC18-4B8A-4647-8DD9-D1B71A8EF139.avhdx' is not an existing virtual hard disk file.'`

**Comment by dhoehna** [comment]
Logs for DevHome and the Azure extension.

[DevHomeLogs.zip](https://github.com/microsoft/devhome/files/15169191/DevHomeLogs.zip)

**Comment by dhoehna** [comment]
Crashes even when logged in.

**Comment by bbonaby** [comment]
Can you pull from main and try again? I don't see a crashing issue in the Dev build, Canary or Preview. The error you put in the "actual result" section wouldn't crash the app/process as there is a try/catch there.

**Comment by dhoehna** [comment]
> Can you pull from main and try again? I don't see a crashing issue in the Dev build, Canary or Preview. The error you put in the "actual result" section wouldn't crash the app/process as there is a try/catch there.

After getting the windows upgrades and pulling from main, the crash went away.
