### ISSUE TITLE
Dev Box configuration constantly gives "log in required" and "resume" button without working

### ISSUE THREAD

**Issue by hamza-usmani** [microsoft/devhome#2774]
### Steps to reproduce the bug

When trying to configure Dev Box, an error saying "log in required" pops up 5-6 times, prompting the user to hit Resume. After 5-6 times of the error and hitting resume, configuration finally works.

This entire UX is extremely confusing and took a few times before I realized I should continue pressing resume until it works. There needs to be clearer action prompts (telling the user explicitly what to do and how to do it, similar to how Hyper-V has a login prompt) and this should not take 5-6 prompts simply to work.

### Actual result

Configuration only works once I figured out that pressing resume 5-6 times when prompted and waiting would do it. The text in-product is not informative and the experience is blocking.

**Comment by kanismohammed** [comment]
Issue is fixed in the latest build
