### ISSUE TITLE
Creating new Dev Box displays Projects not visible in Dev Center (incorrect projects)

### ISSUE THREAD

**Issue by hamza-usmani** [microsoft/devhome#2775]
### Steps to reproduce the bug

Create new dev box, in the projects screen dropdown we are seeing projects that should not be there.

### Actual result

Incorrect and larger projects list.

**Comment by jiayac** [comment]
Any updates on this?

**Comment by huzaifa-d** [comment]
In development. Scheduled for July release.

**Comment by huzaifa-d** [comment]
Fixed in the PR above.
