### ISSUE TITLE
Can't navigate to the environment summery information in the summary screen.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#2802]
### Steps to reproduce the bug

Make an environment and get to the Summary Screen.

### Expected result

When focus is on the expander, I can use my keyboard to navigate to items in the expander.

### Actual result

I can't navigate to the summary information in the Expander.

**Comment by bbonaby** [comment]
fyi all the items are just text within the expander so thats probably why you can't tab into them, which is by design. But I could be misinterpreting your bug though so let me know

**Comment by dhoehna** [comment]
Ah.  Sorry.  My intention was unclear.

I understand why I can't use my keyboard to navigate to the items.  I'm concerned about narrator.  If the items can't be navigated to, the narrator won't announce the information.

That is the purpose of this issue.

**Comment by bbonaby** [comment]
oh I see, in that case if you do INSERT + SPACEBAR   that should turn on scan mode and then you should be able to then navigate to the text in the expander I believe. Thats usually what they make me do during the accessibility reviews.

**Comment by dhoehna** [comment]
Right.  I forgot about scan mode.  Cool.  If that works, I'm good.  Closing issue.
