### ISSUE TITLE
Widgets lack their graph in the Widgets panel.

### ISSUE THREAD

**Issue by Friction-less-development** [microsoft/devhome#2817]
### Dev Home version

0.1301.477.0

### Windows build number

10.0.22631.0

### Other software

windows web experience pack 524.12001.20.0  (Latest public ver)

However, previous public versions behaved no differently.

### Steps to reproduce the bug

After installing Dev Home, you get the option to add its Widgets to your Widgets screen. This is the windows widgets screen, outside of dev home.

The preview looks like this, which matches how they look in dev home.

![image](https://github.com/microsoft/devhome/assets/10731326/dcad7f14-bab7-455b-a34b-690799e0a9d7)

But the actual widget looks like this.

![image](https://github.com/microsoft/devhome/assets/10731326/29bb94b6-2729-4aa0-b0c3-42ff5a24cb37)

This applies to all the widgets with graphs.

### Expected result

I'd expect the widgets to be consistent and show graphs when pinned to the widgets board.

### Actual result

The widgets do not have graphs when pinned to the widgets board.

### Included System Information

I have seen the behavior on 3 different computers, so I don't think it's system specific.

**Comment by krschau** [comment]
Hi @Friction-less-development. Since this issue is specific to the Windows Widget Board, please open an issue in Feedback Hub. That way, this issue will be seen by the right people. You can even include something about "base64 encoded images do not show up in widgets," that's how I would report the error.

**Comment by oceanoftear** [comment]
I got exactly the same issue on my brand new win11 laptop
