### ISSUE TITLE
not showing apps to install

### ISSUE THREAD

**Issue by Monkeyskatef** [microsoft/devhome#2818]
### Dev Home version

0.1301.477.0

### Windows build number

10.0.22621.3447

### Other software

OS Build Version: 10.0.22621.3447.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

trying to download apps

### Expected result

it to show the apps I searched

### Actual result

it came up with the recommended apps to install

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
Physical Memory: 7.85GB (1.08GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.450.0_x64__cw5n1h2txyewy

**Comment by AmelBawa-msft** [comment]
Hi @Monkeyskatef, thank you for creating this issue. Just to make sure I understood it correctly. You are able to see the list of recommended applications but when you perform a search you don't see the searched applications? Feel free to post screenshot as well to help better troubleshoot the issue.

/logs
