### ISSUE TITLE
GitHub does not allow DHLOG extensions to be added

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2841]
### Steps to reproduce the bug

Try to update DevHome Log. 
You cannot  as it is not a supported format.

### Expected result

Log files can be attached to GitHub issues

### Actual result

Blocked and had to name it TXT

![image](https://github.com/microsoft/devhome/assets/2146880/191f9b31-e2ac-4913-993c-f3a5701a51c4)

**Comment by dkbennett** [comment]
The guidance is to .zip up the logs.
[testlog.zip](https://github.com/microsoft/devhome/files/15268095/testlog.zip)

**Comment by dkbennett** [comment]
Previous comment demonstrates GitHub has no problem with .dhlog if the log is zipped, so closing this issue.
