### ISSUE TITLE
Utilities Page - Page size can be shrunk to hide launch buttons

### ISSUE THREAD

**Issue by timkur** [microsoft/devhome#2864]
### Dev Home version

0.1401.495

### Windows build number

10.0.22621.3527

### Steps to reproduce the bug

Navigate to the Utilities node, shrink the window to the point where launch buttons are obscured

### Expected result

Expect the page to reflow. If I make it smaller, it does reflow properly, just not at this size.

### Actual result

![image](https://github.com/microsoft/devhome/assets/49733346/a9b58d59-d8ce-476b-acca-f41114ada285)

**Comment by krschau** [comment]
Suggest putting description and Learn More link in ScrollViewer, the way we do for What's New cards. Also, should be "Learn more" (sentence case).
