### ISSUE TITLE
Delete on a running hyper-V VM crashes Dev home

### ISSUE THREAD

**Issue by kanismohammed** [microsoft/devhome#2867]
### Steps to reproduce the bug

1. Create hyper-v environments.
2. Start them
3. Delete the environment

### Expected result

Hyper-V VM is deleted

### Actual result

Dev home crashes

**Comment by bbonaby** [comment]
Issue looks like its coming from this line FYI https://github.com/microsoft/devhome/blob/944910065ae769fb053c06bc913c90b4504c9758/common/Environments/Models/ComputeSystemCache.cs#L232
