### ISSUE TITLE
Launching a dev box from the pinned Start Menu icon is broken

### ISSUE THREAD

**Issue by kanismohammed** [microsoft/devhome#2869]
### Steps to reproduce the bug

1. Pin the dev box to start menu
2. Launch it from Start menu

### Expected result

Launching works fine

### Actual result

![image](https://github.com/microsoft/devhome/assets/95303413/a8e52bf7-3343-4169-917f-5ce337a1fbca)

**Comment by kanismohammed** [comment]
Start menu launched app does not glom with the task bar pinned instance

**Comment by huzaifa-d** [comment]
Verified working on the latest Preview version.
