### ISSUE TITLE
Can't apply a configuration file to a DevBox.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#2875]
### Steps to reproduce the bug

1. Have an already made DevBox.
2. Go to Machine Configuration -> Set up an environment
3. Select the DevBox
4. Add any options (I chose Powershell)
5. Start setting up.

### Expected result

No errors.

### Actual result

An error "We couldn't apply the configuration file onto asdfg"

**Comment by dhoehna** [comment]
[Logs.zip](https://github.com/microsoft/devhome/files/15279149/Logs.zip)

**Comment by kanismohammed** [comment]
duplicate of this issue https://github.com/microsoft/devhome/issues/2840

**Comment by krschau** [comment]
Duplicate of #2840
