### ISSUE TITLE
Quickstart Playground can crash Dev Home if the user saves a project into the same folder twice

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhome#2891]
### Dev Home version

0.1401.495.0

### Windows build number

10.0.26217.5000

### Other software

OS Build Version: 10.0.26217.5000.amd64fre.ge_current_directadept.240509-1700
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

1. Generate a new project via Quickstart Playground
2. Save the project via the 'Save' button and pick a new folder for the generated assets
3. Click 'Save' again and pick that same location

### Expected result

I don't think we've spec'd out exactly what we want the desired behavior here (I could imagine something like prompting the user if they want to overwrite the existing files, or giving an error and asking the user to pick a different destination if we don't want to support overwriting)

### Actual result

Dev Home crashes. 

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
Physical Memory: 31.83GB (17.15GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHomeGitHubExtension_0.1300.477.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1400.495.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.495.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome.Canary_0.1401.495.0_x64__8wekyb3d8bbwe (Dev Home (Canary))
Microsoft.Windows.DevHome.Canary_0.1401.495.0_x64__8wekyb3d8bbwe (Dev Home (Canary))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.12801.0.0_x64__cw5n1h2txyewy

**Comment by adrastogi** [comment]
Discussed internally and we will hold off on trying to get a fix in for this right now (ideally, we will have a proposal UX that we can implement for the 0.15 release). We _think_ this won't be a common scenario, i.e., trying to save the same project on top of itself.

**Comment by krschau** [comment]
Lowering priority since the crash is a rare case.
