### ISSUE TITLE
Quickstart Dependency Checker popup uses wrong theme

### ISSUE THREAD

**Issue by krschau** [microsoft/devhome#2898]
### Steps to reproduce the bug

My machine is in Dark mode, but Dev Home is in Light mode. I went to the Quickstart playground and this popped up:
![image](https://github.com/microsoft/devhome/assets/47155823/06cf2969-1e1f-4286-af81-744478c19e25)

### Actual result

Wrong theme.

**Comment by adrastogi** [comment]
Marking this as closed, courtesy of #3427 (thank you, @dhoehna for digging into this and resolving it across Dev Home!).
