### ISSUE TITLE
Dark mode inconsistency

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#2900]
### Steps to reproduce the bug

Turn latest Canary version + Azure extension in dark mode:
![image](https://github.com/microsoft/devhome/assets/65691598/64282c9c-cf01-4491-9e9b-c3ecffa4ee5e)
the close/expand icons on the top right and progress icons are still in light mode. Please get them fixed.

### Actual result

Dark mode should work as expected.

**Comment by krschau** [comment]
Is your machine in light or dark theme when this happens?

**Comment by krschau** [comment]
Duplicate of #1858
