### ISSUE TITLE
Error retriving adaptive card from extension

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#2903]
### Steps to reproduce the bug

Open Dev Home and Create an Environment
![image](https://github.com/microsoft/devhome/assets/65691598/e3d2df8d-739b-402d-9cff-85b565f396c7)

### Actual result

It should load the project and pools correctly

**Comment by bbonaby** [comment]
Hi @jiayac, can you confirm that you only have 1 azure extension enabled in the extensions tab in Dev Home when you received this error?

**Comment by huzaifa-d** [comment]
This is because of having more than one version of Dev Home Azure Extensions enabled. This can be closed.

**Comment by krschau** [comment]
@huzaifa-d Is this always supposed to happen with 2 Azure extensions (in which case, we add the label "Resolution-By-Design" or is it caused by #2451 (in which case, we should link to that when closing this)?

**Comment by jiayac** [comment]
I sometimes do have more than one extension installed. However, I should always have one extension enabled. What is the anticipated behavior here?

**Comment by huzaifa-d** [comment]
@krschau it should be linked to #2541.

**Comment by krschau** [comment]
Duplicate of #2541
