### ISSUE TITLE
Not seeing Dev Box Projects that I should see

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#2904]
### Steps to reproduce the bug

Create environment and choose Dev Box
![image](https://github.com/microsoft/devhome/assets/65691598/c2add3ad-7531-49d0-bdb1-a4883ef9f377)

### Actual result

I should see all projects that I should have access under which to create new Dev Boxes.

**Comment by huzaifa-d** [comment]
Hi Jiayan. I am unable to repro the issue. Could you make sure you are using the latest canary version 0.1400.500.0 and provide the logs?
