### ISSUE TITLE
Make Changes button not enabled when user inputs text directly into input box

### ISSUE THREAD

**Issue by SohamDas2021** [microsoft/devhome#2906]
### Steps to reproduce the bug

In Dev Home -> Customization -> Dev Drive Insights, click on "Make the change".
The dialog box appears. Directly input a valid path into the text box without clicking the browse button. 

### Expected result

"Make changes" button should be enabled.

### Actual result

"Make changes" button remains disabled.

**Comment by cinnamon-msft** [comment]
This should be fixed now :)
