### ISSUE TITLE
Experimental feature toggle cards in Dev home Settings should contain link to feature "home"

### ISSUE THREAD

**Issue by TWhiteDesigns** [microsoft/devhome#2909]
### Dev Home version

0.1401.495.0

### Windows build number

10.0.22631.3447

### Steps to reproduce the bug

Open Dev Home > Settings > Experimental features. View experimental features cards that currently lack link to where the feature lives in Dev home, so users can more easily find the experimental features they've activated.

### Expected result

Once activated, users should have access to a "link" icon to the right of the activation toggle in which they can click on, and it will take them to the respective area/page of Dev Home in which the feature resides.
![image](https://github.com/microsoft/devhome/assets/127447480/7edcd77c-d477-4ca0-b9e0-ef2e8eb676b5)

https://www.figma.com/design/AZ03I5bFPmrOpjVzFRjVn4/Dev-Home-Settings?node-id=167%3A103590&t=Q5ktisrhIbeKKna5-1

### Actual result

feature destination link is missing.
![image](https://github.com/microsoft/devhome/assets/127447480/754aa620-1efe-4394-95e0-f3654d383be0)

**Comment by krschau** [comment]
@TWhiteDesigns One question here -- everywhere else in Dev Home, we use the "⬜↗️" (use your imagination there 🙂) icon to mean "this link goes outside of Dev Home". Here, we're staying in Dev Home. Do we want to use the default ">" icon that I think people would normally expect to see instead?

**Comment by TWhiteDesigns** [comment]
> @TWhiteDesigns One question here -- everywhere else in Dev Home, we use the "⬜↗️" (use your imagination there 🙂) icon to mean "this link goes outside of Dev Home". Here, we're staying in Dev Home. Do we want to use the default ">" icon that I think people would normally expect to see instead?

@krschau Thanks for the catch. Yes, let's use the right chevron icon for instances where we navigate to a destination within Dev Home, and save the Open in New Window icon exclusively for instances where the action will take the user outside of the Dev Home app.
