### ISSUE TITLE
Two records appearing in environment list when creating a dev box

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#2915]
### Dev Home version

0.1301.477.0

### Windows build number

10.0.22635.3575

### Other software

OS Build Version: 10.0.22635.3575.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Not sure on exact repro... Create a dev box from Dev Home. Deleted another dev box. Close the app. Laptop went to sleep. Returned to App.

### Expected result

Only one entry per dev box.

### Actual result

Found two entries in the list with animated progress bars creating the same dev box.
![image](https://github.com/microsoft/devhome/assets/5457010/ffaf1c42-a6d1-4a1d-80b3-0cef4c86ed96)

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (17.84GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHomeGitHubExtension_0.1300.477.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.800.477.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension.Dev_0.800.493.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Dev))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment]
This is because there are multiple versions of the same extension installed. Please disable either one - 
Microsoft.Windows.DevHomeAzureExtension_0.800.477.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension.Dev_0.800.493.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Dev))
