### ISSUE TITLE
[Windows Customization] Additional Settings for Windows Customization 

### ISSUE THREAD

**Issue by joadoumie** [microsoft/devhome#2920]
### Suggested new feature or improvement

This is a scenario to help keep track of work being done to add more P0 settings/functionality into Windows Customization. 

### Scenario

This is a scenario issue to host other features/issues for P0 settings that are currently in scope for being added to the Windows Customization experience in Dev Home. This list is **not completely exhaustive of all of the work being done** at this point in time. We will test out this approach for tracking primarily P0 settings that we'd like to add into Windows Customization. 

```[tasklist]
### File Explorer P0
- [ ] #2919
- [ ] https://github.com/microsoft/devhome/issues/2921
- [ ] https://github.com/microsoft/devhome/issues/2922
- [ ] Show Compact View
- [ ] Show the details pane for files
- [ ] Use checkboxes to select items
```

```[tasklist]
### Virtual Machine Management P0
- [ ] Windows Sandbox
- [ ] Hyper-V
- [ ] Guarded Host
- [ ] Hyper-V Management Tools
- [ ] Virtual Machine Platform
- [ ] Windows Hypervisor Platform
- [ ] https://github.com/microsoft/devhome/issues/3249
```

```[tasklist]
### Dependencies P0
- [ ] https://github.com/microsoft/devhome/issues/3013
```

```[tasklist]
### General System P0
- [ ] https://github.com/microsoft/devhome/issues/3250
- [ ] https://github.com/microsoft/devhome/issues/2871
```

```[tasklist]
### File Explorer P1
- [ ] https://github.com/microsoft/devhome/pull/2314
```

**Comment by joadoumie** [comment]
@ethanfangg - I added File Explorer Version Control integration here so we can see all changes going into WC broadly.

**Comment by nieubank** [comment]
@joadoumie - with the merge today, most of these are now in. The additional file explorer options will require some private API related negotiations so I'm not sure I would consider them as P0. I'm not planning on doing that work myself in the near term at least.
