### ISSUE TITLE
Dev Box creation not showing pools

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#2924]
### Steps to reproduce the bug

Go to create environment and select Dev Box,
Select project and try to find a pool under the project

### Actual result

Video: https://microsoft-my.sharepoint.com/:v:/p/jiayanchen/EeCLfXHFKWdMpiHxKckgfFEBb11pIgqR3HT2a6dB5gg7LA?e=NM5e2h&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D
Log file: https://microsoft-my.sharepoint.com/:u:/p/jiayanchen/EY1M_8K8pE9MgcxUfib44rkBI2lMlk2c8uELFtcPVnuLbw?e=7zwKeu

**Comment by huzaifa-d** [comment]
@jiayac Can you repro this in the latest canary?
