### ISSUE TITLE
Dev Drive Insights blocks Dev Home UI when moving a package cache

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhome#2925]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.26217.5000

### Other software

OS Build Version: 10.0.26217.5000.amd64fre.ge_current_directadept.240509-1700
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

On a system with a large .NET NuGet package cache (in my case, I had 7.5 GB of packages on the C:\ drive):

1. Navigate to Dev Drive Insights and choose a new folder to move the packages to on an existing Dev Drive
2. Confirm and make the change

### Expected result

I expected that the Dev Home UI would remain responsive and perhaps show progress if the operation were long-running.

### Actual result

The copy took a few minutes, and the Dev Home UI was not responsive to input for that duration. 

![Image](https://github.com/microsoft/devhome/assets/8368026/b2d760b7-85ae-493b-928f-92c16b3fb927)

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
Physical Memory: 31.83GB (16.9GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHomeGitHubExtension_0.1300.477.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1400.500.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by zadjii-msft** [comment]
Yea, it needs to do this on a background thread, and show a progress bar of some sort to show it's working. I got spooked that I had destroyed my cargo setup 😨
