### ISSUE TITLE
Enumerating dev boxes takes 30 seconds after app first launches.

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#2932]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.22631.3296

### Other software

OS Build Version: 10.0.22631.3296.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Enumerating dev boxes takes 30 seconds after app first launches. Then it is down to 10 seconds. Several repeated restarts show the same behavior.

### Expected result

<10 seconds.

### Actual result

30 seconds

### Included System Information

CPU: Intel(R) N200
Physical Memory: 7.83GB (2.71GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.450.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment]
This was fixed in https://github.com/microsoft/DevHomeAzureExtension/pull/168
