### ISSUE TITLE
Configuration errors observed when trying to clone a new repository onto an existing cloud dev box

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhome#2942]
### Dev Home version

0.1401.501.0

### Windows build number

10.0.26220.5000

### Other software

OS Build Version: 10.0.26220.5000.amd64fre.ge_current_directadept.240514-1700
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

In Dev Home, with a pre-existing cloud dev box set up:
1. Navigate to the "Set up an environment" flow in the machine configuration page.
2. Select the pre-existing cloud dev box
3. Click 'Add repository'
4. I entered in the clone path that I wanted on the dev box (e.g., C:\users\myalias\source\repos) and gave it the URL to the DevHome GitHub repository

### Expected result

I was expecting that the flow would complete and the repos would be cloned as expected.

### Actual result

I got back an error from winget with trying to apply a few packages (see screenshot). The logs also indicated that there was some sort of error installing Powershell (because it already exists)- I don't think I knowingly selected to install that, though.

![Image](https://github.com/microsoft/devhome/assets/8368026/ebe858d7-4bf0-4a09-9875-549828dfb054)

[2024/05/16 11:22:56.349 INF] (LoadingViewModel) Starting all tasks
[2024/05/16 11:22:56.352 INF] (ConfigureTargetTask) Starting configuration on adityar-razzle
[2024/05/16 11:23:12.914 INF] (ConfigureTargetTask) Ignoring configuration unit pending state.
[2024/05/16 11:25:14.968 ERR] (ConfigureTargetTask) Target experienced an error while applying the configuration: Short error description: [2024-05-16T18:23:09.430641+00:00] PowerShell 7 is already installed 
Detailed error description:  

[2024/05/16 11:25:30.104 INF] (ConfigureTargetTask) Configuration stopped

### Included System Information

CPU: AMD Ryzen Threadripper PRO 3945WX 12-Cores     
Physical Memory: 63.86GB (47.63GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
9932MartCliment.WingetUIWidgets_0.5.0.0_x64__g91dtg5srk15g (WingetUI Widgets (Preview))
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1400.500.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.501.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome.Canary_0.1401.501.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.501.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by dhoehna** [comment]
@AmelBawa-msft I think this might be a configuration issue?  `CloneRepositoryAsync` in `GenericProvider` is not invoked when the repo is cloning.

@bbonaby how does the environment flow clone repositories?

**Comment by huzaifa-d** [comment]
Unable to repro this. @adrastogi are you able to repro this through the latest preview? Also, please provide the logs from C:\Users\<UserName>\AppData\Local\Packages\Microsoft.Windows.DevHomeAzureExtension.<Canary/Dev>_8wekyb3d8bbwe\TempState if you are able to repro.

And the "Powershell already installed" isn't an error. It is just logging that specifies that the dependent PowerShell module is already installed.

**Comment by adrastogi** [comment]
Thanks, @huzaifa-d; I hit what I think are some unrelated errors initially (related to the state of the dev box), but eventually was able to repro.

![Image](https://github.com/user-attachments/assets/b723100e-cf08-40f6-b911-6875592f3687)

Will follow up separately regarding the logs.

**Comment by huzaifa-d** [comment]
Unable to repro this/logs have nothing worthwhile. Will have to work offline with @adrastogi to figure this one out.

**Comment by huzaifa-d** [comment]
Confirmed offline; no repro in latest version.
