### ISSUE TITLE
Quick Start dialog for AI key is a white box and not actionable.

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2949]
### Dev Home version

0.1401.501

### Other software

I tried to use QS with my current PC but the AI screen has no UI and I could not do anything.
I am guessing it maybe a memory issue on my PC.

![image](https://github.com/microsoft/devhome/assets/2146880/c30fc52d-0dcc-4709-8092-77a7e886dff7)

### Steps to reproduce the bug

Run DevHome and choose to run QuickStart

### Actual result

see above image.
logs attached
[2024-05-16DevHome.Zip](https://github.com/microsoft/devhome/files/15340421/2024-05-16DevHome.Zip)

**Comment by adrastogi** [comment]
Thanks! We haven't seen this before. You mention a possible memory issue, so if for example you closed some other programs, did the problem still reproduce?

Is that the complete set of logs in the .zip? Based off the timestamps, there aren't many recent log files in that folder (e.g., most are from before 5/8, with the exception of some sandbox extension logs); wondering if some got left behind? I don't see any hits for our providers in there.
