### ISSUE TITLE
After adding user to Hyper-V administrators group "Restart now" button doesn't do anything.

### ISSUE THREAD

**Issue by sshilov7** [microsoft/devhome#2954]
### Steps to reproduce the bug

On a device with Hyper-V manager enabled but with a user who is not a member of "Hyper-V administrators" group:
In Dev Home go to Environments view. There should be a warning that the user is not a member of "Hyper-V administrators" group:

![image](https://github.com/microsoft/devhome/assets/51001703/fbc7aef8-e1f9-4757-9e3d-3dfab01aaab4)

Click "Add user to group"
After that you should see notification to restart the device:

![image](https://github.com/microsoft/devhome/assets/51001703/9408820c-d2db-402c-8943-0ae4d456c84a)

Click "Restart now"

Video:

https://github.com/microsoft/devhome/assets/51001703/e5f00d7b-9da5-4755-8305-c5e7f2c0aede

### Expected result

Device restarted.

### Actual result

Nothing happens.

**Comment by huzaifa-d** [comment]
No repro on the latest preview version.
