### ISSUE TITLE
Dev home does not refresh Dev Box Status after machine start

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#2976]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.22635.3640

### Other software

OS Build Version: 10.0.22635.3640.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

I have a stopped dev box. 
I start the dev box
Connect to the dev box.
Click on Configure Environment.
Add a winget package to the dev box I started.

### Expected result

Periodically refresh the dev box status and updated it in all parts of dev home and do not fail winget install.

### Actual result

Dev Home reports an error the dev box is not started.
![image](https://github.com/microsoft/devhome/assets/5457010/21b244b2-2188-4183-b37d-05256593c3c8)
![image](https://github.com/microsoft/devhome/assets/5457010/73572ae9-1c1b-4440-944c-865a6c524f1b)

After manual resync
![image](https://github.com/microsoft/devhome/assets/5457010/e519b286-55a2-4076-8e0b-3e1c6f668366)
![image](https://github.com/microsoft/devhome/assets/5457010/e5077b83-3b90-4588-b603-cc92f419b72c)

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (22.33GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment]
Fixed in the PR above.
