### ISSUE TITLE
Dev Home failed to apply winget package on my dev box

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#2977]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.22635.3640

### Other software

OS Build Version: 10.0.22635.3640.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Not clear why this failed.
It is an older dev box.

### Expected result

Install Notepad++

### Actual result

Error. See logs.
[devhome.zip](https://github.com/microsoft/devhome/files/15390510/devhome.zip)

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (22.19GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment]
Unable to repro. Also, please provide the Azure extension logs from 
C:\Users\<UserName>\AppData\Local\Packages\Microsoft.Windows.DevHomeAzureExtension.<Canary/Dev>_8wekyb3d8bbwe\TempState
