### ISSUE TITLE
Dev Home takes 40-60 seconds before starting to apply a winget package to a dev box.

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#2980]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.22635.3640

### Other software

OS Build Version: 10.0.22635.3640.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Try to install notepad++ or another config and it takes Dev Home 40-60 seconds before starting to apply a winget package to a dev box.
It takes Dev Home 40-60 seconds before starting to apply a winget package to a dev box.
It should take a few seconds for the Dev Home request to be send to the dev center and routed to the correct Dev Box. 
The windows app can connect to a dev box in 5-10 seconds. A package install should start in the same amount of time.

### Expected result

It should take a few seconds for the Dev Home request to be send to the dev center and routed to the correct Dev Box. 
The windows app can connect into a dev box in 5-10 seconds. A package install should start in about the same amount of time.

### Actual result

It takes Dev Home 40-60 seconds before starting to apply a winget package to a dev box.

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (22.17GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment]
This is the expected behavior since Dev Box takes time for initializing. A bug will have to be logged with the Dev Box team responsible for configuration to speed this up, if needed.
