### ISSUE TITLE
No access to DevBoxes despite being in Hyper-v group

### ISSUE THREAD

**Issue by assyrus-favolo** [microsoft/devhome#2989]
### Dev Home version

0.1401.505.0

### Windows build number

10.0.19045.3930

### Other software

OS Build Version: 10.0.19045.3930.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

1. Add yourself to Hyper-V group (and reboot)
2. Open "Enviornments"

### Expected result

I should be able to see my virtual machines after adding myself to the Hyper-V group

### Actual result

An error message appears saying this:
```
Microsoft Dev Box
Unable to retrieve all Dev Boxes for
<my-email>. DevBoxHttpRequest failed:
Forbidden {"errori':
provide below
info when asking for support: timestamp =
correlationld b6ef3c46-
cc79-44ce-a6cO-20931 eadf87c.
is denied to the
requested resource. The user might not have enough
permission."}])}
```

### Included System Information

CPU: Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz
Memoria fisica: 15.88GB (2.75GB free)
Architettura processore: x64

### Included Extensions Information

Estensioni: 
Microsoft.Windows.DevHomeAzureExtension_0.900.505.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Estensione widget principale)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Estensione Hyper-V)
Microsoft.Windows.DevHomeGitHubExtension_0.1400.505.0_x64__8wekyb3d8bbwe (Estensione Dev Home GitHub (Anteprima))
9932MartCliment.WingetUIWidgets_0.2.0.0_x64__g91dtg5srk15g (WingetUI Widgets (Preview))

Servizio widget: 
Microsoft.WidgetsPlatformRuntime_1.3.0.0_x64__8wekyb3d8bbwe

**Comment by huzaifa-d** [comment]
Access to Dev Box depends on your admin. Do you see any dev boxes on the web portal at devbox.microsoft.com?

**Comment by assyrus-favolo** [comment]
> Access to Dev Box depends on your admin. Do you see any dev boxes on the web portal at devbox.microsoft.com?

Thank you and sorry for the delay, I've been away.  
Anyways, yes, I can't access anything on devbox.microsoft.com, as you say, it tells me to contact the administrator to gain access.  
Is [this](https://learn.microsoft.com/en-us/azure/dev-box/quickstart-configure-dev-box-service) the right documentation for the admin to enable it?

**Comment by huzaifa-d** [comment]
@assyrus-favolo yes, that would be the right documentation.
