### ISSUE TITLE
Can't change api key in quickstart-playground

### ISSUE THREAD

**Issue by Abdulbaqi-Alshareef** [microsoft/devhome#2996]
### Dev Home version

0.1401.505.0

### Windows build number

10.0.22631.3593

### Other software

OS Build Version: 10.0.22631.3593.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

After entering the OpenAI api key I can't change it

### Expected result

I should be able to change it

### Actual result

There is no way to change the api key

### Included System Information

CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Physical Memory: 15.84GB (4.53GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1400.505.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.900.505.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.10.0_x64__cw5n1h2txyewy

**Comment by adrastogi** [comment]
Thanks for trying out Quickstart Playground! It's a bit tucked away, but there's a control for resetting the API key in the settings for the Azure extension. 

If you click on `Extensions` on the lower-left side of the navigation menu, and then click on the entry for the Dev Home Azure Extension, you'll see a dropdown that looks like the below:

![Image](https://github.com/microsoft/devhome/assets/8368026/bc30f963-ce22-4bdb-8bc9-c9772a206423)

You can click on that bottom half, and you'll be taken to a page with a button you can click on to clear the key.

![Image](https://github.com/microsoft/devhome/assets/8368026/9e96c315-cb9d-410d-a836-c1cf7c6f576f)

We have this documented here as well: https://learn.microsoft.com/en-us/windows/dev-home/quickstart-playground#troubleshooting

Once the key has been cleared, navigating back to the Quickstart Playground page will prompt you to enter in a new one. 

Let me know if that helps.

**Comment by Abdulbaqi-Alshareef** [comment]
Thanks @adrastogi, that's resolved my issue
