### ISSUE TITLE
Add an option to scan for or add Existing Repos

### ISSUE THREAD

**Issue by TheEndHunter** [microsoft/devhome#2998]
### Suggested new feature or improvement

Have options for scanning a directory for existing repos and for also adding existing repos into the program

### Scenario

this would allow people who already have there repos downloaded and configured to just add them straight to dev home.

**Comment by shakersMSFT** [comment]
Hi, please take a look at this issue: https://github.com/microsoft/devhome/issues/2161 and let us know if this would align with your ask. Thanks!

**Comment by TheEndHunter** [comment]
> Hi, please take a look at this issue: https://github.com/microsoft/devhome/issues/2161 and let us know if this would align with your ask. Thanks! 

Yes this is probably what is needed, as there is also no way to monitor or know which repos you already have.
