### ISSUE TITLE
Terminate the target process, restart it, PI shows (terminated) multiple times

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3027]
### Dev Home version

0.503

### Windows build number

10.0.22631.3672

### Steps to reproduce the bug

1. Run PI, and associate with some app.
2. Go to Expanded mode
3. Terminate the target process.
4. See we append (terminated).
5. Restart the target app, and associate PI with it (via process list or hotkey)
6. Terminate the target process again.
7. See we append (terminated) (terminated)
8. 

### Actual result

(terminated) is repeated.
![terminated-terminated](https://github.com/microsoft/devhome/assets/30507740/14c9cdef-364c-43c3-a6a1-29c51f5fbbea)

**Comment by zadesai** [comment]
No repro
