### ISSUE TITLE
On startup, the standard chrome buttons are missing

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3053]
### Dev Home version

0.503

### Windows build number

10.0.22631.3672

### Steps to reproduce the bug

This doesn't always happen, but about half the time, when I start PI, the chrome buttons are present but not visible. If you hover over them, they show highlighted, but not otherwise. The buttons don't become visible until you expand/collapse.

### Actual result

Chrome buttons not visible
![missing-chrome](https://github.com/microsoft/devhome/assets/30507740/c0b0a788-7e49-4611-85ff-3b650ad88ab4)

**Comment by timkur** [comment]
Only repros in dark mode. Not in light mode. Not in default mode even if personalization is dark.

**Comment by andreww-msft** [comment]
No improvement from latest fixes. Now I'm seeing this 100% of the time (in dark mode) even when in expanded mode.
