### ISSUE TITLE
GPU performance counter is not reporting correct values

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3058]
### Dev Home version

0.503

### Windows build number

10.0.22631.3672

### Steps to reproduce the bug

1. Run any app that uses GPU, eg any DirectX app.
2. Target PI to this app
3. See that TaskManager reports some GPU usage
4. See that PI always reports zero GPU usage

### Actual result

PI always reports zero GPU usage.

**Comment by xhan65** [comment]
Investigating
