### ISSUE TITLE
[Investigation & Dev Design] Review of all-up UI/UX workflows, leveraging DevHome, etc

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3089]
### Suggested new feature or improvement

PI has evolved organically, and has gone through multiple prototypes. Some existing UX behaviors are from early prototypes which might not be appropriate any more. Conversely new features have been added into the existing model, and might warrant some redesign. PI has also evolved as a separate app from DevHome proper, and has then increasingly been folded into DevHome. It's possible that some pieces should be in DevHome core rather than in PI. Does PI need its own expanded window and its pages, or should these be hosted in DevHome's window? What are the trade-offs in terms of performance, reliability, risk of crashing DevHome, etc?

### Scenario

This is a long-term architecture issue - however we decide to refactor, we must not negatively impact usability or any functional requirements of either DevHome proper or PI.

**Comment by timkur** [comment]
Investigation is done, UR study is done, we'll open individual work items for each change.
