### ISSUE TITLE
PI horizontal/vertical bar implementation needs cleaning up

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3099]
### Suggested new feature or improvement

BarWindowHorizontal seems to be mostly implemented, but BarWindowVertical is missing some pieces. Also, there's a lot of common code between the two, which suggests that perhaps there should be a common ancestor class.

Also consider ViewStateManager model as an alternative approach instead of two separate window classes.

### Scenario

Consider re-designing the bar window, as part of the all-up UI design investigations.

**Comment by timkur** [comment]
After moving the code of out of the code models for both external tools and snapping, things are looking in reasonable shape. I don't think there is anything more we would want to do in the short term.
