### ISSUE TITLE
When logged in both my MSA and Azure AD account, I could not see any Dev Box from my Azure AD account any more

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#3100]
### Steps to reproduce the bug

1. Login both Azure AD and MSA Account on Dev Home
2. Go to environment tab and hit refresh
3. No Dev Box ever shows up any more

### Actual result

![image](https://github.com/microsoft/devhome/assets/65691598/d9a0cece-04b8-4165-8aaf-3f50e9e1ff00)

**Comment by huzaifa-d** [comment]
So, this one was a little tricky to track. We have tested multiple accounts and didn't encounter any issues. But I believe that the default user here is the .edu one. And the other account, which has the dev boxes configured, is secondary. As such, it probably requires logging in again. 
@jiayac could you help verify this in your repro - when you get to the stage shown in your screenshot above, please close the error shown using the X on the top right of the error popup UI. You should be able to see the actual issue as to why the other account's dev boxes aren't showing up.

**Comment by jiayac** [comment]
I reproduced the issue. After I close the error, nothing is showing up.

**Comment by jiayac** [comment]
![image](https://github.com/microsoft/devhome/assets/65691598/531cd7ae-c222-47f6-b162-d37f9d08e92b)

**Comment by jiayac** [comment]
Also a note, I could still see my Dev Boxes with multiple accounts in the setup environment flow but not in the environments page.
