### ISSUE TITLE
Customization of Dev Box Consistently failing

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3104]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.22635.3646

### Other software

OS Build Version: 10.0.22635.3646.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Open Machine Configuration
Click Setup an environment
Click a dev box and click next
Skip adding a repo
Click + on an app. I used Notepad++.
Click next 
Agree and click setup.

### Expected result

Add notepad++ to dev box.

### Actual result

[CoreWidgets.zip](https://github.com/user-attachments/files/15540478/CoreWidgets.zip)

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (15.53GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment]
No repro. Also please add the logs from C:\ProgramData\Microsoft\DevBoxAgent\LogsC:\Users\<UserName>\AppData\Local\Packages\Microsoft.Windows.DevHomeAzureExtension.<Canary/Dev>_8wekyb3d8bbwe\TempState
