### ISSUE TITLE
[Environments reliability] Hyper-V Operations: Can't add standard user account to Hyper-V Administrator group if elevating using a separate administrator account

### ISSUE THREAD

**Issue by hollowdrutt** [microsoft/devhome#3112]
### Dev Home version

0.1401.505.0

### Windows build number

10.0.22635.0

### Steps to reproduce the bug

* On my computer I have one standard user account and one administrator user account.
* When I run Dev Home as standard user and try to create an environment I get the message "The current user is not in the Hyper-V administrators group."
* I click the "Add user to group"-button, get a UAC prompt asking for an administrator account, I authenticate with my administrator account, the error message about "The current user is not in the Hyper-V administrators group." disappears.

### Expected result

My user is added to Hyper-V administrators group and I am able to create an environment.

### Actual result

When I once again try to create an environment I get the same message "The current user is not in the Hyper-V administrators group.".
When I start lusrmgr.msc and look in the Hyper-V Administrators group only my administrator account is added to it, probably because the PowerShell script adds my administrator account instead of my user account to Hyper-V Administrator group.

**Comment by huzaifa-d** [comment]
Fix not working in latest canary. Will need to investigate.
