### ISSUE TITLE
PI use Application.Current.GetService<Window>().DispatcherQueue

### ISSUE THREAD

**Issue by zadesai** [microsoft/devhome#3120]
### Steps to reproduce the bug

[krschau](https://github.com/krschau) [yesterday](https://github.com/microsoft/devhome/pull/3094#discussion_r1624765673)
This is going to be null when not running on the UI thread (which this isn't guaranteed to be doing). Use
var dispatcherQueue = Application.Current.GetService<DispatcherQueue>();
or
var dispatcherQueue = Application.Current.GetService<Window>().DispatcherQueue;
like here https://github.com/microsoft/devhome/pull/2934
(I'm not actually sure if one is preferred... @nieubank?)

### Actual result

-

**Comment by timkur** [comment]
Won't fix.
