### ISSUE TITLE
Dev Boxes that are not pinned to the start menu show an "unpin" option

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3121]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.22635.3646

### Other software

OS Build Version: 10.0.22635.3646.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Open Environments
Click the ... next to a dev box

### Expected result

For a dev box that is not pinned to the start menu or the task bar it should say "pin"

### Actual result

Currently the menu command says "unpin".

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (14.29GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by acangialosi** [comment]
Hi Branden. Just confirmed on a newer build. This time Preview channel with latest dev home and matching azure extension.
For the dev box in the screenshot below I have not pinned this dev box ever on my machine. 

![image](https://github.com/microsoft/devhome/assets/5457010/2d1adbca-c31e-4eb4-a36e-d6aa6d8fe433)
![image](https://github.com/microsoft/devhome/assets/5457010/98288d05-35b3-4ce7-8141-367d336d8851)
![image](https://github.com/microsoft/devhome/assets/5457010/8144b26a-f24e-4acd-9a88-a28d57d337d1)

**Comment by huzaifa-d** [comment]
Fixed in the PR mentioned above.
