### ISSUE TITLE
[Environments reliability] Dev Box operations: Pin to start menu fails

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3122]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.22635.3646

### Other software

OS Build Version: 10.0.22635.3646.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Open Environments
Click on ... next to a dev box. 
Click "unpin from start menu"

### Expected result

Menu text is correct and there is no failure. No Failure

### Actual result

An error surfaces. 
![image](https://github.com/microsoft/devhome/assets/5457010/f2e160f8-22d6-4944-b6df-fd50c1ef8e25)

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (14.54GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment]
Verified in the latest preview version as working; confirmed with team and closing.
