### ISSUE TITLE
Cannot create dev box. Dev Home does not find pools associated with project

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3125]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.22635.3646

### Other software

OS Build Version: 10.0.22635.3646.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Click create environment
Click dev box
Name your dev box
Pick a project

### Expected result

A list of pools appears

### Actual result

No list of pools is populated.

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (15.51GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by acangialosi** [comment]
This stopped reproducing this morning and then repro'd against later in the day. I had restarted Dev Home to prep for demos and then had it running for 1-2 before delivering the demo. I wonder if there is a timeout and we aren't getting a new access token.

**Comment by acangialosi** [comment]
Uploading Recording 2024-07-03 025020.mp4…


Uploading Recording 2024-07-03 025020.mp4…

**Comment by acangialosi** [comment]
Uploading Recording 2024-07-03 025020.mp4…

**Comment by huzaifa-d** [comment]
This was fixed in the latest canary. Please re-open if you have a repro.

**Comment by krschau** [comment]
@huzaifa-d If this was fixed in 0.16 it would be great if you could have changed the milestone of this item to reflect that, and put a "resolution" label on it.
