### ISSUE TITLE
Can't add standard user account to Hyper-V Administrator group on computer with Swedish installation of Windows 

### ISSUE THREAD

**Issue by hollowdrutt** [microsoft/devhome#3128]
### Dev Home version

0.1401.505.0

### Windows build number

10.0.19045.4412

### Steps to reproduce the bug

* I use a computer with Swedish language Windows installed
* When I run Dev Home as standard user and try to create an environment I get the message "The current user is not in the Hyper-V administrators group."
* I click the "Add user to group"-button, get a UAC prompt asking for an administrator account, I authenticate with my administrator account

### Expected result

* The error message about "The current user is not in the Hyper-V administrators group." disappears.
* The user is added to the Hyper-V Administrator group

### Actual result

I get an error message "Unable to add the user to the Hyper-V administrators group or enable Hyper-V. Hyper-V virtual machines may not load. To resolve the issue manually, add the user to the Hyper-V administrators group, enable Hyper-V and reboot"

Probably because the PowerShell script refers to the group by name 'Hyper-V Administrators ' but on my computer the group is called 'Hyper-V-administratörer' 
https://github.com/microsoft/devhome/blob/f9e5ae2f0e7b5db345322fa28c5e1a9c288d1147/common/Environments/Scripts/HyperVSetupScript.cs#L85

**Comment by Natriss** [comment]
![Image](https://github.com/user-attachments/assets/35e1f12d-94a5-4318-abf1-622aa0663976)

I still have this issue
