### ISSUE TITLE
Dev Home is missing region information in dev box pool drop down

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3129]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.22635.3646

### Other software

OS Build Version: 10.0.22635.3646.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Create a new dev box
Expand the dev box pool control

### Expected result

Region is shown

### Actual result

Region is missing. A user can't tell where their dev box will get created unless the admin happened to put it in the pool name. The region has a significant effect on the dev box user experience.
You can see for Devdiv's basic project the pool names appear in the dev home on the right but the region is also show in the drop down for dev portal on the left.

![image](https://github.com/microsoft/devhome/assets/5457010/ac907353-b024-4d0a-9913-e06cbd767a8e)

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (17.61GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment]
Fixed in the PR above.

**Comment by huzaifa-d** [comment]
Fixed in the PR above.

**Comment by jiayac** [comment]
![image](https://github.com/user-attachments/assets/f992f0af-1a2b-4338-93d9-4323d5280090)
Reopening since I still could not see the region in Dev Box creation flow.

**Comment by krschau** [comment]
@jiayac Did you mean to reopen this? I'll do it.

**Comment by huzaifa-d** [comment]
Please confirm that the DevHome version you are using is 0.1701 or greater.

**Comment by krschau** [comment]
Closing since from the screenshot, @jiayac could not have been using the right Preview version on the day they left their comment.
