### ISSUE TITLE
Enabling admin for environments detached my dev drive.

### ISSUE THREAD

**Issue by azchohfi** [microsoft/devhome#3135]
### Dev Home version

0.1401.505.0

### Windows build number

10.0.22631.3672

### Other software

OS Build Version: 10.0.22631.3672.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

Literally just enabled admin for environments, and after reboot my dev drive was "gone". Just had to re-attach it.

### Expected result

Dev drive stays how it was.

### Actual result

Dev drive detached.

### Included System Information

CPU: Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz
Physical Memory: 63.59GB (49.84GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
9932MartCliment.WingetUIWidgets_0.5.0.0_x64__g91dtg5srk15g (WingetUI Widgets (Preview))
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1400.505.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.900.505.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.10.0_x64__cw5n1h2txyewy

**Comment by p4nu** [comment]
This apparently happens to me every time I restart the computer.

**Comment by adrastogi** [comment]
Related discussion in #1903. 

@azchohfi / @p4nu thanks for the reports here. 

If you are still experiencing this issue, would you mind filing feedback through the Feedback Hub under the Developer Platform -> Dev Drive category? There's an option for sharing the link to the report, which you can paste here. Thank you!
