### ISSUE TITLE
Dev Home is not using display name for dev box project

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3141]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.22635.3646

### Other software

OS Build Version: 10.0.22635.3646.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Click on Create environment. 
Click Dev Box
Expand projects

### Expected result

Dev Home should use the display name property and not the resource name for a Dev Box project. The resource name has restrictions like no spaces and length limits. Display name is more flexible.

### Actual result

Uses resource name. 

![image](https://github.com/microsoft/devhome/assets/5457010/2879ecdc-ae0f-4c30-8de7-754fdc580974)

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (17.27GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment]
Not sure what the ask is here since the JSON returned by the API doesn't have said fields. There is a Tags->FriendlyName field. Is that what you require?

**Comment by huzaifa-d** [comment]
Fixed in the PR above.
