### ISSUE TITLE
PI bar is missing icons on Windows 10

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhome#3146]
### Dev Home version

0.1501.522.0

### Windows build number

10.0.19045.4412

### Other software

OS Build Version: 10.0.19045.4412.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

In Dev Home on Windows 10, with Project Ironsides enabled:
1. Launch the feature without elevation

### Expected result

Project Ironsides toolbar shows up, complete with icons.

### Actual result

The icons appear to be placeholders

![Image](https://github.com/microsoft/devhome/assets/8368026/442ccf8d-f4ae-4aab-b7b5-80545bbfef55)

(I don't see this on Windows 11, for comparison)

### Included System Information

CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
Physical Memory: 15.93GB (8.29GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.1501.522.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1501.522.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome.Canary_0.1501.522.0_x64__8wekyb3d8bbwe (Windows Sandbox Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.1000.522.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1500.522.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))

Widget Service: 
Microsoft.WidgetsPlatformRuntime_1.3.0.0_x64__8wekyb3d8bbwe

**Comment by jaholme** [comment]
Looks like we need the DevHomeFluentIcons.ttf to be updated with new icons so we can work on win10.
