### ISSUE TITLE
Learn more link on PI card is incorrect

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#3153]
### Steps to reproduce the bug

Click Learn more on the card in Utilities after enabling Project Ironsides in experimental feature settings

### Expected result

This should take you to Dev Home documentation at a minimum, ideally to Project Ironsides docs once they're published
This link should also use a go.microsoft.com link, not an aka.ms link

### Actual result

This goes to microsoft.com using an aka.ms link

**Comment by andreww-msft** [comment]
Hmm... I'm guessing you're looking at a very old build. This was changed a while back. Here's the PR: https://github.com/microsoft/devhome/pull/3018 , and here's the current code in tools/PI/DevHome.PI/Strings/en-us/Resources.resw

  <data name="SettingsDocumentationLink.Content" xml:space="preserve">
    <value>Documentation</value>
    <comment>Label for the link to the documentation for the product.</comment>
  </data>
  <data name="SettingsDocumentationLink.NavigateUri" xml:space="preserve">
    <value>https://github.com/microsoft/devhome/issues/2796</value>
    <comment>Link to the documentation for the product.</comment>
  </data>
  <data name="SettingsPrivacyPolicyLink.Content" xml:space="preserve">
    <value>Privacy Statement</value>
    <comment>Label for the link to the standard privacy policy statement.</comment>
  </data>
  <data name="SettingsPrivacyPolicyLink.NavigateUri" xml:space="preserve">
    <value>https://go.microsoft.com/fwlink/?linkid=2234882</value>
    <comment>Link to the standard privacy policy statement.</comment>
  </data>
  <data name="SettingsSourceCodeLink.Content" xml:space="preserve">
    <value>Source code</value>
    <comment>Label for the link to the source code for the product.</comment>
  </data>
  <data name="SettingsSourceCodeLink.NavigateUri" xml:space="preserve">
    <value>https://go.microsoft.com/fwlink/?linkid=2234396</value>
    <comment>Link to the source code for the product.</comment>
  </data>

**Comment by cinnamon-msft** [comment]
This is talking about the card in the Utilities page. Here's the code that still has the aka.ms link: https://github.com/microsoft/devhome/blob/71c6700691f4e8fd2252379edc2ee465682a5800/tools/Utilities/src/ViewModels/UtilitiesMainPageViewModel.cs#L57
