### ISSUE TITLE
PI should be called "Project Ironsides" everywhere in the product

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#3155]
### Dev Home version

0.15 Canary 1

### Steps to reproduce the bug

I'm not sure if these are the only places, but the title of the experience should be "Project Ironsides" and not "Dev Home PI" within the title bar and About section
Guidance from branding is we must use the project name until we have a name finalized, so all references to "Dev Home PI" should be replaced with "Project Ironsides":
![image](https://github.com/microsoft/devhome/assets/48369326/9791145e-5d5f-4748-b89b-911a917b9b73)
![image](https://github.com/microsoft/devhome/assets/48369326/16c3bec2-c8c6-47d4-a752-84703a5048d4)

### Expected result

Everywhere should say "Project Ironsides"

### Actual result

"Dev Home PI" appears in the title bar and the About section

**Comment by krschau** [comment]
Should "Project Ironsides" strings also be locked, ie. not localized?

**Comment by cinnamon-msft** [comment]
I think "Project" should probably be localized, but "Ironsides" is more of a proper name
