### ISSUE TITLE
PI forgets small bar layout when switching from large view

### ISSUE THREAD

**Issue by krschau** [microsoft/devhome#3158]
### Dev Home version

0.15 Canary #1

### Steps to reproduce the bug

1. Open PI
2. Switch to Vertical view
3. Switch to Large content panel
4. Switch to small content panel
5. See bar is now Horizontal

### Expected result

Bar should use last small configuration

### Actual result

Bar forgot which layout was using before switching to large

**Comment by andreww-msft** [comment]
We could consider this by-design. That is, when you switch to expanded mode you're also switching to horizontal bar. Then if you later switch back to collapsed mode, you're only switching between expanded/collapsed, but you're not switching horizontal/vertical. Even in expanded mode, you have the option to switch to vertical (in which case it also switches to collapsed). I agree the flows are not symmetric, but that isn't always required. Anyway, needs Design input to figure out the optimal behavior.

**Comment by krschau** [comment]
I definitely was surprised by the behavior. Do we ever expect the user to switch to big mode only to do/check one little thing and quickly switch back? I think losing state there would be unpleasant.

**Comment by andreww-msft** [comment]
Yes, one possible option would be to keep the bar orientation and the expanded/collapsed modes completely decoupled. So if you start collapsed/vertical then go to expanded, you'd still have a vertical bar. Anyway, needs Design input.

**Comment by andreww-msft** [comment]
A related behavior that should be addressed together with this issue:
1. Start with PI in horizontal collapsed mode.
2. Switch to expanded mode.
3. See that the size increases, in particular the width. This is expected.
4. Switch back to collapsed mode.
5. See that the width does not go back to what it was before expanding; instead it remains at the same width as when expanded.

**Comment by timkur** [comment]
This has been fixed.
