### ISSUE TITLE
Cant install application

### ISSUE THREAD

**Issue by nathanlee136** [microsoft/devhome#3174]
### Dev Home version

0.1401.505.0

### Windows build number

10.0.22631.3593

### Other software

OS Build Version: 10.0.22631.3593.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

i was setting up machine configuration by step create repository to install applications 

### Expected result

there should have application for code edit like vscode or GitHub appear

### Actual result

didn't appear any applications

### Included System Information

CPU: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
Physical Memory: 11.78GB (3.65GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1400.505.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.900.505.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.10.0_x64__cw5n1h2txyewy

**Comment by AmelBawa-msft** [comment]
@nathanlee136, thank you for reporting this issue. Can you share a screenshot of the issue and share the logs to better understood the root issue?

/logs
