### ISSUE TITLE
Seperator should be Separator

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3176]
### Steps to reproduce the bug

This PR introduced a new Seperator type: https://github.com/microsoft/devhome/pull/3154. Probably just my OCD, but correct spelling would be Separator.

### Actual result

Seperator misspelled.

**Comment by krschau** [comment]
Good reminder to turn of Visual Studio's spell checker!
![image](https://github.com/microsoft/devhome/assets/47155823/fafc87f1-b77a-4b40-9646-82b65b9bff45)
