### ISSUE TITLE
Built-in utilization widgets not loading

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/devhome#3193]
### Dev Home version

0.1401.505.0

### Windows build number

10.0.22631.0

### Steps to reproduce the bug

1. Keep running in an extended period of time (possibly needs to enable quiet background processes)
2. Remove the widgets
3. Re-add the widgets back

### Actual result

![73c159a778707e3748eafb5fa7944a5e](https://github.com/microsoft/devhome/assets/42881734/3554972f-145b-41a1-abb1-83b1ed478219)

Notice how it consumed 12G RAM for not loading anything 😅

**Comment by krschau** [comment]
Are you saying that you saw this behavior when you added the widgets with "Quiet background processes" turned on?

**Comment by HO-COOH** [comment]
> Are you saying that you saw this behavior when you added the widgets with "Quiet background processes" turned on?

Yes. Then maybe I closed the main window and left the CoreWidgetProvider process running in the background. After a weekend, it's like this.

**Comment by krschau** [comment]
I recently checked in PR #3559 which fixed a scenario with the same symptoms as this one. I'm going to close this as fixed by that, but please let us know if you see it again (in which case, we'll ask for logs because they'll be helpful).
