### ISSUE TITLE
Ensure all icon glyphs used also work on Windows 10

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3194]
### Steps to reproduce the bug

Project Ironsides uses Segoe Fluent Icons, which are available on Windows 11 but not Window 10. Windows 10 uses the older Segoe MDL2 Assets font.

### Expected result

The older Segoe MDL2 Assets are not recommended going forward, so we need to come up with an alternative approach, possibly extending the DevHome fonts.

### Actual result

Segoe Fluent Icons not on Windows 10.

**Comment by HO-COOH** [comment]
Does this mean DevHome is going to be brought to Windows 10? That's a great news!

**Comment by krschau** [comment]
@andreww-msft Is this really a bug? I was under the impression that Segoe MDL2 was expected on Windows 10 (but I obviously definitely could be wrong)

**Comment by andreww-msft** [comment]
Dupe of https://github.com/microsoft/devhome/issues/3146
