### ISSUE TITLE
Learn More should have lowercase 'm' on Utilities and be localized

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#3217]
### Dev Home version

0.1501.529.0

### Steps to reproduce the bug

Navigate to the Utilities page

### Expected result

The "Learn More" links should have a lowercase 'm' to match with the Introducing Dev Home page

### Actual result

"Learn More" uses a capital "M"
![image](https://github.com/microsoft/devhome/assets/48369326/b42dcbf3-9b92-406e-8fee-b651195d79ad)

**Comment by krschau** [comment]
This sting is not localized.
