### ISSUE TITLE
the software is crashing

### ISSUE THREAD

**Issue by mohamed-swalih** [microsoft/devhome#3234]
### Dev Home version

1.0.0.0

### Windows build number

10.0.26120.770

### Other software

OS Build Version: 10.0.26120.770.amd64fre.ge_release.240331-1435
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

when I try to open accounts from the settings.. the software crasher.. I am using this from the standard account of windows instead of administrator account

### Expected result

I was expected to open the accounts tab

### Actual result

software crashed

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
Physical Memory: 15.79GB (8.18GB free)
Processor Architecture: x64

**Comment by krschau** [comment]
@mohamed-swalih Are you experiencing Dev Home crashing, or Windows Settings? Your bug report is unclear -- I'm surprised to see Dev Home version 1.0.0.0 and no Included Extensions, which makes me think this is a crash in Windows Settings. If that is the case, please open your bug in Feedback Hub, as this repo is only for Dev Home issues.
