### ISSUE TITLE
PI: Multimon: switching between minimal UI and full UI caused the app to jump windows

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#3262]
### Steps to reproduce the bug

I was using PI and it started in minimal mode on my secondary monitor.
Then when I jump to full UI, the app jumped to my laptop.
I would have expected it to change modes in same location.

### Expected result

I was using PI and it started in minimal mode on my secondary monitor.
Then when I jump to full UI, the app jumped to my laptop.
I would have expected it to change modes in same location.

### Actual result

I would have expected it to change modes in same location.

**Comment by timkur** [comment]
I believe this has since been fixed. I don't see this behavior anymore.
