### ISSUE TITLE
Account page is not picking up the Azure extension

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#3275]
### Steps to reproduce the bug

Install Azure extension -> Go to account page and try to add account

### Expected result

Able to add my account

### Actual result

![image](https://github.com/microsoft/devhome/assets/65691598/5b77dee6-81ce-414c-9751-2c956a8130da)

**Comment by krschau** [comment]
First, please update to the latest version of Dev Home (generally, it's very helpful if you include a version number in your bug reports. If you open the GitHub issue via the Feedback page in Dev Home, we will do this for you).

If you're still seeing this bug on the latest version, please include the extension information the template asks for -- you can copy this from the Feedback page as well. Please also ensure that you didn't disable the Azure extension in the extensions page.
