### ISSUE TITLE
Ironsides translation in French

### ISSUE THREAD

**Issue by squew** [microsoft/devhome#3285]
### Dev Home version

0.1501.533.0

### 🌐 Language

French

### ❌ Actual phrase(s)

Ironsides is wrongly translated as "Barrière de fer"

### ✔️ Expected phrase(s)

Since Ironsides is a product/feature name, I think this does not need to be translated. And I cannot think of any translation 

### Why is the current translation wrong

Ironsides is translated in French by "Barrière de fer" (so Iron Fences). In that context, this is very weird French for a feature... it would be a perfect name for a military operation though :D

**Comment by krschau** [comment]
Looks like not all instances of "Ironsides" were locked.

**Comment by squew** [comment]
Thanks!
