### ISSUE TITLE
The add new widget button in the Dashboard is not centered

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#3286]
### Dev Home version

0.1501.533.0

### Windows build number

10.0.22621.3737

### Other software

OS Build Version: 10.0.22621.3737.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

Go to the Dashboard.

### Expected result

The add new widget should be centered.

### Actual result

It is not centered

### Included System Information

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Physical Memory: 11.89GB (2.78GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
9932MartCliment.WingetUIWidgets_0.6.1.0_x64__g91dtg5srk15g (Widgets for UniGetUI (formerly WingetUI))
Microsoft.Windows.DevHomeAzureExtension_0.1000.533.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.536.0_x64__8wekyb3d8bbwe (Dev Home Microsoft Game Dev Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

### A screenshot

![image](https://github.com/microsoft/devhome/assets/99239826/fe6ee7d7-d7ca-4cb5-8a04-c1fef363af5a)

**Comment by skanda890** [comment]
Label this as 'Resolution-Duplicate'.

**Comment by krschau** [comment]
> Label this as 'Resolution-Duplicate'.

A "please" would go a long way!

**Comment by krschau** [comment]
Duplicate of #3216
