### ISSUE TITLE
PI sometimes seems to record its collapsed size as its expanded size

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3313]
### Steps to reproduce the bug

Inconsistent repro, but here's the behavior:
1. Start PI. See it starts collapsed.
2. Use the finder tool to associate with a target app.
3. Tap the Expand button.
4. See that it doesn't expand. 
5. I have no evidence, but my suspicion is its expanding to its last saved expanded size, but that we last saved a collapsed size instead.

### Actual result

PI thinks its expanded, but it looks collapsed.

https://github.com/microsoft/devhome/assets/30507740/65dedf36-199a-4663-a339-5df6693d6095

**Comment by jaholme** [comment]
Might be fixed by #3330. Any repro steps Andrew?

**Comment by andreww-msft** [comment]
No repro in latest build.
