### ISSUE TITLE
Process list doesn't align with the title

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3324]
### Steps to reproduce the bug

On all the other pages, the lists or other items line up with the page title.

### Actual result

The list on the process list page is indented ~10-15 px.

**Comment by willibrandon** [comment]
The left margin for the grid and datagrid on the process list page is currently set to 16. All of the other pages have the left margin for the grid and datagrid set to 0.

I can submit a PR for this issue if it isn't already being worked on by somebody else.
