### ISSUE TITLE
Hotkey for Dev Home Project Ironsides not documented

### ISSUE THREAD

**Issue by tpajenkamp** [microsoft/devhome#3339]
### Provide a description of requested docs changes

A new autostart "Hotkey for Dev Home Project Ironsides" was randomly added to my PC. There is no explanation or documentation available what it is useful for and what it has to do with "hotkeys". I cannot even find any feature within Dev Home (unconfigured) that looks related to this.

**Comment by adrastogi** [comment]
Tagging @andreww-msft / @timkur.

**Comment by timkur** [comment]
This is documented.
