### ISSUE TITLE
Accounts page does not refresh when Azure account is signed in/out

### ISSUE THREAD

**Issue by dkbennett** [microsoft/devhome#3357]
### Dev Home version

0.1501.547.0

### Windows build number

10.0.22635.3858

### Other software

OS Build Version: 10.0.22635.3858.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

Go to Settings -> Accounts, add and remove an Azure account.

### Expected result

Account will appear after authorization is complete, and disappear after signing out.

### Actual result

The accounts were successfully signed in/out but the page did not refresh.

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i9-13900KF
Physical Memory: 63.85GB (30.92GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1500.530.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHomeAzureExtension.Canary_0.1000.530.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome.Dev_0.0.0.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Dev_0.0.0.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Dev_0.0.0.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Dev))
Microsoft.Windows.DevHome.Canary_0.1501.547.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1501.547.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.18000.0.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment]
I am not reproing this with Dev Home (Dev) and Azure Extension (Preview) or GitHub Extension (Preview).
