### ISSUE TITLE
Dashboard not refreshing when removing widgets

### ISSUE THREAD

**Issue by guimafelipe** [microsoft/devhome#3360]
### Dev Home version

0.1501.547.0

### Windows build number

10.0.22621.3737

### Other software

OS Build Version: 10.0.22621.3737.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

Add a widget to dashboard and remove it. It will stay in the dashboard but in a frozen state. Navigate out of dashboard page and navigate back to it to see it actually removed.

### Expected result

Widgets removed should not be shown in dashboard.

### Actual result

Widgets stay in the dashboard in a frozen state after being removed. It is needed to navigate away from dashboard page to see the changes in UI.

### Included Extensions Information

Extensions: 
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.536.0_x64__8wekyb3d8bbwe (Dev Home Microsoft Game Dev Extension (Preview))
Microsoft.Windows.DevHome.Canary_0.1501.547.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1501.547.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.1000.549.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.30.0_x64__cw5n1h2txyewy

**Comment by dkbennett** [comment]
I was able to reproduce this as well, it is a refresh issue, the widgets are being removed and are not active after removal.
