### ISSUE TITLE
Title for error is not user friendly. "There was an error retreiving the adaptive card session from the extension"

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#3363]
### Dev Home version

0.1501.547.0

### Windows build number

10.0.22631.3874

### Other software

OS Build Version: 10.0.22631.3874.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

![image](https://github.com/microsoft/devhome/assets/1462282/4e437b43-dae1-4e99-8cb9-d321219083df)
"There was an error retreiving the adaptive card session from the extension"

Having back end display tech be the title for the error is not useful.

### Expected result

useful error title

### Actual result

![image](https://github.com/microsoft/devhome/assets/1462282/4e437b43-dae1-4e99-8cb9-d321219083df)

### Included System Information

CPU: Intel(R) Core(TM) Ultra 7 165H
Physical Memory: 31.64GB (13.35GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1500.530.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHomeAzureExtension.Canary_0.1000.530.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHome.Canary_0.1501.547.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1501.547.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.18000.0.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment]
Similar to #2879
