### ISSUE TITLE
I never asked for Dev Home to be installed

### ISSUE THREAD

**Issue by jamesaepp** [microsoft/devhome#3374]
### Dev Home version

0.1501.533.0

### Windows build number

10.0.19045.4529

### Other software

OS Build Version: 10.0.19045.4529.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

Nothing

### Expected result

Nothing

### Actual result

Somehow this software became installed on my system. I never requested this. I was doing my normal weekly check of `winget update` and noticed this application showed up. Why? How was it installed?

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service:

**Comment by jamesaepp** [comment]
I also noticed when checking in the MS Store for updates there are two other products, "Widgets Platform Runtime" and "Dev Home GitHub Extension (Preview)". Maybe those are clues.

**Comment by jamesaepp** [comment]
Come to think of it....a couple weeks ago I downloaded the Windows SDK installer and I extracted from it _just_ the Orca MSI installer so I could modify an MSI file, but to my recollection I didn't install the SDK in full, nor do I see it in programs & features.

Hoping that helps. Maybe there's some kind of detection mechanism going on? Either way I don't think this behavior should be expected.

**Comment by krschau** [comment]
Dev Home is a system component to enhance the developer experience on Windows. You can uninstall the GitHub Extension if you'd like.

**Comment by jamesaepp** [comment]
> Dev Home is a system component to enhance the developer experience on Windows. You can uninstall the GitHub Extension if you'd like. For more context, see [#1615 (comment)](https://github.com/microsoft/devhome/issues/1615#issuecomment-1856931703).

Respectfully, that doesn't seem like a full answer to me. Is this yet another application Microsoft is force feeding us? I will add that I was using a different system yesterday and noticed it had Dev Home installed too despite it never having any SDKs or similar software from MS installed.

It would be nice of Microsoft to be transparent with us as to why this is being installed. All new code is new attack surface. This needs to be considered with the "security first" approach MS leadership is championing.

**Comment by Marlor** [comment]
Why would you even think about installing a dev tool für EVERYONE?
Especially silent so the devs dont even know of its existence?
Is there a shareholder number in need of pushing? like "lock how many devs use windows"

**Comment by bhupesh98** [comment]
> Why would you even think about installing a dev tool for EVERYONE? Especially silent so the devs dont even know of its existence? Is there a shareholder number in need of pushing? like "lock how many devs use windows"
> 
> For the ones landing here via google like me `Get-AppxPackage -name *DevHome* | Remove-AppxPackage` did help

Though it seems like it uninstalled but I can still see its components taking space in `C:\Program Files\WindowsApps\Microsoft.Windows.DevHome_0.1101.416.0_x64__8wekyb3d8bbwe`. I have no clue how to delete these files as SYSTEM don't allow me to do so. I don't want to fuck it up so I'm scared to do it forcefully as it might break the system. Anyone who knows about, please reply here.

Thanks!
