### ISSUE TITLE
Cancelling the Create Environment flow goes to Machine Config, even if you started in Environments

### ISSUE THREAD

**Issue by krschau** [microsoft/devhome#3395]
### Dev Home version

0.15

### Steps to reproduce the bug

Go to Environments page
Click Create Environment
Click Cancel
See navigation go to Machine Configuration

### Expected result

Navigation should go back to whatever page the user started from

### Actual result

Navigation goes to machine configuration, no matter where you started

**Comment by bbonaby** [comment]
This is by design currently, the create environment button only redirects you to machine configuration and starts the create environment flow.

**Comment by huzaifa-d** [comment]
By design as mentioned by bbonaby.
