### ISSUE TITLE
PI process is started without the user launching it

### ISSUE THREAD

**Issue by kanismohammed** [microsoft/devhome#3412]
### Steps to reproduce the bug

1. Launch Dev Home

### Expected result

PI does not start until it is launched by the user in the Utilities page.

### Actual result

PI launches without the user noticing.

**Comment by kanismohammed** [comment]
![image](https://github.com/user-attachments/assets/58af3bcb-8bb0-4aa4-af6e-df09b8b5c7f5)

**Comment by jaholme** [comment]
Fixed in #3308

**Comment by jaholme** [comment]
If you have that fix and the experimental feature is enabled that is by design to support the Win-F12 hotkey.
