### ISSUE TITLE
Compatibilidad con VSCode Insiders 

### ISSUE THREAD

**Issue by erikh22l18** [microsoft/devhome#3420]
### Suggested new feature or improvement

El creador de Dev Container con IA no detecta la extension cuando se tiene instalado la version Insiders

### Scenario

Los usuarios del VSCode Insider quieren probar estas nuevas caracteristicas

**Comment by adrastogi** [comment]
Thanks, @erikh22l18! The extension should detect VS Code Insiders if you have it available when it's doing its dependency checks (you can see the implementation of that [here](https://github.com/microsoft/DevHomeAzureExtension/blob/main/src/AzureExtension/QuickStartPlayground/DependencyUIController.cs), so this might be a bug. If you run `where code-insiders.cmd` from a command prompt, what path gets reported?

**Comment by krschau** [comment]
Bing Translator: 

Compatibility with VSCode Insiders

The AI Dev Container builder does not detect the extension when the Insiders version is installed

VSCode Insider users want to try out these new features

**Comment by adrastogi** [comment]
@erikh22l18 can you please let me know the output of running `where code-insiders.cmd`? Thanks!
