### ISSUE TITLE
Falsch GPU anzeige im Dashboard

### ISSUE THREAD

**Issue by Karotte123** [microsoft/devhome#3422]
### Dev Home version

0.1501.533.0

### Windows build number

10.0.22631.3880

### Other software

OS Build Version: 10.0.22631.3880.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

Im Falle zweier Grafikkarten (in meinem Falle eine NVIDIA GeForce RTX 3060Ti und einer Intel(R) UHD Graphics 770) werden die Auslastungen vertauscht sein

### Expected result

die Auslastung meiner RTX 3060Ti

### Actual result

die Auslastung der RTX 3060Ti Graphikkarte wird stattdessen bei der Intel 770 angezeigt

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i5-12600K
Physischer Speicher: 15.78GB (8.97GB free)
Prozessorarchitektur: x64

### Included Extensions Information

Erweiterungen: 
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget-Erweiterung)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V-Erweiterung)
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (Dev Home-GitHub-Erweiterung (Vorschau))

Widgetdienst: 
MicrosoftWindows.Client.WebExperience_524.16300.20.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment]
Bing translator:

Incorrect GPU display in dashboard #3422

In the case of two graphics cards (in my case an NVIDIA GeForce RTX 3060Ti and an Intel(R) UHD Graphics 770), the loads will be reversed

the utilization of my RTX 3060Ti

the RTX 3060Ti graphics card load is displayed on the Intel 770 instead

**Comment by krschau** [comment]
Duplicate of #2800
