### ISSUE TITLE
PI can't start Spy++

### ISSUE THREAD

**Issue by davidegiacometti** [microsoft/devhome#3423]
### Dev Home version

0.1501.533.0

### Windows build number

10.0.19045.4651

### Other software

OS Build Version: 10.0.19045.4651.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

- Launch PI (not elevated)
- Configure Spy++ (`C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\spyxx_amd64.exe`) as new tool
- Try to launch Spy++

### Expected result

Spy++ launched as expected

### Actual result

Spy++ failed to launch with error `740 ERROR_ELEVATION_REQUIRED`.

```
[2024/07/12 14:27:39.070 ERR] (ExternalTool) Tool launched failed
System.ComponentModel.Win32Exception (740): An error occurred trying to start process 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\spyxx_amd64.exe' with working directory 'C:\Windows\System32'. The requested operation requires elevation.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at DevHome.PI.Helpers.ExternalTool.Invoke(Nullable`1 pid, Nullable`1 hwnd)
```

**Comment by jaholme** [comment]
@davidegiacometti thanks for this bug report.  PI's external tool integration is currently evolving, we'll be addressing some of these issues in the next monthly update of DevHome.  In the meanwhile you can launch PI elevated from the DevHome > Utilities page to avoid these issues.
