### ISSUE TITLE
Environments

### ISSUE THREAD

**Issue by RX0327** [microsoft/devhome#3432]
### Dev Home version

0.1501.533.0

### 🌐 Language

英文

### ❌ Actual phrase(s)

Environments

### ✔️ Expected phrase(s)

环境

### Why is the current translation wrong

汉化不完全

**Comment by krschau** [comment]
It sounds like you're saying that not everything is translated from English to Chinese. Could you please be more specific about which places? You can also wait for the next version to be released, which may have more translations.
/needinfo
