### ISSUE TITLE
Preview v0.16 installer is missing

### ISSUE THREAD

**Issue by stamminator** [microsoft/devhome#3459]
The [v0.1601.561.0 release](https://github.com/microsoft/devhome/releases/tag/v0.1601.561.0) is missing the installer file in the list of assets. Prior releases have them.

Also, the [Microsoft Store listing](https://apps.microsoft.com/detail/9n8mhtphngvv) doesn't say what version you're installing, even though that info is available in via winget.

```
> winget search --id "Microsoft.DevHome"
Name               Id                Version      Source
---------------------------------------------------------
Dev Home (Preview) Microsoft.DevHome 0.1501.533.0 winget
PS C:\Users\jstamm>
```

**Comment by krschau** [comment]
We can't change how the Store works but I believe the installer should be available from the GitHub page at some point soon. There are sometimes issues with uploading to GitHub, and we'd prefer not to delay posting the release because of them. (@cinnamon-msft)

**Comment by stamminator** [comment]
@krschau @cinnamon-msft It's still not there. It might be no coincidence that this deploy happened curing the CrowdStrike outage. Maybe some automated build steps failed because of that. Can you guys manually retrigger the build steps that add the installer .msixbundle file to the release?

**Comment by krschau** [comment]
Uploading seems to have worked just now. Let us know if there are any issues.

**Comment by stamminator** [comment]
There it is! Thank you.
