### ISSUE TITLE
Logs do not provide information 

### ISSUE THREAD

**Issue by kris-koford** [microsoft/devhome#3475]
### Dev Home version

0.1601.561.0

### Windows build number

10.0.22631.3880

### Other software

OS Build Version: 10.0.22631.3880.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

create Hyper-V environment. it does not matter the size. close dev home. reopen dev home, click third icon down (edit environment) then on that screen click create environment (again third option down. in the wizard select already created Hyper-V environment. add a git repo to the environment. I got prompts for user name and password for environment that I did not create. had to go into environment and create password. entered password. installing environment script fails. error logs created and told to see logs. 

### Expected result

should see error logs or information from logs or information on how to correct the issues or information on what was provided to the environment that failed.

### Actual result

no logs are created, no information on how to create or handle issues is given. 

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
Physical Memory: 31.84GB (18.97GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.1600.561.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.16300.20.0_x64__cw5n1h2txyewy

**Comment by kris-koford** [comment]
this issue is dealing with adding a configuration to an existing hyper-V environment.

**Comment by krschau** [comment]
@kris-koford You can find the logs easily by navigating to Settings -> About -> View Logs. Did you find that location but not see logs for the Hyper-V extension? Or are you suggesting that we make the logs more easily accessible from the error message? (Similar to #3409)
