### ISSUE TITLE
Improve Hyper-V Function Detection Based on Windows Version

### ISSUE THREAD

**Issue by xyuxy4** [microsoft/devhome#3477]
### Suggested new feature or improvement

DevHome should automatically hide the Hyper-V functionality and suppress any notifications about missing Hyper-V when running on systems that do not support Hyper-V, such as Windows Home editions. This will prevent unnecessary alerts and improve the user experience.

### Scenario

DevHome should automatically detect whether Hyper-V is supported based on the Windows version. If the Windows version does not support Hyper-V (e.g., Windows Home editions), the Hyper-V functionality should be hidden.

The notification about missing or unsupported Hyper-V should be suppressed in such cases to avoid confusion and improve user experience.

### Additional details

Currently, when opening the environment page, a notification appears indicating that Hyper-V functionality is not recognized, and Hyper-V environments are not listed. This notification includes a link to enable Hyper-V functionality. Clicking the link triggers a UAC confirmation window, but it seems no action is taken, and no terminal window opens to show that the system is performing any operations. The functionality of WSL2 is unaffected, and the notification persists.

**Comment by bbonaby** [comment]
This one's actually a bug. Thanks for bringing this to our attention!
