### ISSUE TITLE
connecting accounts is not working

### ISSUE THREAD

**Issue by jamesbraun12** [microsoft/devhome#3478]
### Dev Home version

0.1601.561.0

### Windows build number

10.0.22631.3880

### Other software

OS Build Version: 10.0.22631.3880.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

?

### Expected result

to connect my account

### Actual result

it didn't work

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHomeAzureExtension_0.1100.561.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHomeGitHubExtension_0.1600.561.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.16300.20.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment]
There's nothing we can do without information about what you tried to do. If you add more information to your bug report, I'll be happy to reopen this.
