### ISSUE TITLE
dev home

### ISSUE THREAD

**Issue by MonicaJohns** [microsoft/devhome#3514]
### Dev Home version

0.1601.561.0

### Windows build number

10.0.22631.3880

### Other software

OS Build Version: 10.0.22631.3880.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

I don't seem to be able to install what I need to 

### Expected result

I get to the setup screen and accept and nothing happens 

### Actual result

I get to the setup screen and i click on the highlighted setup but nothing happens from there

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
Physical Memory: 15.73GB (4.05GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1600.561.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.16300.20.0_x64__cw5n1h2txyewy

**Comment by shakersMSFT** [comment]
Hi, @MonicaJohns, thanks for filing this. Can you share a screenshot of the bug and share the logs so we can try to understand the root cause?

/logs
