### ISSUE TITLE
Why was the Windows Sandbox extension removed?

### ISSUE THREAD

**Issue by AnthonyMastrean** [microsoft/devhome#3566]
I briefly witnessed Windows Sandbox support in a Microsoft Build session but can no longer find the feature. I see multiple mentions that the Sandbox extension was removed (https://github.com/microsoft/devhome/pull/3196), but no explanation why. I don't see it on the roadmap... what's up?

**Comment by bbonaby** [comment]
Hi @AnthonyMastrean, the Sandbox team has taken ownership of the extension and is currently ironing out some issues with it. They'll release the extension when it's ready. Keep an eye out in the future for updates, Thanks!
