### ISSUE TITLE
Extremely long Git commit messages should be trimmed instead of sending to File Explorer.

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/devhome#3603]
### Steps to reproduce the bug

Enable File Explorer integration, and register a repository.
Make a commit with an extremely long commit message all on a single line. (e.g. "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")

### Expected result

I would expect to see the commit message trimmed to a "reasonable" length. Somewhere around 50-200 characters. Enough so that we can expand to see more content when needed, but not so much that if I auto-expand the column width the view gets unmanageably wide, or causes slowdowns.

### Actual result

The commit message field is limited to a "reasonable" length.

**Comment by DHowett** [comment]
Git's best recommendation for titles is 80 chars, but you know, people stopped using 80x25 terminals in 2023. I definitely wouldn't truncate it below 100 these days. :)

**Comment by DefaultRyan** [comment]
While we're at it, we should also limit excessively long strings for the other properties as well. These others are less likely to be extremely long in practice, but no need to subject File Explorer to a quasi-DOS attack.

These strings are coming straight from Git as-is, so trim their length to something reasonable as matter of basic sanitation:
- System.VersionControl.LastChangeAuthorName
- System.VersionControl.LastChangeAuthorEmail
- System.VersionControl.LastChangeID

This string is synthesized by the Git extension. Should trim, but also assert that we aren't generating too much.
- System.VersionControl.Status

This string is mostly synthesized, but contains the branch name as-is from Git. Trim the branch name to a reasonable length. Assert that the full string is reasonable length.
- System.VersionControl.CurrentFolderStatus
