### ISSUE TITLE
File Explorer integration, wrong error with dubious ownership.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#3610]
### Steps to reproduce the bug

Run the following in a debugger.

Enable File Explorer Integration.
Go to Windows customization > File Explorer.
Click "Add Folder"
Add a repo that has dubious ownership.
Click the drop down.
Click "git"

### Expected result

I would get a correct exception about a dubious relationship.

### Actual result

RepositoryWrapper.ctor calls new Repository(rootFolder).  LibGit2Sharp throws when making the Repository because the dubious ownership.

The exception bubbles up to GitLocalRepository.ctor.  The catch case throws a new ArgumentException("Invalid repository path").  The Argument extension is logged, not the original exception.

LibGit2Sharp correctly throws with the exception message "repository path 'blah' is not owned by current user'.  The message is removed when `ArgumentException` is thrown.

**Comment by dhoehna** [comment]
The logs do not help either because the original error is not logged.

**Comment by DefaultRyan** [comment]
Thanks! @ssparach has already been looking into this. Was this the result of adding a WSL repo?
