### ISSUE TITLE
Crash when navigating to extensions

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#3615]
### Dev Home version

0.1601.561.0

### Windows build number

10.0.26100.1457

### Other software

OS Build Version: 10.0.26100.1457.arm64fre.ge_release.240331-1435
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

Go to settings
Go to extensions

This happened once, maybe on a fresh reboot it will happen again.  Event viewer logs below

### Actual result

Faulting application name: DevHome.exe, version: 0.1601.561.0, time stamp: 0x66470000
Faulting module name: Microsoft.UI.Xaml.dll, version: 3.1.5.0, time stamp: 0xf1a6b27f
Exception code: 0xc000027b
Fault offset: 0x000000000000a1e8
Faulting process id: 0x14C0
Faulting application start time: 0x1DAEF4F6BBE58E4
Faulting application path: C:\Program Files\WindowsApps\Microsoft.Windows.DevHome_0.1601.561.0_arm64__8wekyb3d8bbwe\DevHome.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.5_5001.178.1908.0_arm64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll
Report Id: 3439a376-d503-4dca-8a89-b5c5fa2f64e1
Faulting package full name: Microsoft.Windows.DevHome_0.1601.561.0_arm64__8wekyb3d8bbwe
Faulting package-relative application ID: App

### Included System Information

CPU: Snapdragon
Physical Memory: 63.24GB (45.91GB free)
Processor Architecture: ARMx64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1601.561.0_arm64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1601.561.0_arm64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1601.561.0_arm64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1600.561.0_arm64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.21802.0.0_arm64__cw5n1h2txyewy
Microsoft.WidgetsPlatformRuntime_1.4.0.0_arm64__8wekyb3d8bbwe

**Comment by joadoumie** [comment]
I was able to replicate this and cannot replicate it on additional launches after my first launch. 

CPU: Snapdragon
Processor Architecture: ARMx64

**Comment by krschau** [comment]
@crutkas @joadoumie /logs ?

**Comment by crutkas** [comment]
@krschau emailed logs with subject as URL of this issue

**Comment by krschau** [comment]
Haven't been able to repro since the original reports, and didn't see anything helpful in logs or crash dump (stack seemed focused on WinUI rather than Dev Home). I'm going to close, but I'll keep an eye out if we see this again. A note if we do come back to this: both reports were from arm machines.
