### ISSUE TITLE
CPU Monitor

### ISSUE THREAD

**Issue by cocleu** [microsoft/devhome#3635]
### Suggested new feature or improvement

CPU Monitor should sort the tasks by their CPU usage (my CPU usage is 40% but all tasks that display is just 0%).

### Scenario

It just a little improvement and doesn't need any.

**Comment by krschau** [comment]
@cocleu This sounds like a bug -- the widget should be showing the top three tasks by CPU usage. Can you share your logs so we can try to see what's going on?
/logs
/needinfo
