### ISSUE TITLE
[Environments reliability] Dev Box operations: Adaptive card from Dev Box creation is taking too long to load

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#3637]
### Dev Home version

0.1601.561.0

### Windows build number

10.0.22631.4037

### Other software

OS Build Version: 10.0.22631.4037.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

Go to create environment and select create a new Dev Box

### Expected result

Loading finishes in a reasonable timeline

### Actual result

Loading takes about 30 seconds
![image](https://github.com/user-attachments/assets/327b82da-46ff-4572-9e7d-c7c0b53a7cda)

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
Physical Memory: 63.73GB (47.36GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Dev_0.1301.491.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Dev_0.1301.491.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Dev_0.899.490.321_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Dev))
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
9932MartCliment.WingetUIWidgets_0.6.1.0_x64__g91dtg5srk15g (Widgets for UniGetUI (formerly WingetUI))
Microsoft.Windows.DevHomeAzureExtension_0.1100.561.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHomeGitHubExtension_0.1600.561.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.18500.10.0_x64__cw5n1h2txyewy

**Comment by bbonaby** [comment]
Hey @jiayac Can you confirm if you still have this issue when only the latest version of Dev Home preview and the Azure extension (preview) are installed? I just want to confirm how long it takes when only those two are installed. Thanks

**Comment by huzaifa-d** [comment]
It would be great if you could also confirm if you see the issues in the latest Canary. I have sent you the links over IM.
