### ISSUE TITLE
Searching for apps takes a long time

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#3655]
### Steps to reproduce the bug

Navigate to install applications
Search for something

### Expected result

This should be fairly instant, winget search comes back with results rather quickly within Terminal

### Actual result

Takes a few seconds before anything shows up
![image](https://github.com/user-attachments/assets/97e6733d-c197-4c2a-9ac0-217605cc0b91)

**Comment by AmelBawa-msft** [comment]
@cinnamon-msft, I made a PR to accelerate the package search. On my machine, I got x1.44 perf improvement (more details in PR description). Unfortunately, we will unlikely be able to match the perf of WinGet-CLI. The main reason here is that WinGet has all the code and APIs in-process and does not have to pay the cost for transferring data between processes, whereas in Dev Home we exchange data out-of-proc with `WindowsPackageManagerServer.exe` which comes at a cost. We can further improve the performance by possibly reducing the communication with the COM server, but that also implies potentially showing less data on the UI or possibly updating the UI experience to incrementally surface ready packages as they are fully obtained from the out-of-proc processor. There may also be some minor enhancements here and there in the code, but I don't expect that to move the needle too much on perf as the main issue here is that we need to communicate with WinGet process a lot to render packages on the UI.
