### ISSUE TITLE
[Environments reliability] Hyper-V Configuration error: The parameter is incorrect. (0x80070057)

### ISSUE THREAD

**Issue by bbonaby** [microsoft/devhome#3664]
### Steps to reproduce the bug

Attempt to configure a Win 10/11 Hyper-V VM

### Expected result

User is able to configure their Win 10/11 VM. If it succeeds, re-attempt to configure the VM again.

### Actual result

The user receives an error similar to:

"Cannot send message to VM '<VM guid>': 'Failed to set value of the item '<DevSetup-Id>' Data Exchange integration service item for virtual machine '<VM Name>': The parameter is incorrect. (0x80070057) "

I can repro this one, I noticed when I get this error message, if I restart the VM and try again it'll work once before I get the error again. I'll add the logs to this issue once I have them.

**Comment by sshilov7** [comment]
There are 14 events for this and #3663. At least 6 of them are for non-Windows VMs, judging from VM names.
