### ISSUE TITLE
[FE + Version Control] Accessibility Insights Fast Pass: Section 508 502.3.1: (DevHome/button '') The Name property must not contain any characters in the private Unicode range.

### ISSUE THREAD

**Issue by ethanfangg** [microsoft/devhome#3665]
The following accessibility issue needs investigation.

**App:** DevHome

**Element path:** button ''

**Issue Details:** The Name property must not contain any characters in the private Unicode range. [Section 508 502.3.1](https://www.access-board.gov/ict/#502-interoperability-assistive-technology)

**How To Fix:** Modify the Name property, removing all characters in the range U E000 to U F8FF and replace them with meaningful, standard text content.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by DefaultRyan** [comment]
@ethanfangg can you clarify (visual tree path or owning type) that tells us which button this is referring to?

**Comment by ethanfangg** [comment]
@DefaultRyan, @ssparach should know but let me also attach a screenshot of the Accessibility Insights tool analysis:

![image](https://github.com/user-attachments/assets/f5a7e958-1f8c-4993-a56f-82dbac41890e)

(I believe this has to do with the "Git" drop down)

**Comment by ssparach** [comment]
> @DefaultRyan, @ssparach should know but let me also attach a screenshot of the Accessibility Insights tool analysis:
> 
> ![image](https://private-user-images.githubusercontent.com/117125208/360145848-f5a7e958-1f8c-4993-a56f-82dbac41890e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjAwMzgsIm5iZiI6MTcyNDM1OTczOCwicGF0aCI6Ii8xMTcxMjUyMDgvMzYwMTQ1ODQ4LWY1YTdlOTU4LTFmOGMtNDk5My1hNTZmLTgyZGJhYzQxODkwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQyMDQ4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWE0NzkzMmEwNGZkZmRlMDNjM2U2ZTJhYjRlOTllMjdlYTY4Mzc4YTQ0ZTY5ZmE0ZWIyZTE2OWJiMDU2MGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cvC3_8fuYbnIXbYOve2BQH7zzS2j5IpKmgQSsEYrj3E)
> 
> (I believe this has to do with the "Git" drop down)

Yes, this has to do with hardcoding the name of the extension on the dropdown i.e. Git

**Comment by DefaultRyan** [comment]
I just ran the Accessibility Insights again on Canary 0.1701.612.0, and it's still reporting improperly named Button. It's the "..." next to the Dropdown.

<img width="127" alt="image" src="https://github.com/user-attachments/assets/8d659f4e-5646-4983-b1c4-38ded45a9c6d">
