### ISSUE TITLE
[Environments reliability] Dev Box Configuration error: Exception of type 'DevHome.SetupFlow.Exceptions.SDKOpenConfigurationSetResultException' was thrown. 

### ISSUE THREAD

**Issue by bbonaby** [microsoft/devhome#3667]
### Steps to reproduce the bug

This one is hard to repro but its been seen out in the wild. Attempt to configure a Dev Box

### Expected result

The user is able to configure their Dev Box, or if an error does occur a better error message is shown

### Actual result

the user receives this error message:

"Exception of type 'DevHome.SetupFlow.Exceptions.SDKOpenConfigurationSetResultException' was thrown."

There are two things here:

- looks like this is happening on [this line](https://github.com/microsoft/devhome/blob/4288bc20569032a7058b50d5dc0dfddb2a1825a7/tools/SetupFlow/DevHome.SetupFlow/Models/ConfigureTargetTask.cs#L311). The exception message property in this class [here](https://github.com/microsoft/devhome/blob/main/tools/SetupFlow/DevHome.SetupFlow/Exceptions/SDKOpenConfigurationSetResultException.cs)  isn't updated with any useful information to help us figure out why the extension failed to open the configuration file. 
- The Dev Box provider tells us the field and value where the error took place. So we should use this information as the exception error message. Fixing this would help all other extensions as well.

**Comment by huzaifa-d** [comment]
No repro in the current version and for the past one month. Closing this for now.
