### ISSUE TITLE
[Environments reliability] Dev Box Configuration error: The Dev Box isn't running. Please start the Dev Box and try again 

### ISSUE THREAD

**Issue by bbonaby** [microsoft/devhome#3669]
### Steps to reproduce the bug

Attempt to configure a Dev Box that is currently not running

### Expected result

The user is able to configure their Dev Box

### Actual result

The user receives the following error:

"The Dev Box isn't running. Please start the Dev Box and try again"

We probably want to confirm with the Dev Box team what they'd want the experience to be. Should we start the DevBox first then run the configuration file after its started instead of having the user start it manually themselves?

**Comment by huzaifa-d** [comment]
Completed in #https://github.com/microsoft/DevHomeAzureExtension/pull/273
