### ISSUE TITLE
Dev Insights buttons are inconsistent

### ISSUE THREAD

**Issue by jaholme** [microsoft/devhome#3673]
![image](https://github.com/user-attachments/assets/a07c2576-bec1-4d84-a230-f5ed28e530f8)
Might be related to icons vs. font glyphs

**Comment by andreww-msft** [comment]
There's also inconsistency between the 3 main panels:

- Buttons on the target app panel have a transparent background, and a size of ~24?
- The External tools button has a non-transparent background, but a zero border, size ~24?
- External tools and the clipboard monitor tool have a non-transparent background, and a non-zero border, size ~16


![button-transparent-background](https://github.com/user-attachments/assets/64c405a9-954c-4623-afa8-7fb321c03232)

![button-zero-border](https://github.com/user-attachments/assets/09eb7a5e-ec5a-434a-82d5-e02ec182bd55)

![button-standard-border](https://github.com/user-attachments/assets/fa3c8d4e-56bf-47b9-8ca0-b91ffe209b28)
