### ISSUE TITLE
Environments sometime don't load and clicking 'Create new environment' causes a crash

### ISSUE THREAD

**Issue by mdanish-kh** [microsoft/devhome#3726]
### Dev Home version

0.1701.597.0

### Windows build number

10.0.22631.0

### Other software

N / A

### Steps to reproduce the bug

I haven't got solid steps to repro this every time, but it's happening quite frequently with me visiting the environments page. Don't really know what triggers it. What happens is that sometimes Environments don't load properly, and it shows "No environments found". When I click to "Create new environment", devhome crashes. See the video for better understanding. First time the environments load correctly, but second time they don't.

https://github.com/user-attachments/assets/225f190d-91ce-4089-a5c5-d5828b19a718

### Expected result

Environments screen to always load correctly

### Actual result

Environments not always loaded, and cause a crash when you click "Create new environment"

### Included System Information

Windows: Windows.Desktop v10.0.22631.4037
System Architecture: X64

### Included Extensions Information

DevHome GitHub Extension version 0.1700.597.0

**Comment by bbonaby** [comment]
Hi @mdanish-kh, would you be able to file a feedback hub bug for this issue and provide us with the link? That will help us diagnose this issue faster. 

You can launch the Feedback hub app by entering the Windows Key + the F key on your keyboard at the same time. During your feedback, there will be an option to recreate the issue in your video. Feedback hub will capture the data needed for further debugging on our side.

Thank you!

**Comment by mdanish-kh** [comment]
@bbonaby Feedback Hub was not cooperating yesterday, so it took me some time to get back. This should be the issue: https://aka.ms/AAs318i

I also used the "Recreate the issue" and was able to successfully repro it. Let me know if you need anything else from me

**Comment by huzaifa-d** [comment]
Fixed as a side effect of #3907
