### ISSUE TITLE
Dev Home hangs on first launch

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3735]
### Dev Home version

0.1701.597.0

### Windows build number

10.0.22631.4112

### Other software

OS Build Version: 10.0.22631.4112.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.7

### Steps to reproduce the bug

Setup a new Windows 11 machine
Open Start Menu and search for dev home
Start Dev home from the stub installed with the OS

### Expected result

App starts in a few seconds

### Actual result

Update hangs at 90% indefinitely
![image](https://github.com/user-attachments/assets/3ee60222-ecdc-4e26-b419-a97a7597508b)

### Included System Information

CPU: Intel(R) Core(TM) Ultra 7 165H
Physical Memory: 31.64GB (20.79GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1200.597.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.18500.10.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment]
@acangialosi Do you know if Dev Home had hydrated successfully after all? Or did it actually never finish downloading/installing?
