### ISSUE TITLE
Pin to start menu doesn't work

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3737]
### Dev Home version

0.1701.597.0

### Windows build number

10.0.22631.4112

### Other software

OS Build Version: 10.0.22631.4112.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.7

### Steps to reproduce the bug

Install dev box extension
Click on environments
Click ... to expand sub menu
Click on Pin to start menu

### Expected result

Pin that dev box to the start menu.

### Actual result

Nothing happens.

### Included System Information

CPU: Intel(R) Core(TM) Ultra 7 165H
Physical Memory: 31.64GB (23.03GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1200.597.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.18500.10.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment]
Verified working on the latest Preview version; confirmed with team and closing.
