### ISSUE TITLE
For some reason Dev Home installed itself NOT on a system drive

### ISSUE THREAD

**Issue by PastorGL** [microsoft/devhome#3758]
### Dev Home version

0.1701.597.0

### Windows build number

10.0.19045.4842

### Other software

OS Build Version: 10.0.19045.4842.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.7

### Steps to reproduce the bug

Since Dev Home appeared on my machine back in March, it keeps installing itself on drive G: (where I keep only games, so the drive letter).

No matter how many times I change drive letter (on the screenshot its O: thos time), it still keeps installing there for some reason, while all other Store Apps are placed correctly on C: (which is selected in Settings, of course).

The worst thing it doesn't allow to Move its install location in Settings, because it is a System Component. Its GitHub Extension, for example, is allowed to be moved.

![image](https://github.com/user-attachments/assets/b00d5de2-2507-4804-9f28-8485ec68c0c5)

### Expected result

Dev Home should install on the selected drive, not anywhere else on a random drive.

### Actual result

Still on non-system drive, can't place it anywhere else.

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
Physical Memory: 63.84GB (51.3GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
Microsoft.WidgetsPlatformRuntime_1.4.0.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Hi @PastorGL This sounds like something going on with the Store. Could you open the issue in Feedback Hub? That way the right eyes will get on it.
/feedbackhub

**Comment by PastorGL** [comment]
> Hi @PastorGL. Please file this issue on Feedback Hub [Windows]+[f] and paste the link here so we can more easily find your information on the back end. The link can be found at the bottom of the feedback report. Please use "Apps" and "Dev Home" for the Category.

Well, that's not the answer I've hoped for, cause all other Store apps behave as expected. Only Dev Home is an exception. But okay, I'll do that, if you insist.

But is there any way to fix this installation? Move-AppxPackage doesn't work with system components.
