### ISSUE TITLE
Widgets cleared out of my dashboard

### ISSUE THREAD

**Issue by shakersMSFT** [microsoft/devhome#3778]
### Dev Home version

0.1701.597.0

### Steps to reproduce the bug

I opened Dev Home today and it opened to my dashboard that previously had a mix of core widgets and GitHub widgets and they are all gone now, so my dashboard is empty. 

### Expected result

I expect once I set up my widgets, they should only disappear if I choose to delete them. 

### Actual result

My dashboard is empty upon launching Dev Home. 

### Included Extensions Information

GitHub extension version 0.1700.597.0

**Comment by krschau** [comment]
@shakersMSFT I need your widget service version(s) and Windows version.
in powershell, do 
`get-appxpackage *widget*`
`get-appxpackage *webexp*`

**Comment by shakersMSFT** [comment]
Widgets: 1.4.0.0
WebExp: 524.24900.0.0

**Comment by shakersMSFT** [comment]
logs: 
[devhome20240905.zip](https://github.com/user-attachments/files/16911110/devhome20
[log20240905.zip](https://github.com/user-attachments/files/16911141/log20240905.zip)
240905.zip)
I have no logs from the Azure extension.

**Comment by shakersMSFT** [comment]
Dev Home: [devhome20240905.zip](https://github.com/user-attachments/files/16911157/devhome20240905.zip)
GitHub ext: [log20240905.zip](https://github.com/user-attachments/files/16911158/log20240905.zip)
I have no logs from the Azure ext

**Comment by dinirichard** [comment]
Having a similar issue, began after the latest windows update
[DevHomeLogs.zip](https://github.com/user-attachments/files/16931541/DevHomeLogs.zip)

**Comment by krschau** [comment]
Duplicate of #2945
