### ISSUE TITLE
Dev Home has trouble displaying widgets even after restart

### ISSUE THREAD

**Issue by calebgiardino** [microsoft/devhome#3801]
### Dev Home version

0.1701.597.0

### Windows build number

10.0.22631.4037

### Other software

OS Build Version: 10.0.22631.4037.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.7

### Steps to reproduce the bug

Launching Dev Home with widgets installed. Restarted Dev Home and local machine and the error message is still there.

### Expected result

Dev Home widgets/extensions displaying.

### Actual result

A message pops up on the dashboard:

![image](https://github.com/user-attachments/assets/2cd31003-0880-44c5-a51e-814df5309ee1)

### Included System Information

CPU: AMD Ryzen 9 5900HX with Radeon Graphics        
GPU: RTX 3080 16 GB Laptop GPU
Physical Memory: 15.4GB (9.31GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.23700.10.0_x64__cw5n1h2txyewy

**Comment by calebgiardino** [comment]
Self resolved. Closing Dev Home the using win + w shortcut, and finally relaunching dev home seems to have fixed the issue!

**Comment by krschau** [comment]
Duplicate of #2945
