### ISSUE TITLE
Quickstart playground has combobox dropdown with only 1 provider

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#3860]
### Dev Home version

0.1801.621.0

### Windows build number

10.0.22631.4169

### Other software

OS Build Version: 10.0.22631.4169.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.8

### Steps to reproduce the bug

Screenshot shows combo box but user has no choice for what to pick as we only have 1

![image](https://github.com/user-attachments/assets/9d27bc95-f44e-47e6-8de0-214ffec928d7)

### Expected result

This feels odd to be here as we only have 1 provider.  

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i7-13700K
Physical Memory: 63.78GB (35.46GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1200.597.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1800.621.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHome.Canary_0.1801.621.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1801.621.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome.Canary_0.1801.621.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome.Canary_0.1801.621.0_x64__8wekyb3d8bbwe (Git (Canary))
Microsoft.Windows.DevHomeAzureExtension.Canary_0.1300.621.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.24900.10.0_x64__cw5n1h2txyewy

**Comment by adrastogi** [comment]
@crutkas thanks for the feedback. This is by design since we wanted to ensure the user is in control of the initial selection (the original version of the extension supported Azure OpenAI (which was moved to Debug-only en route to this past year's //BUILD), so when we eventually fix [this issue](https://github.com/microsoft/DevHomeAzureExtension/issues/216), there'd be two to choose from).
