### ISSUE TITLE
[ci]: WinGet publish action failed

### ISSUE THREAD

**Issue by mdanish-kh** [microsoft/devhome#3875]
### Other software

N/A

### Steps to reproduce the bug

See - https://github.com/microsoft/devhome/actions/runs/10908161759/job/30273488330

A contributor submitted a [PR for the latest version](https://github.com/microsoft/winget-pkgs/pull/173962), but we should fix the action for future release runs

Probably a case of incorrect/expired token?

### Expected result

PR submitted to microsoft/winget-pkgs

### Actual result

Action run failed

**Comment by krschau** [comment]
Duplicate of #2967
