### ISSUE TITLE
DevHome crashes when using SSH wallet widget

### ISSUE THREAD

**Issue by niiiksh** [microsoft/devhome#3878]
### Dev Home version

0.1801.625.0

### Windows build number

10.0.22631.0

### Steps to reproduce the bug

Click any item in SSH wallet widget in DevHome app.

### Expected result

Open SSH connection in default terminal.

### Actual result

DevHome crashes.

**Comment by krschau** [comment]
Duplicate of #3888
(Normally I dupe the newer to the older but in this case, the newer one has some logs I don't want to overlook)
