### ISSUE TITLE
왜 도구에 대한 설명이 없는거죠?

### ISSUE THREAD

**Issue by kimyeongdae** [microsoft/devhome#3903]
### Dev Home version

0.1801.625.0

### Windows build number

10.0.22631.4169

### Other software

OS Build Version: 10.0.22631.4169.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.8

### Steps to reproduce the bug

1

### Expected result

도구의 대한 설명으로 프로그램을 깔 수 있게해줌

### Actual result

아무것도 모르겠음

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i5-12600KF
실제 메모리: 15.86GB (6.31GB free)
프로세서 아키텍처: x64

### Included Extensions Information

확장: 
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (핵심 위젯 확장)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Hyper-V 확장)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Linux용 Windows 하위 시스템 확장)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1800.625.0_x64__8wekyb3d8bbwe (Dev Home GitHub 확장(미리 보기))

위젯 서비스: 
MicrosoftWindows.Client.WebExperience_524.24900.80.0_x64__cw5n1h2txyewy
Microsoft.WidgetsPlatformRuntime_1.4.0.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Bing translate:
Why isn't there an explanation of the tool? #3903
Allows you to install the program with a description of the tool
I don't know anything

**Comment by krschau** [comment]
Documentation about Dev Home can be found online: https://learn.microsoft.com/windows/dev-home/
