### ISSUE TITLE
No translation. No language change option.

### ISSUE THREAD

**Issue by SzydercaMiki** [microsoft/devhome#3920]
### Dev Home version

0.1801.640.0

### 🌐 Language

Polish

### ❌ Actual phrase(s)

No language change option. English only. No translation to anything!  

### ✔️ Expected phrase(s)

Language change option or use the same language as the system

### Why is the current translation wrong

The translation is error-free. The language cannot be change.

**Comment by krschau** [comment]
Dev Home is translated into (I believe the number is) 12 languages, and will use the language that your Windows Settings are set to use.
