### ISSUE TITLE
The pin buttons for the dev boxes are not displaying correctly

### ISSUE THREAD

**Issue by iceygjy** [microsoft/devhome#3933]
### Dev Home version

0.1801.640.0

### Windows build number

10.0.26100.0

### Steps to reproduce the bug

1.Sign in your account.
2.Enter 'environment' page and sync the dev boxes.
3.Click 'more options' icon on the top right corner of dev boxes.
![Screenshot 2024-10-09 145139](https://github.com/user-attachments/assets/057c6b3b-dda3-4c36-bb42-25f50815b9d6)
4.Click 'pin to taskbar' and click 'more options' icon again.

### Expected result

The options should display normally.

### Actual result

1.Options 'Pin to taskbar' and 'Pin to Start Menu' disappeared.
![image](https://github.com/user-attachments/assets/6de543cf-1ecd-42bb-9d98-1a7af81f587a)
2.Repeated display of options 'Pin to taskbar', 'Pin to Start Menu' or 'unpin from Start menu'.
![image (1)](https://github.com/user-attachments/assets/f8f83488-62b8-4526-8620-864313f820e1)
![image (2)](https://github.com/user-attachments/assets/5c3fd82c-ac22-4631-b3af-6988a747f0e6)

**Comment by bbonaby** [comment]
should be fixed in the november release of the Azure extension via https://github.com/microsoft/DevHomeAzureExtension/pull/280
