### ISSUE TITLE
After pinning the dev box to the Taskbar, sometimes the "Unpin" button will not be shown in Dev Home

### ISSUE THREAD

**Issue by Dorisls** [microsoft/devhome#3934]
### Dev Home version

0.1801.640.0

### Windows build number

10.0.22631.0

### Steps to reproduce the bug

1. There are some dev boxes shown in the Dev Home.
2. Select any dev box. Click "..." and then click "Pin to Taskbar".
3. After successfully pinning the dev box to taskbar, go to Dev Home and click "..." again. Try to find the "Unpin From Taskbar" button.

### Expected result

1. After successfully pinning the dev box to the taskbar, the "Unpin" button can be shown in Dev Home. 
![image](https://github.com/user-attachments/assets/c45bb25d-8956-4bbc-952d-2d338fe6988c)

### Actual result

1. After successfully pinning the dev box to taskbar, go to Dev Home and click "..." again, sometimes the "Unpin From Taskbar" button will not be shown in Dev Home.

**Comment by bbonaby** [comment]
fixed over in azure extension via https://github.com/microsoft/DevHomeAzureExtension/pull/280. Should be in the November release of the Azure extension
