### ISSUE TITLE
When will Dev home support Native AOT

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/devhome#3951]
### Dev Home version

0.1801.640.0

### Windows build number

10.0.26100.0

### Other software

None

### Steps to reproduce the bug

When will Dev home support Native AOT

### Expected result

Provide Native AOT Dev home version

### Actual result

Dev home does not support Native AOT

### Included System Information

10.0.26100.0

### Included Extensions Information

None

**Comment by krschau** [comment]
We don't have a timeline specifically, but I have been looking into it. In order to support Native AOT, we need to upgrade to WindowsAppSDK 1.6. In order to do that, we need to update CsWinRT, Adaptive cards, and some other things. We're currently working on those dependencies.
