### ISSUE TITLE
no puedo desinstalar esta porqueria

### ISSUE THREAD

**Issue by reyteo8** [microsoft/devhome#3957]
### Dev Home version

0.1801.640.0

### Windows build number

10.0.22631.4317

### Other software

OS Build Version: 10.0.22631.4317.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.8

### Steps to reproduce the bug

lo instale no sirvió para lo que quería (medir la temperatura del cpu) lo quiero desinstalar y no puedo

### Expected result

se desinstale

### Actual result

no aparece en la lista de aplicaciones

### Included System Information

CPU: AMD Ryzen 5 5600G with Radeon Graphics         
Memoria física: 15.37GB (7.21GB free)
Arquitectura del procesador: x64

### Included Extensions Information

Extensiones: 
Microsoft.Windows.DevHome_0.1801.640.0_x64__8wekyb3d8bbwe (Extensión de widget principal)
Microsoft.Windows.DevHome_0.1801.640.0_x64__8wekyb3d8bbwe (Extensión de Hyper-V)
Microsoft.Windows.DevHome_0.1801.640.0_x64__8wekyb3d8bbwe (Extensión de Subsistema de Windows para Linux)
Microsoft.Windows.DevHome_0.1801.640.0_x64__8wekyb3d8bbwe (Git)

Servicio de widget: 
MicrosoftWindows.Client.WebExperience_524.28801.20.0_x64__cw5n1h2txyewy
Microsoft.WidgetsPlatformRuntime_1.4.0.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Duplicate of #1615, see specifically https://github.com/microsoft/devhome/issues/1615#issuecomment-1856931703
