### ISSUE TITLE
Add an uninstall button.

### ISSUE THREAD

**Issue by HylianKirby** [microsoft/devhome#3972]
### Suggested new feature or improvement

Not everyone wants or needs to use this software, and for people like me it just takes up unnecessary space. Add an uninstall button.

### Scenario

I don't know what this app does, nor do I care. I just want it off my device.

### Additional details

🖕

**Comment by mcgonrya** [comment]
Microsoft needs to stop installing stuff like this without permission.

**Comment by krschau** [comment]
Duplicate of #1615, see specifically https://github.com/microsoft/devhome/issues/1615#issuecomment-1856931703
