### ISSUE TITLE
QuickStart Playground - Extension Provider bug

### ISSUE THREAD

**Issue by johnkennyuk** [microsoft/devhome#3980]
### Dev Home version

0.1801.640.0

### Windows build number

10.0.26120.1843

### Other software

OS Build Version: 10.0.26120.1843.amd64fre.ge_release.240331-1435
.NET Version: .NET 8.0.8

### Steps to reproduce the bug

Machine Config - QuickStart Playground - Prompted to install the dev containers vscode extension 

### Expected result

the Dev Containers vscode extension would be detected regardless of the vscode build installed

### Actual result

stuck at the install dev containers vscode extension prompt?

### Included System Information

CPU: Intel(R) Core(TM) i9-9960X CPU @ 3.10GHz
Physical Memory: 31.69GB (12.59GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.1800.625.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHome_0.1801.640.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1801.640.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1801.640.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1801.640.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeAzureExtension_0.1300.624.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
9932MartCliment.WingetUIWidgets_0.7.0.0_x64__g91dtg5srk15g (Widgets for UniGetUI)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.27701.0.0_x64__cw5n1h2txyewy
Microsoft.WidgetsPlatformRuntime_1.6.1.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
The Quickstart Playground experimental feature has been removed from Dev Home.
