### ISSUE TITLE
When running cargo check in the dev drive, the system may crash and automatically restart.

### ISSUE THREAD

**Issue by juzi5201314** [microsoft/devhome#3982]
### Dev Home version

0.1801.640.0

### Windows build number

10.0.22631.0 

### Other software

rust toolchain: `nightly-x86_64-pc-windows-msvc`
rust-analyzer: `v0.3.2172`
vs code: `1.95.2`
sccache: `0.7.7`

I'm also running League of Legends from WeGame, which has an anti-cheat software. But it's on another physical disk. I don't know if that's related.

### Steps to reproduce the bug

Use vsc+rust-analyzer to write rust code and save it. rust-analyzer will trigger `cargo check`. 
Rust project in dev drive.
There is a certain chance of crashing with a blue screen `FAST_ERESOURCE_PRECONDITION_VIOLATION`, which has occurred an average of 2-3 times per day in the past two days.

### Actual result

[Memory.dmp](https://github.com/user-attachments/files/17749572/Memory.dmp)

![Image](https://github.com/user-attachments/assets/c836e37d-688b-4913-977a-5311ff7d75d1)

![Image](https://github.com/user-attachments/assets/7268fa39-5aa7-449e-97a4-a93d31ea25f3)

**Comment by krschau** [comment]
Closing, since I don't think this bug is related to Dev Home. To report general bugs, please use Feedback Hub.
