### ISSUE TITLE
Missing Widget Dependencies

### ISSUE THREAD

**Issue by divinebovine** [microsoft/devhome#3983]
### Dev Home version

0.1801.640.0

### Windows build number

10.0.26100.1742

### Other software

After installing on a new machine I am unable to add or display any widget.

![Image](https://github.com/user-attachments/assets/9f9604b6-f9ca-49c5-ac69-bf67015fafd8)

The error suggests that I need to install a dependency or package from the Store, however my organization has disabled the Microsoft Store on my machine. So I have no idea what I should install.

![Image](https://github.com/user-attachments/assets/433eeb17-fe49-45eb-843a-fddf4d5fe600)

### Steps to reproduce the bug

1. Install Dev Home
2. Install Azure and GitHub extensions
3. Try to add a widget

### Expected result

Be able to add widgets

### Actual result

Unable to add widgets

### Included Extensions Information

Dev Home Azure Extension version 0.1300.624.0
Dev Home GitHub Extension version 0.1800.625.0

**Comment by krschau** [comment]
Sorry, if your organization has disabled the store (and, seemingly, widgets), Dev Home can't circumvent that.
