### ISSUE TITLE
Windows Search

### ISSUE THREAD

**Issue by djtEtO** [microsoft/devhome#3986]
### Dev Home version

0.1901.687.0

### Windows build number

10.0.26100.2314

### Other software

OS Build Version: 10.0.26100.2314.amd64fre.ge_release.240331-1435
.NET Version: .NET 8.0.10

### Steps to reproduce the bug

Escribir texto en el cuadro de busqueda

### Expected result

respetar textos introducidos

### Actual result

Al escribir las búsquedas Windows Search elimina los espacios de esta manera:
AlescribirlasbúsquedasWindowsSearcheliminalosespaciosdeestamanera: 

Lo cual imposibilita la búsqueda y obliga a volver a introducir el texto, tomando pausas entre cada palabra escrita, eso sin mencionar que no muestra historial de búsqueda, indexación SUPER LENTA Y MÁS

### Included System Information

CPU: AMD Ryzen 7 5800H with Radeon Graphics         
Memoria física: 27.92GB (22.19GB free)
Arquitectura del procesador: x64

### Included Extensions Information

Extensiones: 
Microsoft.Windows.DevHome_0.1901.687.0_x64__8wekyb3d8bbwe (Extensión de widget principal)
Microsoft.Windows.DevHome_0.1901.687.0_x64__8wekyb3d8bbwe (Extensión de Hyper-V)
Microsoft.Windows.DevHome_0.1901.687.0_x64__8wekyb3d8bbwe (Extensión de Subsistema de Windows para Linux)
Microsoft.Windows.DevHome_0.1901.687.0_x64__8wekyb3d8bbwe (Git)

Servicio de widget:

**Comment by krschau** [comment]
This repository is only for issues related to Dev Home, which this issue does not seem to be. Please open your issue in Feedback Hub and the right people will see it.
