### ISSUE TITLE
Dev Home: Machine Config, Cancel button not working

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#466]
### Expected result

Description
On last step of E2E setup the cancel button stopped working

**Comment by AmelBawa-msft** [comment]
Item moved from ADO to Github. From internal discussion, this issue does not repro.
Closing issue as no-repro, please re-activate with repro steps if this issue persists.

Reference: [44586578](https://task.ms/44586578)

CC: @florelis @pehammer
