### ISSUE TITLE
[SetupFlow][AppManagement] Resizing the window sometimes causes the catalog height to stretch vertically

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#470]
### Other software

Feedback hub not responsive on my machine, filing manually:

 Resizing the window sometimes causes the catalog height to stretch vertically
![image](https://github.com/microsoft/devhome/assets/111322232/ec11fa6d-d868-4738-9be6-8350d8dfc078)

**Comment by AmelBawa-msft** [comment]
Closing, this was applicable before the latest UI changes for the App Install page.
