### ISSUE TITLE
[Log in] Browser shows empty screen when connecting accounts for the Nth time

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#473]
### Steps to reproduce the bug

Need to collect Fiddler logs with HTTPS intercept enabled and share them with [@Hirsch Singhal](https://dev.azure.com/microsoft/OS/_workitems/edit/44063672#) from GitHub to debug.

Vineeth reproed across multiple OAuth clients and browsers so it appears to be a GitHub-specific issue.

This reproes most consistently when the user is already authenticated in the browser and has already authorized the OAuth client previously. Connecting an account at that point passes through AUTHN and AUTHZ and lands the user on the redirection page shown below. In the repro scenario, the redirection page is blank.

Expected:

Image

Actual:

Image

Please see [other feedbacks in userfeedback Vso](https://userfeedback.visualstudio.com/DefaultCollection/UIF/_workitems?_a=query&wiql=Select+%5bUIF.NumInstances%5d%2c%5bUIF.NumLogs%5d%2c%5bUIF.NumScreenshots%5d%2c%5bMicrosoft.VSTS.Build.FoundIn%5d%2c%5bSystem.Title%5d%2c%5bUIF.HowFound%5d+From+WorkItems+where+%5bUIF.PromotedBugId%5d%3d%2744063672%27+Order+By+%5bUIF.NumInstances%5d+desc) for feedbacks that are tracked by this work item.

**Comment by ezekielalexthomas** [comment]
This is fixed with the new "Account Picker" page being displayed always.

**Comment by vineeththomasalex** [comment]
This is fixed with the "account picker" page being always displayed during login.

**Comment by vineeththomasalex** [comment]
This is fixed with the "account picker" page being always displayed during login.

**Comment by vineeththomasalex** [comment]
This was fixed with an external change to force display the account selection page for all logins. 

Also related to:
https://github.com/microsoft/devhomegithubextension/pull/339
