### ISSUE TITLE
clone repo review detail page lacks any relevant detail

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#487]
### Steps to reproduce the bug

Description
try to clone a repro, in recap page, it just says the the file path, nothing more.

This lacks useful levels of detail.

**Comment by krschau** [comment]
@dhoehna This is quite old and thing may have changed, can you look at this and close if appropriate?

**Comment by dhoehna** [comment]
More information has been added and the review page includes the provider being used.
