### ISSUE TITLE
CPU End process buttons from Add Widget dialog are destructive (Dev Home)

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#506]
### Steps to reproduce the bug

The end process buttons here are actionable from the dialog itself. Its a bit destructive to kill an app from here in my opinion. Wondering if we can just show the graphs here without the buttons below. 
![image](https://github.com/microsoft/devhome/assets/111322232/7f512cd5-c7cb-4642-bcac-89b4ae7ad374)

**Comment by krschau** [comment]
@cinnamon-msft FYI this was originally opened by Christian on the Design team. I'm not sure if that affects your closing as "by design".
