### ISSUE TITLE
Create an Azure DevOps Extension

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#521]
### Suggested new feature or improvement

Functionality at parity with the [Dev Home GitHub Extension](github.com/microsoft/devhomegithubextension).
- Cloning ADO repositories
- ADO widgets working on the Dev Home dashboard

```[tasklist]
### Tasks
- [ ] #998 
```

**Comment by JanRajnoha** [comment]
I hope this extension will be top priority, I use ADO for example more than GitHub

**Comment by actionthomas** [comment]
Please make it compatible with Azure DevOps Server too

**Comment by qJake** [comment]
Yes please! GitHub is great, but being able to use this awesome app against our large DevOps enterprise org would be even better!

Bonus points for custom query and chart object support!

**Comment by drchilds** [comment]
I'd like to weigh-in and add my voice to this request.

**Comment by johnkattenhorn** [comment]
I am looking forward to this feature 😊

**Comment by aksoftware98** [comment]
@cinnamon-msft I'm thinking of starting implementing this task, as I have worked on something similar before and it will be a big addition to me and manyt other developers who rely heavily on AZ DevOps . But regarding the authentication for the extension do you need to implement full Microsoft Authentication or use Personal Access Token paste in the Settings of the Extension so it will be to authenticate the endpoint? 
Any ideas about that?

**Comment by TheJaysH** [comment]
Why wasnt this a day one feature. mad. I dont really use GitHub.

**Comment by aksoftware98** [comment]
> Why wasnt this a day one feature. mad. I dont really use GitHub.

The product is just started, and I think it's obvious, GitHub has +100M users compared to the number of users who use Azure DevOps on a daily bases, I think GitHub deserves the priority. But it's very indeed. I started investigating the repo to get started with it

**Comment by actionthomas** [comment]
> @cinnamon-msft I'm thinking of starting implementing this task, as I have worked on something similar before and it will be a big addition to me and many other developers who rely heavily on AZ DevOps. But regarding the authentication for the extension do you need to implement full Microsoft Authentication or use Personal Access Token pasted in the Settings of the Extension so it will be used to authenticate the endpoint? Any ideas about that?

For on-prem Azure Devops Server, Windows Integrated authentication should be used.

**Comment by cinnamon-msft** [comment]
> @cinnamon-msft I'm thinking of starting implementing this task, as I have worked on something similar before and it will be a big addition to me and many other developers who rely heavily on AZ DevOps. But regarding the authentication for the extension do you need to implement full Microsoft Authentication or use Personal Access Token pasted in the Settings of the Extension so it will be used to authenticate the endpoint? Any ideas about that?

We're working directly with the ADO team to implement this one, just as a heads up :)

**Comment by jrdodds** [comment]
Settings -> Accounts should support Azure DevOps accounts.

**Comment by cleferman** [comment]
also interested in this!

**Comment by AClerbois** [comment]
I need it :-)

**Comment by mikebattista** [comment]
I wanted to get a sense for everyone's expectations and priorities here given the breadth of functionality that Azure DevOps supports.

Here are some principles and constraints guiding the initial goals for the extension:

* Support Azure DevOps and Azure DevOps Server
* Support functional parity with GitHub for Machine Configuration
* Support functional parity with GitHub for widgets while preserving familiar look and feel of the equivalent Azure DevOps widgets
* Support additional Azure DevOps widgets over time based on priority and demand
* Make it easy to import existing widgets from existing Azure DevOps Dashboards (need to explore what's possible here)

Azure DevOps and Dev Home Widget platforms are different so initially we'll need to prioritize which widgets we support. The initial set of widgets chosen below is based on what we support for GitHub today and top usage data from Azure DevOps.

Here is the current thinking on short-term goals for the extension:

* Accounts
  * Ability to connect MSA and AAD accounts to Dev Home for connecting to Azure DevOps and Azure DevOps Server
* Machine Configuration
  * Ability to clone/configure Git repos within Azure DevOps as with GitHub
  * QUESTION: What about TFVC repos? Is that a priority to support?
* Widgets (in priority order)
  1. [Query Results](https://learn.microsoft.com/azure/devops/report/dashboards/widget-catalog?view=azure-devops#query-results-widget) QUESTION: How much control do you expect to have over the size of widgets? How much horizontal scrolling is acceptable?
  2. [Query Tile](https://learn.microsoft.com/azure/devops/report/dashboards/widget-catalog?view=azure-devops#query-tile-widget)
  3. [Query Chart](https://learn.microsoft.com/azure/devops/report/dashboards/widget-catalog?view=azure-devops#chart-wit-widget) QUESTION: Which chart types are most important to you?
  4. [Pull Requests](https://learn.microsoft.com/azure/devops/report/dashboards/widget-catalog?view=azure-devops#pull-request-widget)
  5. [Assigned to Me](https://learn.microsoft.com/azure/devops/report/dashboards/widget-catalog?view=azure-devops#assigned-to-me-widget)
  6. [Burndown](https://learn.microsoft.com/azure/devops/report/dashboards/widget-catalog?view=azure-devops#burndown-analytics-widget) (STRETCH)
  7. [Sprint Burndown](https://learn.microsoft.com/azure/devops/report/dashboards/widget-catalog?view=azure-devops#sprint-burndown-analytics-widget) (STRETCH)
  * Ideally if you've already set up these widgets in Azure DevOps, it should be easy to import those into Dev Home with a few clicks without having to reconfigure them. We need to explore what's possible here.
  * QUESTION: Are you looking to load an existing Azure DevOps Dashboard within Dev Home as is? What's the value of that compared to just interacting with the dashboard within Azure DevOps in the browser itself?
  * QUESTION: If you're looking to load individual widgets as described above to view them alongside widgets from other extensions, what other widgets are top priority for you?
* QUESTION: What other aspects of Azure DevOps would you like to see integrated into Dev Home?

Let us know what you think!

**Comment by JanRajnoha** [comment]
For me this list of features will be absolutely enough (mainly query results, pull requests, query chart (pie with grouped tasks by state), query tile and cloning). TFVC repos support would be nice addition.

**Comment by mikebattista** [comment]
Thanks.

@qJake by "build and release statuses" are you referring effectively to the [Build History](https://learn.microsoft.com/azure/devops/report/dashboards/widget-catalog?view=azure-devops#build-history-widget) and [Release Pipeline Overview](https://learn.microsoft.com/azure/devops/report/dashboards/widget-catalog?view=azure-devops#release-definition-widget) widgets?

**Comment by qJake** [comment]
@mikebattista Yes! 👍

**Comment by ronzinms** [comment]
Hello.  Any ballpark timeframe on the ADO extension ?
Thanks !

**Comment by MizardX** [comment]
> Hello. Any ballpark timeframe on the ADO extension ? Thanks !

This issue is currently in the [Dev Home v0.5](https://github.com/microsoft/devhome/milestone/5) milestone, which currently has a due date of September 15, 2023.

**Comment by mikebattista** [comment]
> > Hello. Any ballpark timeframe on the ADO extension ? Thanks !
> 
> This issue is currently in the [Dev Home v0.5](https://github.com/microsoft/devhome/milestone/5) milestone, which has a due date of September 15, 2023.

The milestones are tentative, but we're working on it.

October/November seems more realistic based on current trajectory.

**Comment by blogcraft** [comment]
It looks like Microsoft won't invest more in Azure DevOps in favor of Github (There have been no new features in years, only small updates) which is a shame... Clearly, it's no longer a priority.

**Comment by Zhaph** [comment]
Even the ability to check out my repos in Dev Home would be nice - or point to an existing repo on disk.

**Comment by vladimirgomezf** [comment]
Please I think that is very important the Azure Dev Ops support, at least as important as the GitHub support!!
And please Microsoft has developers to work on this without going to ruin...
I work for a USA company and we use ADO for all our projects so please consider this as a priority please!!!

**Comment by cinnamon-msft** [comment]
This is a top priority for us and is in this month's milestone. :)

**Comment by cinnamon-msft** [comment]
We've just published the repo for the Azure extension 🎉 https://github.com/microsoft/devhomeazureextension
We're planning to release this next week in the Microsoft Store and then we'll close this issue as completed! :smile:

**Comment by BenS13** [comment]
@cinnamon-msft Does that mean we have to wait another week? The repo says you can install manually but there are no releases available.

**Comment by jrdodds** [comment]
For me, the Dev Home Azure Extension appeared in the Microsoft Store this morning.

**Comment by MISTikus** [comment]
I gues this extension does not work with AzureDevOpsServer?

**Comment by mikebattista** [comment]
> I guess this extension does not work with Azure DevOps Server?

Not yet but we do intend to support this. The work is tracked by https://github.com/microsoft/DevHomeAzureExtension/issues/45.

**Comment by DavidEggen** [comment]
Is there a way to install an extension without having access to the Microsoft Store?
