### ISSUE TITLE
Crash when opening Preferences in Dark HighContrast mode

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#550]
### Steps to reproduce the bug

Description
Put the app in dark mode, put your machine in High Contrast. Go to Settings. Click Preferences. Crash.
Tried to recreate for this bug. Didn't repro while recording, did repro after I cancelled recording.

**Comment by chendrixson** [comment]
Touching bug to test an internal process thing.

**Comment by mathewleeza** [comment]
[Bug 44269230](https://dev.azure.com/microsoft/OS/_workitems/edit/44269230): Crash when opening Preferences in Dark HighContrast mode

**Comment by krschau** [comment]
Ok to close, since I haven't repro'ed this in a long time.
