### ISSUE TITLE
Error infos for Dev Home plugin exceptions are getting dropped crossing Out of proc boundary

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#552]
### Steps to reproduce the bug

This is specifically tracking the error info getting dropped leading to a degraded diagnosability experience of such exceptions in crash dumps and under the debugger. 

Process A calls an API in Process B via Out-Of-Proc call.

Process B throw's an exception and adds a string to the message member.

Process A catches the error.  The message field is blank.

**Comment by vineeththomasalex** [comment]
Fixed with OperationResult objects #1453
