### ISSUE TITLE
DevHome process doesn't end when app is closed.

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#553]
### Steps to reproduce the bug

Description
Close the app by invoking the X button. The process can still be seen in Task Manager.

**Comment by luislhg** [comment]
I think I'm experiencing this issue. I can't open DevHome after closing it.

A lot of times the user will not notice this, he will just try to open DevHome and it wont open!
Searching through the Task Manager I can see it is never closed thus it cannot be opened again.
I always have to open task manager, search for DevHome and End the task.

https://github.com/microsoft/devhome/assets/16278387/38d36991-969e-40a8-ba13-2a3b443c1822

**Comment by mathewleeza** [comment]
[Bug 44323610](https://dev.azure.com/microsoft/OS/_workitems/edit/44323610): DevHome process doesn't end when app is closed.

**Comment by krschau** [comment]
Marking Priority-2 since I haven't been seeing, and also maybe was mitigated by #1712. But worth taking another quick look at.

**Comment by krschau** [comment]
Duplicate of #3411
