### ISSUE TITLE
Dev home plugins should have a way to communicate extended error messages

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#565]
### Steps to reproduce the bug

This is related to the linked bug.  But when that bug is resolved, you will still not get the experience where the exception from the plugin marshaled to Dev Home has the detailed error message that it was initially thrown with.  This is because the exception is translated to an WinRT error which is an HRESULT and an error info.  The latter is only used to improve diagnosability in a debugger / dump and isn't used by C# to rehydrate the exception message especially for out of proc scenarios.  In addition, the error info marshaling is best effort as it is a diagnosability feature.  Due to that, Dev Home shouldn't rely on the exception message in such scenarios if it needs something to show to the user.

Instead, Dev Home should have something like a Result return for such APIs and that should have some ExtendedError or similar property which plugins and Dev home can rely on to communicate known errors to display to the user.

See the following for guidance:

https://www.osgwiki.com/wiki/WinRT_API_Design_Patterns#Return_a_rich_error_object

https://www.osgwiki.com/wiki/WinRT_API_Design_Patterns#Extended_Errors

Please see [other feedbacks in userfeedback Vso](https://userfeedback.visualstudio.com/DefaultCollection/UIF/_workitems?_a=query&wiql=Select+%5bUIF.NumInstances%5d%2c%5bUIF.NumLogs%5d%2c%5bUIF.NumScreenshots%5d%2c%5bMicrosoft.VSTS.Build.FoundIn%5d%2c%5bSystem.Title%5d%2c%5bUIF.HowFound%5d+From+WorkItems+where+%5bUIF.PromotedBugId%5d%3d%2744572590%27+Order+By+%5bUIF.NumInstances%5d+desc) for feedbacks that are tracked by this work item.

**Comment by krschau** [comment]
@dhoehna Am I correct in remembering that you added something like this?

**Comment by dhoehna** [comment]
Fixed in #1509
