### ISSUE TITLE
Titles on all pages are consistent but are too large

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#567]
### Description
Page titles should be standard "Subtitles" semibold display 20/28

From Ian:
All page title should be using the subtitle style
Text="Subtitle" Style="{StaticResource SubtitleTextBlockStyle}"/> "

**Comment by JanaganSaravanan** [comment]
Hi! I would like to work on this issue. Can you please provide me more information such which file needs to be updated. Thanks.
