### ISSUE TITLE
Dev Home Settings: Accounts page out of spec

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#571]
### Steps to reproduce the bug

Description
When there are no accounts added in Dev Home, The 'Github' section header should be hidden. Also, when the GitHub section header is shown, there should be a little more vertical space between it and the elements above the header. figma spec calls for the section header to be bottom aligned in a container that is 42px tall with 4px margin top and bottom.

**Comment by krschau** [comment]
At some point it seems this got fixed.
