### ISSUE TITLE
[Dashboard][Feature request] System widgets should be pinned by default

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#575]

**Comment by krschau** [comment]
PMs: which widgets would we want to pin by default?

**Comment by cinnamon-msft** [comment]
We should pin CPU, GPU, and Network by default. We could do some experimentation around this later, but I think those three are great to start with. :)

**Comment by krschau** [comment]
Reverted temporarily by https://github.com/microsoft/devhome/pull/2179
