### ISSUE TITLE
Excessive top margin space on page headers

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#592]
### Steps to reproduce the bug

Description

**Comment by crutkas** [comment]
this is larger than just summary, this is just across most things, this doesn't need design as this is stock app design guidelines.
![image](https://github.com/microsoft/devhome/assets/1462282/09015bf2-7746-4cff-ab6d-f8e201540349)

**Comment by krschau** [comment]
Duplicate of #869
