### ISSUE TITLE
Implement What's New page

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#602]
### Suggested new feature or improvement

The Introducing Dev Home page should become a What's New page once we send out our next release.

### Scenario

We're constantly adding new features and what's new should be showcased within Dev Home.

**Comment by dhoehna** [comment]
@cinnamon-msft this issue still a thing?

**Comment by cinnamon-msft** [comment]
Yeah, we have it designed and spec'd. Just waiting for implementation. :)
