### ISSUE TITLE
DevHome.Test needs to initialize the correct version of Windows App SDK.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#605]
### Steps to reproduce the bug

TODO in DevHome.Text.Initialize.cs
TODO in Devome.SetupFlow.UnitTest.Initialize.cs
TODO in DevHome.SetupFlow.UnitTest.Initialize.cs

**Comment by krschau** [comment]
@AmelBawa-msft, do you remember what this is about?

**Comment by AmelBawa-msft** [comment]
Closing since unit test run as of today's main branch. Please re-activate if necessary.
