### ISSUE TITLE
DeveloperID should be hashed and LoginId should not be used for telemetry events.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#611]
### Steps to reproduce the bug

TODO: DevHome.Common.DeveloperIdEvent.cs

However, the developer ID is hashed.  I believe this is an old comment.  Making the issue to track its removal.

This specific comment is in other XEvent.cs classes because developer id is used in other events.

This issue represents all classes that the "Don't use loginID and hash developerID" is present.

**Comment by vineeththomasalex** [comment]
This has been fixed:
https://github.com/microsoft/devhome/blob/90e272e9f2b6bcefa730147eb8e48f25961b7528/common/TelemetryEvents/DeveloperId/DeveloperIdEvent.cs
