### ISSUE TITLE
DevHome WinRT extension should use API contract to check if a member is avalible.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#625]
### Steps to reproduce the bug

TODO found in DevHome.SetupFlow.Common.WinRTObjectExtensions.cs

**Comment by krschau** [comment]
This may actually be the best way to do this (what if the API is added in v 2 but removed in v 10?)

**Comment by dhoehna** [comment]
My SDK change cemented how DevHome will check for the existence of API versions.  DevHome will [QI](https://github.com/microsoft/devhome/blob/main/tools/SetupFlow/DevHome.SetupFlow/Models/RepositoryProvider.cs#L241) the interface.
