### ISSUE TITLE
Add counting telemetry events instead of firing for every UI change.

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#628]
### Steps to reproduce the bug

Currently for filtering, and adding/removing repos via accounts page one telemetry event is fired.

This behavior should change to more of a "User removed X repos, added Y repos, Z of them were duplicates" something of that nature.

**Comment by dhoehna** [comment]
Closing as this is an old bug.  If the DAS team want to make this change a reality, please re-open this bug.
