### ISSUE TITLE
Remove "this" calls from Create Instance

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#631]
### Steps to reproduce the bug

TODO found in DevHome.SetupFlow.RepoConfigTaskGroup.cs

**Comment by krschau** [comment]
@AmelBawa-msft The task may be outdated but there's still a link to this issue in the code (https://github.com/microsoft/devhome/blob/29c3ce67aa81adc3e2c79c2ea4debf2a7687dd6e/tools/SetupFlow/DevHome.SetupFlow/TaskGroups/RepoConfigTaskGroup.cs#L35). Can you just remove that comment in an upcoming PR?
