### ISSUE TITLE
Use API to check if something requires elevation instead of try/catch

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#635]
### Steps to reproduce the bug

TODO found at DevHome.SetupFlow.WinGetPackage.cs

**Comment by AmelBawa-msft** [comment]
This was originally suggested for the OOP calls to WinGet. However, as naturally all OOP COM calls need to be try/catch-ed for RPC errors, checking for the version is nice to have but not necessary as of today's requirements. I will close this issue and if necessary, in the future, I will re-activate it.
