### ISSUE TITLE
NeedsReboot should consider other reboot scenarios

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#637]
### Steps to reproduce the bug

TODO found at DevHome.SetupFlow.ISetupTasks.cs

**Comment by balaji-sivasakthi** [comment]
@dhoehna need any help?

**Comment by dhoehna** [comment]
DevHome hasn't had to contemplate other restart scenarios.  The comment in ISetupTask is also removed.

A discussion can happen if other rebooting scenarios pops up.
