### ISSUE TITLE
File picker sometimes hangs the window after the dialog closes

### ISSUE THREAD

**Issue by AmelBawa-msft** [microsoft/devhome#657]
### Other software

 Example: When selecting a DSC configuration file

**Comment by roxk** [comment]
Other workaround includes hovering UI elements that are not close parents/sibling of the elements that generate the click, e.g. navigation bar. Resizing the window also works.

**Comment by AmelBawa-msft** [comment]
I am able to repro this issue from an empty WinUI project.
Created a new issue in WinUI repo with an example code:
- https://github.com/microsoft/microsoft-ui-xaml/issues/8527
