### ISSUE TITLE
[SDK] Update mentions of plugin to extension

### ISSUE THREAD

**Issue by asklar** [microsoft/devhome#66]
### Steps to reproduce

Standardize on "extension" rather than plugin. We should update the SDK accordingly.

**Comment by asklar** [comment]
still applicable, see e.g. https://github.com/microsoft/devhome/blob/main/pluginsdk/Microsoft.Windows.DevHome.SDK/Microsoft.Windows.DevHome.SDK.idl#L19

need to decide whether we do this before we hit 1.0 as this is abi breaking

**Comment by krschau** [comment]
FYI @ujjwalchadha
