### ISSUE TITLE
Apps to install are dropped from the UI if there is an exception in the elevated process

### ISSUE THREAD

**Issue by florelis** [microsoft/devhome#667]
### Steps to reproduce the bug

Not sure how to trigger it, but what happens is:

If there is an exception in the `ElevatedInstallTask()` on the elevated process side, we don't catch it and convert it to a failed result, instead we just let the exception propagate. When it gets back to the main process, the handling of this call in the `InstallPackageTask.ExecuteAsAdmin()` does not expect an exception, but rather that any error is converted to a failed task result. Since it doesn't expect it, we just let it propagate. Then on `LoadingViewModel.StartTaskAndReportResult()` what we do on an exception instead of setting the task result is just ignore it. So, we just don't have any result to show it for the task after this.

Things to change:
* Add exception handling to convert these errors to task failures
* Figure out what's causing the exception

**Comment by AmelBawa-msft** [comment]
PR: #1071

**Comment by florelis** [comment]
Closed by #1071
