### ISSUE TITLE
Marketplace & Library for extensions 

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#676]
### Suggested new feature or improvement

Dev Home is built to be extensible.  Users should have an easy way to find, install, & manage extensions built for Dev Home. This includes an **Extensions Marketplace** page & an **Extensions Library** page to support accessing & managing first- and third-party-built extensions directly within Dev Home.

**Extensions Marketplace:**
- Dev Home provides UI for users to discover & browse all of the Dev Home extensions published in the Microsoft Store
- Users can install extensions directly from Dev Home

**Extensions Library:**
- Dev Home provides UI for users to view all installed Dev Home extensions
- Users can check for updates, update, uninstall, sort, & view high-level details (i.e. version) for their installed Dev Home extensions

### Scenario

Getting / finding new Dev Home extensions.  

Managing installed Dev Home extensions.

**Comment by soroshsabz** [comment]
Please add sub menu or special tags into Microsoft Store, to help users better find Dev Home Extensions
