### ISSUE TITLE
How to import existing repos

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/devhome#703]
### Suggested new feature or improvement

How could I import already cloned repos from PC to app?

### Scenario

PC has already cloned repos

**Comment by Aaron-Junker** [comment]
Why would this be neccesairy? You already have them on your PC, so there's no need to redownload them. Or am I missing something here?

**Comment by JanRajnoha** [comment]
Maybe I don't understand it right, but I want to see it in app, but currently I could only download them
![image](https://github.com/microsoft/devhome/assets/16069721/b38a3d8b-5cb4-489a-a13f-343228743001)

**Comment by Aaron-Junker** [comment]
> Maybe I don't understand it right, but I want to see it in app, but currently I could only download them
> ![image](https://github.com/microsoft/devhome/assets/16069721/b38a3d8b-5cb4-489a-a13f-343228743001)
> 

So maybe I understand it wrong, but when you download it from here it won't appear in this list forever. It will just download it, like when using git clone

**Comment by JanRajnoha** [comment]
According to video probably in future updates you could directly access repos from file explorer
![image](https://github.com/microsoft/devhome/assets/16069721/f06f7449-ff73-413b-87e7-48d513324d13)
and this will be really helpful than in case of many repos you don't have to search manually, but you have it on one place and I think this will be linked to cloned repositories listed in app, but when I can't add already cloned repos, you won't see it, so therefore I ask, if is any possible way to add it there without removing it and cloned it again.

**Comment by dhoehna** [comment]
@JanRajnoha what expirence would you like if DevHome did find already existing repos?  Move them to the same location for new repos, something else?

**Comment by JanRajnoha** [comment]
I think it would be great to have one place for all repos in File Explorer, where I could go through them (like in provided screenshot from video)

**Comment by dhoehna** [comment]
Ahh, I understand.  You're looking for "I want to see all my repos, even the ones on my computer."

I was confused because the initial screenshots showed the RepoTool.  The RepoTool is for cloning repos from remote.  That led me to ask "If the Repo Tool does show repos already on your system, what do you want it to do?"

But, I see I misunderstood your intent.

**Comment by JanRajnoha** [comment]
And me too, because I thought it works like place, where I see all cloned repositories :D Sorry for useless issue - closed

**Comment by dhoehna** [comment]
> Sorry for useless issue
It isn't useless.  If you looked at this and thought "I can see all my repos" it means other people are also thinking the same thing.  This is a fantastic issue and I'm glad you made it.

**Comment by Aaron-Junker** [comment]
I have to admit I was firstly also tried to add an existing repo. But I got it after trying it with one repo.

**Comment by krschau** [comment]
Duplicate of #780
