### ISSUE TITLE
When connecting accounts, label it as "GitHub" instead of "Dev Home GitHub Extension"

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#709]
Current experience is confusing because I don't know what an extension is. I am connecting a GitHub account.

![image](https://github.com/microsoft/devhome/assets/53200638/1ce2e9ea-e241-43af-8e41-3567c77a577e)

**Comment by dhoehna** [comment]
Closing as multiple GitHub extensions would all show up as "GitHub".  This will stay the way it is.
