### ISSUE TITLE
Connecting GitHub account doesn't allow me to see all orgs

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#713]
After connecting a GitHub account, I cannot see any of the many organizations I have access to:

![image](https://github.com/microsoft/devhome/assets/53200638/ce2f15b2-2377-48de-bea1-7b067f38bc3b)

I would expect the picker (the one that says `localden`) to allow me to filter through organizations I have access.

Additionally, if I need to authorize additional organizations, I can't do that now from Dev Home and I need to go to GitHub OAuth settings to re-request permissions.

**Comment by dhoehna** [comment]
duplication of #831
