### ISSUE TITLE
Noticeable lag when connecting a repository and navigating to the account tab

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#715]
After adding an account, if I go back and add a repository, if I switch to the Account tab there is a clear, variable lag, likely caused by the web API call blocking the UI thread.

![lag-dev-home](https://github.com/microsoft/devhome/assets/53200638/174b787b-7e76-42da-9cda-71bd46de4afb)

**Comment by dhoehna** [comment]
Fixed with #1088
