### ISSUE TITLE
Application installation screen should be smarter about already installed apps

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#717]
Notice that I have Python already installed, at the exactly the same version.

The same view also suggests I install Visual Studio 2022 Community, when I already have the Enterprise edition installed.

![image](https://github.com/microsoft/devhome/assets/53200638/402a073b-619c-4e99-afaf-a4667f7d0c76)

It did detect VS Code, though.

![image](https://github.com/microsoft/devhome/assets/53200638/f9944634-b251-49ef-8213-71a5c174f8f5)

**Comment by localden** [comment]
@denelon 
![image](https://github.com/microsoft/devhome/assets/53200638/8ed7298a-ece2-44f3-b5f7-70d0ff2d7054)

**Comment by denelon** [comment]
How was it installed?
It looks like it might have something to do with the matching logic in WinGet, or the source of the original install.

**Comment by localden** [comment]
Directly from the Python website.

**Comment by denelon** [comment]
Can you share the URL so we can test?

**Comment by localden** [comment]
https://www.python.org/ftp/python/3.11.4/python-3.11.4-amd64.exe

**Comment by denelon** [comment]
I linked the Issue over at the WinGet community repository. It might be a simple case, of not having the latest version of Python.

**Comment by denelon** [comment]
I just noticed in the screenshot it looks like it's reporting 3.11.3 and the URL provided is 3.11.4. One of the WinGet community repository members already has a PR for the new version in the linked issue. Once that publishes, we can test and see if that resolves the issue, or if we need to dig in a bit further to see why we're not able to correlate based on the metadata in the registry keys behind Windows Apps & Features.

**Comment by cinnamon-msft** [comment]
I think this may be resolved. I'm not seeing apps I already have installed appearing in the popular apps list. I'm going to close as fixed, but let us know if you're still seeing this!
