### ISSUE TITLE
Failed tasks provide no context on the errors

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#718]
For example, cloning one of the repositories that I own gives me this:

![image](https://github.com/microsoft/devhome/assets/53200638/8286981a-6577-4435-b75c-82f47ca516c4)

I have no idea what this means or what I should do about it. Clicking on the card with the error does nothing. I can't even copy the error message and have to manually write it out in the search engine, which is somehow a Windows Store error?

![image](https://github.com/microsoft/devhome/assets/53200638/e4cde7b4-a651-4026-81a4-69b13e3abc64)

Why do I get a store error when cloning a Git repo? 🤔

**Comment by dhoehna** [comment]
Hello.  We are aware of the lack of information on the error messages and how frustrating it is to not find the correct solution.  This is a part of DevHome that we're aware of.  Adding issue-feature to get PM eyes on this.

**Comment by dhoehna** [comment]
Closed as fixed in #1509
