### ISSUE TITLE
Task retry does nothing

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#720]
Related to #718, retrying a task provides a message that is not helpful:

![image](https://github.com/microsoft/devhome/assets/53200638/2c00ff0a-033b-4299-9ec1-96f86aea9bc8)

I am not sure why the task can't be retried or why it couldn't be completed, yet am given the option to continue?

**Comment by localden** [comment]
@dhoehna I think we're talking about separate issues here? 😀 The main challenge above is that the error messages are contextually pointless - I, as a user, have no idea what an error code means. There is not even a button for me to go and Google the term.

**Comment by dhoehna** [comment]
> The main challenge above is that the error messages are contextually pointless
Yes.  I agree.  They are.  The Hresults for any failed task when cloning a repo is for a generic exception.  Not helpful.

>  it's also very hard to understand why the task cannot be retried.
That makes absolute sense.  A generic exception says nothing.

I understand that the story of how DevHome handles and displays exceptions is lacking.  Expecially when a user has no knowledge of how DevHome works.  This is an area that needs to be improved.

**Comment by dhoehna** [comment]
Errors now contain more information and not just a hex.
