### ISSUE TITLE
Option to configure from a file, with no way to export current configuration

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#721]
I am not sure what configuration file I can use here since there are no pointers anywhere in the UI about it. There is also no obvious way to _export_ the current configuration.

![image](https://github.com/microsoft/devhome/assets/53200638/824a4704-0fa0-4fb9-835a-eee739487022)

**Comment by fflaten** [comment]
👍 Was expecting a Export-button on the last page (Review & finish) of end-to-end setup wizard.

**Comment by AmelBawa-msft** [comment]
The YAML input expected here is a [WinGet Configuration](https://learn.microsoft.com/en-us/windows/package-manager/configuration/) file.

### Examples:
- You can use this [configuration file](https://github.com/microsoft/devhome/blob/main/.configurations/configuration.dsc.yaml) to help setup you machine for building Dev Home source code. Steps are available here: [Building the code](https://github.com/microsoft/devhome#building-the-code)
- You can also use the [sample configuration files](https://github.com/microsoft/devhome/tree/main/sampleConfigurations) to setup you machine for building other GitHub repositories.

**Comment by localden** [comment]
@AmelBawa-msft this issue is not necessarily related to the configuration file that I can import, but rather - I would expect an option to **export** the configuration after it was created through Dev Home.

**Comment by AmelBawa-msft** [comment]
@localden  thank you for the question and request. Adding PM @shakersMSFT to help with feature requests in the setup flow.

**Comment by florelis** [comment]
I know we have a DSC resource for winget, so a configuration file can include installed apps. But do we have DSC resources for git or Dev Drive? I'm also not sure how/if the configuration code handles accounts to be able to clone private repos

**Comment by ryfu-msft** [comment]
> I know we have a DSC resource for winget, so a configuration file can include installed apps. But do we have DSC resources for git or Dev Drive? I'm also not sure how/if the configuration code handles accounts to be able to clone private repos

@florelis, we don't have any DSC resources for git or Dev Drive. Currently for winget configure, we just assume that the github repository has already been cloned separately.

**Comment by florelis** [comment]
For creating the yaml configuration from the current machine state, I think the foundational work would be microsoft/winget-cli#3274. We would still need to integrate it into the Dev Home UI, but detecting the state and creating the file would probably be on the winget side

For creating a yaml configuration from the step by step setup provided by Dev Home, I think on the Dev Home side we could create one for applications, but for cloning and Dev Drive we would first need to have resources for that

**Comment by soroshsabz** [comment]
related to #685

**Comment by shakersMSFT** [comment]
Hi, we are currently exploring how we might accomplish this through Dev Home. Please take a look and let us know what you think! https://github.com/microsoft/devhome/issues/2160

**Comment by shakersMSFT** [comment]
fixed by https://github.com/microsoft/devhome/pull/2466
