### ISSUE TITLE
Getting "The widget could not be displayed" when opening the "Add widget" view for a few seconds

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#722]
Getting "The widget could not be displayed" when opening the "Add widget" view for 2-3 seconds before the widget loads. This should likely pre-load the data or show a loading indicator, otherwise this communicates an error state when it's not.

![image](https://github.com/microsoft/devhome/assets/53200638/3dd505d0-73ec-4b00-bf36-314a97b76c23)

**Comment by mathewleeza** [comment]
Duplicate of #1047

**Comment by krschau** [comment]
Duplicate of #595

**Comment by krschau** [comment]
Actually not really a dupe of 595 -- 595 is if the widget itself wants to display a progress ring.
