### ISSUE TITLE
Creating a dev drive takes me to a confusing view

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#725]
Clicking here:

![image](https://github.com/microsoft/devhome/assets/53200638/0ac790e7-8841-4893-872a-1cf2119bf3d4)

Takes me here:

![image](https://github.com/microsoft/devhome/assets/53200638/c10a34f0-c08e-4760-8e2f-4cd7476aaf98)

Not sure what I am supposed to configure here?

**Comment by loczek** [comment]
Same thing happens on the dev channel of windows

**Comment by Jinjiang** [comment]
+1 didn't find the option to create a dev drive. I think the prerequisites have been all reached.

https://learn.microsoft.com/en-us/windows/dev-drive/#prerequisites

<img width="483" alt="Screenshot 2023-05-24 163740" src="https://github.com/microsoft/devhome/assets/206848/457cd871-0e2a-4c96-b4f9-8d68b148b127">

<img width="479" alt="Screenshot 2023-05-24 163547" src="https://github.com/microsoft/devhome/assets/206848/2c3944aa-615d-4e44-bb16-975ba8bb7b86">

<img width="492" alt="Screenshot 2023-05-24 163816" src="https://github.com/microsoft/devhome/assets/206848/23abba1a-8107-45a3-bdf5-408b6132e646">

**Comment by bbonaby** [comment]
@localden, @Jinjiang @fflaten @loczek 
Dev Drive functionality was released today in build 23466.

https://blogs.windows.com/windows-insider/2023/05/24/announcing-windows-11-insider-preview-build-23466/

Let us know/create another issue if anything else you see from that build seems out of place. Thanks. Will update our check in Dev Home with this build number for now.

**Comment by fflaten** [comment]
Thanks for the update @bbonaby, will try it out 😃 

Still, the app is also available for stable channel so the button should inform users with unsupported builds some way.

**Comment by innellea** [comment]
I'm on the dev build, `23466.1001`, and it isn't showing up.

**Comment by Jinjiang** [comment]
It works. Thanks.

**Comment by innellea** [comment]
Hey @Jinjiang, what happened? Did you change anything, or has it just appeared?

**Comment by Jinjiang** [comment]
I just updated my Windows to the latest dev version and the button showed up immediately
