### ISSUE TITLE
Widget ordering is not consistent

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#726]
I set up my widgets like this:

![image](https://github.com/microsoft/devhome/assets/53200638/e9a8e723-aca3-44de-b7bf-0c1782cb6ee8)

Navigating away from the view and back to it now gives me this:

![image](https://github.com/microsoft/devhome/assets/53200638/40d7992a-6f3f-44df-88e6-6fed18930585)

**Comment by krschau** [comment]
Duplicate of #463
