### ISSUE TITLE
When searching for applications, no context is given around authenticity or authorship

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#729]
See example when searching for "GitHub":

![image](https://github.com/microsoft/devhome/assets/53200638/39d1c9c2-ff10-49ce-ac6c-f852fde25c4d)

Gets even funkier when you try to disambiguate between different results with the same name - which of these is the legit one?

![image](https://github.com/microsoft/devhome/assets/53200638/3e500d45-9089-4d5c-ad19-32d9426b24fa)

![image](https://github.com/microsoft/devhome/assets/53200638/da09ce87-6831-475e-a44e-e9222ff82f76)

**Comment by AmelBawa-msft** [comment]
@localden, information about the publisher is visible when a newer version of winget is installed. You can get the latest winget version by updating your [App Installer](https://apps.microsoft.com/store/detail/app-installer/9NBLGGH4NNS1?hl=en-us&gl=us) application then restarting Dev Home.

Here's an example of the search result with newer version of winget installed:

<img src="https://github.com/microsoft/devhome/assets/104940545/c6d31aea-d0cc-4b1c-a5ca-29edccec8f5c" />

**Comment by shakersMSFT** [comment]
This is a result of not having the latest version of App Installer. If this issue persists when updated, please re-open and let us know.
