### ISSUE TITLE
Machine Configuration: node.js is cancelled but continues to run.

### ISSUE THREAD

**Issue by Zakpak0** [microsoft/devhome#733]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Add any extension,
Add the Node.js extension, click next.
When prompted by windows to allow Node.js to make changes to your device, click no.

### Expected result

Installation should cancel completely or cancel the node.js installation and continue to the next installation.

### Actual result

Installation say's node.js is cancelled, continues to run. But shows now progress or noticeable change.

### Included System Information

CPU: AMD Ryzen 9 5900X 12-Core Processor            
Physical Memory: 63.91GB (32.94GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
Hello.

Can you still repro the issue with version 0.200?  I am not able to repro this issue.
Here is a movie of me trying to repro the issue.

Movie!
![StoppingNodeJs](https://github.com/microsoft/devhome/assets/2517139/a249c93d-c16d-4a52-aaea-dd2686d603b2)
