### ISSUE TITLE
Add repo already cloned to local drive

### ISSUE THREAD

**Issue by csymonds** [microsoft/devhome#737]
### Suggested new feature or improvement

Unless I am missing it, I cannot seem to add a repo that I have already cloned to my local drive. I don't want to have to clone it again.

### Scenario

If I already have a repo cloned to my local computer, I would like to add that repo instead of having to clone again. If this is already possible, it is not obvious how to do it.

**Comment by krschau** [comment]
Duplicate of #703

**Comment by krschau** [comment]
Duplicate of #780
