### ISSUE TITLE
full screen close button not working

### ISSUE THREAD

**Issue by iAkashPattnaik** [microsoft/devhome#740]
### Dev Home version

0.137.141.0

### Windows build number

10.0.25309.0

### Steps to reproduce the bug

Just Installed the app on my pc after pinning memory widget to home, on full screen the close button doesn't work.

### Expected result

It should work?

### Actual result

After changing the size a bit it works but not in full screen mode.

### Included System Information

<img width="752" alt="image" src="https://github.com/microsoft/devhome/assets/55914808/91c90694-825f-48ee-a6d4-00a5b406e386">

**Comment by krschau** [comment]
@iAkashPattnaik Could you attach a screenshot of the app when the Close button isn't working?

**Comment by iAkashPattnaik** [comment]
https://github.com/microsoft/devhome/assets/55914808/d8b41be0-2b42-4dcc-8eb3-377420abfc32

Here you go, as you can see, on full screen it doesn't close, it works for `Alt+F4` but not the button.
