### ISSUE TITLE
Pinned widgets were not persisted 

### ISSUE THREAD

**Issue by pcisko** [microsoft/devhome#742]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Pin widgets to app (I used CPU, GPU, Memory and Network). PC then froze and restarted(not sure crash was related to DevHome or not). After restart re-open app and the widgets were no longer pinned

### Expected result

Pinned widgets should persist

### Actual result

Pinned widgets did not persist

### Included System Information

CPU: AMD Ryzen 7 Microsoft Surface (R) Edition
Physical Memory: 29.98GB (20.01GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by Bennett-Fourr** [comment]
Any news on this?

**Comment by krschau** [comment]
@Bennett-Fourr and everyone: please try going to the store and updating the Windows Web Experience Pack. Version 523.17300.0.0 has the fix for this.

**Comment by krschau** [comment]
The fix is available to Insiders (update the Windows Web Experience Pack to 523.17300.0.0). There is no fix out yet for the 423 version, so moving this out to the next milestone. Once that version comes out, we'll update the min required versions and close this.

**Comment by krschau** [comment]
Moving out to the 0.5 milestone, when I'm hoping I can make code changes to require the higher versions of the Web Experience Pack.

**Comment by krschau** [comment]
Everyone should have been on a version of the WebExperiece Pack with this fix for quite some time.
