### ISSUE TITLE
top bar button reversed in RTL

### ISSUE THREAD

**Issue by Mi3liX9** [microsoft/devhome#744]
### Dev Home version

0.137.141.0

### 🌐 Language

Arabic

### ❌ Actual phrase(s)

The top bar button is reversed in RTL. When I press close nothing happens, but when I click from left the program closes

### Why is the current translation wrong

The arrangement is worng

**Comment by mathewleeza** [comment]
Thank you for your input. To appropriately triage this issue, do you mind providing a screenshot?

**Comment by krschau** [comment]
https://task.ms/38444281
