### ISSUE TITLE
WSL Integration

### ISSUE THREAD

**Issue by datasantana** [microsoft/devhome#748]
### Suggested new feature or improvement

It'd be nice to integrate WSL since it is my primary local dev environment

### Scenario

When cloning repositories, I'd like to set it up in a path inside WSL

**Comment by FreekVR** [comment]
Second this, would love to see some WSL integrations, for example also:

- Managing WSL itself, monitoring its resources etc. via widgets
- Using the SSH keychain to open connections via OpenSSH in the WSL terminal, rather than through CMD on the Windows host machine
- Running all the bootstrapping command for new projects within WSL

**Comment by mandarinamdar** [comment]
+1, WSL integration is critical for me to leverage devhome. Looking forward to having this supported in Devhome.

**Comment by denelon** [comment]
We've got work to do on the WinGet side to help here:
* https://github.com/microsoft/winget-cli/issues/3320

**Comment by reacts99** [comment]
Support to all the above comments, i think i speak for near all of Devs when i said that we have set up our entire development environment inside WSL. But needless to say that DevHome features are looking good. 🤩 🎉

**Comment by 0xLunch** [comment]
Also would love to see WSL2 integration (or perhaps a future WSL3 feature?).
Dev Home and more specifically Dev Drives are quite interesting to me. But as someone who strictly uses a WSL2 environment on their Windows PC I see no reason to utilize this new feature and file system.

If the reported performance benefits of dev drives can be made possible in the linux filesystem that would be quite impressive. And of course the project management aspects would be nice.
