### ISSUE TITLE
[Japanese translation] Link to end user agreement in end of end to end setup is not clickable

### ISSUE THREAD

**Issue by fusuimoe** [microsoft/devhome#751]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Open app in Japanese environment. Proceed end-to-end setup to the final agreement step shown below.

![image](https://github.com/microsoft/devhome/assets/74000913/54ab6c9a-3e15-4e92-88cc-9093173d3821)

### Expected result

The text [詳細情報] is clickable and linked to the user agreement page

### Actual result

You cannnot read the agreement because the link is not clickable

### Included System Information

CPU: AMD Ryzen 9 4900H with Radeon Graphics         
Physical Memory: 31.42GB (17.32GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
FYI @ssparach

**Comment by AmelBawa-msft** [comment]
@fusuimoe, thank for reporting this issue and sorry for the delayed response. The message in the review page has been updated with the following one: 

> By continuing, you acknowledge that these applications are licensed to you by the owner. Microsoft is not responsible for, nor does it grant any licenses to third-party applications. You are responsible for reviewing any agreements related to your use of these applications, you can select the ‘Applications’ tab to view ‘learn more’ links.

You can find the 'Applications' tab and the 'learm more' buttons here:
![image](https://github.com/user-attachments/assets/3e23fd4f-79a6-48e1-ad2e-795f439ff6f2)
