### ISSUE TITLE
Remove/alter terms checkbox when cloning git repositories

### ISSUE THREAD

**Issue by BreeceW** [microsoft/devhome#754]
### Suggested new feature or improvement

When you use the Clone repositories feature, the wizard takes you to a confirmation page that says “Review the terms” and has a checkbox for “I agree and want to continue.” This is confusing and I assume unnecessary for only cloning repositories and not installing apps.

### Scenario

If no apps are being installed, the mentions of terms and the agreement checkbox should be removed.

**Comment by dhoehna** [comment]
Fixed in #1191.  Terms and agreements show up only if apps are installed.
