### ISSUE TITLE
Provide YAML template

### ISSUE THREAD

**Issue by fordprefect480** [microsoft/devhome#756]
### Suggested new feature or improvement

Make a YAML template for the Machine Configuration available for developers to get started with.

### Scenario

A dev could download the template and tweak it to include/exclude applications they want to install.

**Comment by localden** [comment]
Likely a dupe of #721

**Comment by AmelBawa-msft** [comment]
Here are some [sample configuration files](https://github.com/microsoft/devhome/tree/main/sampleConfigurations) which you can use as a reference. I posted more details and examples in this comment: https://github.com/microsoft/devhome/issues/721#issuecomment-1560364612

Let me know if those files/links help with this issue, or if you have alternative suggestions
