### ISSUE TITLE
Widget graph is not anti-aliased, and is consuming too much resources

### ISSUE THREAD

**Issue by roxk** [microsoft/devhome#760]
### Dev Home version

0.137.141.0

### Windows build number

22624.1755

### Steps to reproduce the bug

Code:
At https://github.com/microsoft/devhome/blob/main/CoreWidgetProvider/Helpers/ChartHelper.cs#L9, it's evident that the graph are rendered with `system.drawing`, which shouldn't really be used, given XAML's path rendering capability and [RenderTargetBitmap](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.imaging.rendertargetbitmap?view=windows-app-sdk-1.3). An alternative that is even better in terms of payload bandwidth and performance is svg. Graph rendering should just use svg.

App:
1. Launch dev home, pin any graph widget.

### Expected result

Graph is anti-aliased. Also consume little resources.

### Actual result

Graph is not anti-aliased (pixelated). Consumes lots of resources (also see #716).

**Image showing graph is not AA-ed. Enlarged for reference (not to scale, was using paint)**
![image](https://github.com/microsoft/devhome/assets/16918354/c1419222-8063-4068-8db2-1448705755e9)

**Comment by krschau** [comment]
Moving this to the 0.3 milestone. I checked in #1093 which does use antialiasing, but doesn't fix the bigger performance issue.
