### ISSUE TITLE
Extension section in setting is blank

### ISSUE THREAD

**Issue by nathangur** [microsoft/devhome#763]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22624.1755

### Other software

OS Build Version: 10.0.22624.1755.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Just click extensions in settings

### Expected result

To show a list of stuff to install so I can add github

### Actual result

It's just blank

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
Physical Memory: 63.73GB (39.65GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Extensions are available to install from the Extensions page, rather than the Extensions page within Settings.

**Comment by nathangur** [comment]
Glad to hear! Thank you!
