### ISSUE TITLE
Connect to GitHub button not working

### ISSUE THREAD

**Issue by mrlacey** [microsoft/devhome#766]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Settings > Accounts > Add account 

### Expected result

Able to connect to my GutHub account

### Actual result

Clicking on the "Sign in to github.com" button did nothing

### Included System Information

CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Physical Memory: 15.92GB (2.44GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by mrlacey** [comment]
possible duplicate of #753

**Comment by manodasanW** [comment]
@mrlacey Do you happen to see this issue consistently or does it work sometimes if you close the _Add account_ dialog and try again?

**Comment by mrlacey** [comment]
I have since connected my account - not sure how and can no longer repro this issue. 😞 
Even signing out nad then back in again doesn't repro.

**Comment by manodasanW** [comment]
Thanks for confirming.  Most likely the below issue.

/dup https://github.com/microsoft/devhomegithubextension/issues/108
