### ISSUE TITLE
Cannot clone private GitHub repositories

### ISSUE THREAD

**Issue by agrmohit** [microsoft/devhome#777]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23419.1000

### Other software

OS Build Version: 10.0.23419.1000.amd64fre.ni_prerelease.230317-1432
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Enter a private GitHub repository url which the signed in account has access to in the Add Repository part

### Expected result

The repository should be cloned since singed in account has access to it

### Actual result

It fails to clone the repository with error 0x80131500

### Included System Information

CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Physical Memory: 7.85GB (0.61GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by andrew-turrentine** [comment]
I am getting the same error code on a public repository as well

**Comment by dhoehna** [comment]
Hello!

DevHome cloning will throw an exception when the directory being cloned to exists and is not empty.  Can you please verify that the location you are cloning to is either
1. not-existent, or
2. empty.

Thanks.

**Comment by agrmohit** [comment]
On trying again, it is able to successfully clone the repository now. 

Its very likely unrelated but cloning any repository creates a symbolic link named `_git2_a<5 digit number>` which points to a non-existent `testing`. This happens on both public and private repositories.

Examples: 
`_git2_a22392` -> `testing`
`_git2_a27800` -> `testing`

Please let me know if this is expected and if its not should I create a separate issue for this and close this.

**Comment by dhoehna** [comment]
Hey @agrmohit I am glad you got it working.

Can you please explain more about the symbolic link?  I can't make the connection between your issue and making a symbolic link.

**Comment by agrmohit** [comment]
I was just mentioning that Dev Home creates a symbolic link with a random name to a non existent `testing` directory inside every cloned repository. I mentioned it here because I only noticed it after I was able to clone private repositories successfully but other than that I don't see how it could be related.

**Comment by dhoehna** [comment]
That looks like something with libgit2.  I'd recommend to bring this issue up with them at https://github.com/libgit2/libgit2.

I don't see a file on my computer with that name.

However, I am closing this as the issue seemed to get resolved.
