### ISSUE TITLE
Cannot connect to Organizations having 2FA requirement

### ISSUE THREAD

**Issue by bstordrup** [microsoft/devhome#778]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.0

### Steps to reproduce the bug

Login with an account that has access to organizations that have 2FA required, and then grant access to the organization during login.

### Expected result

Expected to be guided to the authentication page allowing the organization to give access to the application.

### Actual result

Just getting a spinning wheel that never stops until I click the Authorize button, and then I do not have access to the organization. Is not able to find repositories in it although I easily can in GitHub and in Visual Studio.

**Comment by bstordrup** [comment]
Might be related to #713

**Comment by mikebattista** [comment]
Is the spinning wheel in the browser? Could you share a screenshot if possible?

**Comment by vineeththomasalex** [comment]
Duplicating to #713
