### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by ashraf-kabir** [microsoft/devhome#787]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Go to dashboard, add two or three new widget one after another and the app will crash.

### Expected result

App should remain stable while adding a new widget.

### Actual result

App crashes while adding dashboard widgets.

### Included System Information

CPU: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
Physical Memory: 31.94GB (22.1GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
@ashraf-kabir Would you be able to share your log files under C:\Users\<you>\AppData\Local\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\TempState? You can share via a OneDrive link or open a Feedback Hub issue and attach a zip file there.

**Comment by derkoe** [comment]
I have the same issue - the UI crashes. The process still seems to be there in the background - had to stop it to zip the files in TempState.

[TempState.zip](https://github.com/microsoft/devhome/files/11562873/TempState.zip)
