### ISSUE TITLE
Create a Dev Drive

### ISSUE THREAD

**Issue by jhasmany-fernandez** [microsoft/devhome#792]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23451.1000

### Other software

OS Build Version: 10.0.23451.1000.amd64fre.ni_prerelease.230428-1438
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

The virtual drive option does not appear in the system > storage path > Disks & volumes, to create the virtual drive

### Actual result

![image](https://github.com/microsoft/devhome/assets/36086876/e24cefbb-e055-4186-be76-2a16ff7f1bb1)

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i7-12650H
Physical Memory: 15.63GB (3.35GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by XHQ6666** [comment]
It appeared in previous versions of Canary but disappeared later. It may require using "vivetool" to enable it or waiting for the next Windows update.

**Comment by bbonaby** [comment]
Hey @localden, @jhasmany-fernandez , @XHQ6666 . You should be able to create a Dev Drive using build 23466 in the dev channel released today

https://blogs.windows.com/windows-insider/2023/05/24/announcing-windows-11-insider-preview-build-23466/

**Comment by XHQ6666** [comment]
> Hey @localden, @jhasmany-fernandez , @XHQ6666 . You should be able to create a Dev Drive using build 23466 in the dev channel released today
> 
> https://blogs.windows.com/windows-insider/2023/05/24/announcing-windows-11-insider-preview-build-23466/

I am using the Canary version, and I have previously enabled it using "vivetool." However, I have noticed significant differences in the update content.

**Comment by jhasmany-fernandez** [comment]
con el Update fue solucionado el inconveniente con la creacion dev drive
