### ISSUE TITLE
Botón Agregar Cuenta GitHub no funciona

### ISSUE THREAD

**Issue by danespino** [microsoft/devhome#793]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22624.1755

### Other software

OS Build Version: 10.0.22624.1755.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Al tratar de agregar cuenta y sale un modal window con el logo de GitHub y tras presionar el botón de Inicio de Sesión no avanza a otras pantallas ni lanza una instancia del navegador.

When trying to add a new GitHub account after clicking the assigned button, it throws a modal window with Github's logo in. Nothing else happens after hitting the Login Button (it doesn't show any other screen or throws a browser's instance).

Additional info: I use Mozilla Developer as a default web browser (I do have Edge and Chrome on my PC also).

### Expected result

Loguearse en GitHub mediante un navegador o introduciendo los datos de la cuenta.  |  Get logged-in in GitHub using a web browser or entering account's information

### Actual result

No ha pasado nada.    |  Nothing Happened (I wasn't able to login to my GitHub account by any means)

### Included System Information

CPU: AMD Ryzen 7 4700U with Radeon Graphics         
Physical Memory: 15.36GB (9.06GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by danespino** [comment]
It worked now... Apparently, it didn't throw the browser's instance but after reporting it... it began working apparently... Closing issue... Sorry guys...

**Comment by krschau** [comment]
Duplicate of #472

This is a real issue, but only shows up sometimes.
