### ISSUE TITLE
Auto discover Apps and Repositories

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/devhome#800]
### Suggested new feature or improvement

For an already setup environment the tool don't recognize existing applications or don't allow to add from an existing repository

### Scenario

Loading the application for the first time in an existing environment I'm unable to add my existing Repositories folders

**Comment by asklar** [comment]
(half) duplicate of #799

**Comment by AmelBawa-msft** [comment]
For the application-recognition part of the issue: https://github.com/microsoft/devhome/issues/788#issuecomment-1561687716

**Comment by asklar** [comment]
Duplicate of #702
