### ISSUE TITLE
Visual Studioのインストール検出

### ISSUE THREAD

**Issue by hatsunea** [microsoft/devhome#805]
### Suggested new feature or improvement

Enterpriseなど上位エディションがインストールされているときは、Visual Studioは「インストール済」と判定してほしい

### Scenario

インストール済と判定してもらえば、Communityを新たにインストールしようとしなくて済む

**Comment by topia** [comment]
For people doing triage: This is a dupe of #771 but written in Japanese

**Comment by hatsunea** [comment]
Visual Studio installation detection

When a higher edition such as Enterprise is installed, Visual Studio should determine that it is "installed".

If it is determined that it is already installed, there is no need to install a new Community
