### ISSUE TITLE
Requires to be run as admin otherwise app will crash on the first run

### ISSUE THREAD

**Issue by quadflame** [microsoft/devhome#817]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Install the app, run as normal user

### Expected result

ask for admin permission to install

### Actual result

app opens then crashes

### Included System Information

CPU: Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
Physical Memory: 31.89GB (25.12GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by cinnamon-msft** [comment]
Making sure we've got this right, the app crashes if you _don't_ launch as admin, but works fine if you right click -> launch as admin?

**Comment by denelon** [comment]
Which specific app was selected?

**Comment by QuadFlame** [comment]
> Which specific app was selected?

Dev Home (Preview) downloaded from ms store. I downloaded this 9 hours after the latest github release was published.
I hope this is the information you need.

**Comment by krschau** [comment]
@QuadFlame Is this still an issue you're hitting? We've heard some other instances of crashes, but no other ones where it consistently crashes in non-admin and works in admin. I'm wondering if it's either something the other reports haven't noticed, or a coincidence that it didn't crash when you happened to run as admin.

**Comment by QuadFlame** [comment]
> @QuadFlame Is this still an issue you're hitting? We've heard some other instances of crashes, but no other ones where it consistently crashes in non-admin and works in admin. I'm wondering if it's either something the other reports haven't noticed, or a coincidence that it didn't crash when you happened to run as admin.

It crashed multiple times on first run after install (maybe it needed admin privileges to finish installing something), so once I ran it with admin, it now works without admin
