### ISSUE TITLE
App sometimes crashes after clicking arrow button when installing applications

### ISSUE THREAD

**Issue by QuadFlame** [microsoft/devhome#818]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Start installing applications. Click > button.

### Expected result

Go to the next applications page

### Actual result

crashed dev home

### Included System Information

CPU: Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
Physical Memory: 31.89GB (25.1GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by AmelBawa-msft** [comment]
Duplicate #818
