### ISSUE TITLE
crash of aplication

### ISSUE THREAD

**Issue by gVelezCasas** [microsoft/devhome#823]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

actualize a wiget and the aplication sometimes crash out of the blue and i have to reopen the app

### Expected result

well the result that i hope to see is no crash when actualizing a plugin buit i now is in the early stage but for this is the testing

### Actual result

well cruh of the aplication

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i9-13900K
Physical Memory: 31.79GB (19.04GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
@gVelezCasas Would you be able to share your log files under C:\Users<you>\AppData\Local\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\TempState? You can share via a OneDrive link or open a Feedback Hub issue and attach a zip file there.
