### ISSUE TITLE
Adding a second account

### ISSUE THREAD

**Issue by jpmchia** [microsoft/devhome#824]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22624.1755

### Other software

OS Build Version: 10.0.22624.1755.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. Successfully add a personal GitHub account.
2. Attempt to add another account via the Settings option.

### Expected result

Browser to open with GitHub login page to allow the authorisation of another account.

### Actual result

Browser token flow kicks-off and returns you to Dev Home with a dialog box stating "something went wrong :("

### Included System Information

CPU: AMD Ryzen 9 5950X 16-Core Processor            
Physical Memory: 127.92GB (63.95GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by manodasanW** [comment]
I was able to add a second account, but then repeating it again I ran into the something went wrong message.  Tracking this investigation as part of our something went wrong issue.

/dup https://github.com/microsoft/devhomegithubextension/issues/119
