### ISSUE TITLE
winget no package found matching input criteria

### ISSUE THREAD

**Issue by hoppalazi** [microsoft/devhome#828]
### Provide a description of requested docs changes

According to documentation at [https://github.com/microsoft/devhome#via-windows-package-manager-cli-aka-winget](https://github.com/microsoft/devhome#via-windows-package-manager-cli-aka-winget) devhome can be installed with winget.
But using the documented command only results in the error "No package found matching input criteria.".
Currently there doesn't exist a devhome winget package.
Maybe the documentation should be corrected, until a package is released, to not confuse people.

**Comment by tzzs** [comment]
That's true. I have the same problem.

**Comment by denelon** [comment]
Thanks to @mdanish-kh for working through the process to make it a .zip package for now. We will update the release process and docs to provide a better experience after the holiday weekend.

**Comment by denelon** [comment]
The PR was merged, and the instructions should be valid now.

We still need to update the release process.

**Comment by denelon** [comment]
Thanks @mdanish-kh 

https://github.com/microsoft/devhome/blob/main/.github/workflows/winget-submission.yml
