### ISSUE TITLE
Export current computer config

### ISSUE THREAD

**Issue by hannesne** [microsoft/devhome#829]
### Suggested new feature or improvement

I would love to be able to export my current config, including applications that could be installed using winget and other mechanisms. 

### Scenario

I would use this when I have to shift to a new computer or rebuild my computer.

**Comment by AmelBawa-msft** [comment]
Possibly a duplicate #721

**Comment by AmelBawa-msft** [comment]
Closing to track all export config features in one issue.

**Comment by krschau** [comment]
Duplicate of #721
