### ISSUE TITLE
can't sign in again to add GitHub orgs

### ISSUE THREAD

**Issue by kyleshrader** [microsoft/devhome#836]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22000.1936

### Other software

OS Build Version: 10.0.22000.1936.amd64fre.co_release.210604-1628
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Signed in as my user. Now try to add repo, but don't see orgs.
Try to add account, it opens GitHub and says I'm signed in as myself.
can't add org

### Expected result

I expected to be able to select repos from the orgs im in, or atleast add an org as an account.

### Actual result

Signed in as my user. Now try to add repo, but don't see orgs.
Try to add account, it opens GitHub and says I'm signed in as myself.
can't add org

### Included System Information

CPU: AMD Ryzen 5 1600 Six-Core Processor            
Physical Memory: 63.95GB (34.33GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by rifkitech** [comment]
**I also experienced the same problem**

But now it can be resolved.
