### ISSUE TITLE
Can't make a dev drive

### ISSUE THREAD

**Issue by TechElliott** [microsoft/devhome#837]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23451.1000

### Other software

OS Build Version: 10.0.23451.1000.amd64fre.ni_prerelease.230428-1438
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Try to make a dev drive and it will fail with error code 0x80131501

### Expected result

To make a dev drive on my PC

### Actual result

All items failed

### Included System Information

CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Physical Memory: 31.91GB (25.57GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by bbonaby** [comment]
That build won't have the Dev Drive feature enabled.  The feature should be in https://blogs.windows.com/windows-insider/2023/05/24/announcing-windows-11-insider-preview-build-23466/. I'm updating the build number check to 23466 in this PR #822 so you'll need to upgrade to that build (it was released today) to try out Dev Drives.

**Comment by TechElliott** [comment]
Oh, I forgot

**Comment by TechElliott** [comment]
Updating Windows now

**Comment by daryllabar** [comment]
@bbonaby Is there a general estimate of when the dev drive will not require a preview build of windows?

**Comment by TechElliott** [comment]
This fall maybe
