### ISSUE TITLE
Github account

### ISSUE THREAD

**Issue by rifkitech** [microsoft/devhome#838]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Go to Settings, Account & Login to Github

### Expected result

Fix this problem, becauce i can't login to my Github account when i click Login button

### Actual result

The result is very bad

### Included System Information

CPU: Intel(R) Celeron(R) N4020 CPU @ 1.10GHz
Physical Memory: 3.83GB (1.09GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by rifkitech** [comment]
![Screenshot (61)](https://github.com/microsoft/devhome/assets/112795137/80ff5330-2504-4ac1-8007-f37afe95c152)

![Screenshot (62)](https://github.com/microsoft/devhome/assets/112795137/8400a2ab-9321-45f8-b877-ac68e11d3639)

![Screenshot (63)](https://github.com/microsoft/devhome/assets/112795137/64f15e04-5def-4e15-9350-d7b9c0c530b2)


**It works, but after authentication, it doesn't switch directly to the Dev Home app**

**Comment by rifkitech** [comment]
![Screenshot (64)](https://github.com/microsoft/devhome/assets/112795137/112c2f1c-1274-4799-8c3d-b3fc44c0ea12)

Success. Thanks Microsoft✨

**Comment by rifkitech** [comment]
***Terima Kasih***😎

**Comment by krschau** [comment]
Duplicate of #472
