### ISSUE TITLE
Cannot add repositories

### ISSUE THREAD

**Issue by halink0803** [microsoft/devhome#839]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

End to end set up > add repositories > copy link of git@... > app close unexpectedly

### Expected result

Repo added to dev home

### Actual result

App close unexpectedly

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
Physical Memory: 15.71GB (1.43GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
Hello!

Just to make sure you and I are on the same page.  Are you referring to SSH links?  For example DevHome is git@github.com:microsoft/WindowsAppSDK.git

**Comment by dhoehna** [comment]
FYI: I can repro this with git@github.com:microsoft/WindowsAppSDK.git
