### ISSUE TITLE
Crash on swiping the install apps screen (with trackpad) or scrolling (with mouse)

### ISSUE THREAD

**Issue by ZackFairMoaz** [microsoft/devhome#845]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1413

### Other software

OS Build Version: 10.0.22621.1413.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Fix this bug of crashing by navigation (code error)

### Expected result

Scroll through app installer on dev home

### Actual result

The App Crashes

### Included System Information

CPU: AMD Ryzen 7 6800H with Radeon Graphics         
Physical Memory: 15.25GB (7.82GB free)
Processor Architecture: x64

**Comment by AmelBawa-msft** [comment]
Duplicate #768
