### ISSUE TITLE
Ability to add existing repositories from a cloned folder

### ISSUE THREAD

**Issue by jamesmcroft** [microsoft/devhome#846]
### Suggested new feature or improvement

Currently, you can only clone new repositories. It would be great if you could add existing repositories that already exist on drive.

### Scenario

Either you can point to a folder that contains one or more git repositories and it automatically adds them, or add individual ones.

**Comment by jamesmcroft** [comment]
After having a play around, I may have misinterpreted how the repository cloning feature works. I'd assumed it indexed the repositories and allowed you to interact with them from within Dev Home but that's not the case.

**Comment by krschau** [comment]
Duplicate of #780
