### ISSUE TITLE
Add widget to dashboard doesn't work for "Core" widgets on ARM64

### ISSUE THREAD

**Issue by gknowd** [microsoft/devhome#855]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.arm64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

When I try and add a widget for any item under the "Core" widgets nothing shows up or I get a "cannot display information" message

### Expected result

Ability to see widget data and ability to add a widget to the screen

### Actual result

Nothing or no data is displayed

### Included System Information

Physical Memory: 31.41GB (19.66GB free)
Processor Architecture: ARMx64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_arm64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_arm64__8wekyb3d8bbwe

**Comment by krschau** [comment]
If you give it a while to load, do the Core widgets eventually display? See issue #722
