### ISSUE TITLE
Only CPU widget stays on Dev Home relaunch

### ISSUE THREAD

**Issue by cartifanwlr** [microsoft/devhome#856]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22624.1755

### Other software

OS Build Version: 10.0.22624.1755.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Pinning a few widgets to the dashboard and restarting the app will only show the CPU widget.

### Expected result

All widgets I pinned show.

### Actual result

Only CPU widget was shown.

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i5-1235U
Physical Memory: 15.64GB (3.43GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Did you only restart the app or restart your machine? (The machine restart issue has been previously reported.)
