### ISSUE TITLE
GitHub Authenticator identification

### ISSUE THREAD

**Issue by GraniteStateHacker** [microsoft/devhome#858]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23466.1001

### Other software

OS Build Version: 10.0.23466.1001.amd64fre.ni_prerelease.230522-1422
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

When I connected my GitHub account I authenticated using the authenticator on my phone.  The authentication flow asked me on my iPhone to enter the number shown in the browser on my PC.  The authentication dialog identified itself incorrectly. 

### Expected result

It feels like the authentication request phone popup should have been more on-brand.

### Actual result

Phone prompt dialog said something like "Sudo" account...  I understand what it meant, but I worry a less experienced developer might be scared off by it.

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
Physical Memory: 15.73GB (3.27GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by Aaron-Junker** [comment]
It probably said "sudo mode" which just means that you give devhome some more capabilites to make certain things.

**Comment by GraniteStateHacker** [comment]
Yes, I think that was it...  I would have expected it to have some kind of clear indication/reference that it was related to connecting to Dev Home. Without the clear ref, I momentarily worried that this might be some kind of MitM concern.

**Comment by asklar** [comment]
@GraniteStateHacker I believe that is GitHub's own authentication UI. See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/sudo-mode

**Comment by mikebattista** [comment]
Agreed this sounds out of the control of Dev Home.
