### ISSUE TITLE
Persist the list of cloned repo's

### ISSUE THREAD

**Issue by azureholic** [microsoft/devhome#861]
### Suggested new feature or improvement

I really like the fast onboarding of repo's. Keep the list of cloned repo's persistent after the fact. That way I can see which repo's I have cloned already.

### Scenario

Machine configuration -> Clone Repositories -> Add Repository
Maintain the list of repo's I've cloned earlier.

**Comment by dhoehna** [comment]
PR for thsis fix is here: https://github.com/microsoft/devhome/pull/668
