### ISSUE TITLE
Ability to generate configuration file from end to end setup

### ISSUE THREAD

**Issue by jwp528** [microsoft/devhome#863]
### Suggested new feature or improvement

It would be nice to have the option at the end of the end to end setup process to download the setup to a configuration file as opposed to running it on the machine.

### Scenario

In this case my home PC is already setup for work. but it would make my life easier if I could go through the end to end setup process and then at the end just download the configuration file for my selections. 

### Additional details

This would allow me to easily setup and configure the defaults we require for devs as a company and be able to export the configuration file right from dev home.

**Comment by AmelBawa-msft** [comment]
Duplicate #721
