### ISSUE TITLE
Add widget does not trigger anything

### ISSUE THREAD

**Issue by andysterland** [microsoft/devhome#866]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22624.1755

### Other software

OS Build Version: 10.0.22624.1755.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1) Go to dashboard
2) Click +Add Widget (in the center or top right)

### Expected result

Something happens, like a picker pops up to show the widgets that could be added.

### Actual result

Nothing happens.
![Recording of nothing happening when Add Widget is pressed](https://github.com/microsoft/devhome/assets/10997361/641a4019-3b7e-434c-bb59-76d54b9b8e69)

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.59GB (12.9GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by jmarbutt** [comment]
This is happening to me also.

**Comment by rifkitech** [comment]
🥲🤣

**Comment by krschau** [comment]
@andysterland and @jmarbutt Could you tell me what version of the Windows Web Experience Pack you have installed (if any?). You can run `Get-AppxPackage *webexp*` from a powershell prompt to get it.

**Comment by andysterland** [comment]
@krschau 

Name              : MicrosoftWindows.Client.WebExperience
Publisher         : CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond,
                    S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 521.20060.675.0
PackageFullName   : MicrosoftWindows.Client.WebExperience_521.20060.675.0_x64__cw5n1h2txye
                    wy
InstallLocation   : C:\Program Files\WindowsApps\MicrosoftWindows.Client.WebExperience_521
                    .20060.675.0_x64__cw5n1h2txyewy
IsFramework       : False
PackageFamilyName : MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy
PublisherId       : cw5n1h2txyewy
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00_14.0.32530.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok

**Comment by jmarbutt** [comment]
@krschau 

```
Name              : MicrosoftWindows.Client.WebExperience
Publisher         : CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 521.20060.365.0
PackageFullName   : MicrosoftWindows.Client.WebExperience_521.20060.365.0_x64__cw5n1h2txyewy
InstallLocation   : C:\Program
                    Files\WindowsApps\MicrosoftWindows.Client.WebExperience_521.20060.365.0_x64__cw5n1h2txyewy
IsFramework       : False
PackageFamilyName : MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy
PublisherId       : cw5n1h2txyewy
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00_14.0.30704.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

**Comment by krschau** [comment]
@andysterland and @jmarbutt Thanks for the info! You both have version 521, which made me realize we have a bug when we check which version is installed. There should be a popup asking you to update that app, but we're not displaying it in this case. I expect that there will be an update available in the store, and that updating will fix the issue: 
https://apps.microsoft.com/store/detail/windows-web-experience-pack/9MSSGKG348SP

(If you update *while* Dev Home is open, there's a small bug with widget formatting, but a fix is in PR right now.)

**Comment by amm10090** [comment]
My version cannot display the widget properly

`Get-AppxPackage *webexp*


Name              : MicrosoftWindows.Client.WebExperience
Publisher         : CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 524.34401.20.0
PackageFullName   : MicrosoftWindows.Client.WebExperience_524.34401.20.0_x64__cw5n1h2txyewy
InstallLocation   : C:\Program Files\WindowsApps\MicrosoftWindows.Client.WebExperience_524.34401.20.0_x64__cw5n1h2txyew
                    y
IsFramework       : False
PackageFamilyName : MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy
PublisherId       : cw5n1h2txyewy
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00_14.0.33519.0_x64__8wekyb3d8bbwe, Microsoft.WindowsAppRuntime.1.5_5001.311.
                    2039.0_x64__8wekyb3d8bbwe, Microsoft.VCLibs.140.00.UWPDesktop_14.0.33728.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
`
