### ISSUE TITLE
Can't create dev drive, no options on disk and volumn

### ISSUE THREAD

**Issue by aliuq** [microsoft/devhome#867]
### Dev Home version

0.137.141.0

### Windows build number

10.0.25375.0

### Steps to reproduce the bug

![image](https://github.com/microsoft/devhome/assets/11707934/93a06457-b401-4db9-955d-74f9bbd1e67b)

### Actual result

No options to create a dev drive on disk and volumns

### Included System Information

![image](https://github.com/microsoft/devhome/assets/11707934/41486b52-19c2-44d6-93fe-42c28115bd23)

**Comment by LynxarA-Coding** [comment]
The channel is Dev. build: 23481.1000 ni_prerelease
There is no option to create new Drives inside System > Storage > Advanced > Disks & Volumes
(there are no buttons, only disk partitions info)
