### ISSUE TITLE
Cloned repositories are not visible.

### ISSUE THREAD

**Issue by slinnor** [microsoft/devhome#877]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23466.1001

### Other software

OS Build Version: 10.0.23466.1001.amd64fre.ni_prerelease.230522-1422
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Clone a Git repository with new Virtual disk.
App will sometimes exit itselves (you should wait for it)
Then the cloned repository is not visible.

### Expected result

My cloned repository from GitHub should be visible in my list.

### Actual result

I can't see cloned repository in the app also I am not able to find a repository to clone it again.

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
Physical Memory: 31.84GB (17.26GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
Hello.  Question.  I'm trying to better understand your issue so I can figure out a solution.

Can you please help me understand
> My cloned repository from GitHub should be visible in my list.

What list?  The list of cloned repos in the summary page, list in the repo tool (Where repos are selected), or somewhere else?

Is this happening after the app crashes?  Where does it crash?
