### ISSUE TITLE
Show error if SSH url is entered for repo cloning

### ISSUE THREAD

**Issue by swsd2544** [microsoft/devhome#887]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.0

### Steps to reproduce the bug

1. Go to the machine configuration tab
2. Click 'Clone repositories'
3. Click 'Add repository'
4. Copy the repository `ssh` url to 'Repository URL' input field
5. Click 'Add'
6. The program exit

### Expected result

Show some error about why shouldn't I use ssh URL as a repository URL, or clone the repository like normal.the 

### Actual result

The program exit without any sign.

**Comment by dbuttric** [comment]
For me the software doesn't exit, but it does report an error:

![Screenshot 2023-05-27 215402](https://github.com/microsoft/devhome/assets/4155915/45bf4d22-2c64-43e1-8163-0630d5b4db1b)

I can't seem to use any kind of URL but an HTTPS one.

**Comment by dbuttric** [comment]
I host my repos on a synology, that has git installed.
I can clone them manually onto my devdrive on my laptop. But once I've done that, they dont show up in Dev Home.

**Comment by kanismohammed** [comment]
Dev Home does not have view to show all cloned repositories today. Adding to the list of feature asks.

**Comment by dhoehna** [comment]
Hello @swsd2544 can you please upgrade to a more recent version of Dev Home.  The URL screen shows text if the user put in an SSH link.

Closing as fixed in 0.2.

![image](https://github.com/microsoft/devhome/assets/2517139/2def8c2f-9c73-4cf0-8754-2d15eea4c968)
