### ISSUE TITLE
I cannot create dev drive what is the use If I cant creaete dev drive partition

### ISSUE THREAD

**Issue by sande5h** [microsoft/devhome#889]
### Dev Home version

0.137.141.0

### Windows build number

10.0.25375.1

### Other software

OS Build Version: 10.0.25375.1.amd64fre.zn_release.230520-1632
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

just install new canaary insider build and installed dev home preview . i cannot do anything here 

### Actual result

just install new canaary insider build and installed dev home preview . i cannot do anything here 

### Included System Information

CPU: AMD Ryzen 5 5500U with Radeon Graphics         
Physical Memory: 7.4GB (3.2GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by MeikTranel** [comment]
I mean i feel you - i'd like canary to be more unstable as well but this isnt really an issue with dev home. Its the canary build that doesnt have dev drives enabled. If you want to try dev drives you'd have to be on the dev channel. Microsoft documented this when they announced the canary channel - its not a linear progression of features - canary is where they test things to see what sticks but they are moving features and general state of the code in and out of the branch. 
Unfortunately this currently means the dev channel is at the higher state of features rolled out (at least when it comes to user facing features - the core OS might be much more experimental).
