### ISSUE TITLE
Translation issues with the "开发人员主页规范" in Chinese

### ISSUE THREAD

**Issue by WhatDamon** [microsoft/devhome#892]
### Dev Home version

0.137.141.0

### 🌐 Language

Simplified Chinese(简体中文)

### ❌ Actual phrase(s)

<img width="1028" alt="image" src="https://github.com/microsoft/devhome/assets/59256766/883bf02b-27ec-4336-8e44-2ea95fc42a3b">

The text **"开发人员主页规范"** in the about page is incorrect.

### ✔️ Expected phrase(s)

I'm not quite sure what it is in English, so I can only guess that the original is "Dev Home Preview", and if it is, then it should be translated as **"开发人员主页（预览）"**.

### Why is the current translation wrong

Even if the original translation is correct, but for Chinese people such a translation is somewhat obscure, if possible, please provide the original, modify or modify (I do not want to spend a lot of time looking for the original from the code, and there are with my use of habits, switching the system language will also be more trouble)

**Comment by cinnamon-msft** [comment]
@EricJohnson327 did this get fixed with our latest localization changes?

**Comment by WhatDamon** [comment]
> @EricJohnson327 did this get fixed with our latest localization changes?

it's ok now,tks
