### ISSUE TITLE
Crash on trying to open Install Applications window

### ISSUE THREAD

**Issue by theSparro** [microsoft/devhome#897]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23466.1001

### Other software

OS Build Version: 10.0.23466.1001.amd64fre.ni_prerelease.230522-1422
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Go to Machine Configuration > Install Applications. 

### Expected result

To be able to select apps to install and move to the next step

### Actual result

Program crashes after about 5 seconds. I was still able to click and add applications in that time so it was responsive.

### Included System Information

CPU: AMD Ryzen 7 4800H with Radeon Graphics         
Physical Memory: 19.36GB (11.86GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by AmelBawa-msft** [comment]
Likely duplicate #768
