### ISSUE TITLE
Provide full resolution assets

### ISSUE THREAD

**Issue by bennett-sh** [microsoft/devhome#907]
### Provide a description of requested docs changes

It would be cool if we had access to the full res images included in [@MicrosoftDesign's Twitter post](https://twitter.com/MicrosoftDesign/status/1662125325772267521) (primarly the first, second and fourth image).

**Comment by ianyyu** [comment]
We will be posting the full res image on our [Microsoft Design—Wallpapers site](https://wallpapers.microsoft.design) shortly! Stay tuned!
