### ISSUE TITLE
Custom widgets require a Microsoft package ID

### ISSUE THREAD

**Issue by dotMorten** [microsoft/devhome#908]
### Dev Home version

Latest source (as of posting this)

### Steps to reproduce the bug

Create a custom widget and set a custom package id. Note that widget won't show.
Change the package ID to start with `Microsoft.Windows.DevHome` and the widget will show in the Add Widget dialog.

Issue is caused by the filter specified here:
"https://github.com/microsoft/devhome/blob/7d5f8c72bbf0eacef58239f415e8d3aa99e69628/tools/Dashboard/DevHome.Dashboard/Helpers/WidgetHelpers.cs#L71

You can repro with the github extension by changing the package id here:
https://github.com/microsoft/devhomegithubextension/blob/af404f352650ba452f5c29e76226629ee6ae43aa/src/GithubPluginServer/Package.appxmanifest#L3

**Comment by chingucoding** [comment]
If this fix is as simple as removing this filter (why is it included in the first place and what is a suitable alternative), I would like to take my shot at this bug.

**Comment by dotMorten** [comment]
@chingucoding i don't think it is. IIRC I think some sort of filter is needed so it doesn't attempt to load all apps - but it probably shouldn't be based on package id

**Comment by chingucoding** [comment]
The question is what criteria is used to determine whether a widget can be added to the dashboard and which will not be shown as an option. I would argue that being able to see all widgets is fine, after all there aren't many widgets but of course this is rather a product decision rather than a technical one.
