### ISSUE TITLE
Core widgets are not displaying

### ISSUE THREAD

**Issue by haki-user** [microsoft/devhome#914]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22000.1936

### Other software

OS Build Version: 10.0.22000.1936.amd64fre.co_release.210604-1628
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

goto dashboard then goto add widgets then core widgets

### Expected result

Widgets should be displayed

### Actual result

No core widgets are displaying. 
It is showing: This widget could not be displayed.
![Screenshot 2023-05-28 142840](https://github.com/microsoft/devhome/assets/104914040/bc0a1933-3a13-45fd-8787-77d6a763b569)

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
Physical Memory: 7.7GB (1.33GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by PurpShell** [comment]
+1

**Comment by cinnamon-msft** [comment]
If you click pin without letting it load, does the widget pin and load the data after waiting? This could be a load time issue

**Comment by haki-user** [comment]
> 

When I installed it, that time I was able to pin it, even then it was not loading. But now it is not giving option to pin core widgets.
![Screenshot 2023-05-31 112055](https://github.com/microsoft/devhome/assets/104914040/3afcd479-05b9-4ab2-a721-9991f331e430)

![Screenshot 2023-05-31 112142](https://github.com/microsoft/devhome/assets/104914040/1e966e99-895a-4b31-8e8f-7bcdcb74153a)

**Comment by MoazAlkharfan** [comment]
Similar issue, widgets are not displaying.

https://github.com/microsoft/devhome/assets/8115419/9e115735-90b2-4d20-87c8-67da8b0fab87

**Comment by rjacobs1969** [comment]
Same here, widgets not loading

**Comment by ocdi** [comment]
I thought I would give this a go - CPU and Memory widgets showed this error for me also.

**Comment by krschau** [comment]
I haven't seen this issue in a long time, closing as no repro. If anyone sees this, please comment and I will reopen the issue.
