### ISSUE TITLE
Loosing widgets on boot

### ISSUE THREAD

**Issue by danielvca** [microsoft/devhome#921]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23466.1001

### Other software

OS Build Version: 10.0.23466.1001.amd64fre.ni_prerelease.230522-1422
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Add any hardware widget (CPU, GPU  etc..) and reboot the PC

### Expected result

Widgets won't go away after reboot

### Actual result

Every time i reboot my pc my Dashboard loses my hardware widgets.
It's a blank canvas on each boot.

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i9-13950HX
Physical Memory: 31.64GB (10.1GB free)
Processor Architecture: x64

**Comment by krschau** [comment]
Duplicate of #742
