### ISSUE TITLE
Error when connecting Github

### ISSUE THREAD

**Issue by Akanixon** [microsoft/devhome#925]
### Dev Home version

0.137.141.0

### Windows build number

10.0.25357.1

### Other software

OS Build Version: 10.0.25357.1.amd64fre.zn_release.230428-1528
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Add account, continue with verification, confirm access.
Wait for Dev Home to finish setup

### Expected result

Successfull message

### Actual result

Unexpected Error message

### Included System Information

CPU: AMD Ryzen 9 3900X 12-Core Processor            
Physical Memory: 31.94GB (8.42GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by cinnamon-msft** [comment]
What error message do you see?

**Comment by cinnamon-msft** [comment]
Thanks for the screenshot :) we'll have the team look into this!

**Comment by manodasanW** [comment]
@Akanixon just as a data point for us, what is your default browser where you are seeing this?

**Comment by Akanixon** [comment]
My default browser is Edge

**Comment by vineeththomasalex** [comment]
Hi @Akanixon, do you still hit this? Some related changes on v0.4 and v0.5 should have fixed this. Please reopen if you still hit this. Thanks.
