### ISSUE TITLE
Dev Drive Creation not available on Windows 11 Pro for Workstations

### ISSUE THREAD

**Issue by ehuggz1** [microsoft/devhome#933]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23466.1001

### Other software

OS Build Version: 10.0.23466.1001.amd64fre.ni_prerelease.230522-1422
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. Opt into Insider Preview Dev Channel and update system
2. Verify System running: Windows Pro for Workstations Insider Preview Build 23466
3. Select either Dev Home->Create Dev Drive 
4. Neither Create VM nor Repartition Drive options available for creating Dev Drive

### Expected result

Dev Drive creation option should be available.

### Actual result

No Dev Drive option available.

### Included System Information

CPU: Intel(R) Xeon(R) W-2223 CPU @ 3.60GHz
Physical Memory: 31.69GB (17.49GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by byjokese** [comment]
Same problem here, tried to create it using the clone repository and in the customize options use the clone on Dev Drive (creating a new one) and the task failed. No drive was created and no repository was cloned.

> OS Build Version: 10.0.23466.1001.amd64fre.ni_prerelease.230522-1422
> .NET Version: .NET 6.0.16

**Comment by cinnamon-msft** [comment]
To confirm, are you able to create a Dev Drive using your Windows settings under Disks & Volumes?

**Comment by RetrotecDustin** [comment]
I am having the same issue as @ehuggz1 (except I am on Windows 10 Pro). My Disks & volumes looks like that as well, with Unallocated space and only the option to create a new NTFS volume.

**Comment by AdamBraden** [comment]
> @cinnamon-msft Dev Drive creation not available in Disks & Volumes
> 
> ![image](https://user-images.githubusercontent.com/46914110/242285930-ccc4f271-db9f-4092-8f63-06c95537a60e.png)

I've seen this happen on the Dev channel where upon first logon the feature is not enabled. However doing a **reboot** enables the feature in Settings. Can you try this workaround? If this works, then there is an issue with our channels and how features get enabled. We are looking into this, but don't have a solution yet.

**Comment by ehuggz1** [comment]
@cinnamon-msft That fixed it! 50GB DevDrive created.

**Comment by ehuggz1** [comment]
Thanks to @AdamBrMSFT

**Comment by RetrotecDustin** [comment]
![image](https://github.com/microsoft/devhome/assets/53620171/46c2b517-82c4-48c3-b510-c83fdbc6a153)

Unfortunately rebooting did not solve the issue for me. This is still what I get when I click Create Volume on my ~500GB unallocated space. If you need any more info that could be of use (system specs, Windows info, etc.) let me know.

I was pretty excited to try this out, hopefully it will be something simple like toggled a registry setting or something to enable the feature.

**Comment by snickler** [comment]
@RetrotecDustin - Are you running Windows 11 Pro Insider Dev 10.0.23466.1001?

**Comment by RetrotecDustin** [comment]
@snickler  - I am currently on Windows 11 Pro Insider Preview 25375.1. I was offered the update from 23466 and updated hoping it would resolve the Dev Drive issue. I did try rolling back to see if maybe 23466 was the **only** build it would be available  on for some reason (since it's the only one mentioned in the docs and blog posts), but no luck.

**Comment by snickler** [comment]
You mean THIS 25375.1? You only will receive that if you're on the Canary channel. If you were previously on the Dev Channel prior to Canary Channel being announced, then you were automatically migrated to there. You won't be able to use Dev Drive yet, until the feature possibly gets rolled up into Canary. 

![image](https://github.com/microsoft/devhome/assets/4016293/1f7f11cb-90f3-476d-8d97-b0920911f890)

**Comment by RetrotecDustin** [comment]
@snickler - Hmm, I am on Dev right now but it's possible I switched to Canary to see if it was resolved there, but I understand not bumping features up until they've been vetted. Any chance rolling back to 23466 and staying on Dev might get it working?
![image](https://github.com/microsoft/devhome/assets/53620171/7995dc0b-a251-4a1c-b220-cbd8cc8316bc)

**Comment by snickler** [comment]
@RetrotecDustin - You were on the *old* Dev Channel at some point in time or temporarily switched to Canary which is why you were offered a 25XXX build. Once you're on a 25XXX build, you're there unless you wipe everything away and start fresh from a non-Insider build. Simply switching to Dev Channel while already on a build offered through Canary won't bring the feature to you, but I would say to switch your channel to Canary for now since there's some weirdness you'll encounter with retrieving builds at some point.

**Comment by RetrotecDustin** [comment]
@snickler - Looks like it is possible to roll back an update, would that risk messing stuff up?

![image](https://github.com/microsoft/devhome/assets/53620171/a2f2418d-9c91-4629-9c61-b329ffbe9737)

**Comment by snickler** [comment]
> @snickler - Looks like it is possible to roll back an update, would that risk messing stuff up?
> 
> ![image](https://user-images.githubusercontent.com/53620171/242429212-a2f2418d-9c91-4629-9c61-b329ffbe9737.png)

If you were on a NON-25XXX build prior to this and you've been on this build less than a week (typically the length of time the Windows.old folder exists for until it clears out), you should be able to roll-back to the previous build and possibly switch back to Dev Channel and might receive 23466, but if that previous build was a 253XX build then you're stuck.

**Comment by RetrotecDustin** [comment]
@snickler  - This is the only build I've been offered post-23466. I've only been trying to get this working for a few days since the blog post popped up in my news feed. Worth a shot I suppose, I'll give it a try after hours and post results here just in case it might help someone else. Thanks for the help!

**Comment by snickler** [comment]
> 

@RetrotecDustin  - No problem! If you're able to roll back and get on a 23XXX build, make sure that it's set to Dev Channel and try again. I hope it works out!

**Comment by RetrotecDustin** [comment]
I was able to roll back to 23466, and am on the Dev channel.

> Edition	Windows 11 Pro Insider Preview
> Version	22H2
> Installed on	‎5/‎24/‎2023
> OS build	23466.1001
> Experience	Windows Feature Experience Pack 1000.23466.1001.0

But no luck with the Dev Drive feature. My System > Storage > Disks & volumes looks the same as it did before. I did try rebooting a couple times as that seemed to do the trick for a couple people above, but it didn't work for me.

**Comment by AdamBraden** [comment]
I've been talking to folks about what could have happened here, and its hard to know if the rollback from Canary and 25xxx builds impacted something. They are curious if you received yesterday's update to the Dev External channel - build ni_prerelease 23471. And of course, try an extra reboot after first logon.

**Comment by RetrotecDustin** [comment]
I did get the update, yes. Still no Dev Drive (First thing I checked after the reboot.) 😆 

> Edition	Windows 11 Pro Insider Preview
> Version	22H2
> Installed on	‎6/‎1/‎2023
> OS build	23471.1000
> Experience	Windows Feature Experience Pack 1000.23471.1000.0

**Comment by blueatria** [comment]
I also do not have the option of creating a dev drive. I am on build 23471.1000 from the dev channel. I have tried rebooting and checked Hyper-V is installed. No luck. Any other suggestions?

**Comment by RetrotecDustin** [comment]
Still no resolution for me, all other bugs related to this seem to marked as duplicates of this closed one. Should I create a new issue or just twiddle my thumbs until this "feature" comes out of preview?
