### ISSUE TITLE
No "Create Dev drive button"

### ISSUE THREAD

**Issue by DenysDovgan** [microsoft/devhome#934]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23466.1001

### Other software

OS Build Version: 10.0.23466.1001.amd64fre.ni_prerelease.230522-1422
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

I downloaded new windows version from Dev channel, installed DevHome. I wanted to create Dev Drive but there is no button in Storage settings

### Expected result

I whished to create Dev Drive

### Actual result

It is not possible

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i3-12100
GPU: NVidia GeForce RTX 3060
Physical Memory: 31.78GB (23.85GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by DenysDovgan** [comment]
Now Working

**Comment by RetrotecDustin** [comment]
Why is this closed? There was no resolution offered and I am facing the same issue.

**Comment by krschau** [comment]
@RetrotecDustin This was closed by the person who opened it. It would be helpful if you could open a new issue so we have appropriate system information, etc, for your situation.
