### ISSUE TITLE
Could not clone repository and create dev drive

### ISSUE THREAD

**Issue by byjokese** [microsoft/devhome#939]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23466.1001

### Other software

OS Build Version: 10.0.23466.1001.amd64fre.ni_prerelease.230522-1422
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Go to Machine configuration.
Clone A repository.
Select a private repository from linked GitHub Account.
Customize and add a new Dev drive with 50GB and Z letter on a new NTFS SSD drive (F:/)
Click Next
Failed to run two tasks (clone and create dev drive, both failed)

### Expected result

To create a new dev drive and clone the repository to the newly created dev drive.

### Actual result

Two failed tasks with no trace and nothing created on the Drive (Empty folder)

### Included System Information

CPU: AMD Ryzen 9 7950X3D 16-Core Processor          
Physical Memory: 63.14GB (42GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by byjokese** [comment]
After a System restart got it working, seems like the first boot up of this version is not totally correct. The Windows explorer did not work properly either (seeing old Windows 10 explorer).

**Comment by grievercr** [comment]
> After a System restart got it working, seems like the first boot up of this version is not totally correct. The Windows explorer did not work properly either (seeing old Windows 10 explorer).

Rebooting it resolved the issue for me. I was running into a creation issue as well at first launch.
