### ISSUE TITLE
Can't ask for GitHub's OAuth permission after revoking access

### ISSUE THREAD

**Issue by gcarramate** [microsoft/devhome#941]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

- Link GitHub account to Dev Home
- Revoke access to account inside GitHub
- Try to link again, or add repositories

### Expected result

I would be able to link my account again.

### Actual result

Dev Home just closes.

### Included System Information

CPU: AMD Ryzen 7 5800H with Radeon Graphics         
Physical Memory: 15.35GB (5.54GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by UltimateZero** [comment]
Encountered this issue as well, even re-installing Dev Home and Dev Home Github Extension doesn't fix it.
You need to open [Credential Manager](https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0), and delete the `GithubDevHomeExtension` credential entry.

**Comment by gcarramate** [comment]
I signed out, reset the app under settings -> apps and even uninstalled Dev Home and installed it again.

After trying all of this, the only way to fix it was by manually deleting the `GithubDevHomeExtension` credential entry on Credential Manager, as @UltimateZero mentioned.

**Comment by vineeththomasalex** [comment]
Logging out and logging in will work to display the autorization page of  the Dev Home GitHub Extension OAuth app while signing in to GitHub since v0.4
