### ISSUE TITLE
Panel keeps deleting my tiles

### ISSUE THREAD

**Issue by Poi9912** [microsoft/devhome#944]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

add tiles to the panel, close the app normally, restart the system, open the app after boot

### Expected result

the panel should be in the same position or not be deleted without user interaction

### Actual result

panels get deleted 

### Included System Information

CPU: AMD Ryzen 7 5800X 8-Core Processor             
Physical Memory: 31.93GB (17.52GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Duplicate of #742
