### ISSUE TITLE
Can't connect GitHub account

### ISSUE THREAD

**Issue by DamienFoulon** [microsoft/devhome#951]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Go for link a GitHub account, click on the login button

### Expected result

The button should redirect to the GitHub's login page on the browser

### Actual result

The button login doesn't take any effect.

### Included System Information

CPU: AMD Ryzen 5 5500U with Radeon Graphics         
Physical Memory: 7.39GB (1.32GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by ManuSquall** [comment]
Encounter the same issue this morning; didn't work on first attempt but fine on the third 🙃

**Comment by manodasanW** [comment]
If you close the account sign in popup and try again, it should work (known issue we are looking into).  If it doesn't, let me know.

/dup https://github.com/microsoft/devhomegithubextension/issues/108
