### ISSUE TITLE
Integration with Microsoft Dev Box

### ISSUE THREAD

**Issue by asilverman** [microsoft/devhome#955]
### Suggested new feature or improvement

[Microsoft Dev Box](https://learn.microsoft.com/en-us/azure/dev-box/) gives you self-service access to high-performance, preconfigured, and ready-to-code cloud-based workstations. Connecting to a Dev Box happens through a RDP connection. 

As a developer using Dev Box, I would like to be able to instantiate, connect and manage my Dev Box instances from Dev Home. I would also like to provision my Dev Box machines with a configuration stored in Dev Home, that way I can create fully customizable development sandboxes that are ready to go from within Dev Home. 

### Scenario

One example is https://devbox.microsoft.com/. 

Currently, the only way to create a new Dev Box is through this portal. When I create a new Dev Box, I need to spend a lot of time provisioning it with my custom developer configurations including:

- Applications not pre-installed in the image
- Visual Studio Code Extensions and Settings
- Creating a familiar folder structure to store my code and other work artifacts
- Creating new SSH keys and granting them access in the different remote services (GitHub, AzDO, Docker, etc.)

I would be useful to store a private GitHub repository with a deploy configuration for a new Dev Box and have Dev Home orchestrate the provisioning and make it available for me to connect to the newly provisioned machine from within the app.

### Additional details

One example is https://devbox.microsoft.com/. 

Currently, the only way to create a new Dev Box is through this portal. When I create a new Dev Box, I need to spend a lot of time provisioning it with my custom developer configurations including:

- Applications not pre-installed in the image
- Visual Studio Code Extensions and Settings
- Creating a familiar folder structure to store my code and other work artifacts
- Creating new SSH keys and granting them access in the different remote services (GitHub, AzDO, Docker, etc.)

I would be useful to store a private GitHub repository with a deploy configuration for a new Dev Box and have Dev Home orchestrate the provisioning and making it available for me to connect to the newly provisioned machine from within the app.

**Comment by asklar** [comment]
Looking into this a bit. 
Whoever picks this up, ping me on teams.
