### ISSUE TITLE
Can't add repositories as GitHub account prompt doesn't appear

### ISSUE THREAD

**Issue by RDMacLachlan** [microsoft/devhome#958]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1776

### Other software

OS Build Version: 10.0.22621.1776.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

I've installed Dev Home previously, and have skipped past a few of the important setup steps. But now, when I go to End-to-End setup of my dev device I choose to add a repository and then select Accounts.  Here I'm not prompted for a login to GitHub, and instead am left with no repositories...

### Expected result

Prompt for GitHub authentication

### Actual result

Empty list.

### Included System Information

CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Physical Memory: 15.92GB (2.44GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
> I've installed Dev Home previously
This makes me wonder if you encountered an issue with how the extension handled credentials.

Can you still repro this with the version from the store?
