### ISSUE TITLE
Export WinGet Configuration YAML from end-to-end setup

### ISSUE THREAD

**Issue by carlheinrichhancke** [microsoft/devhome#970]
### Suggested new feature or improvement

Once all the desired applications have been selected for installation, have an option that would allow exporting a winget configuration file that would perform the same installation.

### Scenario

This would allow a customized setup to be "snapshot", so on future installations the winget config file can be used to perform the setup instead of having to search & select the individual applications again.

**Comment by denelon** [comment]
@carlheinrichhancke take a look at:
* #1067 

Is that what you're thinking?
Something along the lines of generate an "export" file for use with `winget import`?

Or are you looking for more than just packages like:
* #876

**Comment by shakersMSFT** [comment]
Hi, we are currently exploring how we might accomplish this through Dev Home. Please take a look and let us know what you think! https://github.com/microsoft/devhome/issues/2160

**Comment by shakersMSFT** [comment]
Fixed by https://github.com/microsoft/devhome/pull/2466
