### ISSUE TITLE
Crashing and widgets scaling working not properly

### ISSUE THREAD

**Issue by AsirRahman** [microsoft/devhome#975]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

When Im opening any section in menu bar, I have 50% chance that program will crash.

### Actual result

crashed :)

### Included System Information

CPU: AMD Ryzen 5 2600X Six-Core Processor 
GPU: WindForce G1 gaming video card (GTX 960)    
Physical Memory: 15.94GB (10.52GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Can you explain more about what you mean by "opening any section in the menu bar" and "widget scaling"?
