### ISSUE TITLE
Application at startup

### ISSUE THREAD

**Issue by AsirRahman** [microsoft/devhome#976]
### Suggested new feature or improvement

Make your application open automatically at startup of pc.  

### Scenario

So, in this feature, application will be opened with dashboard section, so I can access all my dev application (or even folders) in one window. For example, I'm too lazy to open application by myself, so at startup dev home will open it for me (for example it will open VS Studio and CMD).

Also it would be better if you give us access to pin those widgets to home screen (Desktop).

**Comment by balaji-sivasakthi** [comment]
@mathewleeza Could you assign this issue to me? I will work on it.
