### ISSUE TITLE
0x80131534 error at trying to clone repository from Arm system

### ISSUE THREAD

**Issue by alevlasu** [microsoft/devhome#978]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.0

### Steps to reproduce the bug

1. Open the Dev Home app on the device with an Arm processor (e.g. Surface Pro 9 or Parallels Desktop virtual machine on Apple M series)
2. Try to clone a GitHub repo using Dev Home, e.g. https://github.com/microsoft/vscode

### Expected result

The repo is cloned (as it is on Intel PC)

### Actual result

Error:
"Couldn't clone vscode 0x80131534"

<img width="1002" alt="Screenshot 2023-05-31 at 5 30 06 PM" src="https://github.com/microsoft/devhome/assets/13949219/7d34d186-65a7-4b34-af52-7b28c7484f68">

**Comment by dhoehna** [comment]
Closing as not repro.  We could clone with an ARM machine.  Please open if issue persists.
