### ISSUE TITLE
Widgets window auto-resizable

### ISSUE THREAD

**Issue by HojdaAdelin** [microsoft/devhome#979]
### Suggested new feature or improvement

Try to create widgets window auto resizable: bigger and smaller for different circumstance when main window is resizable by the user.

### Scenario

When user resizable the application widgets windows also should resizable to allow the user exit the window, etc.. In my case when I resized the main window the widgets window didn't so I wasn't able to exit the widgets window.

**Comment by krschau** [comment]
Duplicate of #584
