### ISSUE TITLE
Terminal has wrong fonts - prompt displayed incorrectly

### ISSUE THREAD

**Issue by y2k4life** [microsoft/devhome#980]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Launch an SSH terminal into a Linux server that use oh-my-posh.

### Expected result

The prompt to look normal as when launching from termainal.

![image](https://github.com/microsoft/devhome/assets/10999532/75dfaec5-e635-460a-b75c-b7d494e2ab97)

### Actual result

The prompt separators and other prompt segments are wrong.

![image](https://github.com/microsoft/devhome/assets/10999532/85e5ce98-2225-4cf6-9f39-363557a6799a)

**Comment by cinnamon-msft** [comment]
What profile does your terminal window open to when clicking an SSH key? Also, what do your terminal settings look like? It looks like it's using a different font rather than your nerd font.

**Comment by y2k4life** [comment]
I believe I have a better understanding. My initial thought was the Windows terminal profile associated with the Host (in the SSH config) was being launched. Instead, the Windows Terminal profile appears to be the Command Prompt profile, which does not have nerd fonts (I hardly use command prompt). If I open the Window Terminal Command Prompt profile and enter `ssh Rawpower` then I get the same results. 

Might I suggest a feature to pin Windows Terminal Profiles. Having that feature would solve the confusion. Are users more inclined to have SSH Configuration over Windows Terminal Profiles? This insight also answers my question as to why I was seeing less options when pinning the SSH Config (keychain) because I don't have a one-to-one configuration between Windows Terminal and SSH. I have more profiles with Windows Terminal than SSH configurations.
