### ISSUE TITLE
Rename "Core" widget provider to "Dev Home"

### ISSUE THREAD

**Issue by RohitY24** [microsoft/devhome#988]
In the Widget Picker that appears in the Windows Widgets board, the DevHome Widgets are not displayed properly with the App name. Instead they show the app name as 'Core', which should be rectified.

Screenshot for reference: 

![image](https://github.com/microsoft/devhome/assets/35281343/08d2c6b3-be48-4965-9afc-e8f6d635dbda)

**Comment by cinnamon-msft** [comment]
Ah, looks like the provider's name is "core" - we can change that to "Dev Home" :)

**Comment by RohitY24** [comment]
Yes, that is the exact fix needed here :D

**Comment by Sachin24704** [comment]
Hi @cinnamon-msft, is this issue up for grabs? Please assign it to me.

**Comment by cinnamon-msft** [comment]
Go for it!

**Comment by balaji-sivasakthi** [comment]
I think issue was resolved.

![image](https://github.com/microsoft/devhome/assets/65065614/7cace079-6093-458b-bcef-da988bf0652c)

**Comment by balaji-sivasakthi** [comment]
@cinnamon-msft Do you want like this?
![image](https://github.com/microsoft/devhome/assets/65065614/419f9529-f4cb-40fa-b31d-7c885b537349)

**Comment by cinnamon-msft** [comment]
Yep!

**Comment by balaji-sivasakthi** [comment]
Can I make a PR for this?

**Comment by cinnamon-msft** [comment]
Go for it!

**Comment by RohitY24** [comment]
Yes, confirming the name appears as Core right now, with Preview appended to it.

![image](https://github.com/microsoft/devhome/assets/35281343/c1176bee-8db0-4ae2-b200-f8191de1b468)

**Comment by balaji-sivasakthi** [comment]
@cinnamon-msft and @RohitY24  Kindly, check my PR.
